### ISSUE TITLE
Launch error when editing manifest.json as instructed

### ISSUE THREAD

**Issue by davidljung** [Unity-Technologies/barracuda-release#10]
The installation instructions indicate that Barracuda must be installed either via the Unity package manager or by editing the manifest.json file.
The Unity ML Agents SDK project requires Unity 2017.4.35f1, which doesn't appear to have a package manager menu option.
Editing the manifest.json file to read:
```
{
        "dependencies": {
          "com.unity.barracuda" : "https://github.com/Unity-Technologies/barracuda-release.git"
        }
}
```

Results in Unity giving the error:
```
Failed to resolve packages: Manifest /UnityMLTest/UnityPackageManager/manifest.json has invalid dependencies:
  Error for package 'com.unity.barracuda':
    Version is invalid.  Expected a pattern like 'x.x.x[-prerelease]', got 'https://github.com/Unity-Technologies/barracuda-release.git' instead..  Please see the Editor.log file for more information.
```

**Comment by davidljung** [comment]
I was able to get ML Agents SDK running with Unity 2019.2.5f1, which has a package manager with the ability to install Barracuda, hence bypassing this issue.  It will still be an issue for users of Unity 2017.4.35f1.  Perhaps the ML Agents docs should be updated to specify a newer Unity version.

**Comment by mantasp** [comment]
Packages are bit tricky with Unity 2017.x, it's recommended to use Unity 2018.4x LTS as most stable configuration. Unity 2019.x should also work fine.
