### ISSUE TITLE
Working with linear color space

### ISSUE THREAD

**Issue by albanmdb3d** [Unity-Technologies/barracuda-release#100]
Hi,

I'm trying to work with a project that uses a linear color space. I would like to transform a render texture (screenshot of my scene) to a tensor. 

Here is a sample code (assume screenShotRGB contains what my camera sees):

```csharp
RenderTexture screenShotRGB = new RenderTexture(512, 512, 24, RenderTextureFormat.ARGB32);
Tensor test = new Tensor(screenShotRGB, 3);
RenderTexture screenShotRGBPost = new RenderTexture(512, 512, 24, RenderTextureFormat.ARGB32);
test.ToRenderTexture(screenShotRGBPost);
```

This works fine when working with a gamma color space. I have tried changing the RenderTextureReadWrite attribute, but with no luck.

Below is an example of "screenShotRGBPost" when working with a linear color space project. It works fine in gamma. If possible, I would like to avoid doing the conversion on the tensor myself. 

![gamma](https://user-images.githubusercontent.com/69472378/97488631-de176100-1934-11eb-8704-dea0ea6033fc.png)
![linear](https://user-images.githubusercontent.com/69472378/97488632-deaff780-1934-11eb-9ef2-8e2ea73b470c.png)

Thanks for the assistance

**Comment by AlexRibard** [comment]
Hi @albanmdb3d ! Sorry but I have a hard time understanding the issue?
Are you wanting to convert a Linear Texture to sRGB? Or the other way around?
Is this of any help?
https://docs.unity3d.com/ScriptReference/RenderTexture-sRGB.html

**Comment by albanmdb3d** [comment]
Hi @AlexRibard ! Basically I am trying to convert a RenderTexture in a linear space to its equivalent if I were to work in a gamma space. For some reason when working in linear space my screenshot (first screen) is "darkened" when it's converted to a tensor then back to a RenderTexture (second screen). The problem is confusing to me as well so I have a hard time explaining it.
Thanks!

Edit: In other words, I'd like to apply the ~^0.45 correction to my texture values in case the project is in linear color space.

**Comment by AlexRibard** [comment]
I _think_ it might be linked to the sRGB flag mentioned in the link. @mantasp can chime in on that.
If it is simpler for you to do the math yourself, you can do that with the following code:
```
m_Ops = new ComputeOps(ComputeShaderSingleton.Instance.kernels, ComputeShaderSingleton.Instance.referenceKernels);
inputTensor = m_Ops.Pow(inputTensor, 0.45);
```
You can follow here for more details:
https://github.com/Unity-Technologies/barracuda-release/issues/97

Let me know

**Comment by mantasp** [comment]
@albanmdb3d there is extra parameter in RenderTexture constructor, which allows to specify Read/Write sRGB/linear conversion: https://docs.unity3d.com/ScriptReference/RenderTextureReadWrite.html. Could you try it and report if it helps with your issue?

**Comment by albanmdb3d** [comment]
I think the flag just triggers the conversion when the textured is actually rendered. I played around with the flag and it doesn't change the underlying values. I am going to end up doing the correction myself. It's not much code of course but I would have liked my package to natively work for both color spaces. Perhaps a future release of Barracuda could solve the issue? Thanks again

**Comment by AlexRibard** [comment]
Ah, I am beginning to understand were the problem might be coming from.
The Tensor Constructor in Barracuda reads the Texture as is, without using the `TextureSampler`. So some mismatch must be coming from that.
Can you confirm me the `sRGB` flag is correct?
When you put the RenderTexture on a material do you see the discrepancy there?
I'll investigate on my end aswell.

As for your request, I think it makes sense, atm `ToRenderTexture` only supports scale and bias. Maybe exposing color space conversion would be since.
Let me know if the `m_Ops` solution outlined about works for you?

**Comment by albanmdb3d** [comment]
Yes the sRGB flag is correct.
When doing: RenderTexture -> material: no problem
When doing: RenderTexture -> Tensor -> RenderTexture -> material: issue (see screen 2)

The m_Ops solution should work but I haven't tested it just yet.

**Comment by AlexRibard** [comment]
ok thanks, I'll give it a look
