### ISSUE TITLE
Wierd behavior when recreating worker

### ISSUE THREAD

**Issue by DanielDorDev** [Unity-Technologies/barracuda-release#102]
I am getting wierd behavior when recreating worker, the result completely different, 
The wierd part it is happening only in android, in pc everything works fine,
it happens if i create two workers from same model
or reload scene and then create single worker

how does barracuda interface load and unload model? maybe i am doing init wrong?

**Comment by AlexRibard** [comment]
Hi! Can you be a bit more specific about the issue?
Is the inference results different depending on the worker type?
Or is it different from the same worker type but two workers created from the same model?
Which back-end are you testing on? CPU, GPU (Vulkan or android)?

For model loading I would refer you to the documentation:
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Loading.md

Let me know

**Comment by DanielDorDev** [comment]
> Hi! Can you be a bit more specific about the issue?
> Is the inference results different depending on the worker type?
> Or is it different from the same worker type but two workers created from the same model?
> Which back-end are you testing on? CPU, GPU (Vulkan or android)?
> 
> For model loading I would refer you to the documentation:
> https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Loading.md
> 
> Let me know

Using the same type, the same model, the same object
both workers created from same model, both GPU, graphics set to Vulkan, same inputs

The results are different only when executing from android, pc gives same result(what we excpet)

**Comment by AlexRibard** [comment]
Interesting. Can you share the specific code? We'll look into it
