### ISSUE TITLE
DownloadDataFromGPU taking long time on Android

### ISSUE THREAD

**Issue by InternetSalmon** [Unity-Technologies/barracuda-release#103]
Hi,

I've been following the [model output documentation](https://docs.unity3d.com/Packages/com.unity.barracuda@1.2/manual/ModelOutput.html) although have an issue where model execution is quick but performance is held up when using `PeekOutput`

```
Tensor inputTensor = new Tensor(input, 3);

interpreter.Execute(inputTensor);
output1 = interpreter.PeekOutput("Identity");
output0 = interpreter.PeekOutput("Identity_1");
```

From the Profiler it looks like the model is executing in 12.43ms although the peek operation, e.g. "DownloadDataFromGPU" is taking 61.65ms. 
![image](https://user-images.githubusercontent.com/46416514/97955364-1ff34c00-1dfa-11eb-9958-6e46e8186850.png)
![image](https://user-images.githubusercontent.com/46416514/97955538-84aea680-1dfa-11eb-9488-6f46f223673d.png)

Is there any suggested best practice to read the output more efficiently?

**Comment by mantasp** [comment]
It means that GPU is still busy with inference workload. Are you yielding for another frame before accessing contents of the `output0` and `output1`?

**Comment by InternetSalmon** [comment]
Thanks Mantasp,

I took your advice and profiled it further. It looks like the peek operation is quick but its reading the returned tensor that is taking 60ms. I tried yielding before and after the `PeekOutput` operation but the duration remains the same. Its a SSD based model and the "DownloadDataFromGPU" delay seems to coincide with reading the score results from the returned tensors.

Executing and peaking the output seems ok

```
Tensor inputTensor = new Tensor(input, 3);
interpreter.Execute(inputTensor);
output1 = interpreter.PeekOutput("Identity");
output0 = interpreter.PeekOutput("Identity_1");
```
 
Interpreting the result using the returned output Tensors is very slow (60ms)

```
for (int i = 0; i < anchors.Length; i++)
{
    float score = MathB.Sigmoid(output1[0, 0, 0, 0, 0, 0, 0, i]);
    if (score < scoreThreshold)
    {
        continue;
    }

    //placeholder
    SsdAnchor anchor = anchors[i];

    float sx = output0[0, 0, 0, 0, 0, 0, 0, i];
    float sy = output0[0, 0, 0, 0, 0, 0, 1, i];
    float w = output0[0, 0, 0, 0, 0, 0, 2, i];
    float h = output0[0, 0, 0, 0, 0, 0, 3, i];

    float cx = sx + anchor.x * width;
    float cy = sy + anchor.y * height;

    cx /= (float)width;
    cy /= (float)height;
    w /= (float)width;
    h /= (float)height;

    var keypoints = new Vector2[keypointsCount];
    for (int j = 0; j < keypointsCount; j++)
    {
        float lx = output0[0, 0, 0, 0, 0, 0, 4 + (2 * j) + 0, i];
        float ly = output0[0, 0, 0, 0, 0, 0, 4 + (2 * j) + 1, i];
        lx += anchor.x * width;
        ly += anchor.y * height;
        lx /= (float)width;
        ly /= (float)height;
        keypoints[j] = new Vector2(lx, ly);
    }

    results.Add(new Result()
    {
        score = score,
        rect = new Rect(cx - w * 0.5f, cy - h * 0.5f, w, h),
        keypoints = keypoints,
    });
}

output0.Dispose();
output1.Dispose();
```

Is there a better approach to reading the network output? My guess is each time I read a value from the Tensor object there is a CPU to GPU request? I can upload a sample project if that is better. Thanks!

**Comment by InternetSalmon** [comment]
I tried `Tensor.CopyToReadOnlyArray()` first with similar results. I've attached my test project below. 

The model I've converted from tf to onnx, I was previously using Tensorflow Lite with Unity for this project. My hope was that by keeping more resources on the GPU pipeline with Barracuda I'd be able to reduce inference times (with TF lite I have to read input textures to float arrays for the input tensor adding GPU-CPU sync lag).

> It means that GPU is still busy with inference workload. 

Does that suggest then that the model takes 73ms~ to complete inference? Would you have any recommendations on how I could improve that on my side or is that fixed with the current barracuda release? Unfortunately the TFlite model was ~15ms and thats why I thought Execute() in the profiler might have been the inference stage. 

Many thanks!

[TestProject.zip](https://github.com/Unity-Technologies/barracuda-release/files/5487918/TestProject.zip)
_The Barracuda source is slightly changed in the test project to support this model as per [padding issue](https://github.com/Unity-Technologies/barracuda-release/issues/91#issuecomment-720846383)_

**Comment by marson666** [comment]
> I tried `Tensor.CopyToReadOnlyArray()` first with similar results. I've attached my test project below.
> 
> The model I've converted from tf to onnx, I was previously using Tensorflow Lite with Unity for this project. My hope was that by keeping more resources on the GPU pipeline with Barracuda I'd be able to reduce inference times (with TF lite I have to read input textures to float arrays for the input tensor adding GPU-CPU sync lag).
> 
> > It means that GPU is still busy with inference workload.
> 
> Does that suggest then that the model takes 73ms~ to complete inference? Would you have any recommendations on how I could improve that on my side or is that fixed with the current barracuda release? Unfortunately the TFlite model was ~15ms and thats why I thought Execute() in the profiler might have been the inference stage.
> 
> Many thanks!
> 
> [TestProject.zip](https://github.com/Unity-Technologies/barracuda-release/files/5487918/TestProject.zip) _The Barracuda source is slightly changed in the test project to support this model as per [padding issue](https://github.com/Unity-Technologies/barracuda-release/issues/91#issuecomment-720846383)_

hi, I also meet the same problem, read tensor from gpu to cpu is very slow, have you solve the problem？
