### ISSUE TITLE
Incorrect batch size for Tiny-YOLO v2 on version 1.2.0

### ISSUE THREAD

**Issue by abeug** [Unity-Technologies/barracuda-release#104]
I am getting an unexpected batch size after executing the 
[Tiny YOLO v2](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2) model (with ONNX opset 8) on version 1.2.0. The batch size is as expected in versions 1.0.4, 1.1.0 and 1.1.2. I use an input shape of [1, 416, 416, 3] and expect and output shape of [1, 13, 13, 125] in version 1.0.4 or [1, 1, 1, 1, 1, 13, 13, 125] in later versions. However, in version 1.2.0 my output tensor has a shape of [1, 1, 3, 1, 1, 13, 13, 125] with a batch size of 3 instead of 1.

I have tried reimporting the model, unchecking optimized

Using version 1.2.0:
![barracuda1 2 0](https://user-images.githubusercontent.com/25258352/98023121-181cb300-1dcc-11eb-90f6-be939340ffb2.png)
 model checkbox.

I have noticed that the model constants are different between versions.

Constants in version 1.1.2:
![barracuda1 1 2](https://user-images.githubusercontent.com/25258352/98023261-47cbbb00-1dcc-11eb-99f8-394efa84ba43.png)

The output of the first batch is correct and the model works correctly, but there should only be 1 batch.

Additional info:
Using ComputePrecompiled worker.
Using StartManualSchedule to schedule layers on different frames.

**Comment by AlexRibard** [comment]
Hi @abeug sorry for the confusion. In 1.2 we added support for 8D tensors, as a result the UI became quite unreadable (if you are not familiar with our internal tensor layout).
Sorry about that, it will be addressed in a upcoming version.
For a 4D input internally we represent it as a 1,1,N,1,1,H,W,C tensor.
So in your case it looks to match your expected shape 1,416,416,3 => 1,1,N=1, 1, 1, H=416, W=416, C=3
The constants follow similar rules as in they are padded on 8D

However execution should remain identical and correct

**Comment by abeug** [comment]
The input shape is interpreted correctly, but the output shape is what is causing me confusion.
I expect the output shape to be the following:
1,13,13,125 => 1, 1, N=1, 1, 1, H=13, W=13, C=125

But on 1.2.0 i get N=3:
1,13,13,125 => 1, 1, N=3, 1, 1, H=13, W=13, C=125

**Comment by AlexRibard** [comment]
oh really? my bad I missed that in your comments. I'll take a look at it then.
Thanks for bringing it up

**Comment by abeug** [comment]
Here is some proof using the visual studio debugger:

Version 1.1.2 (but also similar on 1.0.4, and 1.1.0):
![barracuda1 1 2Batch1](https://user-images.githubusercontent.com/25258352/98143034-3cd95f00-1e8e-11eb-8012-c20046b30fcf.png)


Version 1.2.0:
![barracuda1 2 0Batch3](https://user-images.githubusercontent.com/25258352/98143047-3f3bb900-1e8e-11eb-87e1-98255fb26af4.png)

**Comment by AlexRibard** [comment]
Ok I got the bug, will fix it for the next release

**Comment by abeug** [comment]
Good to hear. Thanks.

**Comment by abeug** [comment]
This issue is still present on version 1.2.1.

Input:
![TinyYoloV2InputBarracuda1 2 1](https://user-images.githubusercontent.com/25258352/103937297-306fbd80-50ee-11eb-8a62-d95a3b00cf05.png)

Output:
![TinyYoloV2OutputBarracuda1 2 1](https://user-images.githubusercontent.com/25258352/103937316-38c7f880-50ee-11eb-9a06-a50a95b1ce1e.png)

The output still has 3 batches when it should be 1.

**Comment by AlexRibard** [comment]
strange! Let me double check.
1.2.1 was more a patch than a full version so it could very well be that we missed to merge the fix on that version

**Comment by abeug** [comment]
Batch size returns the expected value of 1 on version 1.3.0.
