### ISSUE TITLE
Image super-resolution with Barracuda, problem with output

### ISSUE THREAD

**Issue by tvkamara** [Unity-Technologies/barracuda-release#105]
Hi All, I'm trying to use an ONNX super-resolution model in Barracuda as I noticed there were some promising commits in the latest version regarding support for super-resolution. I'm using a network from here (https://github.com/dusty-nv/super-resolution) which is using RGB input as I'm trying to avoid any YUV conversions. The network seems to be exactly this (https://github.com/onnx/models/tree/master/vision/super_resolution/sub_pixel_cnn_2016) just with RGB input (3 channels).

I haven't properly trained my network yet, just a couple of epochs so in Torch-side I get a valid looking output (looks similar to input at least). I'm able to export the model to Unity (Barracuda) and input a RenderTexture (which looks correct also when sanity checking and importing back to Texture from Tensor). The only problem left is a weird-looking output. I'm attaching a screenshot here with the input on the left and the output on the right:

![image](https://user-images.githubusercontent.com/8319136/98635398-94177d80-232d-11eb-88c9-db9d9a4fa31d.png)

I'm wondering if the color channels somehow get mixed as there seems to be 3 "strips" in the output image. I'm using the built-in ToRenderTexture -function for displaying the output Tensor.

`outputTensor.ToRenderTexture(outputTexture, 0 /* batch */, 0 /* from channel */, 1 /* scale */, 0 /* bias */, null /* lut texture */);`

Here is the network I'm using:

[super_resolution_5.zip](https://github.com/Unity-Technologies/barracuda-release/files/5515199/super_resolution_5.zip)

Do you have any sample of a working super-resolution model or a Barracuda "texture to texture" pipeline I could have look at? Or perhaps an idea what could be going wrong in the ONNX to Barracuda conversion.

Thanks,
Teemu

**Comment by mantasp** [comment]
@tvkamara thank you for reporting this!
We will add your model to our investigation list.

**Comment by AlexRibard** [comment]
Hey @tvkamara there is indeed an error coming from the end part of the model
![image](https://user-images.githubusercontent.com/12990800/98714608-18322b00-2357-11eb-8c96-887ba0058f35.png)
We are checking the bug

**Comment by tvkamara** [comment]
Ok, good to know. Thank you both for your quick response!

**Comment by FlorentGuinier** [comment]
Hey @tvkamara , Just to let you know that the fix is currently in landing process. I will let you know in what version it goes probably 1.3.0.

**Comment by FlorentGuinier** [comment]
Hey @tvkamara, fix have landed and will be present in next Barracuda version (1.3.0). Thanks for taking the time to report!

**Comment by tvkamara** [comment]
Awesome, thank you very much!
