### ISSUE TITLE
My barracuda model(NN model) don't have input name

### ISSUE THREAD

**Issue by gkhj0516** [Unity-Technologies/barracuda-release#106]
Hi

I have h5 file and converted to barracuda model.
But, I can't find input name of NN model in unity.

What can I do? Help me please

![my_model](https://user-images.githubusercontent.com/59754664/98662266-e33fcb80-238a-11eb-9021-ab0f9591b01f.png)

**Comment by mantasp** [comment]
It's probably just some whitespace character. Though for models that use single input you could just use `IWorker.Execute(input)`method that doesn't require to pass input name.
