### ISSUE TITLE
Update from 1.0.4 to 1.2.0

### ISSUE THREAD

**Issue by DanielDorDev** [Unity-Technologies/barracuda-release#107]
Great update, tested the new cpu brust, and it seems amazing.

what am i looking to change or to deal with differently when updating from 1.0.4 to 1.2.0, because straight forward update mass the results, meaning, all prcoess from input to output , acts different in 1.2.0

**Comment by mantasp** [comment]
@DanielDorDev could you please provide more details on specific issues you see?

**Comment by DanielDorDev** [comment]
> @DanielDorDev could you please provide more details on specific issues you see?

Exmaple of using the same input, different version, different results( 1.0.4 & 1.2.0) .

Outputs:

1.0.4:
2.078794E-09 1.22584E-08 6.612019E-10 7.467452E-08 1.025297E-09 2.315215E-08 3.946147E-09 3.08494E-07 9.06745E-08 1.395142E-08 **6.193861E-09 3.305571E-07** 7.283347E-08 9.086062E-08 

1.2.0:
2.078791E-09 1.22585E-08 6.612019E-10 7.467462E-08 1.025297E-09 2.315215E-08 3.946152E-09 3.084944E-07 9.067521E-08 1.395142E-08 **6.193869E-09 3.305566E-07** 7.283386E-08 9.086074E-08 


It's important because i am using argMax, therefore diffrenet outputs influence the final results 
for example bolded results

**Comment by AlexRibard** [comment]
That seems reasonable margins of errors.
Our usual floating point error tolerance is 10e-4 or 10e-5.
Depending on the version, operators are optimized/refactored sometimes resulting is some floating point errors/differences.
+ it is hard to judge which is the more correct result, one would need to validate with double inference in onnx-runtime/pytorch to be sure.
If 10e-5 precision is important for you, you can try removing optimizations and switching to a `ComputeRef` worker, as they tend to be slightly more stable.
Let me know.

**Comment by DanielDorDev** [comment]
> That seems reasonable margins of errors.
> Our usual floating point error tolerance is 10e-4 or 10e-5.
> Depending on the version, operators are optimized/refactored sometimes resulting is some floating point errors/differences.
> 
> * it is hard to judge which is the more correct result, one would need to validate with double inference in onnx-runtime/pytorch to be sure.
>   If 10e-5 precision is important for you, you can try removing optimizations and switching to a `ComputeRef` worker, as they tend to be slightly more stable.
>   Let me know.

The problem was tensor shape, i didn't realize at first that 8D change the way i am indexing data, after change shape[3] => shape[7] and etc, it works fine 👍 

for brust: , "Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak"
Internal: deleting an allocation that is older than its permitted lifetime of 4 frames (age = 5)

Is it important?

**Comment by AlexRibard** [comment]
Unless you are managing burst job, we probably have a leak somewhere. Thanks for bringing it up, I'll keep a eye out for this bug in the future.
Which back-end are you using? (Compute, CSharp)

**Comment by DanielDorDev** [comment]
> Unless you are managing burst job, we probably have a leak somewhere. Thanks for bringing it up, I'll keep a eye out for this bug in the future.
> Which back-end are you using? (Compute, CSharp)

I am using CSharpBurst

Really impressive performance, barracuda allows executing heavy NN in mid-end devices 👍 

But still unlike GPU backend , it is unstable, why is it?
