### ISSUE TITLE
Loading a model at runtime

### ISSUE THREAD

**Issue by albanmdb3d** [Unity-Technologies/barracuda-release#108]
Hi, 

I'm a bit confused about loading a model at runtime. Say I am creating a package using Barracuda with an .onnx model. How can I load the model from path ? The documentation allows the import of .bc (.barracuda ?) at runtime. What are they ? How do I convert my .onnx to a .bc ?
Thanks!

**Comment by AlexRibard** [comment]
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Loading.md
Does this help?
Your file should be a .onnx in the Asset/Ressources folder
You then need to load the binary and compile it as a model
```
var assetName = "myOnnxfile.onnx";
var modelBinary = Resources.Load<NNModel>(assetName.Substring(0, assetName.LastIndexOf('.')));
return ModelLoader.Load(modelBinary, Verbose);
```

**Comment by albanmdb3d** [comment]
Thanks for the reponse. From the doc you linked, under runtime loading, doing ModelLoader.Load(modelPath) expects a .bc file. That's the part I find confusing as it's not explicit what those are. 
Your code works, but I don't necessarily want my file to be in the Ressources folder

Edit: I did some reading about Resources.Load. It actually loads from all directories called Resources. This means as long as I have a Resources folder in my package, I'm good.

**Comment by albanmdb3d** [comment]
Actually, what I would like to do is load my model from a script. I want my model to be anywhere on the disk, not in my Unity project or package. Is this possible?

Edit: I was successful using AssetBundles. For anyone interested, create the asset bundle from a .onnx file in unity. To load, something like this does the trick

```csharp
var bundleLoadRequest = AssetBundle.LoadFromFileAsync("path/to/bundle/bundle_name");
var myLoadedAssetBundle = bundleLoadRequest.assetBundle;
var assetLoadRequest = myLoadedAssetBundle.LoadAssetAsync<NNModel>("model_name");
Model model = ModelLoader.Load((NNModel)assetLoadRequest.asset, true);
```

I'm still interested in the .bc files though.

**Comment by mantasp** [comment]
.bc files can be loaded the same way, just rename them to have .nn extension.
