### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by nukadelic** [Unity-Technologies/barracuda-release#11]
**Colab Research Google Notebook**
```
tensorflow-1.15.0
keras-2.2.5
numpy-1.17.4
onnx-1.6.0
h5py-2.8.0
barracuda scripts ( 0.3.2 )
```
Saved, then loaded h5 files and got this message
```
/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py:310: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
```
Converted h5 to pb via : https://stackoverflow.com/a/45466355/2496170
```
WARNING:tensorflow:From <ipython-input-42-102ff4f8144d>:32: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 16 variables.
INFO:tensorflow:Converted 16 variables to const ops.
```
### ERROR 
when running this line 
`!python './drive/My Drive/unity.barracuda.0.3.2/Tools/tensorflow_to_barracuda.py' ./models/encoder_model.pb ./export/encoder_model.nn`

```
Converting ./models/encoder_model.pb to ./export/encoder_model.nn
WARNING:tensorflow:From /content/drive/My Drive/unity.barracuda.0.3.2/Tools/tensorflow_to_barracuda.py:1328: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

Traceback (most recent call last):
  File "./drive/My Drive/unity.barracuda.0.3.2/Tools/tensorflow_to_barracuda.py", line 21, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "/content/drive/My Drive/unity.barracuda.0.3.2/Tools/tensorflow_to_barracuda.py", line 1373, in convert
    lambda tensor: get_tensor_data(tensor))
  File "/content/drive/My Drive/unity.barracuda.0.3.2/Tools/barracuda.py", line 221, in setup_constants
    data = np.reshape(get_tensor_data_lambda(tensor), shape).astype(np.float32))]
  File "/content/drive/My Drive/unity.barracuda.0.3.2/Tools/tensorflow_to_barracuda.py", line 1373, in <lambda>
    lambda tensor: get_tensor_data(tensor))
  File "/content/drive/My Drive/unity.barracuda.0.3.2/Tools/tensorflow_to_barracuda.py", line 658, in get_tensor_data
    return np.array(data).reshape(dims)
UnboundLocalError: local variable 'data' referenced before assignment
```

Edit: printed the data type of the tensor that caused the issue, its a `DT_INT64`

Edit 2: 
For my current use case did a quick modification of the `tensorflow_to_barracuda.py` ([gist](https://gist.github.com/nukadelic/fe2ae08e834a6cecc36fb38d73482f89)) file to return None and skipp adding the item to the array of tensors, ran the same script again, now i see this message:
```
[x] UNSUPPORTED: data type DT_INT64
GLOBALS: 'dense_1/kernel', 'dense_1/bias', 'dense_2/kernel', 'dense_2/bias', 'SGD/iterations', 'SGD/lr', 'SGD/momentum', 'SGD/decay', 'training/SGD/Variable', 'training/SGD/Variable_1', 'training/SGD/Variable_2', 'training/SGD/Variable_3', 'dense_2_1/kernel', 'dense_2_1/bias'
IN: 'input_1_1': [-1, 1, 1, 3] => 'dense_1_1/BiasAdd'
OUT: 'dense_1_1/Relu'
DONE: wrote encoder_model.nn file.
``` 
then imported the generated file into unity. On the initial import i was able to see the file asset in the inspector and view all the tensors from there, but once i have created a script and moved the NN file into the streaming assets folder, loaded it from a mono script it became a generic white icon file, i don't seem to see any errors or warning tho. During play mode start the unity now outputs all the tensors information to the console.

**Comment by nukadelic** [comment]
Well i just solved it in #12 
so this [gist](https://gist.github.com/nukadelic/fe2ae08e834a6cecc36fb38d73482f89) looks like a temporary solution for 0.3.2
ill keep it open so it will be visible with the link above

**Comment by mantasp** [comment]
`but once i have created a script and moved the NN file into the streaming assets folder, loaded it from a mono script it became a generic white icon file`
this is expected behaviour as `StreamingAssets` folder has special meaning to deliver files directly to the final build bypassing whole import pipeline, so in this case it is treated as regular system file.

**Comment by nukadelic** [comment]
yea i realized that after moving the file back and forth, figured to keep the post as it is, thanks @mantasp
