### ISSUE TITLE
Different outputs between onnx-runtime and barracuda!

### ISSUE THREAD

**Issue by FD-MINGJIE** [Unity-Technologies/barracuda-release#112]
Hello, Alex:
       Nice to meet you. Well, I find the similar bug like issue#109 that same input indeed produces **different output in onnx-runtime and barracuda**.  Left picture is produced by barracuda and right picture is produced by onnxruntime.
![result_barracuda](https://user-images.githubusercontent.com/43561860/99501399-a725ef80-29b6-11eb-9f41-650a83383a92.jpg) Left picture![result_onnxruntime](https://user-images.githubusercontent.com/43561860/99501410-aab97680-29b6-11eb-9b77-90e7e0309374.jpg) Right picture
      1. The problem may be lie in **‘Reshape’** operation, which may cause channel shuffle(RGB shuffle) in memory. 
      2. And there is some difference in python script and barracuda when i debug the output after **'Upsample'** operation. The upsample in python will pad bias in the feature map, but no any changes in barracuda.
      So, I hope you can _check the output tensor_ and solve my problem if you have enouth time. All test scripts are as following:
[TensorBug.zip](https://github.com/Unity-Technologies/barracuda-release/files/5558873/TensorBug.zip)
      Thanks: ) 
      Thanks: )
      Thanks: )

**Comment by FlorentGuinier** [comment]
Hi FD-MINGJIE, This is most likely a bug on our end. 
I'm gonna investigate and will let you know if more info are needed for the repro. 

Thanks for taking the time to report this!

**Comment by FD-MINGJIE** [comment]
Hi, @FlorentGuinier:
     Is there any discovery or progress? 
     I found the problem lies in the local chaos in channel data storage when the channel changes between NCHW and NHWC during model conversion from onnx into barracuda(i.e. when calling Model.load() from script ONNXModelConverter.cs).
     I don't know why ONNXModelConverter class was not called when making a breakpoint in ONNXModelConverter.cs script.
![image](https://user-images.githubusercontent.com/43561860/99938956-f77cc300-2da3-11eb-91ad-4eb55e5518bb.png)
    Thanks for taking the time to fix this!

**Comment by FlorentGuinier** [comment]
Hi FD-MINGJIE, We have indeed a bug on the first reshape layer of the network.
![image](https://user-images.githubusercontent.com/20201082/99971004-e8464700-2d9c-11eb-80a1-b6eaa736a75a.png)

ONNX is channel first: _Reshape_ take a 2D tensor and convert it to 4D NCHW[1,32,16,16] shape
Barracuda import as channel last and _Reshape_ take a 2D tensor and convert it to 4D NHWC[1,16,16,32] shape

However this is not equivalent, we should insert a transpose to match ONNX behavior here, i'm currently looking into this.

Have a great day
Florent

**Comment by FlorentGuinier** [comment]
Hey FD-MINGJIE, fix have landed and will be present in next Barracuda version (1.3.0), again thanks for taking the time to report!

**Comment by FD-MINGJIE** [comment]
Awesome, too strong, thank you very much！
Have a good day!
I just got off work！
