### ISSUE TITLE
Inconsistent results across inferences (windows)

### ISSUE THREAD

**Issue by albanmdb3d** [Unity-Technologies/barracuda-release#113]
Hello,

Up until now, I only used Barracuda on Linux. I switched to windows to do some testing. I noticed that my inferences are not deterministic. Sometimes the results are correct, sometimes they are widely off. I never had that issue on linux. I don't dispose of my memory properly. Could that be the issue ? Below are some examples.
Additionally, I notice that my bounding boxes predictions don't change, but my segmentation masks do. Interesting.

<img width="412" alt="good" src="https://user-images.githubusercontent.com/69472378/99716665-6392ba80-2a76-11eb-9c14-a11b5083eb48.PNG">
<img width="377" alt="bad" src="https://user-images.githubusercontent.com/69472378/99716672-65f51480-2a76-11eb-8c79-9ef135829a15.PNG">

Thanks!

**Comment by mantasp** [comment]
Could you please post your main inference loop code? Maybe you are starting new inference while previous one hasn't yet finished?

**Comment by albanmdb3d** [comment]
Hi, 

I think I found the issue but I am still puzzled as to why it happens. 
My inference is actually decomposed in two steps: the main network and some post-processing steps that are decomposed into subnetworks and manual IOps calls.
I created a network class to wrap my ONNX model. My "Forward" method is followed by the post-processing steps. 

Below is my network class:
```csharp
public class Network
{
    protected Model model;                 // Runtime model wrapper (binary)
    protected IWorker modelWorker;       // Barracuda worker for inference
    private string[] outputNames;

    public Network(NNModel modelSource, string[] outputNames)
    {
        this.outputNames = outputNames;

        model = ModelLoader.Load(modelSource);
        ModelBuilder builder = new ModelBuilder(model);
        modelWorker = WorkerFactory.CreateWorker(WorkerFactory.Type.ComputePrecompiled, builder.model, outputNames, false);
    }

    /// <summary>Performs forward propagation of the network. </summary>
    /// <param name="inputs">Dictionary of tensors following Barracuda convention.</param>
    public IDictionary<string, Tensor> Forward(IDictionary<string, Tensor> inputs)
    {
        modelWorker.Execute(inputs);

        IDictionary<string, Tensor> outputs = new Dictionary<string, Tensor>();
        foreach(string outputName in outputNames)
            outputs[outputName] = modelWorker.PeekOutput(outputName);
        
        return outputs;
    }

    /// <summary>Performs forward propagation of the network. <summary>
    /// <param name="inputs">Dictionary of tensors following Barracuda convention.</param>
    public async Task<IDictionary<string, Tensor>> ForwardAsync(IDictionary<string, Tensor> inputs)
    {
        var executor = modelWorker.StartManualSchedule(inputs); 

        bool hasMoreWork;
        do
        {
            hasMoreWork = executor.MoveNext();
            modelWorker.FlushSchedule();
            await Awaiter.Instance.magicAwaiter.Await();  // Allows me to allocate a certain amount of time before yielding

        } while (hasMoreWork);

        IDictionary<string, Tensor> outputs = new Dictionary<string, Tensor>();
        foreach(string outputName in outputNames)
            outputs[outputName] = modelWorker.PeekOutput(outputName);

        
        return outputs;

    }

    /// <summary>Primes the network for inputs.</summary>
    /// <param name="inputShapes">Shapes of input tensors.</param>
    public void PrepareForInput(IDictionary<string, TensorShape> inputShapes)
    {
        modelWorker.PrepareForInput(inputShapes);
    }

    /// <summary>Free network memory. Must be called explicitely.</summary>
    public virtual void Dispose()
    {
        modelWorker?.Dispose();
    } 
}
```

In my inference method, I call the "Forward" or "ForwardAsync" followed by the postprocessing.
```csharp
    public async Task<Tensor> ComputeInstanceMasksOnRenderTexture(RenderTexture inputTexture) 
    {
        IDictionary<string, Tensor> inputs = new Dictionary<string, Tensor>();
        inputs["images"] = new Tensor(inputTexture, 3);

        IDictionary<string, Tensor> outputs = Network.Forward(inputs);  // Alternatively, call ForwardAsync with await
        TensorUtils.DisposeTensors(inputs);

        IDictionary<string, Tensor> processedOutputs = await PostProcess(outputs);
       
        return processedOutputs ["masks"];
    }
```

I usually call my ForwardAsync method to allocate the time I want for inference per frame. However, on windows, it creates the issues above. On Linux, it's fine. I found that if I do something in between network forward pass and post-processing (e.g. printing the values of a tensor), the issue disappears. If I call my Forward method, it works fine.

**Comment by mantasp** [comment]
How does `PostProcess()` method look like?

**Comment by albanmdb3d** [comment]
Hello, sorry for the late reply.
I've upgraded to 1.2.0 which allowed me to clean up PostProcess() very nicely and it fixed the problem (I still don't know where it came from). This is really taking shape and I really like the direction Barracuda is taking. Thanks'!
