### ISSUE TITLE
Odd Input Shapes

### ISSUE THREAD

**Issue by abigos** [Unity-Technologies/barracuda-release#114]
Hi,

I have some unexpected input/output shapes when I load the attached simple model.  I expect to see a (-1,3) or similar shapes, but I see (1,1,0,1111,3).  You can verify the expected shape in Netron or similar.  Any ideas?

Thanks,
Andy

[diffuse_net.zip](https://github.com/Unity-Technologies/barracuda-release/files/5589572/diffuse_net.zip)

**Comment by mantasp** [comment]
At the moment we are showing all 8 tensor dimensions we support, which sometimes is bit confusing. There is UI improvement in the works, which will reduce the noise. Here is quick tip how to decode these dimensions:
1 - sequence number (currently unused, default 1)
1 - direction number (currently unused, default 1)
0 - batch size (0 or -1 mean any batch size you pass will override this)
1 - extra dimension (currently unused, default 1)
1 - depth dimension (currently unused, default 1)
1 - height dimension (height of the spatial input, default 1)
1 - width dimension (width of the spatial input, default 1)
3 - channels dimension (default 1)

**Comment by abigos** [comment]
Great - thanks for the quick clarification - much appreciated.

**Comment by abigos** [comment]
Actually can I just ask for a clarification @mantasp .  I'm using the network attached and I get an error 'Off-axis dimensions must match' - but it's not clear where it's coming from.  From your description above this would load a 4096 long vector of 3 component values.

```
int n = 1;
int w = 4096;
int h = 1;
int c = 3;
m_RuntimeModel = ModelLoader.Load(modelAsset);
var engine = WorkerFactory.CreateWorker(m_RuntimeModel, WorkerFactory.Device.CPU);

var position = new Tensor(n, w, h, c, "position");
var direction = new Tensor(n, w, h, c, "normal direction");

var inputs = new Dictionary<string, Tensor>();
inputs["position"] = position;
inputs["normal direction"] = direction;      

var output = engine.Execute(inputs).PeekOutput();
```

The difference in the axes is show as:  (1, 1, 1, 1, 1, 1, 1, 32) vs (1, 1, 1, 1, 1, 4096, 1, 3)  - but the expected shape is not the input shape.

I'm not sure if it's related but the inputs to the model don't all get routed to the first layer:  
![image](https://user-images.githubusercontent.com/836739/100111521-15126100-2e66-11eb-8a2f-d39eddc16c22.png)

Thanks

**Comment by AlexRibard** [comment]
Hi @abigos can you declare your Tensor as follows:
```
// they are 2D tensors, you can declare them using the 2D constructor
var position = new Tensor(4096, 3, "position");
var direction = new Tensor(4096, 3, "normal direction");

var inputs = new Dictionary<string, Tensor>();
inputs["position"] = position;
inputs["normal direction"] = direction;      

var output = engine.Execute(inputs).PeekOutput();
```
On top of the layout @mantasp told you, we are in NHWC layout compared to NCHW ONNX.
Thus there is some internal mapping going on
```
ONNX 2D: NC  -> N__C Barracuda
ONNX 3D: NCW -> N_WC Barracuda
ONNX 4D: NCHW -> NHWC Barracuda
(_ = 1)
```
It can require a bit of metal gymnastic to remember the mapping, so I would recommend using the default constructor depending on the dimension

**Comment by abigos** [comment]
Doh!  Thanks @AlexRibard and @mantasp for the great support - do appreciate it.
