### ISSUE TITLE
[iOS] Execution of the command buffer was aborted due to an error during execution.

### ISSUE THREAD

**Issue by BorisKourt** [Unity-Technologies/barracuda-release#115]
Using the barracuda style transfer example, building on Unity 2020.2 for iOS 14.2, running on an iPad Pro (Spring 2020) 

The version of barracuda is: 1.1.2-preview as 1.2.0 appears to cause the error I see here: https://github.com/UnityLabs/barracuda-style-transfer/issues/1

I get the following error when attempting to initiate style transfer:

```
Test[828:227543] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
```

This works fine on the Mac itself, running metal. The iPad should be running metal as well.

The build in both unity and xcode don't provide any warnings or issues.

Best,
Boris

**Comment by mantasp** [comment]
Thanks for reporting issue with 1.2.0. Regarding, iOS, this demo is meant to be desktop-only.

**Comment by BorisKourt** [comment]
@mantasp is that a limitation for the way style transfer is implemented? Anything I can update to run style transfer on iOS?

**Comment by mantasp** [comment]
In general it wasn't tested or optimised for iOS and is expected to be very slow or not work at all.

**Comment by BorisKourt** [comment]
After testing style transfer using native iOS tools on these newer devices (especially the 2020 pros) it appears that the Neural Engine chip shipping with them can provide some pretty decent performance for some workloads. Does Barracuda plan to take advantage of this in the future? 

I was able to style transfer a 720p back camera feed, fairly reliably and without many of the optimizations I could have made. I understand that this also doesn't include a 3D workload on top of it, but it seems that the GPU and neural engine can be quite complimentary.

**Comment by AlexRibard** [comment]
@BorisKourt 
Spot on. Yes we plan on adding support for neural chips for high end mobiles in the future.
Atm it is still internal WIP however.

**Comment by BorisKourt** [comment]
Looking forward to it. Happy to help test it out as well!
