### ISSUE TITLE
Broadcastable MatMul

### ISSUE THREAD

**Issue by albanmdb3d** [Unity-Technologies/barracuda-release#116]
Hello, 

I simply would like to know if broadcastble MatMul is anything you are considering. Currently, what I am trying to achieve is doing something like this

```python
C = A @ B
```
where A and B are pytorch tensors of shapes (H, W, n) and (n, k) respectively. The equivalent c# code is something like this:

```csharp
        // prototypes of shape (1, H, W, 32)
        // mask_coefficients of shape (k, 1, 1, n)
        Tensor[] masksParts = new Tensor[prototypes.shape.height];
        Tensor prototypesTemp = mOps.Transpose(prototypes, new[] {2, 1, 0, 3});  // shape (W, H, 1, n)
        Tensor maskCoefficientsTemp = mOps.Transpose(maskCoefficients, new[] {3, 1, 2, 0});  // shape (n, 1, 1, k)

        for (int h = 0; h < prototypes.shape.height; h++)
        {
            Tensor prototypePart = mOps.StridedSlice(prototypesTemp, new[] {0, h, 0, 0}, new[] {0, h+1, 0, 0}, new[] {1, 1, 1, 1});
            masksParts[h] = mOps.MatMul(prototypePart, false, maskCoefficientsTemp, false);
        }

        Tensor rawMasks = mOps.Concat(masksParts, 5);  // shape (1, 1, W = 128, 1, 1, H = 128, 1, k)
        rawMasks = mOps.Transpose(rawMasks, new[] {2, 1, 0, 3});  // shape (1, H, W, k)

        return rawMasks;
```

So in this case A = prototypes, B = maskCoefficients. Right now, MatMul asserts the dimensions are equal, which in this case they are not (3 != 2). I could repeat tensor B but the Tile operator is not currently implemented (as of 1.2.0).

Any feedback?

Thanks'

**Comment by albanmdb3d** [comment]
I found a workaround using Expand. I didn't know the operator existed. For anyone interested:

```csharp
        Tensor prototypesTemp = mOps.Transpose(prototypes, new[] {1, 2, 3, 0});  // shape (H, W, n, 1)
        Tensor maskCoefficientsTemp = mOps.Transpose(maskCoefficients, new[] {1, 3, 0, 2});  // shape (1, n, k, 1)
        Tensor maskCoefficientsTempExpanded = mOps.Expand(maskCoefficientsTemp, new TensorShape(128, maskCoefficientsTemp.shape.height, maskCoefficientsTemp.shape.width, 1));  // shape (H, n, k, 1)

        Tensor rawMasksTransposed = mOps.MatMul(prototypesTemp, false, maskCoefficientsTempExpanded, false);  // shape (H, W, k, 1)
        Tensor rawMasks = mOps.Transpose(rawMasksTransposed, new[] {3, 0, 2, 1});  // shape (1, H, W, k)
```

Edit: Actually, this is only works n >1 or k > 1. Otherwise the assertion is raised (3 != 2). 
Perhaps it should be removed ?

**Comment by AlexRibard** [comment]
hey @albanmdb3d !
Yes multi dim matmul is something we are looking to supporting. There is some support coded for the upcoming version (code performance is still sub-par however). The main issue atm is broadcast rules with different dimensions. We haven't found an elegant way of supporting it (without some more custom implementation that is)
One idea that has some traction is the following:
A : (7,2,5) x B (5, 6) -> reshape A to (7*2, 5) x (5, 6) -> (7*2, 6) reshape to (7,2,6)
But when broadcasting to the right it breaks the current code and would require some custom code.
You can always Slice A on batches -> do the matmul (2,5) x (5,6) -> concatenate on batches to get the final result.
I'll let you know once we have a simpler solution

**Comment by albanmdb3d** [comment]
Hi Alex! Thanks' for the feedback. I'm glad you are working on it. For now I simply commented the assertion and it works fine so that will do for now. The performances are not great though.

On a different but related topic, I'm wondering if it is possible to create a handwritten worker that uses the shape of a previous layer output as a variable. Something like this:

```csharp
builder.Expand("maskCoefficientsTempExpanded", "maskCoefficientsTemp", new int[] {128, 32, previous_layer.shape.width, 1}
```

Thanks

**Comment by albanmdb3d** [comment]
@AlexRibard ?

**Comment by AlexRibard** [comment]
@albanmdb3d apologies for the later reply.
On which version are you on? Do you have access to `ModelBuilder : public Layer Shape(string name, object input, int axis = -1)`
It works as follows:
```
if (axis > 0)
    O = { shape[axis] };
else
    O = shape;
```
Be careful with the indexing on 1.2.0 as internally shapes are 8D.
Alternatively given that this op is done on the CPU, it wouldn't change much if you fed `tensor.shape.ToArray()`, or `{tensor.batch, tensor.height, tensor.width, tensor.channels}` to said network.

I would recommend the second option as it will be less bug prone given our shapes being padded either to 4D or 8D internally.

**Comment by albanmdb3d** [comment]
Hi Alex. I am working with Barracuda 1.2.0 so I have access to the shape op. Adding a shape layer is pretty straightforward in a builder. What is less so is using the result 

```csharp
ModelBuilder builder = new ModelBuilder();

builder.Shape("predictionsCount", "maskCoefficients", axis:2);
builder.Expand("maskCoefficientsExpanded", "maskCoefficients", new[] {128, 32, previousLayer.Value, 0});  // How to use shape dimension in new shape ?
```

Thanks!

**Comment by AlexRibard** [comment]
Ah yes, if you want to do it that way it will not work.
Unfortunately some ops only support static inputs. That is the case for Expand and the shape input. 
As a rule of thumb, for shape inference, a lot of the logic is baked down at import time so anything involving a dynamic shape will unfortunately not work most of the time.
So at the modelbuilder stage, the final op with have shape baked down.
For your case you'd need to hard code the shape I'm afraid.
Why not use a `Concat` node then? And concat maskCoefficientsTemp on the batch axis H times?

**Comment by albanmdb3d** [comment]
Oh indeed that's a clever trick. Silly me. Thank you again.
