### ISSUE TITLE
Custom worker Reduce layer error

### ISSUE THREAD

**Issue by albanmdb3d** [Unity-Technologies/barracuda-release#117]
Hello again.

I am working with Barracuda 1.2.0. I am having trouble with Reduce layers with custom workers. 
```csharp
builder.Reduce(Layer.Type.ReduceMax, "maxClassConfidence", "slicedSoftmaxConfidence");
```

This code always throws KeyNotFoundException: The given key was not present in the dictionary. I am positive that the key exists. This used to work in 1.0.2. Doing the same with a computeOps works however.

```csharps
Tensor maxClassConfidence = mOps.ReduceMax(slicedSoftmaxConfidence, -1);
```

Am I missing something?

Thanks'

**Comment by AlexRibard** [comment]
Hi! Sorry for the late reply.
How are you using the model builder?
```
Model model = new Model();
var builder = new ModelBuilder(model);

// optional
var input = new Model.Input();
input.name = "input";
input.shape = (new TensorShape(1, 37, 37, 2)).ToArray();
builder.model.inputs.Add(input);


builder.Reduce(Layer.Type.ReduceMax, "reduceLayer", "input", axis:3);

// optional
List<string> outputs = new List<string> { "reduceLayer" };
builder.model.outputs = outputs;

Tensor I = new Tensor(1,37,37,2);
var worker = WorkerFactory.CreateWorker(workerType, model);
worker.Execute(I);
```
Could it be that you are stitching this layer to an input model? does the string literal of the layers matches?
What about when calling execute?

**Comment by albanmdb3d** [comment]
Ooooh I found what causes the bug. For some reasons, It won't work on 1D arrays (in theory the op shouldn't do anything in that case). 

Try the following code. It will throw the KeyNotFound error I'm talking about. I don't believe it was an issue back in 1.0.2. 
```csharp
        Model model = new Model();
        var builder = new ModelBuilder(model);

        // optional
        var input = new Model.Input();
        input.name = "input";
        input.shape = (new TensorShape(10, 1, 1, 1)).ToArray();
        builder.model.inputs.Add(input);


        builder.Reduce(Layer.Type.ReduceMax, "reduceLayer", "input", axis:3);

        // optional
        List<string> outputs = new List<string> { "reduceLayer" };
        builder.model.outputs = outputs;

        Tensor I = new Tensor(10, 1, 1, 1);
        var worker = WorkerFactory.CreateWorker(WorkerFactory.Type.ComputePrecompiled, model);
        worker.Execute(I);

        Tensor outTensor = worker.PeekOutput();
        Debug.Log(outTensor.shape);
```

Thanks' for the continuous support it's really appreciated.

**Comment by AlexRibard** [comment]
Ok thanks! I will try out said code and check the regression then.

**Comment by albanmdb3d** [comment]
Thanks' I'm closing the issue

**Comment by kyuhyoung** [comment]
@albanmdb3d 
Hello.  albanmdb3d
Based on what you wrote, I think you had worked on YOLO segmentation. For the post-processing of YOLO segmentation, I am wondering which is the faster way between using Barracuda Tensor Ops or Unity shader.  
I can not find you contact point.  If you prefer direct message, you can message me at kyuhyoung@gmail.com
