### ISSUE TITLE
Asset import failed

### ISSUE THREAD

**Issue by Roberto7766** [Unity-Technologies/barracuda-release#121]
Hi,
I'm trying to import a Tensorflow based NN. I converted the network from tensorflow to ONNX and then I quantized the ONNX format. The issue is that I cannot import this into Unity because I obtain:

_OnnxImportException: Unknown type DynamicQuantizeLinear encountered while parsing layer StatefulPartitionedCall/inference_model/resnet/conv1_conv/Conv2D__6:0_quantized._

_Asset import failed, "Assets/Models/model_quant.onnx" > OnnxImportException: Unknown type DynamicQuantizeLinear encountered while parsing layer StatefulPartitionedCall/inference_model/resnet/conv1_conv/Conv2D__6:0_quantized._

What shall I do? Thank you.

**Comment by AlexRibard** [comment]
Hi @Roberto7766 
We don't support the operator `DynamicQuantizeLinear` atm.
Looking at it it doesn't seem too hard to add support to it.
Could you provide your onnx model for reference?

Thanks

**Comment by Roberto7766** [comment]
Hi @AlexRibard 
Yes I can share the model. It is quite huge: which is the best way to share it?

Thank you

**Comment by AlexRibard** [comment]
ah! can you share a google drive link? or a zip file?

**Comment by Roberto7766** [comment]
Hi @AlexRibard,
here the drive link.
https://drive.google.com/file/d/1itnI5uLngTYx_Q_Y2cdykH3n-N7KRVaa/view?usp=sharing

Please let me know when you download it in order to remove the link.
Thanks

**Comment by AlexRibard** [comment]
Ok thanks. I have requested access. My email is barracuda-support@unity3d.com

**Comment by AlexRibard** [comment]
@Roberto7766 sorry for the late reply. We do not support quantized model in Barracuda.
We don't have short term plans on supporting it, but maybe we should un-quantize the weights at import time
