### ISSUE TITLE
model does not work on android (emulator and real device)

### ISSUE THREAD

**Issue by sharpgraf** [Unity-Technologies/barracuda-release#123]
Hi ! Tried many options to make my model work. Used vulkan and opengl, changed baracuda versions from 1.04 to the latest preview version. I used cpu and gpu, but still nothing. 
Everything works fine in editor
What could go wrong? 

notebook:
https://colab.research.google.com/github/zaidalyafeai/zaidalyafeai.github.io/blob/master/sketcher/Sketcher.ipynb#scrollTo=NoFI1msFYpCN
my converted to onnx version:
[sketcher.zip](https://github.com/Unity-Technologies/barracuda-release/files/5579163/sketcher.zip)
Code
```
public class QDraw : MonoBehaviour
{
    public NNModel modelAsset;
    private Model m_RuntimeModel;
    private IWorker m_Worker;
    public Texture texture;
    private int channels = 1;
    public TextAsset dataFile;
    public string topPredict;
    List<string> _classes;

    void Start()
    {
        m_RuntimeModel = ModelLoader.Load(modelAsset);
        m_Worker = WorkerFactory.CreateWorker(WorkerFactory.Type.CSharpRef, m_RuntimeModel);
        _classes = LocalizationManager.instance.GetLocalizedClassNamesValues();
    }
    public void Predict()
    {

        Tensor input = new Tensor(texture, channels);
        m_Worker.Execute(input);
        var tensor = m_Worker.PeekOutput();
        int[][] t = tensor.ArgSort();
        int[] m = tensor.ArgMax();
        var shape = input.shape;


        topPredict = _classes[tensor.ArgMax()[0]];
        input.Dispose();
    }
}
```
Thank you !

**Comment by AlexRibard** [comment]
thanks for providing the model, we'll look at it :)

**Comment by Aurimasp** [comment]
Hi, I'm getting similar results on both Editor and Android. Could you please check my example?
[Test.zip](https://github.com/Unity-Technologies/barracuda-release/files/5775479/Test.zip)

**Comment by Aurimasp** [comment]
Also, which Android device and version have you tried?

**Comment by sharpgraf** [comment]
hi, at the moment everything is working, the whole problem was in the System.Drawing.dll library. (i used image processor library for image processing) I also want to note that barracuda does not work on the emulator (Memu) for some reason. I used Xiaomi Redmi Note 4 in testing, it is very strange that it does not support Vulkan, but my application still starts, although it gives incorrect predictions when using the GPU. Thanks for helping !

**Comment by AlexRibard** [comment]
oh! and CPU is ok?

**Comment by sharpgraf** [comment]
> oh! and CPU is ok?

yes, only cpu works with Xiaomi Redmi Note 4, GPU gives wrong predictions or probably the same result all the time ( 0 )
nothing works with the emulator at all

**Comment by AlexRibard** [comment]
ok, you are using OpenGL or Vulkan?
OpenGL we don't officially support/guarantee correctness as there is a lot of lack of driver support.
If it is failing on Vulkan we should take a look at it

**Comment by FlorentGuinier** [comment]
@sharpgraf closing the issue as there was no update on it. Please reopen if this is still a problem.
