### ISSUE TITLE
Onnx - ScatterElements

### ISSUE THREAD

**Issue by tramper2** [Unity-Technologies/barracuda-release#124]
Hello

i'm try to run https://github.com/PeterL1n/BackgroundMattingV2

but i got this error "OnnxImportException: Unknown type ScatterElements encountered while parsing layer 878."

How to?

thanks

**Comment by mantasp** [comment]
At the moment `ScatterElements` operation is not supported by Barracuda. But you might look into this project: https://github.com/keijiro/NNCam, which does similar thing.

**Comment by L4Z3RC47** [comment]
Sorry to re-open this. Are there plans at all to support ScatterElements in the future?

**Comment by brgishy** [comment]
I believe they plan on supporting this.  Here is an identical issue that is still open (https://github.com/Unity-Technologies/barracuda-release/issues/136)

**Comment by tramper2** [comment]
i posted it 1. JAN and now is 1. Apr

**Comment by AlexRibard** [comment]
well we are getting more traction on this now :) so prio is definitely up a notch now
Could you guys provide specific onnx models were you are using `ScatterElements`? It would be useful for us to verify that your models are working.

**Comment by Vilyx** [comment]
@AlexRibard hello, here it is: https://drive.google.com/drive/folders/1onSGHYmNRROI2R39lqxf2CvtTaIVRXnB this models relates to "Background matting V2"
