### ISSUE TITLE
SpaceToDepth assert fails

### ISSUE THREAD

**Issue by tvkamara** [Unity-Technologies/barracuda-release#125]
Hello,

I'm playing around with the SpaceToDepth function but an assertion fails:

[Assert.AreEqual(X.channels % (blocksize[0] * blocksize[1]), 0);](https://github.com/Unity-Technologies/barracuda-release/blob/58f8b903a25ebdc1f7e12795df0afefbefea8c05/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs#L1263)

I can manually remove this assertion and the function seems to work. Is there a reason why this assert exists? For example going from input shape { 1, 480, 480, 1 } to { 1, 240, 240, 4 } fails as 1 % (2 * 2) is not 0. Should the blocksize be compared with input height and width instead or am I missing something?

Thanks,
BR, Teemu

**Comment by mantasp** [comment]
Thanks for spotting this! Any chance you could share your model with us?

**Comment by tvkamara** [comment]
I'm actually creating a "model" with only the SpaceToDepth layer as I'm planning on then to input this output to an existing onnx model. I'm creating the spacetodepth model model like this:
```
builder = new ModelBuilder(model);
var input0 = new Model.Input();
input0.name = "input0";
input0.shape = new int[] { 1, 480, 480, 1 }; ;
builder.model.inputs.Add(input0);
builder.model.outputs = new List<string> { "spacetodepth" };
builder.SpaceToDepth("spacetodepth", input0, 2);
worker2 = WorkerFactory.CreateWorker(WorkerFactory.Type.ComputePrecompiled, model);
```
Then I'm using the worker with a couple of textures (1 channel):
```
var tensor = new Tensor(textures, 1);
worker2.Execute(tensor);
var outputTensor2 = worker2.PeekOutput();
```

**Comment by AlexRibard** [comment]
`SpaceToDepth.blocksize` expects an array of length 2 (one block size for X and one for Y).
Try calling `builder.SpaceToDepth("spacetodepth", input0, new [] {2, 2});` instead of `builder.SpaceToDepth("spacetodepth", input0, 2);`

**Comment by tvkamara** [comment]
Hi @AlexRibard. The public builder function actually takes an int:

`public Layer SpaceToDepth(string name, object source, int blocksize)` See code [here](https://github.com/Unity-Technologies/barracuda-release/blob/58f8b903a25ebdc1f7e12795df0afefbefea8c05/Barracuda/Runtime/Core/ModelBuilder.cs#L622).

The int is then transformed internally into an array:

`layer.pool = new int[] { blocksize, blocksize };`

So I believe this is not the issue.

BR, Teemu

**Comment by AlexRibard** [comment]
Ah yes, my bad sorry, I missed that.
After looking at the code, you are right.
This assert shouldn't be there, I'll update the code

**Comment by AlexRibard** [comment]
closing, in 1.3.3 the assert is removed
