### ISSUE TITLE
Cannot import ONNX model of Ultra-Light-Fast-Generic-Face-Detector-1MB (version-slim-320.onnx)

### ISSUE THREAD

**Issue by tonysung** [Unity-Technologies/barracuda-release#127]
OS: macOS 10.15.6
Barracuda version: 1.2.1-preview
Unity version: 2019.4.17f1

When importing the following ONNX model:

https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/models/onnx/version-slim-320.onnx

Produces the following error:

Asset import failed, "Assets/Models/version-slim-320.onnx" > OnnxImportException: Unexpected error while parsing layer 381 of type Mul.
Cannot reshape array of size 8840 into shape (1, 1, 1, 1, 1, 1, 4420, 1)

**Comment by AlexRibard** [comment]
Hey @tonysung thank you for providing the model.
This error has been addressed in latest and will be pushed in a upcoming version.
In the mean-time are you able to modify layer `Mul.381` and `Add.383` to have rank2 constants instead of rank3 ones?

Let me know

**Comment by tonysung** [comment]
> In the mean-time are you able to modify layer Mul.381 and Add.383 to have rank2 constants instead of rank3 ones?

I'm not sure if I can do that. The other input to Mul.381 and Add.383 are rank3 and seems to be necessarily rank3?

**Comment by AlexRibard** [comment]
Rank 2 constant would broadcast to the rank3 input.
But it's ok, if it's not possible, you'd unfortunately have to wait for the upcoming version for support.

**Comment by AlexRibard** [comment]
@tonysung your issue is fixed in 1.3.0
