### ISSUE TITLE
OnnxImportException: Unknown type Softplus encountered while parsing layer 20.

### ISSUE THREAD

**Issue by yaoling1997** [Unity-Technologies/barracuda-release#129]
Hi guys,
This is the first time I'm using barracuda to import my Pytorch Model, but the OnnxImportException happens like this:
![1](https://user-images.githubusercontent.com/24959396/103868228-9286ed80-5103-11eb-8332-4d852ca8e41b.png)
Is there any chance to solve this problem? Does this mean I can't use softplus function in my model?

**Comment by AlexRibard** [comment]
Hi @yaoling1997 right now it is not implemented, so you'll need to use another activation function.
(you can find the supported op here: https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/SupportedOperators.md)
I have added support for it and it will be present in the next release.

**Comment by yaoling1997** [comment]
Thanks a lot, you guys are excellent!
