### ISSUE TITLE
Tensorflow to Barracuda(FusedBatchNormV3)

### ISSUE THREAD

**Issue by robinydv** [Unity-Technologies/barracuda-release#13]
I have a yolov3tiny model in a frozen graph (.pb) file. When I run the tensorflow_to_barracuda.py script I get the following error.  

IGNORED: FusedBatchNormV3 unknown layer
Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 26, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "C:\Users\sudes\Documents\barracuda-release\Tools\tensorflow_to_barracuda.py", line 1347, in convert
    process_model(i_model, args)
  File "C:\Users\sudes\Documents\barracuda-release\Tools\tensorflow_to_barracuda.py", line 1209, in process_model
    process_layer(node, o_context, args)
  File "C:\Users\sudes\Documents\barracuda-release\Tools\tensorflow_to_barracuda.py", line 1084, in process_layer
    assert(all_elements_equal(input_ranks))
AssertionError

Is this because FusedBatchNormv3 is not supported. If not, when will it be?

**Comment by mantasp** [comment]
@Robin2091 any chance you could share your model? It might be with random weights.
Thanks!

**Comment by MarkTension** [comment]
Hey @mantasp ! I have the same problem. IGNORED: FusedBatchNormV3 unknown layer. 
I used mobilenet pretrained on imagenet from keras (keras.applications.mobilenet.MobileNet(.....)).
Seems like it's not supported from the documentation, but would be really helpful if support is added later, because basically all keras networks have fused batchnormv3 .


If you'd like to check download from here for your comfort.
https://drive.google.com/file/d/1VOKgwqitPusfgHsDdJqN6k8fqG2ZT27v/view?usp=sharing

**Comment by mantasp** [comment]
Thank you! adding it to our issue tracker.

**Comment by rejunity** [comment]
@Robin2091 @MarkTension I just implemented support for FusedBatchNormV3 and FusedBatchNormV2. Will be shipped with the next release.

Meanwhile you could try my fix locally. Just replace Tools/tensorflow_to_barracuda.py with the one in this zip: [tensorflow_to_barracuda.py.zip](https://github.com/Unity-Technologies/barracuda-release/files/4198431/tensorflow_to_barracuda.py.zip).
Hope it helps.

**Comment by MarkTension** [comment]
Thank you! @rejunity  It seems though that the local fix by itself, combined with the latest barracuda.py file crashes when converting the model.

```
Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 21, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "/Users/schmark/Unity_Projects/shapeNetwork/tensorflow_to_barracuda.py", line 1393, in convert
    barracuda.setup_constants(o_model,
AttributeError: module 'barracuda' has no attribute 'setup_constants'
```
