### ISSUE TITLE
Performance difference between Version 1.0.4 and 1.2.1

### ISSUE THREAD

**Issue by abeug** [Unity-Technologies/barracuda-release#130]
I am seeing a large performance difference between version 1.0.4 and 1.2.1. Here is some profiling from the Unity Profiler.

Unity Barracuda 1.0.4:
![image](https://user-images.githubusercontent.com/25258352/103938521-f99aa700-50ef-11eb-9554-5358f7e176ff.png)

Unity Barracuda 1.2.1:
![image](https://user-images.githubusercontent.com/25258352/103940344-c7d70f80-50f2-11eb-864a-5a88048c08be.png)

The majority of the red under GPU Usage is from Unity Barracuda compute shaders. Most of "Rendering" tasks in CPU Usage (Green) is for waiting for the GPU since the compute shaders have to finish before the next frame. As the graphs show, the GPU usage is largely increased when using version 1.2.1 when compared with the 1.0.4 version.

Here is one particular layer running on each version (the biggest Conv2D):
**Biggest Convolution (Version 1.0.4):**
![image](https://user-images.githubusercontent.com/25258352/103940799-914dc480-50f3-11eb-9f39-5a2d07e32be1.png)

**Biggest Convolution (Version 1.2.1):**
![image](https://user-images.githubusercontent.com/25258352/103940666-50ee4680-50f3-11eb-8317-1027bb36a1ee.png)

The GPU time for this one layer is increased by more than double.

**Implementation Details:**
StartManualSchedule is used to schedule a different amount of layers per frame. Large Conv2d layers are performed on their own frame and these are the large spikes in the GPU Usage. There is a slight difference between how I schedule the layers for each version because ScaleBias layers seem to be bundled with other layers in newer versions. I account for this difference between Barracuda versions.

**Platform**: Microsoft HoloLens 2 (UWP) (ARM), (ARM64 build has same issue)
**Model**: [Tiny Yolo V2](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2)

-----------------------------------------------------------------------------------
**Test 2:**

Here is another scenario I tested on a different platform:

**Platform**: PC (Windows 10) (In Unity Editor)
**GPU**:  GTX 1080 Ti
**Model**: [Tiny Yolo V2](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2)

In this test, all layers are scheduled within the same frame. The GPU times from the Unity Profiler are shown for each barracuda layer on both versions:

**Unity Barracuda 1.0.4:**
![YoloV2Tiny_GPUTime2_Barracuda1 0 4](https://user-images.githubusercontent.com/25258352/103941610-bb53b680-50f4-11eb-8ca0-d98694feb36e.png)

**Unity Barracuda 1.2.1:**
![YoloV2Tiny_GPUTime_Barracuda1 2 1](https://user-images.githubusercontent.com/25258352/103941593-b4c53f00-50f4-11eb-8806-4bae6c119c54.png)

There is an increase for each layer here aswell.

**Comment by AlexRibard** [comment]
@abeug I haven't personally profiled on hololense which kernel would be more efficient.
We have some heuristic to guess which kernel is better, but we might be wrong on our heuristic on this platform.
It would be worth profiling there. If you want I can tell you how to switch between which kernels to select the optimal one.

But what confuses me is that in your example, it is using the _exact same_ kernel in each run and the perf is noticeably different.
Perf can vary a bit depending on the run, so make sure the average is noticeably different rather than focusing on one run.

I'll profile it locally and see if I can spot something.

**Comment by abeug** [comment]
I have looked at the compute shaders used on both versions in the Unity Frame Debugger. Here is that convolution that I showed previously (The biggest Conv2D):

**Version 1.0.4**
![30_V1 0 4](https://user-images.githubusercontent.com/25258352/104038611-f5779380-519a-11eb-9fa8-3037a42fb5aa.png)

**Version1.2.1**
![27_V1 2 1](https://user-images.githubusercontent.com/25258352/104038578-e98bd180-519a-11eb-8d70-0bb27d0d7f78.png)

Though it uses the same kernel, there is a different thread group size and some of the shapes have an incorrect batch size of 3 like in Issue #104.

In fact it looks like this batch size of 3 is introduced on the second layer of network, which is an Add layer that uses BroadcastAdd_NHWC.

**Version 1.0.4**
![2_V1 0 4](https://user-images.githubusercontent.com/25258352/104038397-af223480-519a-11eb-8305-b8af626ef276.png)

**Version1.2.1**
![2_V1 2 1](https://user-images.githubusercontent.com/25258352/104038408-b21d2500-519a-11eb-8804-299d827f3998.png)

The OdeclShape changes to a batch size of 3 here when it should be 1. It seems to stay like this for the rest of the network.

If it is useful, here is a zip file of images (like shown above) of each compute shader used in the network, for both versions of Barracuda.
https://drive.google.com/file/d/1N9QqhFsQYfPkWCWNzNVc3t4WLQXj-fby/view?usp=sharing

Perhaps this performance disparity is simply due to this incorrect batch size in issue #104 which you mentioned might not may been merged,

**Comment by abeug** [comment]
Issue seems fixed on version 1.3.0.
