### ISSUE TITLE
Invalid kernelIndex running onnx model

### ISSUE THREAD

**Issue by giuntnic** [Unity-Technologies/barracuda-release#133]
Pulled a model from the onnx github [here](https://github.com/onnx/models/tree/master/vision/body_analysis/age_gender), specifically googlenet_age_adience and I am unable to run it using a precompiled compute shader. Stack:
```IndexOutOfRangeException: Invalid kernelIndex (2) passed, must be non-negative less than 16.
Unity.Barracuda.ComputeFunc..ctor (UnityEngine.ComputeShader[] cs, System.String kn) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:1780)
Unity.Barracuda.ComputeKernel.CalculateEntryScore (UnityEngine.ComputeShader[] kernels, Unity.Barracuda.ComputeKernelLibrary+Entry entry, System.Boolean verbose) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:680)
Unity.Barracuda.ComputeKernel.BestKernel (UnityEngine.ComputeShader[] kernels, System.Collections.Generic.List1[T] entrees, System.Boolean verbose) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:725)
Unity.Barracuda.ComputeOps.BestKernel (System.Collections.Generic.List1[T] entrees) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:787)
Unity.Barracuda.PrecompiledComputeOps.PrepareModel (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary2[TKey,TValue] inputShapes) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/BarracudaPrecompiledCompute.cs:374)
Unity.Barracuda.StatsOps.PrepareModel (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary2[TKey,TValue] inputShapes) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/StatsOps.cs:44)
Unity.Barracuda.GenericWorker+<StartManualSchedule>d__30.MoveNext () (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/GenericWorker.cs:169)
Unity.Barracuda.GenericWorker.Execute () (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/GenericWorker.cs:121)
Unity.Barracuda.GenericWorker.Execute (Unity.Barracuda.Tensor input) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/GenericWorker.cs:115)
MeshToTexture+<RunPoseEstimator>d__4.MoveNext () (at Assets/Scripts/MeshToTexture.cs:102)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <bad59441812943c7b8d5a5ba85795810>:0)
```

There is also this error immediately preceding the above:
```
Shader error in 'Pool': failed to open source file: 'Tensor.cginc' at kernel MaxPool2D_NHWC at Pool.compute(18) (on d3d11)
```

Relevant bits of code:
```c#
var worker = WorkerFactory.CreateWorker(WorkerFactory.Type.ComputePrecompiled, m_runtimeModel); 
// var worker = WorkerFactory.CreateWorker(WorkerFactory.Type.CSharp, m_runtimeModel);  // Runs without error
var texture = new Texture2D(2, 2);
// Pull the png from disk
yield return ImageManager.LoadTextureFromFile(FileManager.PoseFile(), (result => texture = result));
// Resize to 224x224 for model
ImageManager.Resize(texture, m_tensorWidth, m_tensorHeight);
// Need values between 0 and 255 so manually flatten the image to a 1D NHWC format
float[] tensorData = Flatten(texture);  
var input = new Tensor(1, m_tensorHeight, m_tensorWidth, m_tensorChannels, tensorData);  
worker.Execute(input); // Exception here
```

**Comment by FlorentGuinier** [comment]
Thanks for reporting @giuntnic , taking a look.

**Comment by FlorentGuinier** [comment]
Hey @giuntnic , I can't repro both on our latest code and 1.2.1 release. Furthermore the error above is quite weird as the "Tensor.cginc" file should be there (or nothing related to the GPU backends would work at all).

Can you verify your local Barracuda package is unaltered and the file exist please? 
File should be in `Barracuda/Runtime/Core/Resources/Tensor.cginc`

Also can you share your Unity version number as well as the Barracuda package number used?

Thanks
Florent

**Comment by giuntnic** [comment]
@FlorentGuinier Barracuda package should be unaltered and I verified that the Tensor.cginc file exists (Using a different model I am able to run on a GPU backend).

 Running unity 2020.1.17f1 and Barracuda 1.0.4. Looks like I am using a slightly outdated release but I seem to recall there was a bug with this unity version where Barracuda doesn't show up in the Package Manager so I'm pulling it in via the ML Agents package which only supports 1.0.4.

**Comment by Aurimasp** [comment]
Hello @giuntnic,

We created an example using the provided information, but it doesn't reproduce locally on our machines. Could you please send us the example Unity project that breaks on your machine?

I looked for other issues of similar nature in our database. Some other potential fixes to try:
* Download the latest Barracuda package from this repository and add it to the Editor with the + symbol in the Package Manager by selecting the 'package.json' file.
* Delete and rebuild the Library folder.

**Comment by FlorentGuinier** [comment]
@giuntnic closing the issue as there was not update on it, please reopen if this is still a problem.

**Comment by TV4Fun** [comment]
I also ran into this issue. The problem for me was incompatible cached libraries transferred from another machine. I fixed it by deleting my project's `Library` folder.

**Comment by Aragami-delp** [comment]
> I also ran into this issue. The problem for me was incompatible cached libraries transferred from another machine. I fixed it by deleting my project's `Library` folder.

I also got the same issue, but without moving from another pc. But deleting the Library folder also fixed it.
