### ISSUE TITLE
NLP processing

### ISSUE THREAD

**Issue by alienflip** [Unity-Technologies/barracuda-release#135]
I was wondering if barracuda be able soon to process models such as this

https://github.com/onnx/models/tree/master/text/machine_comprehension/bert-squad

**Comment by AlexRibard** [comment]
It is planned yes! As so far of giving an ETA, it's a bit too early for that I'm afraid

**Comment by alienflip** [comment]
> It is planned yes! As so far of giving an ETA, it's a bit too early for that I'm afraid

Ok! Great this is good to know

**Comment by alienflip** [comment]
I would be happy to help if needed

**Comment by AlexRibard** [comment]
If you have your own custom model you are targeting, we can add it to the list / make sure it imports correctly.
Atm, we are mostly looking at the off the shelve onnx models

**Comment by alienflip** [comment]
Ok ... so that means that if I make a custom onnx it will not necessarily work when imported? Even if it's in the list of acceptable architectures?

**Comment by AlexRibard** [comment]
Bert is _not_ a supported architecture atm, so yes if you have a custom Bert model, it might not work.
If on the other hand your model is in the supported architecture list, yes it should import correctly

**Comment by alienflip** [comment]
... ok ... what's BERT?

**Comment by AlexRibard** [comment]
https://github.com/onnx/models/tree/master/text/machine_comprehension/bert-squad
https://towardsdatascience.com/bert-explained-state-of-the-art-language-model-for-nlp-f8b21a9b6270
It's the architecture you were referring to

**Comment by alienflip** [comment]
Ah ok yes, thanks!
