### ISSUE TITLE
ExecuteAsync

### ISSUE THREAD

**Issue by alienflip** [Unity-Technologies/barracuda-release#137]
I'm having trouble with ExecuteAsync : it works, but the error message says it is deprecated. What is the updated syntax?

This is the section of code that I'm having trouble with:

https://github.com/stackedflows/Machine-Learning/blob/main/Worker.cs
    
is there a reason this is happening? I am using version 1.0.4

Maybe its the model that I'm using?

Any help would be appreciated,

Cheers,

Kai

**Comment by AlexRibard** [comment]
Oh, no worries. We just changed the name of the function to `StartManualSchedule`
So just call it as follows:
```
worker.StartManualSchedule(input)
```

**Comment by AlexRibard** [comment]
it seems I do not have access to the github you are referring to.
Apart from the error message saying it's deprecated is there anything not working?

**Comment by alienflip** [comment]
So it seems there is still a GPU leakage warning arising, even though the code is technically working perfectly. 

The model I am using is  the official MNIST model, paired with the code from:

https://github.com/MarekMarchlewicz/AI-Drawing

**Comment by alienflip** [comment]
This is how I build the ONNX

https://github.com/stackedflows/Machine-Learning/tree/main/MNIST

**Comment by alienflip** [comment]
Again much appreciated if you can help, absolutely no worries if not!

**Comment by AlexRibard** [comment]
ok could you share the execution code you are using?
Be sure to destroy all allocated tensors/worker

**Comment by alienflip** [comment]
It is in two parts:

**Comment by alienflip** [comment]
using System;
          using System.Collections;
          using UnityEngine;
          using Unity.Barracuda;
          
          namespace MNISTPainter
          {
              //must implement Dispose()
              public class Worker : IDisposable
              {
                  //specifies 'public' objects
                  private IWorker worker;
                  private Model model;
                  private float[] results;
                  private PrecompiledComputeOps ops;
          
                  //initialise public objects: loads MNIST model, creates a pool of workers to do inference,
                  //initialises relevant GPU architecture
                  public Worker(NNModel nnmodel, WorkerFactory.Type type)
                  {
                      bool verbose = false;
                      model = ModelLoader.Load(nnmodel, verbose);
                      worker = WorkerFactory.CreateWorker(type, model, verbose);
          
                      var kernels = ComputeShaderSingleton.Instance.kernels;
                      ops = new PrecompiledComputeOps(kernels, kernels[0]);
                  }
          
                  //method for cleaning garbage, adapted for gpu 
                  public void Dispose()
                  {
                      worker?.Dispose();
                      model = null;
                      ops = null;
                  }
          
                  //runs through pixels in image, converts to model executable tensor, breaks each time a new column
                  //is finished, and begins to execute prediction based on this updated information, 
                  //outputs the model prediction
                  public IEnumerator ExecuteAsync(Texture2D texture)
                  {
                      int width = texture.width;
                      int height = texture.height;
          
                      Tensor input = new Tensor(1, height, width, 1);
          
                      for(int y = 0; y < height; y++)
                      {
                          for(int x = 0; x < width; x++)
                          {
                              input[0, 27 - y, x, 0] = texture.GetPixel(x, y).r;
                          }
                          yield return worker.StartManualSchedule(input);
                      }
          
                      Tensor output = worker.PeekOutput();
          
                      results = output.data.Download(output.shape);
          
                      input.Dispose();
                      output.Dispose();
                  }
          
                  public IEnumerator ExecuteAsyncTexture(Texture2D texture)
                  {
                      Tensor input = new Tensor(texture, 1);
                      yield return worker.StartManualSchedule(input);
          
                      Tensor output = worker.PeekOutput();
                      results = output.data.Download(output.shape);
          
                      input.Dispose();
                      output.Dispose();
                  }
          
                  public float[] get_result()
                  {
                      return results;
                  }
              }
          }

**Comment by alienflip** [comment]
using System.Collections;
          using System.Collections.Generic;
          using UnityEngine;
          using UnityEngine.UI;
          using Unity.Barracuda;
          
          namespace MNISTPainter
          {
              public class Inference : MonoBehaviour
              {
          
                  //Developer UI handling
                  [SerializeField]
                  public pCanvas paint_canvas;
          
                  //Note: Inference with MNIST is buggy in unity: memory leaks seem to occur due to the structure
                  //of the neural net
                  [SerializeField]
                  private NNModel MNIST_model;
          
                  [SerializeField]
                  private WorkerFactory.Type m_worker_type = WorkerFactory.Type.ComputePrecompiled;
          
                  [SerializeField]
                  private Text[] m_results_array;
          
                  [SerializeField]
                  private Transform[] m_results_positon_array;
          
                  public Transform point_to_max;
          
                  //main algorithm 'public' objects
                  private Worker m_barracuda_worker;
          
                  private string[] m_Labels = { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" };
          
                  private bool m_is_busy = false;
          
                  //initialise observer pattern
                  //instantiate worker for our model and backend execution type
                  private void Start()
                  {
                      paint_canvas.on_update_texture += texture_listener;
          
                      m_barracuda_worker = new Worker(MNIST_model, m_worker_type);
                  }
          
                  //runs worker on mouse down
                  private void texture_listener(Texture2D texture)
                  {
                      if (!m_is_busy)
                      {
                          StartCoroutine(ExecuteAsync(texture));
                      }
                  }
          
                  //concurrency: each frame updates the estimated model output by calling the Worder script
                  //updates the UI to show predictions based on worker output
                  IEnumerator ExecuteAsync(Texture2D texture)
                  {
                      if (m_is_busy)
                      {
                          yield break;
                      }
          
                      m_is_busy = true;
          
                      yield return m_barracuda_worker.ExecuteAsyncTexture(texture);
          
                      var result = m_barracuda_worker.get_result();
          
                      Dictionary<int, float> results = new Dictionary<int, float>();
          
                      float max = result[0];
                      int type = 0;
          
                      for (int i = 0; i < result.Length; i++)
                      {
                          results[i] = result[i];
          
                          foreach (KeyValuePair<int, float> keyValuePair in results)
                          {
          
                              m_results_array[i].text = $"{m_Labels[keyValuePair.Key]}: {keyValuePair.Value}";
          
                              if (keyValuePair.Value > max)
                              {
                                  max = keyValuePair.Value;
                                  type = keyValuePair.Key;
                              }
          
                              point_to_max.position = m_results_positon_array[type].position + new Vector3(30f, 18f, -2f);
                          }
                        
                      }
          
                      m_is_busy = false;
                  }
              }
          }

**Comment by AlexRibard** [comment]
@stackedflows did you managed to fix the issue? If so what was it?

**Comment by alienflip** [comment]
@AlexRibard  same issue as https://github.com/Unity-Technologies/barracuda-release/issues/147

**Comment by AlexRibard** [comment]
I see, thank you for clarifying
