### ISSUE TITLE
Unable to import model from CustomVision.ai (Unexpected error while parsing layer block0_1_branch0 of type Split.)

### ISSUE THREAD

**Issue by jmbrunskill** [Unity-Technologies/barracuda-release#138]
I'm trying to import an onnx model trained using Azure Custom Vision.

However I'm receiving an error with 'Split' on import.

```
OnnxImportException: Unexpected error while parsing layer block0_1_branch0 of type Split.
Unsupported default attribute `split` for node block0_1_branch0 of type Split. Value is required.

Json: { "input": [ "block0_0" ], "output": [ "block0_1_branch0", "block0_1_branch1" ], "name": "split", "opType": "Split", "attribute": [ { "name": "axis", "i": "1", "type": "INT" } ] }
  at Unity.Barracuda.ONNX.ONNXModelConverter+<>c.<UseStandardImporter>b__22_10 (Unity.Barracuda.ModelBuilder net, Unity.Barracuda.ONNX.ONNXNodeWrapper node) [0x0001b] in /Users/james/src/badgersfrommars/TFClassify-Unity-Barracuda/Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:309 
  at Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) [0x003a8] in /Users/james/src/badgersfrommars/TFClassify-Unity-Barracuda/Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2616 

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:3115)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2625)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:104)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at /Users/bokken/buildslave/unity/build/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:22)
UnityEditor.Experimental.AssetImporters.AssetImporterEditor:ApplyRevertGUI()
Unity.Barracuda.Editor.ONNXModelImporterEditor:OnInspectorGUI() (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Editor/ONNXModelImporterEditor.cs:67)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

```

Is this type of model supported by barracuda?
I'm trying this on the 1.3.0 preview release in Unity.

Model file is [here on google drive](https://drive.google.com/file/d/1IHNrPWgZScUlTcmPTCNiGHVcZEyh0hp3/view?usp=sharing)

**Comment by AlexRibard** [comment]
Hey @jmbrunskill ! I took a look at your model, our `Split` operator is not fully complete unfortunately.
Currently we require a `split` input. 
I will add support for it. In the meantime you can just create your Split layer with split=116/2 it should work

**Comment by jmbrunskill** [comment]
Thanks @AlexRibard! 
Adding support for this would be fantastic.

Is adding the ‘split’ input something I should be able do to an existing onnx model? Do you have any pointers where I could learn this? Because I’m using an AutoML service I don’t have direct control over the model shape from the service.

**Comment by AlexRibard** [comment]
Sure, I think it is possible to edit the onnx file directly.
Let me try it out and get back to you.

**Comment by AlexRibard** [comment]
@jmbrunskill I managed to get a working model in Barracuda. Here is the code to do that (rename the file as .py)
[modifyonnxmodel.txt](https://github.com/Unity-Technologies/barracuda-release/files/5946041/modifyonnxmodel.txt)
Do note that your model has additional nodes that are not supported:
`ArrayFeatureExtractor` and `ZipMap` so for these you'd need to manually implement them. Shouldn't be too hard on the CPU
https://github.com/onnx/onnx/blob/master/docs/Operators-ml.md

In the meantime I'll update our split operator to support your model 
Let me know.

**Comment by jmbrunskill** [comment]
Thanks @AlexRibard! 
I'll have a play around with this tonight and see what I can get working.
Really appreciate the extra effort.

**Comment by AlexRibard** [comment]
model runs without `ArrayFeatureExtractor` and `ZipMap` so closing for now.
@jmbrunskill create a new ticket if you want us to implement those two ops
