### ISSUE TITLE
Inaccurate prediction results on Apple A10X devices

### ISSUE THREAD

**Issue by lkuich** [Unity-Technologies/barracuda-release#14]
Hi, we are having a strange issue, where specifically on an iPhone 7 and iPad Pro (2017), we are getting wildly inaccurate image predictions. Both of these devices use the A10X/A10X Fusion SoC.

We tested the same project on an iPhone 5, 6, 7, 8, X, an iPad Pro 2017/2019, as well as on plenty of Android devices, and only observed the issue on 2 separate iPhone 7's running iOS 12 and iOS 13 (both have since been updated to iOS 13.3 with no effect). Using Unity 2019.2.18f1, tried multiple different versions and build machines.

Our project downloads a Barracuda model (converted from Tensorflow 1.14) trained for recognizing `daisies`, `roses`, and `sunflowers`. Pressing the rose button runs a prediction on a preloaded rose image. On other devices, it guesses `roses` with 99% confidence, on the iPhone 7 and iPad Pro 2017 however, it almost always guesses `daisies`, I get a full prediction and no errors, but it's just inaccurate.

Here is a link to my project:
https://github.com/coach-ml/coach-flowers-demo

And I've included my model and a snippet to run it:
https://coach-public.s3.amazonaws.com/unity.bytes

```csharp
// This normalizes the inputs
private Tensor ToTensor(Texture2D tex)
{
    var pic = tex.GetPixels32();
    int INPUT_SIZE = 224;
    int IMAGE_MEAN = 0;
    float IMAGE_STD = 255;

    float[] floatValues = new float[(INPUT_SIZE * INPUT_SIZE) * 3];

    for (int i = 0; i < pic.Length; i++)
    {
        var color = pic[i];
        floatValues[i * 3] = (color.r - IMAGE_MEAN) / IMAGE_STD;
        floatValues[i * 3 + 1] = (color.g - IMAGE_MEAN) / IMAGE_STD;
        floatValues[i * 3 + 2] = (color.b - IMAGE_MEAN) / IMAGE_STD;
    }

    var shape = new TensorShape(1, INPUT_SIZE, INPUT_SIZE, 3);
    return new Tensor(shape, floatValues);
}

var myTexture = Resources.Load<Texture2D>("Materials/rose");
var scaledTexture = ... // I have another function for scaling the texture to 224x224
var imageTensor = ToTensor(scaledTexture);

var modelPath = Path.Combine(path, "unity.bytes");
Model model = ModelLoader.LoadFromStreamingAssets(modelPath);

var Worker = WorkerFactory.CreateComputeWorker(model);
Worker.PrepareForInput(new Dictionary<string, TensorShape>()
{
    { "input", new TensorShape(1, 255, 255, 3) }
});

Worker.Execute(imageTensor);
var output = Worker.Fetch("output");
```

Are you guys experiencing any accuracy issues on A10X devices? I'm wondering if this has something to do with the graphics API.

Thanks,
Loren

**Comment by mantasp** [comment]
@lkuich which Barracuda version are you using?

**Comment by lkuich** [comment]
@mantasp The newest release, 0.4.0

**Comment by lkuich** [comment]
Just an update, I managed to get ahold of an older iPad Pro (MPDY2CL/A) as it has a similar SoC (A10X/A10X Fusion) to the iPhone 7, and experienced the same issue. I also tested on my iPad Pro 2019, which did not experience the issue. This seems specific to devices with that SoC.

**Comment by lkuich** [comment]
Since discovering the correlation between the 2 devices, I dug around for any A10X specific logic, and noticed the logic for setting `maxComputeWorkGroupSize`. I found the issue was resolved by setting `maxComputeWorkGroupSize = 224u`. Here's the change I made in my fork that fixed it, note, I haven't tested my other devices yet (5, 6, 8, 10, iPad Pro 2017/2019):
https://github.com/lkuich/barracuda-release/commit/bc9379cbf0c9895a49c484a7a7423fa923c81842#diff-f011cea3b7e46f6044c698f15e22a70bL43-L44

Interestingly `SystemInfo.maxComputeWorkGroupSize` in Unity 2019.3 is also incorrect, as I still get poor prediction results.

**Comment by mantasp** [comment]
Thanks, will look into it!

**Comment by lkuich** [comment]
We have since tested that fix on iPhone 5, 6, 7, 8, X, XS, and iPad Pro 2019, and it seems to work.

**Comment by mantasp** [comment]
Fix for A10 landed main branch of Barracuda and will be part of 0.4.1 release
