### ISSUE TITLE
Mismatch between Compute and ComputeRef 

### ISSUE THREAD

**Issue by abigos** [Unity-Technologies/barracuda-release#140]
Hi,

I have a mismatch between the reference compute and optimized compute backends (WorkerFactory.Type.Compute vs WorkerFactory.Type.ComputeRef). I'm using 1.3.0-preview. The difference appears to be in Dense_Tilled2x2_Cached. 

I've enclosed the log and the model for reference.  It's rather hard to provide the whole project, but let me know if you need any more information.

Thanks

[mismatch.txt](https://github.com/Unity-Technologies/barracuda-release/files/5943308/mismatch.txt)
[net-network_config-dynamic-diffuse.zip](https://github.com/Unity-Technologies/barracuda-release/files/5943316/net-network_config-dynamic-diffuse.zip)

**Comment by AlexRibard** [comment]
interesting, I will check

**Comment by AlexRibard** [comment]
@abigos bug fixed, pushing on main
