### ISSUE TITLE
ONNX Sign-Operator

### ISSUE THREAD

**Issue by rfilkov** [Unity-Technologies/barracuda-release#141]
Hi,

I'm trying to import an ONNX model, but it reports the following error in the console, because Barracuda (v1.3) doesn't support the ONNX Sign-operator. Could you please add support for the [Sign](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Sign)-operator?

Thank you in advance!

"
OnnxImportException: Unknown type Sign encountered while parsing layer Sign:0.

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:3115)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2636)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:104)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <1e441e8684a14fe4b8f8a926d91afc3a>:0)
"

**Comment by AlexRibard** [comment]
That shouldn't be very hard, let me add it for the next release.
In the meantime are you able to get around with `Greater/Less/LessEqual/Equal/Or/And/Not/Xor/Where`?

**Comment by rfilkov** [comment]
Thank you, Alex!
I try to utilize a ready-made ONNX model and would not like to modify it by myself.

**Comment by AlexRibard** [comment]
sure ok, that makes sense. Can you provide your model so I can validate that it works?

**Comment by rfilkov** [comment]
Yes, sure. But it's quite large (over 150 MB). Where should I upload it, or could I send it to you via WeTransfer.com?

**Comment by AlexRibard** [comment]
sure or googledrive, what you prefer

**Comment by rfilkov** [comment]
I would need your e-mail address.

**Comment by AlexRibard** [comment]
barracuda-support@unity3d.com

**Comment by rfilkov** [comment]
I just sent you the model via WeTransfer.com. Please check your Inbox (or Spam-folder).
Please also feel free to remove your e-mail address above.

**Comment by AlexRibard** [comment]
got it thanks

**Comment by AlexRibard** [comment]
@rfilkov 
Sadly this part will not work (even with `Sign` support).
![image](https://user-images.githubusercontent.com/12990800/107285990-fa479580-6a2d-11eb-9b1b-2f9c221d6cfb.png)
We only support const inputs for `Conv` weights atm

**Comment by AlexRibard** [comment]
`ConvTransposeWithDynamicPads` is also not currently implemented in our importer but the pads seems to be inferable at compile time so I guess it's ok.

**Comment by AlexRibard** [comment]
Also a lot of dimensions are unknown for the input.
Atm it is best to fix input dimensions (except batch)

**Comment by rfilkov** [comment]
OK. Please anyway add the Sign-operator, as well as anything else you find useful and easy to implement. I'm going to test Barracuda with other ONNX models, as well.

**Comment by AlexRibard** [comment]
Sure, the dynamic Conv is not the end of the world either but it'll take some time to implement

**Comment by AlexRibard** [comment]
closing as `Sign` operator is implemented.
@rfilkov will open a new issue for your model
