### ISSUE TITLE
'InvalidProtocolBufferException' occurs when importing Tiny-YOLO v2 assets

### ISSUE THREAD

**Issue by Kazuhito00** [Unity-Technologies/barracuda-release#143]
Hello. Thank you for the wonderful project.

I tried to import Tiny-YOLO v2 into Unity under the following conditions:
　Model : [tinyyolov2-7.onnx](https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/tiny-　yolov2/model/tinyyolov2-7.onnx)(ONNX Model Zoo)
　OS : Windows 10
　Unity version : 2017.4.25f1 (64-bit)
　Barracuda version : 1.3.0

At that time, I received the following message and failed.
![image](https://user-images.githubusercontent.com/37477845/107656148-377a8480-6cc7-11eb-9958-40e1641a348b.png)

I think Barracuda supports "Tiny-YOLO v2".
Did I make a mistake in building my environment?

The error message is:
---
InvalidProtocolBufferException: Protocol message contained a tag with an invalid wire type.
Google.Protobuf.UnknownFieldSet.MergeFieldFrom (Google.Protobuf.CodedInputStream input) (at T:/src/github/protobuf/csharp/src/Google.Protobuf/UnknownFieldSet.cs:232)
Google.Protobuf.UnknownFieldSet.MergeFieldFrom (Google.Protobuf.CodedInputStream input) (at T:/src/github/protobuf/csharp/src/Google.Protobuf/UnknownFieldSet.cs:222)
Google.Protobuf.UnknownFieldSet.MergeFieldFrom (Google.Protobuf.UnknownFieldSet unknownFields, Google.Protobuf.CodedInputStream input) (at T:/src/github/protobuf/csharp/src/Google.Protobuf/UnknownFieldSet.cs:257)
Onnx.ModelProto.MergeFrom (Google.Protobuf.CodedInputStream input) (at Library/PackageCache/com.unity.barracuda@fd3de8935d/Barracuda/Runtime/ONNX/Generated/Onnx.cs:1645)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@fd3de8935d/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:100)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@fd3de8935d/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@fd3de8935d/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <a936841cea2147a2a55ea27843fa46ae>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by AlexRibard** [comment]
We do import onnx tiny-yolov2-7 zoo model.
This crashes in google's protobuf importer. My guess is that the model is corrupted.
I wouldn't be surprised that it doesn't load in onnxruntime aswell

I would re-download the whole model and try again.
https://github.com/onnx/models/raw/master/vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-7.tar.gz
You can download the model here.

**Comment by Kazuhito00** [comment]
Thank you very much.
I was able to import the model downloaded from this link.
https://github.com/onnx/models/raw/master/vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-7.tar.gz

Comparing the model sizes, I think it was damaged because there was a slight difference.

**Comment by romygt** [comment]
I have the same problem, @Kazuhito00 @AlexRibard  could you please send me the onnx model.
