### ISSUE TITLE
ONNX Range Operator

### ISSUE THREAD

**Issue by Drod917** [Unity-Technologies/barracuda-release#144]
Hello, I have exported [this model (mobilenetv2+duc+dsntnn variant)](https://github.com/YuliangXiu/MobilePose-pytorch) successfully to ONNX using opset_version=11, then (in Python) verified with the ONNX runtime that the outputs match those of the PyTorch network.

However, when I try to import the ONNX model into Unity using Barracuda v1.3, it errors because there is no Range operator support. Is there any possibility this could be added? Thank you!

[Here is the exported ONNX file, ](https://drive.google.com/file/d/17D0PlSKS_k91498rN18pDITVNJFquP8K/view?usp=sharing) and the error message for reference.

''
Asset import failed, "Assets/Models/mobilenet_duc_dsnt.onnx" > OnnxImportException: Unknown type Range encountered while parsing layer 605.

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:3115)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2636)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:104)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <afa5b9a1793446ff98b741dc036c4c6e>:0)
''

**Comment by AlexRibard** [comment]
Yeah, it seems easy enough.
We'll add it. Thanks for providing your model for reference

**Comment by AmbroxMr** [comment]
Any solution to this problem at this time?

**Comment by AlexRibard** [comment]
I've pushed support for Range in latest.
It didn't make it for 1.3.3, will come out in 1.3.4
@AmbroxMr could you provide your model so I can test it out?
thanks

**Comment by AmbroxMr** [comment]
Im using a model recently added to PyTorch 1.8: 
`torchvision.models.detection.fasterrcnn_mobilenet_v3_large_fpn()`

**Comment by AlexRibard** [comment]
ok let me export that
