### ISSUE TITLE
ONNX GRU support plans

### ISSUE THREAD

**Issue by kirillgerasimov** [Unity-Technologies/barracuda-release#145]
Hello,
I'm pretty new to barracuda. I'm trying to import ONNX (**Opset 12**) exported from pytorch. Haven't found information if this opset supported. It's fine if it's not. 

Currently I have "Unknown type **GRU**" error when importing ONNX file.  Barracuda version is **1.3.0-preview**.
```OnnxImportException: Unknown type GRU encountered while parsing layer 669.```

Onnx (200mb)
https://drive.google.com/file/d/16s24uUvDhjX2ItNmepL7m4qYxK_tU1mH/view?usp=sharing

Unity versions are 2019.4.17f1 and 2020.2.2f1

Stacktrace
```
Asset import failed, "Assets/Scripts/Model/example2.onnx" > OnnxImportException: Unknown type GRU encountered while parsing layer 669.

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:3115)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2636)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:104)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset
```

**Comment by kirillgerasimov** [comment]
I went through the ONNX file. Unfortunately there are couple more operators that are not supported. I gathered them in a table. 

| Used onnx operator | Barracuda 1.3 support | Comment |
| - | - | - |
| Shape | + ||
| Gather | + ||
| Unsqueeze | + ||
| Concat | + ||
| Reshape | + ||
| Conv | + ||
| Relu | + ||
| Maxpool | + ||
| Add | + ||
| Pad | + ||
| AveragePool | +? | Barracuda: Unsupported attribute: ceil\_mode. NN uses ceil_mode = 0 (default)|
| ConstantOfShape| + ||
| Slice | + ||
| GRU | - ||
| Gemm | +? | Barracuda: Unsupported attribute: alpha, beta, transA. NN uses alpha, beta default multiplier (1)  |
| Transpose | + ||
| Squeeze | + ||
| Mul | + ||
| Equal| + ||
| Cast | + ||
| Where | + ||
| Expand | + ||
| Einsum | - ||
| ReduceL2 | - ||
| Clip | + | |
| Expand | + ||
| Div | + | |
| ReduceSum | + | |
| ScatterND | - | |
| Transpose | + | |
| Sub | + | |
| MatMul | + | |
| Range | - | |
| IsNaN | - | |
| Tile | + | |
| Sqrt | + | |
| Less | + | |
| Not | + | |

**Comment by AlexRibard** [comment]
@kirillgerasimov for now we do not have plans for `GRU` support unfortunately.
Looking at it however looks like we could add it to the list. What sequence length are you using?

`Gemm` should be ok, looks like you are using default values for all inputs and not transA
`ReduceMean` indeed we are missing the `ceil_mode = 0`

**Comment by kirillgerasimov** [comment]
@AlexRibard Thank you for response. Sequence length is typically 8 or 16. It would be nice if GRU appears someday in Barracuda. If it emerges in your 2021 plans, post here please.

The answer is given, so I close the issue I guess.

**Comment by AlexRibard** [comment]
@kirillgerasimov I'm re-opening this. Adding GRU support is a valid request and waiting for 2021 is too far. I see that we can add it in a few months.
Do you have a simpler model (that uses GRU) that we can test out?

**Comment by kirillgerasimov** [comment]
@AlexRibard That's great news. I'll try to mess around with native libtorch dll import until then. So waiting is not a problem, if _GRU_ will be supported eventually.

Unfortunately, I don't have simplier model.

**Comment by xywang01** [comment]
Hi @AlexRibard. Is there any chance to also add the ScatterND support? Thanks so much!

**Comment by mantasp** [comment]
@xywang01 please create separate issue for ScatterND support, also please provide some context for your use case. Thanks

**Comment by mantasp** [comment]
@kirillgerasimov is there any particular reason why you would pick GRU over LSTM?

**Comment by kirillgerasimov** [comment]
There is no particular reason. I was just checking out what object detection capabilities I could implement using Barracuda for my project.

I have integrated some robust networks suggested by other researchers. As far as I know, I have many options to do so besides Barracuda (IPC, DLL etc).

**Comment by FlorentGuinier** [comment]
As LSTM seems to be a good alternative to GRU, closing the issue/feature request for now. Please reopen if you feel GRU have an edge other LSTM for your use case (or in general for the Barracuda community).

**Comment by cschell** [comment]
@FlorentGuinier I would like to make a case for GRUs!

While LSTMs and GRUs are similar, both are important for our research: GRUs are interesting, because they require a little bit less computational resources, which is (obviously) relevant for real time applications. Also, our results show that GRUs achieve better scores in our use cases (might be of course different for other scenarios).

Up until now we've evaluated both architectures outside of Unity with recorded data, but it would be important for our work to also evaluate and test not only LSTMs, but also the GRUs in "real" Unity applications to compare the ups and downs :-)
