### ISSUE TITLE
Runtime Error: MobileNet V2-7

### ISSUE THREAD

**Issue by alienflip** [Unity-Technologies/barracuda-release#147]
I made this post on StackOverflow, would It be better to make it again here?

No problem if so.

https://stackoverflow.com/questions/66227737/unity-object-detection-barracuda-mobilenet-and-webcam

Cheers,

K

**Comment by AlexRibard** [comment]
On which Barracuda version are you running? 
I tested your model on v1.3.0 and validated against onnx-runtime. So things seems right on that version.

**Comment by alienflip** [comment]
Ah ok, This works! Thanks you
