### ISSUE TITLE
Barracuda with unity 2019.1.14f1 Personal: Are they compatable?

### ISSUE THREAD

**Issue by alienflip** [Unity-Technologies/barracuda-release#149]
Like the title says: and if so, which models are supported currently? And which versions of Barracuda can I use?

Thanks :)

Kai

**Comment by mantasp** [comment]
All Barracuda versions are compatible with 2019.4.x. List of supported architectures is listed here: https://github.com/Unity-Technologies/barracuda-release/blob/release/1.3.1/Documentation%7E/SupportedArchitectures.md.
Some others might work, but it's something you would have to try.
