### ISSUE TITLE
On iPad 6th gen, getting error "Metal: Compute shader (Conv.Conv2DKernelKxK_T16x16_R4x4_NHWC) has 256 threads in a threadgroup which is more than the supported max of 224 in this device"

### ISSUE THREAD

**Issue by JoeProgram** [Unity-Technologies/barracuda-release#150]
Hello,

I'm a NN newbie, so I'll do my best to explain what I'm seeing.

I've downloaded [CJ Mill's PoseNet Tutorial](https://github.com/cj-mills/Barracuda-PoseNet-Tutorial) project using Unity Barracuda.  When I build it to my iPad 6th generation _(Model Number MR7J2LL/A)_, shortly after launching XCode reports the error:

`Metal: Compute shader (Conv.Conv2DKernelKxK_T16x16_R4x4_NHWC) has 256 threads in a threadgroup which is more than the supported max of 224 in this device`

I've also found a Unity Answers posting that [reports the same problem](https://answers.unity.com/questions/1808688/ios-app-freezes-when-executing-pose-detection-pose.html).

I see that in the Barracuda changelog, there's a [note in the 0.5.0 release ](https://docs.unity3d.com/Packages/com.unity.barracuda@0.5/changelog/CHANGELOG.html) that says:

> Fix: fixed GPU kernel selection for iPhone7 (A10), as it is limited to 224 thread groups.

Here's the [ticket related to that fix](https://github.com/Unity-Technologies/barracuda-release/issues/14#issuecomment-577522774).

My iPad 6th gen _(aka iPad 2018)_ runs on the [Apple A10 Fusion (16 nm) chipset](https://www.gsmarena.com/apple_ipad_9_7_(2018)-9142.php).  

Would it be possible to get this fix applied to this iPad model?

My Unity Version is 2019.4.18f1

Thanks for your time!

Joe

**Comment by AlexRibard** [comment]
Wow, I didn't know iPads had a limit of 224 threads per threadgroup.
For info, this is related to our compute shader implementation of convolution kernel. In this case we are busting the limit.
I'll fix the problem, thanks for flagging it :)

**Comment by JoeProgram** [comment]
Thanks Alex!

I'm digging around in the Barracuda code a bit - looks like line 105 in ComputeInfo.cs is trying to catch this very issue.  Not sure why it's not working on my device...

_(I'm on Barracuda version 1.3.0 currently)_

**Comment by AlexRibard** [comment]
Yeah not sure entirely why, maybe the gpu name is different on the iPad...

**Comment by JoeProgram** [comment]
Doing some debugging output now.

gpuName comes back as "Apple A10 GPU".  Seems like the code should handle it.

I'm going to add a few more print statements for more info...

**Comment by mantasp** [comment]
This message in the console should not prevent your network from running. It's just compute shader pipeline trying to compile all compute shaders in one go and skipping ones that are not supported on specific device.
Do you see any other issues while running that network?

**Comment by JoeProgram** [comment]
Hi Mantasp,

You're right - the network does run.  I'm investigating what I can do to get the model to run faster on this device, and I was curious if this error would have any impact on the framerate.  From your feedback, it sounds like fixing this error is unlikely to improve the speed. Is that correct?

**Comment by AlexRibard** [comment]
Yeah it will not change the framerate.
We are planning to spend more time polishing our kernels for Apple mobile devices.

But atm what you can do on your end:
* reduce the input image size
* split execution over a few frame (https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation~/ModelExecution.md)

**Comment by JoeProgram** [comment]
Thanks Alex! Both those things are definitely helping - though I'm still looking at 1-2 fps.  I'm also going to see if I can switch to a simpler model that takes less processing power.

Should we close this ticket?  The error is still there, but sounds like it's low priority.

**Comment by AlexRibard** [comment]
Yeah let's close it for now.
We'll keep in mind. The general solution is not compile kernels that are used for a platform. Which is something we are looking into
