### ISSUE TITLE
Error when importing ONNX into Barracuda: Asset import failed, "Assets/Model/MaskRCNN-10.onnx" > OnnxImportException: Unexpected error while parsing layer 1143 of type Squeeze. The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by NathanWoo** [Unity-Technologies/barracuda-release#153]
When importing the [Mask-RNN ONNX model](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn) from ONNX model zoo into Barracuda, I had the following error 
```
Asset import failed, "Assets/Model/MaskRCNN-10.onnx" > OnnxImportException: Unexpected error while parsing layer 1143 of type Squeeze.
The given key was not present in the dictionary.
```

**Comment by AlexRibard** [comment]
hey thank you for raising this one.
We'll take a look

**Comment by NathanWoo** [comment]
Thank you! By any chance, you guys figured out why? I would really appreciate it if you guys could show how this issue can be addressed.

**Comment by AlexRibard** [comment]
Not quite yet unfortunately, sorry to keep you waiting.
I'll let you know asap when we've pushed a fix for it.

**Comment by AlexRibard** [comment]
Hey so I took a look at your model.
We haven't implemented the op `RoiAlign` atm. Definitely in our radar. I'll keep you posted once it gets pushed

**Comment by FlorentGuinier** [comment]
Support for RoiAlign have been added (in the context of Mask R-CNN) to the roadmap, not ETA for now however. Closing the github issue, will let you know when we work on it.
