### ISSUE TITLE
Undisposed Tensor data

### ISSUE THREAD

**Issue by CoaNewco** [Unity-Technologies/barracuda-release#154]
I've had some problems when importing .onnx models to Unity, apparently, they were unreadable. This was solved when I upgraded Barracuda to 1.3.1. Now, new problem appeared. First of all, Unity eats up my RAM memory, not in play, but in 'idle' mode. Second, I disposed Tensor data in code, but Unity registers that it has found some undisposed Tensor giving me the shape that has nothing to do with the input or the output shape of my imported neural network. Could you give me any clarification?

Found unreferenced, but undisposed Tensor data which might lead to GPU resource leak: (GPU:#-1151119360 (n:1, h:45, w:60, c:256) buffer: UnityEngine.ComputeBuffer created at: )
UnityEngine.Debug:LogWarning (object)
Unity.Barracuda.D:LogWarning (object) (at Library/PackageCache/com.unity.barracuda@5ff6a21014/Barracuda/Runtime/Core/Internals/Debug.cs:72)
Unity.Barracuda.ComputeTensorData:Finalize () (at Library/PackageCache/com.unity.barracuda@5ff6a21014/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:121)

**Comment by mantasp** [comment]
Regarding GPU resource leak, could you please show your inference / cleanup code? 

Regarding "Unity eats up my RAM memory", any chance you have Unity Profiler open? I think I have seen such behavior caused by the profiler..

**Comment by CoaNewco** [comment]
`	
private IEnumerator RunCoroutine(byte[] pixels) {

		Tensor modelTensor = TransformInput(pixels);
		
		Dictionary<string, Tensor> inputs = new Dictionary<string, Tensor> {
			{ INPUT_NAME, modelTensor}
		};

		WorkerDeepLab.Execute(inputs);

		Tensor outputTensor = WorkerDeepLab.PeekOutput(OUTPUT_NAME);

		List<float> temp = outputTensor.ToReadOnlyArray().ToList();
		float max = temp.Max();
		int index = temp.IndexOf(max);

		modelTensor.Dispose();
		outputTensor.Dispose();
		yield return null;
	}
`

This is the part of code that executes nn and fetches the output. 

Nothing is opened, my guess is that Barracuda is having some problems internally with converting the our onnx model to NN.

**Comment by mantasp** [comment]
You also have to Dispose() the worker when it's not needed anymore. Another pattern we see is that script owning GameObject destruction is not properly handled and Dispose() for input tensor is not called in such case. Typically adding cleanup code in OnDestroy() method helps with the issue.

**Comment by CoaNewco** [comment]
Actually that was the case, I figured that out few days ago. I thought that I don't have to dispose of the worker if I use PeekOutput() as per documentation statements, but in reality I had to call Dispose on workers in OnDestroy() method. I wanted to update the issue but haven't had time. Thank you a lot :)
