### ISSUE TITLE
GPU inference not working on android phone

### ISSUE THREAD

**Issue by CoaNewco** [Unity-Technologies/barracuda-release#155]
How could I use android gpu for inference using barracuda? While using profiler I can see that application is only utilizing CPU and not GPU, even though I used _WorkerFactory.Type.ComputePrecompiled_ hoping it would run on phone's gpu just like it uses PC's GPU.

**Comment by AlexRibard** [comment]
Hi @CoaNewco if you use `ComputePrecompiled` worker it will run on on your phone's GPU.
Reasons why you might not see it on the profiler: 
* GPU profiling is not working. How are you profiling your application on Android?
* some nodes of your NN are not implemented in compute worker. Usually that is not the case, but you never know.

In any case, could you provide the NN so we can test on our side?
Thanks

**Comment by CoaNewco** [comment]
I am using Unity's profiler to check resources usage. NN I am using is [Resnet18](https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet18-v1-7.tar.gz) . We're in testing phase at the moment, but in the end we would like to use barracuda to infer our model of image segmentation in real time on android devices. So far, barracuda is proving to be really useful, and we're really appreciative of your support and help. Thank you for all your help.

**Comment by mantasp** [comment]
Unity Profiler supports GPU profiling only on some platforms, if it doesn't work on Android, you might try RenderDoc.

**Comment by AlexRibard** [comment]
Yeah that resnet runs fully on GPU, so things should be good.
I didn't profile that exact model, so would have to see how fast it runs.
Definitely keep us posted once you have numbers.
I'd recommend the `Snapdragon profiler` it's pretty good on Android

**Comment by CoaNewco** [comment]
I'll try both of the suggested profilers. Thank you both.
