### ISSUE TITLE
ONNX file import failed with AssertionException: Assertion failure. Value was False

### ISSUE THREAD

**Issue by ParkHaeChan** [Unity-Technologies/barracuda-release#156]
Hi, I'm trying to import onnx file to unity but it fails with this error message.
The model is style transfer network, so it needs two images for input.

> AssertionException: Assertion failure. Value was False
> Expected: True
> UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <9674024ab0e74d27bbe9eaa30dab34d1>:0)
> UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition, System.String message) (at <9674024ab0e74d27bbe9eaa30dab34d1>:0)
> UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition) (at <9674024ab0e74d27bbe9eaa30dab34d1>:0)
> Unity.Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes, System.Collections.Generic.IDictionary`2[System.String,System.Nullable`1[Unity.Barracuda.TensorShape]]& shapesByName) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Backends/ModelAnalyzer.cs:389)
> Unity.Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Backends/ModelAnalyzer.cs:70)
> Unity.Barracuda.ModelAnalyzer.FindLargestNecessaryTensorShape (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Backends/ModelAnalyzer.cs:670)
> Unity.Barracuda.GenericVarsWithPreallocation.PrepareStorage (Unity.Barracuda.Model model, Unity.Barracuda.IOps ops, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Backends/GenericWorker.cs:1353)
> Unity.Barracuda.GenericWorker.PrepareForInput (System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Backends/GenericWorker.cs:116)
> Unity.Barracuda.GenericWorker.SetInput (System.String name, Unity.Barracuda.Tensor x) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Backends/GenericWorker.cs:130)
> Unity.Barracuda.GenericWorker.Execute (System.Collections.Generic.IDictionary`2[TKey,TValue] inputs) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Backends/GenericWorker.cs:145)
> Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.FuseShapesIntoConstants (Unity.Barracuda.Model& model, System.Collections.Generic.IDictionary`2[TKey,TValue] shapesByName, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:117)
> Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.Run (Unity.Barracuda.Model& model) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:23)
> Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:12)
> Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:119)
> Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
> Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at barracuda-release-release-1.3.2/Barracuda/Editor/ONNXModelImporter.cs:58)
> UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <68af50843d0a45398c92799647332ec2>:0)

I tried this onnx file as inference at python-onnxruntime and it worked well.

Network model looks like:
```
vgg = nn.Sequential(
    nn.Conv2d(3, 3, (1, 1)),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(3, 64, (3, 3)),
    nn.ReLU(), # relu1-1
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(64, 64, (3, 3)),
    nn.ReLU(), # relu1-2
    nn.MaxPool2d((2, 2), (2, 2), (0, 0), ceil_mode=True),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(64, 128, (3, 3)),
    nn.ReLU(), # relu2-1
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(128, 128, (3, 3)),
    nn.ReLU(), # relu2-2
    nn.MaxPool2d((2, 2), (2, 2), (0, 0), ceil_mode=True),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(128, 256, (3, 3)),
    nn.ReLU(), # relu3-1
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(256, 256, (3, 3)),
    nn.ReLU(), # relu3-2
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(256, 256, (3, 3)),
    nn.ReLU(), # relu3-3
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(256, 256, (3, 3)),
    nn.ReLU(), # relu3-4
    nn.MaxPool2d((2, 2), (2, 2), (0, 0), ceil_mode=True),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(256, 512, (3, 3)),
    nn.ReLU(), # relu4-1, this is the last layer used
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(512, 512, (3, 3)),
    nn.ReLU(), # relu4-2
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(512, 512, (3, 3)),
    nn.ReLU(), # relu4-3
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(512, 512, (3, 3)),
    nn.ReLU(), # relu4-4
    nn.MaxPool2d((2, 2), (2, 2), (0, 0), ceil_mode=True),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(512, 512, (3, 3)),
    nn.ReLU(), # relu5-1
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(512, 512, (3, 3)),
    nn.ReLU(), # relu5-2
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(512, 512, (3, 3)),
    nn.ReLU(), # relu5-3
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(512, 512, (3, 3)),
    nn.ReLU() # relu5-4
)

decoder = nn.Sequential(
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(512, 256, (3, 3)),
    nn.ReLU(),
    nn.Upsample(scale_factor=2, mode='nearest'),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(256, 256, (3, 3)),
    nn.ReLU(),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(256, 256, (3, 3)),
    nn.ReLU(),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(256, 256, (3, 3)),
    nn.ReLU(),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(256, 128, (3, 3)),
    nn.ReLU(),
    nn.Upsample(scale_factor=2, mode='nearest'),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(128, 128, (3, 3)),
    nn.ReLU(),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(128, 64, (3, 3)),
    nn.ReLU(),
    nn.Upsample(scale_factor=2, mode='nearest'),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(64, 64, (3, 3)),
    nn.ReLU(),
    nn.ReflectionPad2d((1, 1, 1, 1)),
    nn.Conv2d(64, 3, (3, 3)),
)

decoder.eval()
vgg.eval()

vgg_path = './vgg_normalised.pth'
decoder_path = './decoder.pth'

decoder.load_state_dict(torch.load(decoder_path))
vgg.load_state_dict(torch.load(vgg_path))

device = torch.device("cuda")
print(device)

vgg = nn.Sequential(*list(vgg.children())[:31]) # use: first layer ~ ReLU4_1 layer

class Net(nn.Module):
    def __init__(self, encoder, decoder):
        super(Net, self).__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.mse_loss = nn.MSELoss()

        self.encoder.requires_grad = False

       ...(required methods)...

    def forward(self, content, style, alpha=1.0):
        style_feats = self.encode(style)
        content_feat = self.encode(content)
        t = Net.adaptive_instance_normalization(content_feat, style_feats)
        t = alpha * t + (1 - alpha) * content_feat
        g_t = self.decoder(t)
        return g_t
```

And this is how I save the onnx file:
```
import torch.onnx

model = Net(vgg, decoder).to(device)
batch_size = 1
x = torch.randn(batch_size, 3, 256, 256, requires_grad=False, device=device) # content
y = torch.randn(batch_size, 3, 256, 256, requires_grad=False, device=device) # style
output = model(x, y, alpha=0.8)

torch.onnx.export(model,               # model being run
(x, y),                        # model input (or a tuple for multiple inputs)
"AdaInStyleTransfer.onnx",   # where to save the model (can be a file or file-like object)
export_params=True,        # store the trained parameter weights inside the model file
opset_version=11,          # the ONNX version to export the model to
do_constant_folding=True,  # whether to execute constant folding for optimization
input_names = ['input'],   # the model's input names
output_names = ['output'], # the model's output names
dynamic_axes={'input' : {0 : 'batch_size'},    # variable lenght axes
'output' : {0 : 'batch_size'}})
```

Also, many similar warnings occured: (about 70?)

> Found unreferenced, but undisposed Tensor data that potentially participates in an unfinished job and might lead to hazardous memory overwrites: (CPU burst: 1885649408 length: 4 offset: 0 uploaded: 4 ready-to-read: unknown ready-for-reuse: unknown)
> UnityEngine.Debug:LogWarning(Object)
> Unity.Barracuda.D:LogWarning(Object) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Internals/Debug.cs:72)
> Unity.Barracuda.BurstTensorData:Finalize() (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Backends/BarracudaBurstCPU.Core.cs:75)

> Unsupported attribute ceil_mode, node 91 of type MaxPool. Value will be ignored and defaulted to 0.
> UnityEngine.Debug:LogWarning(Object)
> Unity.Barracuda.D:LogWarning(Object) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Internals/Debug.cs:72)
> Unity.Barracuda.ONNX.ONNXNodeWrapper:Warn(String) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXNodeWrapper.cs:154)
> Unity.Barracuda.ONNX.ONNXNodeWrapper:UnsupportedAttribute(String, Int32) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXNodeWrapper.cs:172)
> Unity.Barracuda.ONNX.<>c:<UseStandardImporter>b__22_71(ModelBuilder, ONNXNodeWrapper) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:626)
> Unity.Barracuda.ONNX.ONNXModelConverter:ConvertOnnxModel(ModelProto) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2616)
> Unity.Barracuda.ONNX.ONNXModelConverter:Convert(CodedInputStream) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:104)
> Unity.Barracuda.ONNX.ONNXModelConverter:Convert(String) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
> Unity.Barracuda.ONNXModelImporter:OnImportAsset(AssetImportContext) (at barracuda-release-release-1.3.2/Barracuda/Editor/ONNXModelImporter.cs:58)
> UnityEditor.Experimental.AssetImporters.ScriptedImporter:GenerateAssetData(AssetImportContext)

> Unsupported attribute nearest_mode, node 706 of type Resize. Value will be ignored and defaulted to round_prefer_floor.
> UnityEngine.Debug:LogWarning(Object)
> Unity.Barracuda.D:LogWarning(Object) (at barracuda-release-release-1.3.2/Barracuda/Runtime/Core/Internals/Debug.cs:72)
> Unity.Barracuda.ONNX.ONNXNodeWrapper:Warn(String) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXNodeWrapper.cs:154)
> Unity.Barracuda.ONNX.ONNXNodeWrapper:UnsupportedAttribute(String, String) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXNodeWrapper.cs:182)
> Unity.Barracuda.ONNX.<>c:<UseStandardImporter>b__22_75(ModelBuilder, ONNXNodeWrapper) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:676)
> Unity.Barracuda.ONNX.ONNXModelConverter:ConvertOnnxModel(ModelProto) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2616)
> Unity.Barracuda.ONNX.ONNXModelConverter:Convert(CodedInputStream) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:104)
> Unity.Barracuda.ONNX.ONNXModelConverter:Convert(String) (at barracuda-release-release-1.3.2/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
> Unity.Barracuda.ONNXModelImporter:OnImportAsset(AssetImportContext) (at barracuda-release-release-1.3.2/Barracuda/Editor/ONNXModelImporter.cs:58)
> UnityEditor.Experimental.AssetImporters.ScriptedImporter:GenerateAssetData(AssetImportContext)

Thank you for help.

**Comment by AlexRibard** [comment]
Hey @ParkHaeChan sorry to hear that.
Could you provide your onnx model? I've tried to export from the pytorch code you liked but there is a few errors in the code ( adaptive_instance_normalization not found)

**Comment by ParkHaeChan** [comment]
Thank you for help @AlexRibard .
This is full Net class code:
```
class Net(nn.Module):
    def __init__(self, encoder, decoder):
        super(Net, self).__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.mse_loss = nn.MSELoss()

        self.encoder.requires_grad = False

    @staticmethod
    def calc_mean_std(feat, eps=1e-5):
        size = feat.size()
        #assert (len(size) == 4)
        N, C = size[:2]
        feat_var = feat.view(N, C, -1).var(dim=2) + eps
        feat_std = feat_var.sqrt().view(N, C, 1, 1)
        feat_mean = feat.view(N, C, -1).mean(dim=2).view(N, C, 1, 1)
        return feat_mean, feat_std
    
    @staticmethod
    def adaptive_instance_normalization(content_feat, style_feat):
        #assert (content_feat.size()[:2] == style_feat.size()[:2])
        size = content_feat.size()
        style_mean, style_std = Net.calc_mean_std(style_feat)
        content_mean, content_std = Net.calc_mean_std(content_feat)

        # normalize
        normalized_feat = (content_feat - content_mean.expand(size)) / content_std.expand(size)
        return normalized_feat * style_std.expand(size) + style_mean.expand(size)

    def encode(self, input):
        input = self.encoder(input)
        return input

    def calc_content_loss(self, input, target):
        #assert (input.size() == target.size())
        #assert (target.requires_grad is False)
        return self.mse_loss(input, target)

    def calc_style_loss(self, input, target):
        #assert (input.size() == target.size())
        #assert (target.requires_grad is False)
        input_mean, input_std = calc_mean_std(input)
        target_mean, target_std = calc_mean_std(target)
        return self.mse_loss(input_mean, target_mean) + self.mse_loss(input_std, target_std)

    def forward(self, content, style, alpha=1.0):
        #assert 0 <= alpha <= 1
        style_feats = self.encode(style)
        content_feat = self.encode(content)
        t = Net.adaptive_instance_normalization(content_feat, style_feats)
        t = alpha * t + (1 - alpha) * content_feat

        g_t = self.decoder(t)
        return g_t
```
others are same as before.

Attached is onnx file.
[AdaInStyleTransfer.zip](https://github.com/Unity-Technologies/barracuda-release/files/6142517/AdaInStyleTransfer.zip)

**Comment by AlexRibard** [comment]
ok thanks a lot.
Checking the model, looks like a few edge cases in our constant fusing code. I'll fix them

**Comment by AlexRibard** [comment]
@ParkHaeChan pushed fixes for your model. Passes validation against onnxruntime on latest.
Expect to see if in v1.3.3 next week

**Comment by OmarVector** [comment]
@AlexRibard I hate to open this case again, But the same issue raise up But only for WEBGL, I receive the same error log on webgl but not on any other platform
