### ISSUE TITLE
Trying Yolov5s.onnx model in Barracuda 1.3.2 cause problem off-axis dimensions 

### ISSUE THREAD

**Issue by SUPEZ** [Unity-Technologies/barracuda-release#157]
Hi there, recently tried importing model yolov5s in format ONNX into Unity 2019.4.20f1 with Barracuda 1.0.4 . Several similar errors occurred: 
### **Unity:**
```
OnnxImportException: Unexpected error while parsing layer 396 of type Reshape.
Only tensors of rank 4 or less are supported, but got rank 5
```
### **Netron:**
![image](https://user-images.githubusercontent.com/44005910/111445569-94c98180-871c-11eb-8e34-7c1c29d856a1.png)

I was looking for similar solutions to the problem and came to the conclusion that for now I need to change the model to Yolov2 and maybe it will work, or use ONNXRuntime. Anyway i am noob here. Can I solve the problem with ONNXRuntime? Or need train a new model again on yolov2.
[ONNX model file](https://github.com/Unity-Technologies/barracuda-release/files/6157680/best.zip)
P.S. I solved this problem by switching the Barracuda version to 1.3.2 , but this brings up a new problem:
`Unexpected error while evaluating model output 437. System.ArgumentException: Off-axis dimensions must match`

**Comment by FlorentGuinier** [comment]
Hey Supez, first thanks for sharing your feedback!

Indeed Barracuda 1.0.2 had very light >4D tensor support, as you have noticed 1.3.x releases are the way to go for this :).

In regard to the error on 1.3.x i'm looking into it atm :)

**Comment by FlorentGuinier** [comment]
Hey again Supez,

So indeed we had a bug that your network allowed to discover, thanks!

`Slice` layer were in some case wrongly computing output tensor size --> **fix is currently in landing mode** and will be in next Barracuda patch. (if step is 2 and start is 1 output size was (initial_size/2)-1!)

_By the way:_ Something not immediatly obvious:
* ONNX is channel first and this network output 5D tensors of shapes **[1,3,X,X,6]** with X being 52,26 and 13.
* As Barracuda is channel last and all dimension mandatory the output will be transposed and be of shapes **[S:1,R:1,N:1,T:,1,D:1,X,H:X,W:6,C:3]**
Doc about tensor accessor : https://github.com/Unity-Technologies/barracuda-release/blob/release/1.3.2/Documentation~/TensorHandling.md

Thanks again for you valuable feedback!

I will post here the exact Barracuda release when the fix land.

**Comment by SUPEZ** [comment]
Thanks for the quick answer, looking forward to the next update.

**Comment by FlorentGuinier** [comment]
Hi Supez, fix is in master and will be availalbe with next patch aka 1.3.3 -> closing the bug. 

Thanks again for your feedback this will probably help many others too!
