### ISSUE TITLE
Errors when importing ONNX model with stacked BiLSTMs into unity

### ISSUE THREAD

**Issue by NCEEGEE** [Unity-Technologies/barracuda-release#158]
Hi!
I'm running into issues when importing the following model : . Getting the following error :
```
Asset import failed, "Assets/ONNX/stacked_BiLSTMs.onnx" > KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <9577ac7a62ef43179789031239ba8798>:0)
Unity.Barracuda.ONNX.ONNXModelConverter.BuildNodeSkipList (Onnx.GraphProto graph) (at Library/PackageCache/com.unity.barracuda@1.2.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1857)
```
The issue is possibly a duplicate of https://github.com/Unity-Technologies/barracuda-release/issues/98 .

**Comment by amirebrahimi** [comment]
Hi @NCEEGEE. I brought this in to our latest main branch, which has the recent LSTM fixes. Unfortunately, this model makes use of a bi-directional LSTM, which is currently not supported. I'll confer with the team.

**Comment by NCEEGEE** [comment]
@amirebrahimi Thank you for the reply. In theory, would it play nice with 1.3.3 if I rewrote the model with sequences of regular LSTMs followed by LSTMs that go backwards, instead of using the bidirectional keras layer?

**Comment by NCEEGEE** [comment]
@amirebrahimi I understand. Is there a scheduled date for the release with LSTM fixes? If not, is there any chance you could test this model and tell me if it's going to be compatible? I dare not get started on the training. 
Here's the pass with LSTMs :
```python
for i in range(3):
    if i < 2:
        fw = layers.LSTM(128, name="lstm_fw_%d" % i, dropout=0.3, return_sequences=True)(x)
        bw = layers.LSTM(128, name="lstm_bw_%d" % i, dropout=0.3, return_sequences=True, go_backwards=True)(x)
        x = layers.Concatenate()([fw, bw])
    else:
        fw = layers.LSTM(128, name="lstm_fw_%d" % i, dropout=0.3)(x)
        bw = layers.LSTM(128, name="lstm_bw_%d" % i, dropout=0.3, go_backwards=True)(x)
        x = layers.Concatenate()([fw, bw])
```

**Comment by AlexRibard** [comment]
@NCEEGEE we are running a bit late this week, so those fixes should be out next week

**Comment by amirebrahimi** [comment]
@NCEEGEE - stacked LSTMs are supported, but we don't support the reverse direction either (i.e. only forward). Could you try `keras.backend.reverse(x)` instead of setting `go_backwards=True` and send me that model?

**Comment by NCEEGEE** [comment]
@amirebrahimi Thanks for investigating! Here it is
```python
for i in range(3):
    if i < 2:
        fw = layers.LSTM(128, name="lstm_fw_%d" % i, dropout=0.3, return_sequences=True)(x)
        bw = keras.backend.reverse(x, axes=1)
        bw = layers.LSTM(128, name="lstm_bw_%d" % i, dropout=0.3, return_sequences=True)(bw)
        x = layers.Concatenate()([fw, bw])
    else:
        fw = layers.LSTM(128, name="lstm_fw_%d" % i, dropout=0.3)(x)
        bw = keras.backend.reverse(x, axes=1)
        bw = layers.LSTM(128, name="lstm_bw_%d" % i, dropout=0.3)(bw)
        x = layers.Concatenate()([fw, bw])
```

**Comment by amirebrahimi** [comment]
Thanks @NCEEGEE. This produces a [`ReverseSequence`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#ReverseSequence), which we don't support in Barracuda. Could you try exporting with opset=9 to see if that produces a different set of ops for the reverse? `ReverseSequence` was introduced in opset 10.

**Comment by NCEEGEE** [comment]
@amirebrahimi Sure thing. Here it is

**Comment by AlexRibard** [comment]
@NCEEGEE are you sure about the model? It still contains `ReverseSequence`
Make sure you are exporting with opset_version==9

**Comment by NCEEGEE** [comment]
@AlexRibard Well, here's another attempt in case I screwed something up.

This is the conversion code I used : 
```python
from tensorflow.python.keras.models import load_model
import onnx
import keras2onnx

onnx_model_name = 'foo.onnx'

model = load_model('save_at_15.h5')
onnx_model = keras2onnx.convert_keras(model, model.name, target_opset=9, channel_first_inputs=None)
onnx.save_model(onnx_model, onnx_model_name)
```

**Comment by AlexRibard** [comment]
hum strange... Let me try to retrograde onnx version

**Comment by AlexRibard** [comment]
ok I tried, doesn't work. Also it would seem that keras2onnx does whatever it wants with opsetversion.
That model is not even opset=9 valid.
`ValidationError: No Op registered for ReverseSequence with domain_version of 9`

So I think we can add `ReverseSequence` to the ToDo list

**Comment by NCEEGEE** [comment]
@AlexRibard Thanks for adding it to the list. How long do these features typically take to be implemented from the moment they're added to the list? Don't mean to put pressure, I just need to figure out my next move.

Please let me know if there is anything I can do to help.

**Comment by AlexRibard** [comment]
That depends on the priority. Unfortunately for this you are the only one to raise it. So it might take a while.
If you want a work around you'd have to implement `ReverseSequence` in keras with other ops like slice/transposes...

**Comment by NCEEGEE** [comment]
I'll get right on that. Thank you!

**Comment by NCEEGEE** [comment]
If you guys ever find the time, can you give this model a shot? Ditched the backwards LSTMs.

**Comment by AlexRibard** [comment]
Tested on 1.3.3 against onnxruntime, all seems good. Version should come out this week
Do you have a specific input size you want to try out?

**Comment by NCEEGEE** [comment]
@AlexRibard Thanks for getting back to me! No need to test further, I should be able to figure it out from there.

**Comment by NCEEGEE** [comment]
@AlexRibard Actually, I'm still running into issues. With 1.3.3 the model imports fine, but I'm getting an error and a warning when trying to run inference.

Joining the model which uses 3 stacked LSTMs, however the issue also occurs with a single LSTM using all default keras settings.

Here's the error :
> KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Unity.Barracuda.GenericVars.PeekOutput (System.String name) (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:1375)
Unity.Barracuda.GenericVarsWithReuse.PeekOutput (System.String name) (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:1477)
Unity.Barracuda.GenericVars.GatherInputs (Unity.Barracuda.Layer forLayer) (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:1322)
Unity.Barracuda.GenericWorker+<StartManualSchedule>d__33.MoveNext () (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:223)
Unity.Barracuda.GenericWorker.Execute () (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:159)
Unity.Barracuda.GenericWorker.Execute (Unity.Barracuda.Tensor input) (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:151)
Main.Core.Classifier.ClassifyDrawing (System.Single[] tensorInput) (at Assets/Code/Core/Classifier.cs:31)
Main.Core.PlayerRunner.ClassifyDrawing (System.Single[] drawingOutput) (at Assets/Code/Core/PlayerRunner.cs:89)
Main.Core.PlayerRunner.Update () (at Assets/Code/Core/PlayerRunner.cs:110)

Here's the warning :

> GenericVars missing variable: LSTM_0_Y_wm_h
UnityEngine.Debug:LogWarning (object)
Unity.Barracuda.D:LogWarning (object) (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Internals/Debug.cs:72)
Unity.Barracuda.GenericVars:PeekOutput (string) (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:1373)
Unity.Barracuda.GenericVarsWithReuse:PeekOutput (string) (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:1477)
Unity.Barracuda.GenericVars:GatherInputs (Unity.Barracuda.Layer) (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:1322)
Unity.Barracuda.GenericWorker/<StartManualSchedule>d__33:MoveNext () (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:223)
Unity.Barracuda.GenericWorker:Execute () (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:159)
Unity.Barracuda.GenericWorker:Execute (Unity.Barracuda.Tensor) (at Assets/barracuda-release-release-1.3.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:151)
Main.Core.Classifier:ClassifyDrawing (single[]) (at Assets/Code/Core/Classifier.cs:31)
Main.Core.PlayerRunner:ClassifyDrawing (single[]) (at Assets/Code/Core/PlayerRunner.cs:89)
Main.Core.PlayerRunner:Update () (at Assets/Code/Core/PlayerRunner.cs:110)

**Comment by AlexRibard** [comment]
@NCEEGEE I've just tested out your latest model in 1.3.3
On my end it works fine (checking the final output `dense` with `[2,3,17,1]` input)
Could it be that you are trying to peek an internal layer?
In any case can you share the inference call? (with the output you are trying to query?)

**Comment by NCEEGEE** [comment]
@AlexRibard Initially was calling peekoutput with no arguments. However I get the same results if trying to read "dense".  Here goes : 
```csharp
TensorShape shape = new TensorShape(1, tensorInput.Length / 3, 1, 3); // tensorInput length is a multiple of 3
Tensor input = new Tensor(shape, tensorInput);
IWorker worker = WorkerFactory.CreateWorker(model, WorkerFactory.Device.GPU);
Tensor output = worker.Execute(input).PeekOutput("dense");
```
edit : the execute call also generates the errors

**Comment by amirebrahimi** [comment]
@NCEEGEE - this is a bug that we'll fix in a future version; the issue is that you have to pass the memories explicitly even if your LSTMs did not specify explicit inputs for those. In the future, these will be initialized if not explicitly set as inputs to the model. Use this code snippet to append to the inputs that you pass to `worker.Execute()`:

```csharp
        ...
        foreach (var m in model.memories)
        {
            inputs.Add(m.input, new Tensor(m.shape));
        }
        ...
        worker.Execute(inputs);
```

**Comment by NCEEGEE** [comment]
@amirebrahimi @AlexRibard  Very cool! Thank you both!
