### ISSUE TITLE
Trouble to run in multiple threads

### ISSUE THREAD

**Issue by LyazS** [Unity-Technologies/barracuda-release#16]
when I run the execute() in main thread, it work OK, like this:

    public NNModel palmmodelSource;
    private Model palmmodel;
    private IWorker palmiworker;
    Task task;
    // Start is called before the first frame update
    void Start()
    {
        palmmodel = ModelLoader.Load(palmmodelSource);
        palmiworker = WorkerFactory.CreateWorker(WorkerFactory.Type.ComputePrecompiled, palmmodel);
        Tensor input_texture2d = new Tensor(1, 256, 256, 3);
        Debug.Log("start ex");
        palmiworker.Execute(input_texture2d);
        var t1 = palmiworker.Fetch();
        Debug.Log("end ex");

        input_texture2d.Dispose();
    }

And it outputs "start ex" and "end ex", but when I run it in Task, it cannot work:

    public NNModel palmmodelSource;
    private Model palmmodel;
    private IWorker palmiworker;
    Task task;
    // Start is called before the first frame update
    void Start()
    {
        palmmodel = ModelLoader.Load(palmmodelSource);
        palmiworker = WorkerFactory.CreateWorker(WorkerFactory.Type.ComputePrecompiled, palmmodel);
        Tensor input_texture2d = new Tensor(1, 256, 256, 3);
        task = Task.Run(() =>
        {
            Debug.Log("start ex");
            palmiworker.Execute(input_texture2d);
            var t1 = palmiworker.Fetch();
            Debug.Log("end ex");
        });
        input_texture2d.Dispose();
    }

It only outputs "start ex" but no "end ex". It seems the Execute() blocks in the task and doesn't run.
But I check that the task.IsCompleted() is true in Update(). What's more, when I use task.Wait() in Update(), Unity3d throws exception:

    UnityException: SupportsComputeShaders can only be called from the main thread.
    Constructors and field initializers will be executed from the loading thread when loading a scene.
    Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

So, what happened about those thing, and can you please give out an example to run the Execute() in multithread?
My barracuda version is 0.4.

**Comment by mantasp** [comment]
Compute based workers already work in parallel to CPU, because most of the work is executed on GPU. `Execute()` call in this case only does scheduling of the execution and should be pretty fast. 
If you don't need execution results immediately you might query them on next frame and use CPU for other things to do, while network will be executed in the background. GPU and CPU will synchronise only when you access data from output tensor.

**Comment by LyazS** [comment]
How to query if the computation is finish? Are there any marks to indicate the completion? 
Since the network maybe so large to have hundreds layers and execute across several frames.

**Comment by mantasp** [comment]
At the moment there is no easy way to check for when work is done on GPU, but most of what you want you can achieve via time sliced execution. Rough pseudocode could look like this:
```
public IWorker worker;
public IEnumerator executor;
void Start()
{
        // starts execution in layer by layer mode
        executor = worker.ExecuteAsync(input);
}
void Update()
{
        bool hasWork = false;
        int maxLayersPerTick = 10; // specify how many layers of your network to execute per frame

        do
        {  
            hasWork = executor.MoveNext();           
        } while (hasWork && --maxLayersPerTick > 0);

        if (!hasWork)
        {
            // work finished
            var output = worker.Peek();
            // do something with output
        }
        else
        {
            // Sync GPU and CPU
            worker.WaitForCompletion(); 
        }
}
```
