### ISSUE TITLE
Incorrect Output Shape 

### ISSUE THREAD

**Issue by guoguoguilai** [Unity-Technologies/barracuda-release#163]
I am using customized PoseNet based on ResNet34. I found that the output shape in Inspector is correct, which is (1,28,28,2016). However, the output shape after inderence is wrong, which is (1,32,32,2016)

![image](https://user-images.githubusercontent.com/47267017/114222031-a52dee80-99a0-11eb-84cb-c9468f7a0352.png)

How can I solve this problem?

**Comment by AlexRibard** [comment]
Interesting... Can you provide the model?

**Comment by mantasp** [comment]
@guoguoguilai output shape often depends on input shape, are you passing the same shaped inputs as they are recorded in ONNX model?

**Comment by guoguoguilai** [comment]
Thanks for your help.&nbsp;The link is : https://digital-standard.com/threedpose/models/Resnet34_3inputs_448x448_20200609.onnx
发自我的iPhone


------------------ Original ------------------
From: AlexRibard ***@***.***&gt;
Date: 周六,4月 10,2021 02:07
To: Unity-Technologies/barracuda-release ***@***.***&gt;
Cc: PageGuo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Unity-Technologies/barracuda-release] Incorrect Output Shape  (#163)





 
Interesting... Can you provide the model?

**Comment by guoguoguilai** [comment]
> @guoguoguilai output shape often depends on input shape, are you passing the same shaped inputs as they are recorded in ONNX model?

Yes! You are right. Thanks for your help! Finally I found that the input size was wrong.
