### ISSUE TITLE
Different Result between Onnx-runtime/Tensorflow

### ISSUE THREAD

**Issue by guoguoguilai** [Unity-Technologies/barracuda-release#164]
Hi,
I am using modified ResNet18 and PoseNet, which contains multiply input and output. 
```
The input of onnx : {(1, 448, 448, 3),(1, 448, 448, 3),(1, 448, 448, 3)}
The output of onnx: {(1, 48, 28, 28),(1, 24, 28, 28),(1, 2016, 28, 28),(1, 672, 28, 28)}
The input of Barracuda: {(1, 3, 448, 448),(1, 3, 448, 448),(1, 3, 448, 448)}
The output of onnx: {(1, 48, 28, 28),(1, 24, 28, 28),(1, 2016, 28, 28),(1, 672, 28, 28)}
```
I ran into Debug Mode in both Python and Unity, the following is my result:
![image](https://user-images.githubusercontent.com/47267017/114266716-5036ba80-9a2a-11eb-9743-2f45e5a2a0d6.png)

Given the same input image (448*448), the output value were different. 
In Unity ,the result of output[2] float array was `[0.9999658,-0.8997833,0.705511,...]`. But in Python ,the output was `[1,-0.999309,0.9327699,...]`. And I have tried different transpose Offset3DTranspose in Python, which took no effect. And I also tried to tranfere BGR input image to RGB in python.

Can you help me?

**Comment by AlexRibard** [comment]
@guoguoguilai am I correct to assume that the problematic model was shared here: https://github.com/Unity-Technologies/barracuda-release/issues/163 ?

**Comment by guoguoguilai** [comment]
The issue was resolved. Just be careful of the default RGB/BGR Channel and Normalization between Barracuda and Onnxruntime

**Comment by AlexRibard** [comment]
Interesting! Could you detail a bit on the differences?
