### ISSUE TITLE
Getting data out of the model

### ISSUE THREAD

**Issue by TheBricktop** [Unity-Technologies/barracuda-release#165]
Hello, after reading the docs about working with tensors and output data im kinda confused how does one get the particular data out of nn models. 
For example model ouput shape is (1,1,18,2944), i have to get out data from third and last array, what I have to do to get them out?

**Comment by AlexRibard** [comment]
Hi! Fair enough question!
First off here is the relevant documentation:
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/TensorHandling.md
Once you have recovered the output of the worker, you can access data with multidimensional accessors:
```
// as N batches of 3 dimensional data: N x {X, Y, C}
tensor[n, x, y, c] = 1.0f;
```
For your case it is probably
```
tensor[0,0,3,0];
tensor[0,0,3,1];
tensor[0,0,3,2];
....
```
Now if you wish to extract a whole Slice into a Tensor directly, you can use the `ModelBuilder` class to append a layer to the model to output said slice.
Let me know what you wish to accomplish.

**Comment by TheBricktop** [comment]
Well im not entirely sure how the tensor.AsFloats() work, does it stuff all of the jagged array objects into one dimensional array?
Is there any good way to get only X,Y or C array of data?

**Comment by AlexRibard** [comment]
tensor.AsFloats() yes dumps everything in a 1D array.
I am assuming that you are you wanting to access a single C at a given x,y?
In that case you have a few choices
* iterate of all C
```
var channels = new float[tensor.channels];
for (int i = 0; i < tensor.channels; i++)
   channels[i] = tensor[0,x,y,i];
````
that would be the simplest.
* add an additional  `StridedSlice` layer to your model using the `ModelBuilder`
```
var builder = new ModelBuilder(model);
int[] starts  = {0, x, y, 0};
int[] ends   = {0, x, y,  channels};
int[] strides = {1, 1, 1, 1};
builder.StridedSlice("outputslice, "original_output", starts, ends, strides);
```
now you have an additional output to your model which will output said slice

**Comment by AlexRibard** [comment]
@TheBricktop feel free to re-open if this is still an issue

**Comment by TheBricktop** [comment]
@AlexRibard  Thank You for great tutorial, i think that this should be a part of regular docs on barracuda! Is there a way to preserve Your explanation for future?

**Comment by AlexRibard** [comment]
Good idea! Will update accordingly
