### ISSUE TITLE
How can I load my models from streaming assets on Android device?

### ISSUE THREAD

**Issue by giga1992** [Unity-Technologies/barracuda-release#167]
I'm having some problems figuring out how to load my models from streaming assets using ModelLoader.LoadFromStreamingAssets function and figuring out the path for my android device. Any help would be appreciated. Also, soon I would be trying to do the same for iOS device, so the question would be the same for this issue.

**Comment by CoaNewco** [comment]
Hopefully this will help.

        var path = Path.Combine(Application.streamingAssetsPath, "your.file");
        UnityWebRequest www = UnityWebRequest.Get(path);
        www.SendWebRequest();
        yield return new WaitWhile(() => !enc.isDone);

        myWorker= ModelLoader.Load(www.downloadHandler.data).CreateWorker(WorkerFactory.Device.GPU);

**Comment by FlorentGuinier** [comment]
Closing as answer was provided, thanks @CoaNewco!
