### ISSUE TITLE
How to run a custom NN model for detection on a single image

### ISSUE THREAD

**Issue by gioriog** [Unity-Technologies/barracuda-release#168]
Hello everyone, I have trained a custom yolov3 model and succesfully converted to a onnx format for Unity.
My application has to create an image from a camera and use it as input to the onnx model. Then get the detection and show the result. 

![0](https://user-images.githubusercontent.com/45177062/116260144-b9cafe80-a776-11eb-8d85-f6ba56ce8da0.png)
![0result](https://user-images.githubusercontent.com/45177062/116260160-bc2d5880-a776-11eb-8a39-6bfd9a41c082.png)

However as you can notice, the result image makes no sense. I wonder what am I doing wrong. I link also the code. Thank you for your time. 

[detection.zip](https://github.com/Unity-Technologies/barracuda-release/files/6385364/detection.zip)

**Comment by AlexRibard** [comment]
@gioriog thanks for the code.
Can you provide the onnx model you are using as well?

**Comment by gioriog** [comment]
> @gioriog thanks for the code.
> Can you provide the onnx model you are using as well?

Yes sure. Here you are. File wa too big for a zip.
https://drive.google.com/file/d/1uqhFHXIAAh-HChWwTRwyVd94tvEFHkJb/view?usp=sharing

**Comment by AlexRibard** [comment]
thank you

**Comment by FlorentGuinier** [comment]
@gioriog looking at the code is see a few things that might be around the problem:

1 - Model take 416x416x3 input, if i read correctly the RT from camera is resized to it using TransformInput() itself depending on cam.targetTexture being 416x416, if this is not the case tensor will contain corrupted data afaics.
2 - var output = worker.PeekOutput(); model contain 3 differents output, you may want to call PeekOut(string name) to be sure to grab the correct one.
3 - when converting input in TransformInput() it could be interresting to compute mean and bound to ensure this is consistent with the range the network was trained with in python. Actually exporting inference input/output from python and feeding barracuda with it could really help debug here imho.

Hope it helps :) Let us know :)

**Comment by gioriog** [comment]
Hello @FlorentGuinier, thank you for your feedback. 
The Render Texture 'targetTexture' is a game Object defined for the camera and his size is 416x416, so it should be ok. 
I tried to pass as parameter the name of the output layers (082_convolutional, 094_convolutional and 106_convolutional) to PeekOutput function and those are the results respectively
![0result](https://user-images.githubusercontent.com/45177062/116565413-23c5de00-a906-11eb-9053-f05ca4323ba0.png)
![0result](https://user-images.githubusercontent.com/45177062/116564528-5ae7bf80-a905-11eb-9519-24d301a9044a.png)
![0result](https://user-images.githubusercontent.com/45177062/116564351-2f64d500-a905-11eb-841a-051586fd89a0.png)

About the last comment, I dont know if I understand but you are suggesting to detect the exact mean and standard deviation of the image that I use as input??

This is the link I used to write my code. However it does not explain how i can retrieve BoundingBox and prediction result. 
Actually what I dont understand how to extrapolate those information from the tensor output.
https://docs.unity3d.com/Packages/com.unity.barracuda@0.2/manual/index.html

**Comment by FlorentGuinier** [comment]
> About the last comment, I dont know if I understand but you are suggesting to detect the exact mean and standard deviation of the image that I use as input??

Yes the model in Barracuda should receive an input in the same range it was trained in python. Computing std deviation and mean in both environement would help check that

> However it does not explain how i can retrieve BoundingBox and prediction result

imho you found the problem :)  var output = `worker.PeekOutput().ToRenderTexture()` make no sense here! As you say the output of yolov3 are not textures but rather bounding box and predictions, so you will need to check this particular network and interpret result accordingly (for example https://towardsdatascience.com/yolo-v3-explained-ff5b850390f) for this the easyest is probably to access output tensor using 
`tensor[n, y, x, c]`

**Comment by gioriog** [comment]
Ok I think now I am starting to understand how it works. I will try to interpret the result of the tensor and then I will draw the bounding box on the image on my own. 
My mistake was that I though PeekOutput returned itself the Image with bounding box.
Thank you for clarification, I will try to write some code and let you know if I managed to do it.

**Comment by FlorentGuinier** [comment]
Pleasure! Closing the issue. Feel free to reopen :)

**Comment by Ademord** [comment]
> Ok I think now I am starting to understand how it works. I will try to interpret the result of the tensor and then I will draw the bounding box on the image on my own.
> My mistake was that I though PeekOutput returned itself the Image with bounding box.
> Thank you for clarification, I will try to write some code and let you know if I managed to do it.

were you able to run it? could I email you for you to explain me how you did it? i am trying to do the same

**Comment by gioriog** [comment]
Hi @Ademord. Yes  I was able to interpret the tensor output. You can give a look to this tutorial by microsoft in order to manage using onnx file. 
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx
