### ISSUE TITLE
ONNX model warnings and import error occured (1.4.0 version)

### ISSUE THREAD

**Issue by ParkHaeChan** [Unity-Technologies/barracuda-release#169]
Hello, I found warnings and errors while importing my onnx file.
 
 I reported this issue a month ago and it was solved with 1.3.3 version.
[https://github.com/Unity-Technologies/barracuda-release/issues/156](url) 

 But It has some warnings and NNModel result was not fully returned.
(right image should be same size with left images - version 1.3.3)
![issue_not_fully_returned_133](https://user-images.githubusercontent.com/26519764/116503733-c6c02d00-a8f1-11eb-8e14-a1f356cadafd.PNG)

 
 So today,
 I tried 1.4.0 version but this version incurred error with my onnx file.
![issue_import_error_140](https://user-images.githubusercontent.com/26519764/116503773-d8a1d000-a8f1-11eb-9f6b-37a81bb551aa.PNG)

this onnx file still works well with python onnxruntime.

Attached is my onnx file.
[AdaInStyleTransfer.zip](https://github.com/Unity-Technologies/barracuda-release/files/6396387/AdaInStyleTransfer.zip)

Below is c# script code.
[BarracudaTest.zip](https://github.com/Unity-Technologies/barracuda-release/files/6396454/BarracudaTest.zip)

Thank you for help.

**Comment by FlorentGuinier** [comment]
@ParkHaeChan Thanks for reporting this! This look like a regression in 1.4.0. Here is the related unity bug : https://issuetracker.unity3d.com/product/unity/issues/guid/BAR-57.

**Comment by AlexRibard** [comment]
@ParkHaeChan we've fixed the problem and will push the fix in a upcoming version.
(btw there actually was a bug in 1.3 as well, the output shape doesn't match what it is supposed to)
Here is the result:
![image](https://user-images.githubusercontent.com/12990800/118311861-771b5d00-b4be-11eb-950e-125a5a876ffd.png)
I was not able to run your model in onnxruntime, so I cannot add it to our test suite. Could you try to export with opset 11 or 9 to see if that makes a difference?

**Comment by ParkHaeChan** [comment]
I found opset 9 failed to export onnx file with my model.

this is the error message when I tried opset 9.

C:\Users\Admin\.conda\envs\MLAgentsPytorch\lib\site-packages\torch\onnx\symbolic_helper.py:220: UserWarning: ONNX export failed on _cast_Undefined because input size not accessible not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
Traceback (most recent call last):
  File "c:/Users/Admin/Documents/VisualStudioCode/AdaINStyleTransferPytorch/AdaInST.py", line 221, in <module>
    torch.onnx.export(model,               # model being run
  File "C:\Users\Admin\.conda\envs\MLAgentsPytorch\lib\site-packages\torch\onnx\__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "C:\Users\Admin\.conda\envs\MLAgentsPytorch\lib\site-packages\torch\onnx\utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "C:\Users\Admin\.conda\envs\MLAgentsPytorch\lib\site-packages\torch\onnx\utils.py", line 691, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "C:\Users\Admin\.conda\envs\MLAgentsPytorch\lib\site-packages\torch\onnx\utils.py", line 460, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "C:\Users\Admin\.conda\envs\MLAgentsPytorch\lib\site-packages\torch\onnx\utils.py", line 206, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\Admin\.conda\envs\MLAgentsPytorch\lib\site-packages\torch\onnx\__init__.py", line 309, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\Users\Admin\.conda\envs\MLAgentsPytorch\lib\site-packages\torch\onnx\utils.py", line 994, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "C:\Users\Admin\.conda\envs\MLAgentsPytorch\lib\site-packages\torch\onnx\symbolic_helper.py", line 148, in wrapper
    return fn(g, *args, **kwargs)
  File "C:\Users\Admin\.conda\envs\MLAgentsPytorch\lib\site-packages\torch\onnx\symbolic_opset9.py", line 810, in symbolic_fn
    padding = padding + tuple(numpy.add(padding_ceil, padding))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
(Occurred when translating max_pool2d).


but opset 10, 11 worked.

below is the code, exporting onnx file.

```
torch.onnx.export(model,               # model being run
(content, style),                        # model input (or a tuple for multiple inputs)
"AdaInStyleTransfer_ver9.onnx",   # where to save the model (can be a file or file-like object)
export_params=True,        # store the trained parameter weights inside the model file
opset_version=9,          # the ONNX version to export the model to
do_constant_folding=True,  # whether to execute constant folding for optimization
input_names = ['content', 'style'],   # the model's input names
output_names = ['output'], # the model's output names
dynamic_axes={'content' : {0:'batch_size', 2:'width', 3:'height'},    # variable lenght axes: everything except color channel
'style' : {0:'batch_size', 2:'width', 3:'height'},
'output' : {0:'batch_size', 2:'width', 3:'height'}})
```


I attached the opset 11 onnxfile and onnxruntime script.
[AdaINStyleTransferPytorch.zip](https://github.com/Unity-Technologies/barracuda-release/files/6513823/AdaINStyleTransferPytorch.zip)

**Comment by AlexRibard** [comment]
I took a look at the provided model. Could you export it with known input dimensions?

**Comment by AlexRibard** [comment]
code landed in master, @ParkHaeChan lookout for upcoming version (for the initial NN you provided)
