### ISSUE TITLE
Adding Pixel Shuffle!

### ISSUE THREAD

**Issue by supratikbanerjee** [Unity-Technologies/barracuda-release#17]
Hi,

I have been working on a project for which it would be nice to have a pixel shuffle function as in pytorch. I cannot find any official support for pixel shuffle, but when I export my pytorch model with ONNX it loads properly in unity, except the final rendered image is weirdly warped.

https://pytorch.org/docs/stable/_modules/torch/nn/modules/pixelshuffle.html456

Any help will be sincerely appreciated,

Thanks

**Comment by mantasp** [comment]
Thank you for reporting it, at the moment pixel shuffle is not supported by Barracuda
