### ISSUE TITLE
Fused MLP Support

### ISSUE THREAD

**Issue by abigos** [Unity-Technologies/barracuda-release#182]
Hi,

Small MLPs are becoming a popular representation for implicit representations (see https://github.com/vsitzmann/awesome-implicit-representations), but as they’re quite small there's a performance issue when working with a generic inference library as the overheads of handling layers can become quite high when you evaluate models on a (for example) per pixel basis. One approach is to fuse all the layers into a single code blob and process it one go - you can see an example here: https://github.com/NVlabs/tiny-cuda-nn (this actually includes training and inference).  I was wondering how feasible you think it would be to add this kind of inference to Barracuda, e.g. match for some specific network configs and use an optimized full model code path?     (Mainly makes sense for 'vanilla' MLPs with standard activations)

Thanks

**Comment by AlexRibard** [comment]
Hi @abigos !
You are correct, small MLP are indeed becoming popular (SIREN/NERF...) and are indeed part of our radar.

Could you clarify a bit what do you mean by "fusing all the layers" ?
We currently do fuse consecutive linear layers and contiguous activation in a MLP dispatch, but we stop as soon as there is a non linearity. So MLP0 -> Relu -> MLP1 -> Relu -> MLP2 will become  MLP0Relu -> MLP1Relu -> MLP2 
Judging on the cuda code you shared, I am assuming you mean directly do MLP0 -> Relu -> MLP1 -> Relu -> MLP2.... directly in one dispatch call?

I think that is for sure possible for us to detect that pattern and fuse it together. We actually do similar things currently.

But I feel that unless your MLP weights + input fully fit in shared memory, you'll have some problems with loading the next block needed for the upcoming MatMul (so output of previous MatMul). So I feel you'd need to store to global memory anyway, and that would be the same as multiple dispatches.

I am mostly speculating here however. I think it would be good to do a case study on a specific example.
What is your typical input/weights sizes?

I'd say that what we lack in Barracuda atm in that regards is a specific MLP code specifically designed for large batch size and smaller inner MatMul loop.
One other thing we are looking at is to support the `Loop` operator in onnx to avoid needing to re-schedule your entire network.

But do share more details/examples as we are keen to explore this space

**Comment by abigos** [comment]
Hi Alex,

Yes, I mean create a single dispatch for a complete model evaluation. As you say, it only makes sense if you can fit all the weights into shared memory - but if you can do that you can get a big speedup. I think if this was available you would be tuning your network to be able to fit into memory for the use cases I have in mind (touching each pixel),  e.g. you would be targeting a specific target architecture.

I'm adding a sample net to give you an idea of the ballpark size of model for my specific application (which is retrieving incoming radiance at each pixel in a scene)- this one is on the larger side:   [mlp-model.zip](https://github.com/Unity-Technologies/barracuda-release/files/6547962/mlp-model.zip)

There's a video here with some more details of the repo I linked above : https://tom94.net/data/publications/mueller21realtime/mueller21realtime-gtc.mp4 – it’s worth watching as they cover the benefits of fusing and practical issues along with a very cool use case  (really impressive as they also do the training on the fly!).

**Comment by AlexRibard** [comment]
Thanks!

Indeed yeah, it would be nice to have a fully fused path for these kind of models.
I think for us, since we want to be a bit more generic (and not simply do a custom kernel for NeRF model) it'll take some time before it ships.
But it's doable.

At the moment, making NeRF models more efficient is in our radar. So we'll definitely be making a custom kernel for smaller matmul with large batch size.
If we do come up with a custom shader like you mention we'd most likely release it for some demo in some annex github project

**Comment by abigos** [comment]
Hi Alex,

I agree. NeRF and related are interesting, but that area is developing so quickly that a simple implementation of NeRF (or one of the many approaches to speed it up) isn't so useful.  What would be more useful is to provide examples of how the building blocks of these approaches (positional encoding, fast MLP evaluation) can be implemented in Barracuda in an efficient way.   This would be useful for things like DeepSDF and Neural LOD etc. in addition to NeRF.

I guess one approach might be to have a way to specify a level of optimization - and one level is making a fused network, with the expectation that sometimes (often) this will fail to work (and depends on architecture etc.), but in that case you can always fall back to another implementation.  

Anyway, glad to hear this is on your radar. It would be great to see something like this working on Barracuda.  I'll close this issues, but please ping me if you make progress in this area or would like to discuss more.   

Thanks
Andy
