### ISSUE TITLE
Error Loading Model

### ISSUE THREAD

**Issue by abigos** [Unity-Technologies/barracuda-release#185]
Hi,

I get the assert below when loading a model (on 2.0.0-pre.5).  I've enclosed the onnx model.

Thanks

[bird_256x256_6-256-256-3_SINE_POSITION_1.zip](https://github.com/Unity-Technologies/barracuda-release/files/6597537/bird_256x256_6-256-256-3_SINE_POSITION_1.zip)

`Asset import failed, "Assets/Models/bird_256x256_6-256-256-3_RELU_POSITION_1.onnx" > AssertionException: Assertion failure. Values are not equal.
Expected: 2 == 1
InferOutputRank.Dense inputRanks
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <4577339eb6f24e22b2a4431e652bd511>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <4577339eb6f24e22b2a4431e652bd511>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at <4577339eb6f24e22b2a4431e652bd511>:0)
UnityEngine.Assertions.Assert.AreEqual (System.Int32 expected, System.Int32 actual, System.String message) (at <4577339eb6f24e22b2a4431e652bd511>:0)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.RankInference.InferOutputRank (Unity.Barracuda.Layer layer, System.Int32[] inputRanks) (at Library/PackageCache/com.unity.barracuda@2.0.0-pre.5/Barracuda/Runtime/Core/Compiler/ShapeInference/IRRankInferenceHelper.cs:21)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.RankInference.UpdateKnownTensorRanks (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@2.0.0-pre.5/Barracuda/Runtime/Core/Compiler/ShapeInference/IRRankInferenceHelper.cs:256)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.FuseShapesIntoConstants (Unity.Barracuda.Model& model, System.Collections.Generic.IDictionary`2[TKey,TValue] shapesByName, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@2.0.0-pre.5/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:65)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.0.0-pre.5/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:23)
Unity.Barracuda.Compiler.Passes.ValidateNCHWShapesPass.Run (Unity.Barracuda.Model model, System.Collections.Generic.List`1[Unity.Barracuda.Model+ImporterWarning]& warnings) (at Library/PackageCache/com.unity.barracuda@2.0.0-pre.5/Barracuda/Runtime/Core/Compiler/Passes/ValidatePasses.cs:52)
Unity.Barracuda.Compiler.Passes.ValidateNCHWPass.Run (Unity.Barracuda.Model model, System.Collections.Generic.List`1[Unity.Barracuda.Model+ImporterWarning]& warnings) (at Library/PackageCache/com.unity.barracuda@2.0.0-pre.5/Barracuda/Runtime/Core/Compiler/Passes/ValidatePasses.cs:211)
Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.0.0-pre.5/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:29)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@2.0.0-pre.5/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:170)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@2.0.0-pre.5/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@2.0.0-pre.5/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <2b3dc6c508754760a989e810beb820a9>:0)

 `

**Comment by mantasp** [comment]
At the moment we support tensors that have at least 2 dimensions, so I would recommend to modify your network to accept input of shape `[batch, 6]` instead of `[6]`

**Comment by abigos** [comment]
That makes sense.  Thanks!
