### ISSUE TITLE
Images missing in Getting Started

### ISSUE THREAD

**Issue by Ademord** [Unity-Technologies/barracuda-release#186]
Hello, there are broken files in the documentation. For example: https://github.com/Unity-Technologies/barracuda-release/blob/release/2.1.0/Documentation~/GettingStarted.md.

**Comment by FlorentGuinier** [comment]
Hi @adel-s thanks for reporting we will be looking into it!

**Comment by FlorentGuinier** [comment]
Fixed, thanks again for reporting this.
