### ISSUE TITLE
Not showing in package manager

### ISSUE THREAD

**Issue by jaclemoe** [Unity-Technologies/barracuda-release#189]
It would be great to be able to install Barracuda through the Package Manager. 
I am aware the documentation describes other ways to install and explicitly mentioned it's not on the PM, still I think it would be useful?

**Comment by FlorentGuinier** [comment]
Hi @jaclemoe , Thanks for your feedback.

Indeed this is something we look forward and are working toward. Please note that this should only be a problem with Unity 2020.3. Prior to that you should see it listed in the package manager: https://docs.unity3d.com/Packages/com.unity.barracuda@2.1/manual/Installing.html

**Comment by FlorentGuinier** [comment]
Closing as discussion seems finished here, thanks a lot for your feedback. Please reopen if needed!
