### ISSUE TITLE
Problem converting Tensorflow model

### ISSUE THREAD

**Issue by SestoAle** [Unity-Technologies/barracuda-release#19]
Hi,

I have a complex tensorflow model that can't be converted to a barracuda model using the script you provide, as it says:

"
Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 28, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "/home/sestini/Scrivania/Barracuda/tensorflow_to_barracuda.py", line 1549, in convert
    i_model.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
"

Until now I was able to use these models with TensorFlowSharp, but it seems to not support TensorFlow 2.0.

Is there any simple way to use TensorFlow.NET (https://github.com/SciSharp/TensorFlow.NET) in Unity?

Thanks!

**Comment by mantasp** [comment]
how did you save your model? from the error message it looks like it was saved in keras format.

**Comment by SestoAle** [comment]
I made some progress on saving the file, but now it says:

`IGNORED: GatherV2 unknown layer
Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 28, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "/home/sestini/Scrivania/Barracuda/tensorflow_to_barracuda.py", line 1562, in convert
    i_model, args
  File "/home/sestini/Scrivania/Barracuda/tensorflow_to_barracuda.py", line 1387, in process_model
    process_layer(n, o_context, args)
  File "/home/sestini/Scrivania/Barracuda/tensorflow_to_barracuda.py", line 1230, in process_layer
    assert all_elements_equal(input_ranks)
AssertionError
`

I'm using tensorflow 1.13.1 right now, but I want to pass to Tensorflow 2

**Comment by tomash1234** [comment]
If model is saved in keras format. You can use **keras_to_barracuda.py** script.

python keras_to_barracuda.py model.h5 model.nn

**Comment by SestoAle** [comment]
As I said, the model is not saved in keras but in tensorflow 1.13.1.

Also my question is, if I am not able to convert it into a barracuda model, is there another way to use a complex tensorflow model within Unity instead of using barracuda?

**Comment by mantasp** [comment]
There is another way to get model into Barracuda via tf2onnx and then dropping ONNX file right into Assets folder, where it will be picked by Barracuda. In general it would be interesting to have a closer look at your model and possibly add missing pieces to the Barracuda roadmap.

At the moment there are no plans at Unity to support other NN libraries directly in Unity.

**Comment by Guidosalimbeni** [comment]
HI @tomash1234 , 
have you solved your issue? I think I have the same problems to convert a h5 into nn. Is there a specific version of keras that I need to have or python?

**Comment by AlexRibard** [comment]
@Guidosalimbeni internally we use Keras==2.0.8

@tomash1234 and @Guidosalimbeni You can also use https://pypi.org/project/keras2onnx/ and convert your keras model to onnx then do what @mantasp explained.
If you manage to export it to onnx, then import into Unity should work easily.

Let me know!

**Comment by ghost** [comment]
I tried converting the complete tensorflow saved model folder or saved_model.pb to barracuda (.nn) format using tensorflow_to_barracuda.py and got this:

Converting ../../tensorflow-yolov4-tflite/data/checkpoints/yolov4-tiny-416/saved_model.pb to ../../tensorflow-yolov4-tflite/data/checkpoints/yolov4-tiny-416.nn
WARNING:tensorflow:From /content/drive/My Drive/RE-AI/KfV/Yolov4/barracuda-release/Tools/tensorflow_to_barracuda.py:1350: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 21, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "/content/drive/My Drive/RE-AI/KfV/Yolov4/barracuda-release/Tools/tensorflow_to_barracuda.py", line 1351, in convert
    i_model.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message

kindly please help. Thanks!

**Comment by AlexRibard** [comment]
Hi @re-shubhamturai the tensorflow_to_barracuda.py is slowly being phased out for more consistent import process
Refer to the doc for details:
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Exporting.md
For TF we recommend using `tf2onnx` and import the onnx file to Unity.

Let me know how it goes or if you have any issues
