### ISSUE TITLE
Unknown type Size encountered

### ISSUE THREAD

**Issue by martoko** [Unity-Technologies/barracuda-release#190]
Asset import failed, "Assets/Models/movenet_singlepose_thunder_3_unity.onnx" > OnnxImportException: Unknown type Size encountered while parsing layer Size__357:0.

I am trying to import an ONNX model into Unity, but it seems that the Size operation is not implemented.

**Comment by martoko** [comment]
Seems loop is also missing.

The model was converted using tf2onnx opset 7:
[movenet_singlepose_thunder_3.zip](https://github.com/Unity-Technologies/barracuda-release/files/6638586/movenet_singlepose_thunder_3.zip)

I tried fixing it by hard coding the output of size:
```python
import numpy as np
import onnx
import onnxruntime

model = onnx.load("models/movenet_singlepose_thunder_3.onnx")

node_index = 0
for node in model.graph.node:
	if node.op_type == "Split":
		axis = node.attribute[0].i
		if node.name == "StatefulPartitionedCall/unstack":
			split = np.array([1]).astype(np.int64)
		if node.name == "StatefulPartitionedCall/unstack_1":
			split = np.array([1, 1]).astype(np.int64) # WTH
		if node.name == "StatefulPartitionedCall/unstack_2":
			split = np.array([1, 1]).astype(np.int64) # WTH
		
		new_node = onnx.helper.make_node(
			"Split",
			name=node.name,
			inputs=node.input,
			outputs=node.output,
			axis=axis,
			split=split
		)
		model.graph.node.remove(node)
		model.graph.node.insert(node_index, new_node)

	if node.name == "Size__358":
		values = np.array([3])
		new_node = onnx.helper.make_node(
			"Constant",
			name=node.name,
			inputs=[],
			outputs=node.output,
			value=onnx.helper.make_tensor(
				name='const_tensor',
				data_type=onnx.mapping.NP_TYPE_TO_TENSOR_TYPE[np.dtype(np.int64)],
				dims=values.shape,
				vals=values.flatten()
			)
		)
		model.graph.node.remove(node)
		model.graph.node.insert(node_index, new_node)

	if node.name == "Size__494":
		values = np.array([3])
		new_node = onnx.helper.make_node(
			"Constant",
			name=node.name,
			inputs=[],
			outputs=node.output,
			value=onnx.helper.make_tensor(
				name='const_tensor',
				data_type=onnx.mapping.NP_TYPE_TO_TENSOR_TYPE[np.dtype(np.int64)],
				dims=values.shape,
				vals=values.flatten()
			)
		)
		model.graph.node.remove(node)
		model.graph.node.insert(node_index, new_node)
		
	node_index += 1

onnx.checker.check_model(model)
onnx.save(model, "models/movenet_singlepose_thunder_3_unity.onnx")

# CHECK
img = np.random.rand(1, 256, 256, 3).astype(np.int32)

# ORG
sess = onnxruntime.InferenceSession("models/movenet_singlepose_thunder_3.onnx")


print("The model expects input shape: ", sess.get_inputs()[0].shape)
print("The shape of the Image is: ", img.shape)

input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
result = sess.run(None, {input_name: img})
print(result)
print()

# CHANGED
sess = onnxruntime.InferenceSession("models/movenet_singlepose_thunder_3_unity.onnx")


print("The model expects input shape: ", sess.get_inputs()[0].shape)
print("The shape of the Image is: ", img.shape)

input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
result = sess.run(None, {input_name: img})
print(result)
print()
```

But now the Loop operation is missing.

**Comment by FlorentGuinier** [comment]
Hi @martoko, 
At a quick glance we are at least missing Slice and Loop operator for this model indeed.
- Slice: We don't support it at the moment for a bit of a legacy reason, we need a refactor to support operators with multiple output tensors, so not on the roadmap so far but could definitively happens.
- Loop: This one is more tricky, in general because we among other target GPU inference on a wide range of hardware we haven't dig into the area of conditional operators (ie those are the operators that can alter the graph of execution at runtime) this is by choice as efficient implementation would be tricky on some of those hardware. 

Could you describe your use case and if another model is an option please?

Florent

**Comment by martoko** [comment]
I was trying to get [MoveNet](https://blog.tensorflow.org/2021/05/next-generation-pose-detection-with-movenet-and-tensorflowjs.html) to run inside Unity to perform pose estimation.

Using [ONNX Runtime](https://github.com/microsoft/onnxruntime) inside Unity worked flawlessly however, and I am now using that instead of Barracuda.

It seems that the Loop operation is not actually necessary.
This is the model I got efter converting it with opset 13:
[movenet_singlepose_thunder_3.zip](https://github.com/Unity-Technologies/barracuda-release/files/6649519/movenet_singlepose_thunder_3.zip)

**Comment by amirebrahimi** [comment]
Closing this issue, then, as it seems to be resolved.

**Comment by kurokaj** [comment]
Hi,

I'm facing the same issue with the MoveNet model. I also tried to use the ONNX Runtime inside Unity but I was having trouble loading in the DLL:s. @martoko how did you set up the ONNX Runtime? And what opset did you use in tf2onnx conversion in the current working model? 

-Jonne
