### ISSUE TITLE
Build failed in Unity Cloud Build

### ISSUE THREAD

**Issue by ran-bg** [Unity-Technologies/barracuda-release#193]
Hello. I'm using Barracuda 1.0.4 in my project, and when building Android APK (in both local env and Unity Cloud), everything works fine as expected, and APK file can be created.
After upgrading Barracuda to 1.4.0, Android APK build works only in local env but fails in Unity Cloud. 
I cannot figure out what happened in Unity Cloud, so could you please help me with that issue? Thank you.
My Developing Environment:
- Unity 2019.4.16f1~Unity 2019.4.28f1 
- Target Platform: Android 
- Barracuda ver: 1.4.0
- JDK, Android SDK/NDK: 
    - Local: Built-in with Unity 2019
    - Unity Cloud: Unity Cloud version  

I attached the build log from Unity Cloud Build. Thanks.
[buildlog.txt](https://github.com/Unity-Technologies/barracuda-release/files/6652694/buildlog.txt)

**Comment by amirebrahimi** [comment]
Thank you for reporting this issue. I will have to check in with the Unity Cloud team to see what the issue may be.

**Comment by amirebrahimi** [comment]
@ran-bg - can you clarify which version of Unity you used? You gave a range, but when you tested building locally did you test those two versions or the range of versions?

It looks like Cloud Build is using 2019.4.27f1

**Comment by amirebrahimi** [comment]
@ran-bg - I have our Cloud Build team involved now to help investigate. If you're able to - can you send me the project ID to barracuda-support at unity3d dot com?

**Comment by ran-bg** [comment]
@amirebrahimi 
Hello, Thank you for the response.

> can you clarify which version of Unity you used? You gave a range, but when you tested building locally did you test those two versions or the range of versions?

In Local Env: I tested using Unity 2019.4.16, Unity 2019.4.27, Unity 2019.4.28. all seem ok, and APK can be built without error.
Unity Cloud: I tested using Unity 2019.4.16 and Unity 2019.4.27, neither can build APK successfully, and the error logs are almost identical to the log file I attached at very beginning

**Comment by ran-bg** [comment]
@amirebrahimi 
> If you're able to - can you send me the project ID to barracuda-support at unity3d dot com?

Project ID: e5b12a10-0151-4a67-8375-e40b9c4ed9cc
Config Label: Android Development IL2CPP Test

Thank you.

**Comment by ran-bg** [comment]
I also tested using Unity 2019.4.16 + Barracuda 1.1.0/1.2.0, both versions seem to work and APK can be built successfully.
I'm testing using ver. 1.3.0, and will edit this post again after build finishes.

build with ver. 1.3.0 failed. the error seems almost identical. I attach it here. 
Thank you.

[buildlog-ver1.3.0.txt](https://github.com/Unity-Technologies/barracuda-release/files/6662497/buildlog-ver1.3.0.txt)

**Comment by ran-bg** [comment]
Hello. 
Is there any new progress?
  
Thank you.

**Comment by amirebrahimi** [comment]
Hi @ran-bg, I have someone in the cloud build team who is looking at it. He tried to reproduce the problem by setting up a simple Barracuda project locally and in Cloud Build, but was unsuccessful. He is still on it, but it is proving difficult to solve.

**Comment by ran-bg** [comment]
Thank you.

We use [PoseNet for Unity](https://github.com/infocom-tpo/PoseNet-Unity) + Barracuda(ver 1.0.4) to detect human pose which can be built successfully. 
I don't know why it is failed when upgrading Barracuda to ver.1.4.0.

**Comment by ran-bg** [comment]
I'll extract the parts where Barracuda is applied from my project and share it with you. Please wait for a while.

**Comment by ran-bg** [comment]
Hi, @amirebrahimi 
I created a minimum demo extracted from my project, 
I removed most of the unnecessary parts and kept the Barracuda(ver 1.0.4) + PoseNet implementation.
I uploaded the src to Google drive, and please check this this demo, upgrade Barracuda to ver. 1.4.0, if possible.
Thanks.

https://drive.google.com/file/d/1xw8e3Ahd5bnvCf_SaGAIGKZqj1qYofbu/view?usp=sharing

**Comment by ran-bg** [comment]
Hello,

I created a minimum demo extracted from my project,
I removed most of the unnecessary parts and kept the Barracuda(ver 1.0.4) +
PoseNet implementation.
I uploaded the src to Google drive, and please check this this demo, if
possible.
Thanks.
https://drive.google.com/file/d/1xw8e3Ahd5bnvCf_SaGAIGKZqj1qYofbu/view?usp=sharing

>

**Comment by amirebrahimi** [comment]
Thank you. I will pass this on to the Unity Cloud build dev.

**Comment by amirebrahimi** [comment]
So, some feedback from our Unity Cloud build team:

> The project provided today is building fine everywhere (cloud build and Editor locally).  I'm testing on Android.
I upgraded Barracuda to 1.4.0-preview, as recommended by the user but the build was successful again.
> 
> I tried finding the user's history for this simplified project but I didn't see any builds named similar to CameraSceneFrontSelfieDemo.  It sounded like the user did have it fail for them though, implied.
So for the above, I'd need some logs or better yet the projectID and configID for  whatever they ran in Cloud Build (just as they did in the past here).
> 
> Back to their original IL2CPP project, I'm not able to replicate their issues and I did notice that the user is having successful builds over the last few days, including today, albeit on a different branch of that project.

Is that the case? Are your builds successfully running now? Also, for the minimum demo project you sent us. Do you have cloud builds that have failed with that? Can you send logs and/or IDs?

**Comment by ran-bg** [comment]
it seems that the APK can be built successfully, I don't know what happened though.
There're still other issues about Barracuda, but they have nothing to do with this issue, 
I'll close this issue and I'll create another issue later.

Thank you for the help.

**Comment by amirebrahimi** [comment]
Glad to hear it is working again for you. I guess it will remain an unsolved mystery for now.
