### ISSUE TITLE
Question regarding PReLU-related assertions

### ISSUE THREAD

**Issue by seungwonpark** [Unity-Technologies/barracuda-release#194]
Hi, thanks for maintaining such wonderful Unity library.
I have a question regarding the PReLU activation.

Currently, I need to use PReLU activation between the convolutions.
That being said, the input tensor to PReLU may not satisfy the second assertion in PReLU (line 760):

https://github.com/Unity-Technologies/barracuda-release/blob/5e321aa0db7ebaf77b58db624cb53f8a1c408a9d/Barracuda/Runtime/Core/Backends/BarracudaBurstCPU.Ops.cs#L755-L760

For example, when
- the input tensor `X` has shape `[N, C, H, W]`
- and the PReLU parameters `S` has shape `[1, C]`,
then `X.flatWidth` is `C*H*W`, and `S.flatWidth` is `C`. Thus this leads to assertion error.

I'm not aware of implementation details of PReLU in Barracuda, but I guess the second assertion should be changed into something like:
```csharp
Assert.IsTrue((X.channels == S.channels) || (S.flatWidth == 1)); 
```

**Comment by AlexRibard** [comment]
@seungwonpark you are correct! the only requirement on `S` is that it is broadcastable to X.
I'll fix up the code appropriately.
Do you have a model were you noticed this behaviour, I'd like to add it to our test suite?

**Comment by seungwonpark** [comment]
Great! I'm glad to hear that.

Unfortunately, the model I'm working on won't be appropriate for the test bench, since it's still struggling with other issues. 

_The paragraphs shown below are out of scope of this issue, thus can be simply ignored._

===

Actually, I was trying to run [MediaPipe face mesh](https://google.github.io/mediapipe/solutions/face_mesh) via converting the original tflite file to onnx, then running it with Barracuda. (Although the Mediapipe Unity Plugin exists, I needed to do this due to some reason.) This model uses PReLU activation between convolutions, which made me find this issue.

But I also found that the model requires channel-wise padding, which seems to be not supported in Barracuda currently. As soon as I dig more into this, I'll submit another issue dedicated to this problem.

===

Again, thank you very much!

**Comment by AlexRibard** [comment]
Ok thanks for clarifying.
Would you be ok with sharing the model regardless? Face Mesh is definitely a model we'd like to support

**Comment by seungwonpark** [comment]
Sure. You can either download from the attached or make it by yourself:
```bash
wget https://github.com/google/mediapipe/raw/master/mediapipe/modules/face_landmark/face_landmark.tflite
pip install -U tf2onnx # also requires tensorflow
python -m tf2onnx.convert --tflite face_landmark.tflite --output face_landmark.onnx
# you'll get face_landmark.onnx from here.
```

Please kindly note that this model gives two outputs: one for the 468 3D mesh points, and one for the confidence.

[face_landmark.zip](https://github.com/Unity-Technologies/barracuda-release/files/6664040/face_landmark.zip)

**Comment by AlexRibard** [comment]
Thank you!
I've added support to Channel padding to our roadmap as it seems to be blocking more and more people

**Comment by seungwonpark** [comment]
Just fyi, you might want to refer to https://swpark.me/mediapipe_arch_vis/face_landmark.html to see how MediaPipe face mesh works. You can see channel padding at Ops No. 13 there.

**Comment by AlexRibard** [comment]
Thanks!

**Comment by ozmig77** [comment]
Hello, while this does not updated yet (Barracuda 3.0.0), I suggest quick fix you might consider. 

While the PRelu process operation per each b\*w\*h (function [Execute](https://github.com/Unity-Technologies/barracuda-release/blob/release/3.0.0/Barracuda/Runtime/Core/Backends/BarracudaBurstCPU.Jobs.Activation.gen.cs#L1400)), if we can constantly set initial value of float* gamma as Bptr, it will act as the broadcasting.
To program it, we need to set another variable `isGammaAChannel` in PReluJobHelper that acts similar to `isGammaAVector`.

You can see my changes below

[L94 in `BarracudaBurstCPU.Jobs.cs`](https://github.com/Unity-Technologies/barracuda-release/blob/release/3.0.0/Barracuda/Runtime/Core/Backends/BarracudaBurstCPU.Jobs.cs#L94)
```
    internal partial struct PReluJobHelper
    {
        [ReadOnly] public int inOutChannels;
        [ReadOnly] public int isGammaAVector; //1 if true, 0 if false
        [ReadOnly] public int isGammaAChannel; //1 if true, 0 if false
    }
```

[L873 in `BarracudaBurstCPU.Ops.cs`](https://github.com/Unity-Technologies/barracuda-release/blob/release/3.0.0/Barracuda/Runtime/Core/Backends/BarracudaBurstCPU.Ops.cs#L873)
```
/// <inheritdoc/>
    public override Tensor PRelu(Tensor X, Tensor S)
    {
        var O = NewTensorLike(X, AllocScope.LayerOutput);
        Assert.AreEqual(X.channels, O.channels);
        Assert.IsTrue((X.flatWidth == S.flatWidth) || (S.width * S.height == 1));
            
        var job = new PReluJobHelper();
        job.isGammaAVector = (S.flatWidth == 1) ? 0 : 1;
        job.isGammaAChannel = (X.flatWidth != S.flatWidth && S.flatWidth != 1) ? 0 : 1;
        job.inOutChannels = O.channels;
        job.ScheduleXBO(X, S, O, O.length / O.channels, Math.Max(16, 1024 / O.channels));
        
        return O;
    }
```

[L1404 in `BarracudaBurstCPU.Jobs.Activation.gen.cs`](https://github.com/Unity-Technologies/barracuda-release/blob/release/3.0.0/Barracuda/Runtime/Core/Backends/BarracudaBurstCPU.Jobs.Activation.gen.cs#L1404)
[L1969 in `BarracudaBurstCPU.Jobs.Activation.gen.cs`](https://github.com/Unity-Technologies/barracuda-release/blob/release/3.0.0/Barracuda/Runtime/Core/Backends/BarracudaBurstCPU.Jobs.Activation.gen.cs#L1969)
```
half* gamma = Bptr + i * data.inOutChannels * data.isGammaAVector * data.isGammaAChannel;
```
