### ISSUE TITLE
Unable to run on Android 32bit - Repeated warnings of "error 53 Resource deadlock would occur"

### ISSUE THREAD

**Issue by LinasKo** [Unity-Technologies/barracuda-release#195]
Hi,

I am attempting to run a [tiny-yolo-v2](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2) using `Barracuda 2.1.0-pre` on a `Motorola Moto G5+` phone. I am building the project with `IL2CPP` for `Arm v7` architecture.

The build seems to be successful, but running the inference produces a black screen.
[Logcat dump](https://gist.github.com/LinasKo/4dac61d8a9e92ff5a2f1ddb5c8b810f7) seems to offer a few clues, with warning of `error 53 Resource deadlock would occur` repeating until the app crashes.

I can, however, run this when not using the GPU, and on the `Arm 64` device (both with GPU and without).

**Comment by mantasp** [comment]
@LinasKo is there any particular reason why you want to run it in ARMv7 mode instead of ARM64? I suspect that GPU driver just has lower memory allocation limits in 32-bit mode.

**Comment by LinasKo** [comment]
Hi @mantasp, some of the Android phones we are testing on don't have a 64 bit chip. While right now I'm not 100% sure what share of our end-users would be affected, it is something I want to make an effort to support, if possible.

**Comment by mantasp** [comment]
discussion was moved to other communication channels, closing it here
