### ISSUE TITLE
OnnxImportException: Unexpected error while parsing layer 362 of type ReduceMax.

### ISSUE THREAD

**Issue by Sun-Pak** [Unity-Technologies/barracuda-release#196]
Hi. when i used faster rcnn model, I got 2 errors about "Reduce Max" and failed of importing onnx model. 

Barracuda version: 1.2.0
Opset version: 11
onnx model: faster r-cnn ( mobilNet backbone)

OnnxImportException: Unexpected error while parsing layer 362 of type ReduceMax.
The given key was not present in the dictionary.

<img width="1433" alt="ddddPNG" src="https://user-images.githubusercontent.com/16331744/122719101-b2bcfa00-d2a8-11eb-9ecc-da980da1c691.PNG">

And I imported onnx model to unity barracuda version 2.0.0, got  different type errors.

<img width="1011" alt="캡23" src="https://user-images.githubusercontent.com/16331744/122730677-717f1700-d2b5-11eb-9294-fb568d5dc373.PNG">

It means barracuda does not support hard sigmoid? 

I know barracuda supports MobileNet, if so the last error it's not make sense. because hard sigmoid is used in MobileNet. 

this onnx model loaded well in colab. I don't know what's wrong.

this is my onnx model share url 
https://drive.google.com/file/d/1fIYUpgCuzutXAgRaV0eZNPuXljUORMDJ/view?usp=sharing

**Comment by AlexRibard** [comment]
Thank you for sharing the model. I will check it out and get back to you!

**Comment by AlexRibard** [comment]
@Sun-Pak I've added support for `HardSigmoid`.
Unfortunately your model contains conditional logic: (layer 2306)
![image](https://user-images.githubusercontent.com/12990800/122944478-dbdf9800-d345-11eb-83f2-c6d8e45d4bee.png)
We do not support this, or plan to support it in the near future.
Can you remove this logic from your model?
Usually these if are there if you throw exceptions in your model. You can try exporting with a lower opset (9 is good) and see if it gets rid of the condition.
Alternatively can you share what operation you are doing in python to export to a conditional branching?

**Comment by Sun-Pak** [comment]
thank you.
sure. i can share you . 
https://colab.research.google.com/drive/17FGgPdMYyxkhlknI04Wwwms8Vrrv9dGW?usp=sharing

And can't exporting with opset 9 because a runtime error occurred...
(Unsupported: ONNX export of Pad in opset 9. The sizes of the padding must be constant. Please try opset version 11.)

**Comment by AlexRibard** [comment]
Thanks for sharing the code.
I took a look at it, it doesn't seem serious. Just some exception handling for empty tensor. Which shouldn't be a issue in Barracuda.
Unfortunately, `RoiAlign` is not supported atm

I will close this thread as the task is now to support `RoiAlgin`.
However, this is planned and should roll out in August
cf
https://github.com/Unity-Technologies/barracuda-release/issues/177

So I'd recommend using another architecture in the meantime,
Let me know

**Comment by Sun-Pak** [comment]
thank you. 
Does that mean I have to use a different model before August? 

To use the current model( import this model to unity), is there no other way?

**Comment by AlexRibard** [comment]
Yes, you are correct, `RoiAlign` is core to R-CNN so I think it'll be best to try a different architecture.
What about Yolo or SSD? These should import.

**Comment by Sun-Pak** [comment]
okay. I'll try.. Thank you! :)
