### ISSUE TITLE
OnnxImportException: Unexpected error while parsing layer 512 of type Gemm.

### ISSUE THREAD

**Issue by Daewon-Hwang** [Unity-Technologies/barracuda-release#197]
[Environment]
Barracuda version: 2.1.0
Onnx version : 1.9.0
Opset version: 12
torch version: 1.8.1

Hi. I exported a onnx of a human pose estimation model (https://github.com/nkolot/SPIN). Extraction is successful, but when I load this file on Unity Barracuda, I got this error message

```
Asset import failed, "Assets/Scripts/Model/output.onnx" > OnnxImportException: Unexpected error while parsing layer 512 of type Gemm.
Assertion failure. Values are not equal.
Expected: 2094080 == 2257920

Json: { "input": [ "511", "fc1.weight", "fc1.bias" ], "output": [ "512" ], "name": "Gemm_125", "opType": "Gemm", "attribute": [ { "name": "alpha", "f": 1, "type": "FLOAT" }, { "name": "beta", "f": 1, "type": "FLOAT" }, { "name": "transB", "i": "1", "type": "INT" } ] }
  at UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) [0x00043] in 
....
```

I guess the <1> node (concatenate) and <2> node(fully conneceted layer) are problem. The <1> node concatenates the previous layer[name: 508, (1x2048)] and the constant torch array init_pose(1x144), init_shape(1x10), init_cam(1x3). 

I wonder if the current version of barracuda supports the process of concatenating an intermediate feature layer and a constant array and putting it as input to the fully connected layer. How can we solve this problem?

![image](https://user-images.githubusercontent.com/59599085/122867311-3e479100-d364-11eb-9d2b-9d4e5e166f5d.png)

I attach the onnx file()

Thank you

**Comment by AlexRibard** [comment]
Thank you for providing the model. It is probably a shape inference issue.
I'll check it out!

**Comment by AlexRibard** [comment]
@Daewon-Hwang I took a look at your model.
Every thing seems in order. I even validated against onnxruntime and get expected results at 10e-5.
It would seem that your model is being exported in "legacy mode"
![image](https://user-images.githubusercontent.com/12990800/122948363-dc2d6280-d348-11eb-9eff-57077d471269.png)
Could you check that?
Or simply delete your model and the corresponding meta file and add your model again?

Also FYI, shape logic gets baked down to match the model input shape. If you want your model to work regardless of input shape dim, I'd recommend changing the Reshape(1,-1) to a Flatten
![image](https://user-images.githubusercontent.com/12990800/122948693-18f95980-d349-11eb-809b-07d98aa1ab95.png)
