### ISSUE TITLE
Get index of channel with maximum value from output tensor

### ISSUE THREAD

**Issue by ranibu** [Unity-Technologies/barracuda-release#199]
Hi, I have a segmentation network that outputs for each input image pixel the probability of belonging to one of 19 classes, i.e., `worker.PeekOutput()` returns a `Tensor` of shape (1,128,64,19). While iterating over the entire image, I would like to obtain the class with the maximum predicted value without looping over all Tensor channels. 

Ideally, I'd like to get the slice across all channels at [0, x, y] and apply the maximum operator; something like this (however, this doesn't seem right):
```csharp
for (int j = 0; j < OUT_WIDTH; j++)
{
    for(int i = 0; i < OUT_HEIGHT; i++)
    {
        prediction = outputTensor[0, i, j].ArgMax();
    }
}
```
I was unable to find anything helpful to my problem in the documentation for this.
Any pointer is greatly appreciated!

**Comment by mantasp** [comment]
The easiest solution would be adding `ArgMax` node directly to your network.

**Comment by AlexRibard** [comment]
Side note on this:
Tensor.ArgMax will be on the CPU.
If you want a GPU ArgMax, either add it in your onnx file directly or use the `ModelBuilder` before creating your worker
```
var builder = new ModelBuilder(model);
builder.Reduce(Layer.Type.ArgMax, "argmax_output", "model_output", TensorShape.C, true);
builder.Output("argmax_output");

...
worker = WorkerFactory.CreateWorker(WorkerFactory.Type.ComputePrecompiled, builder.model);

```

**Comment by ranibu** [comment]
Okay, this is great! Thank you very much :) And also thank you for the impressive effort you put in Barracuda in general.
