### ISSUE TITLE
Different result between barracuda and OpenCV.DNN

### ISSUE THREAD

**Issue by LyazS** [Unity-Technologies/barracuda-release#20]
Hi, I have two **.pb** files: the network in **barra_part.pb** is the part of ones in **barra_all.pb**, and I convert them to **.nn** using **_tensorflow_to_barracuda.py_** .

I test **.nn** in Unity using barracuda (**_testbarrann.cs_** in _IncorrectBarra.zip_).
And test **.pb** in python using OpenCV.dnn. (**_testbarrann.py_** in _IncorrectBarra.zip_)

The **barra_part.pb/nn** output the same result, but the **barra_all.pb/nn** output the **different** result.
I got the different thing which should be the same, and **barra_all.pb** just have a little more layers than **barra_part.pb**. 

Have you guys had any problems like this?

Finally my barracuda version is 0.5.
There are my test files:[IncorrectBarra.zip](https://github.com/Unity-Technologies/barracuda-release/files/4174206/IncorrectBarra.zip)

**Comment by mantasp** [comment]
Thank you for reporting it! We will add it to our issue tracker.

**Comment by rejunity** [comment]
Hi, it looks like the type of "Pad" you are using is not supported by Barracuda right now!

Your network is using Pad to add 32 channels (following the MaxPool2d layer), however in Barracuda currently Pad can only add elements in spatial dimension - HW dimensions, but not N or C.

As a temporary workaround you could try to replace Pad with Conv2D filter 1x1x32x64 (1x1 kernel size, 32 channels input and 64 features output). It should automatically learn how to add those missing 32 channels.

**Comment by LyazS** [comment]
> 
> 
> Hi, it looks like the type of "Pad" you are using is not supported by Barracuda right now!
> 
> Your network is using Pad to add 32 channels (following the MaxPool2d layer), however in Barracuda currently Pad can only add elements in spatial dimension - HW dimensions, but not N or C.
> 
> As a temporary workaround you could try to replace Pad with Conv2D filter 1x1x32x64 (1x1 kernel size, 32 channels input and 64 features output). It should automatically learn how to add those missing 32 channels.

Sorry I don't think the "Pad" operator is the key of the problem.
Because in my test, the output of **"BiasAdd_17"** is right the same with the OpenCV.dnn, but the output of **"Conv2D_9"** got the wrong. And all of these outputs go through the "Pad" , so I think the problem is that the **tensorflow_to_barracuda.py** file convert the .pb to a wrong .nn .

**Comment by rejunity** [comment]
Note that Barracuda fuses BiasAdd layer into Convolution. If you compare with result of Tensorflow model between Conv & BiasAdd you might get different results indeed.

Btw, you can use **-json** flag when converting model with tensorflow_to_barracuda.py. This flag will print out layers of Barracuda model.

**Comment by LyazS** [comment]
Thanks for your solution, but something still get wrong.
Below is my code to replace **"Pad"**:
```
pad=np.array([[0,0],[0,0],[0,0],[0,32]])
strides = [1, 1, 1, 1]
filters = np.zeros((1,1,inputs.shape[-1],inputs.shape[-1]+pad[-1,1])).astype(np.float32)
for i in range(pad[-1,1]):
    filters[0,0,i,i]=1.
inputs= tf.nn.conv2d(inputs, filter=filters, strides=strides, padding="SAME")
bias=np.zeros((inputs.shape[-1])).astype(np.float32)
outputs = tf.nn.bias_add(inputs, bias)
```
But there are still +-0.2 numerical difference.
there are my .pb and .nn file:
[testBarracuda.zip](https://github.com/Unity-Technologies/barracuda-release/files/4236279/testBarracuda.zip)

**Comment by AlexRibard** [comment]
Hey @LyazS looking at the .onnx model converted from your example, there is a few ConvTranspose with unsupported attributes (output_shape)
I am guessing that they occur from this part
![image](https://user-images.githubusercontent.com/12990800/80496815-aef94600-8937-11ea-99cb-3d77db33bbe8.png)
Until we implement support for this, can you rewrite the model without using output_shape?

Let me know!

**Comment by LyazS** [comment]
@AlexRibard hi, it seems tensorflow cannot using tf.nn.conv2d_transpose with output_shape=None.
So I think there is no way to rewrite the model without using unsupported attributes (output_shape).
Hope to support it soon ：）

**Comment by AlexRibard** [comment]
Adding it to the list then.
We'll let you know when there is support for it

**Comment by FlorentGuinier** [comment]
@LyazS this had been added to our backlog, closing the github issue.
