### ISSUE TITLE
Cannot use Barracuda in script

### ISSUE THREAD

**Issue by frankplus** [Unity-Technologies/barracuda-release#202]
Hi,
when I try to use the Barracuda package in a script the line `using Unity.Barracuda;` is not working for me.
It says `Assets/Scripts/LodPredict.cs(5,13): error CS0234: The type or namespace name 'Barracuda' does not exist in the namespace 'Unity' (are you missing an assembly reference?)`
I tried to install different version of Barracuda: 2.1.0, 2.0.0, 1.0.4, 1.0.0 and none are working.
Can you please help me?

**Comment by mantasp** [comment]
Hi @frankplus,
how did you install Barracuda? via package manager?

**Comment by frankplus** [comment]
i added the `"com.unity.barracuda": "2.0.0-pre.5"` entry to the manifest.json file

**Comment by mantasp** [comment]
Hmm.. Any chance your script is compiled via .asmdef? in such case you also need to specify Unity.Barracuda assembly as dependency.

**Comment by frankplus** [comment]
solved by starting a new unity project from scratch. Thank you!
