### ISSUE TITLE
Slow Convolutions on HoloLens 2 in Channels First Mode

### ISSUE THREAD

**Issue by abeug** [Unity-Technologies/barracuda-release#203]
The first 2 convolutions execute slower for [Tiny Yolo V4](https://github.com/jkjung-avt/tensorrt_demos) in channels first mode on a HoloLens 2 device. Most convolutions execute faster in channels first mode except for the first 2 which consistently perform slower.

The following image compares the GPU time running on the HoloLens 2 with both channels first and channels last modes. Each layer is scheduled on its own frame and overlays were added to the image to show the first 2 convolutions.
![TinyYoloV4ChannelsFirstVsLast](https://user-images.githubusercontent.com/25258352/126012943-db451d6a-a5e1-411a-b463-048c52cd1fb3.png)

- Blue lines: represent each execution of the model.
- Purple: the first convolution (**000_net_FloatNormalize**)
- Dark Green: the second convolution (**002_convolutional**)

The large spikes are the convolutional layers. Notice that the purple and dark green spikes are much larger in channels first mode, indicating that the first 2 convolutions perform much worse in channels first mode. On a GTX 1080 Ti, I don't see this slowdown.

**Average GPU Time**
|                       | 000_net_FloatNormalize    | 002_convolutional |
| -------------- | ------------------------- | --------------------- |
| Channels Last | 11.38ms  | 28.03ms |
| Channels First | 42.79ms | 86.52ms |

_All sample standard deviations < 3.78ms_

The channels first versions are much slower.  The averages are only based on the 6 samples in the profiler captures, but I have also observed these first 2 slow convolutions in a different custom YOLO model.

**Convolution Kernels**
|                       | 000_net_FloatNormalize                                                  | 002_convolutional |
| -------------- | -------------------------------------------------------- | --------------------- |
| Channels Last |  Conv2D_RegisterBlock4x2_NHWC  | Conv2DKernelKxK_StrictC16K64_T16x16_R4x4_NHWC |
| Channels First | Conv2DKernelKxK_LaxC4StrictK16_T2x32_R8x8_NCHW | Conv2DKernelKxK_StrictC16StrictK64_T8x8_R8x8_NCHW |

**Attached Files**
I have included a small test project with the Tiny Yolo V4 model and 2 .data files containing the GPU profiler data captured with the Unity Profiler on the HoloLens 2 for both channels first and last modes. This is the same capture data shown in the image.
https://drive.google.com/file/d/1JTPZWq2Uzsblm0kprfN0AsXyweMlH8up/view?usp=sharing

**Other Info**
Barracuda version: 2.1.0-preview (Earlier versions have the same issue)
Unity Version: Unity 2020.3.7f
Device: HoloLens 2 (has Adreno 630 GPU)
Platform: UWP

The slowness of these first two convolutions and the [slow CPU transpose of input tensor data](https://github.com/Unity-Technologies/barracuda-release/blob/a15a7648ddea37a52c1ca993370ace6725d1cdb7/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs#L155) are the only two things preventing me from using the channels first layout with my custom YOLO model (not attached) on the HoloLens 2.

**Edit:** Fixed incorrectly labeled figure and swapped tables to match it.

**Comment by AlexRibard** [comment]
@abeug thanks for your analysis and bringing up the issue.
I've tested the model locally, + on a OnePlus with a similar 630 Ardeno GPU

A few things to start:
* your model is input shape independent, so you can pass in any texture with whatever shape you want, it should work. So no need to reshape your image at the begining.
* reshaping the texture on the CPU will indeed result in a overhead in NCHW mode, as you noted we will take the slow CPU NHWC2NCHW (we need to update that on our side). However, if you pass in a RenderTexture as input, everything is done on the GPU, so the overhead is minimized.
* If the output of your model stays on the GPU, you probably don't need a `worker.FlushSchedule()` when finished executing. Instead you can call Tensor.ToRenderTexture`

Now to the core of the issue regarding performance.
Unfortunately with mobile GPUs NCHW is not a clear winner over NHWC, in fact it might be a bit slower sometimes.
So it is best to keep everything in NHWC.
We have a few optimizations for Adreno GPU that will land soon. I've tested locally it improves inference time by ~5/10% (the full model still takes 270ms to execute totally). So you still need execution slicing.
Other improvements as doing everything in fp16 is still in the works so I cannot promise when they will land.
Alternatively, given that your model is size independent is lowering the input size acceptable to you?
-- 416x426: 270ms  // 256x256: 100ms // 128x128: 37ms --
The execution is ~quadratic with respect to the input size. So tweaking that a bit can go a long way
Also can you replace the leakyrelu with relu? we fuse relu with conv so it would yield a bit of improvements.

Let me know

**Comment by abeug** [comment]
- Using a texture can work for me to avoid the CPU NHWC2NCHW in NCHW mode.
- In my actual project, I use  `worker.FlushSchedule()` because I process output on the CPU. This was not included in the test project I sent.

I also have a modified YOLO model that balances the work over several frames with variable layers scheduled per frame.
Here is the GPU usage for that model with both NHWC and NCHW:
![TinyYoloV4BalancedChannelsFirstVsLast](https://user-images.githubusercontent.com/25258352/126197895-25955cb8-8521-4f2f-b94d-b8b6ba2ff82c.png)
_Image is artificially stretched so they line up._

In this model, NCHW is also consistently faster on the HoloLens 2 except for the first few convolutions. The large spikes in the graph are largely dominated by the first few convolutions. Everywhere else in the graph, the GPU usage goes down, so I would prefer to use NCHW if there is a way to improve the performance of the first few convolutions. The same conv kernels mentioned above are used in the convolutions in the modified model.

Lowering input size is something I could explore. Is passing a Tensor with a smaller size to `worker.StartManualSchedule(Tensor input)` all that is required? I haven't yet tried smaller input size because I thought I had to set up a different model.

I can try modifying the model to use relu, but I expect that would only be a minimal improvement if I can't avoid those large spikes.

**Comment by AlexRibard** [comment]
So we're looking at `001_convolutional` and `002_convolutional` being noticeably slower right?
I can spend some time checking if we some of our other kernels are faster for those layers and tweak our selection criterion.
However, I did spend some time on this recently and the issue isn't easily solved with a new implementation.
So I doubt it, but we can try :)

Another solution would be for me to send you the PR of the improved kernels. For your model on the same GPU it's roughly a 5/10% win, so it might be helpful to you.

Yes, you can scale down the inputs no problem (maybe in inference precision since your model looks like to have been trained on 416x416 inputs)

Let me know

**Comment by abeug** [comment]
Yes `001_convolutional` and `002_convolutional` are the slow convolutions.

The improved kernels would be quite helpful. I could test the improved kernels on the HoloLens 2.

**Comment by AlexRibard** [comment]
ok let me spend some time checking on Adreno630

**Comment by AlexRibard** [comment]
@abeug so on latest optimizations on Adreno630 I'm getting the following:
NHWC - 219ms conv0: 53.614ms conv1: 27.494ms conv2: 47.002ms

So far NCHW is a bit slower, but I'll let you know if I get something faster

**Comment by abeug** [comment]
Thanks for the update.

It is strange that I am getting 11.38ms and you are getting 53.614ms for conv0 in NHWC. I assume conv0 is `001_convolutional` in the model (The first conv layer). Conv1 (`002_convolutional`) is similar. For conv2 I am get an average of 54.346 based on the 5 samples in the profiler capture.

Looking forward to the optimizations.

Edit: I just noticed that the first 2 convolutions have a stride of 2, while all other convolutions have a stride of 1. Perhaps this is part of the issue.

**Comment by AlexRibard** [comment]
@abeug what input size are you using? I'll profile with the same size you are using.

You are correct, conv0 is referring to the first conv in the model.
The strides have minimal performance impact. It's mostly the input size that matters.

**Comment by abeug** [comment]
Input size is 1x416x416x3 for (NHWC) and 1x3x416x416 for NCHW.

**Comment by AlexRibard** [comment]
ok, so we have much better numbers on NCHW now (same input size as you)
whole network: 206.859ms
001_convolutional		17.133	
002_convolutional		9.533	
003_convolutional		18.315

On 2.1.0 I was getting ~235ms for the whole network, so that's some improvements even on NHWC.
Overall on different models we're getting a 5/10% speedup on Ardeno.
Unfortunately, the PR is pretty big, so sharing it is a bit cumbersome.
So I'll keep the ticket open until the next version ships (should be in 1 or 2 weeks).

Let me know,

**Comment by abeug** [comment]
Those numbers are looking much better. I can wait for the next version. Thanks.

**Comment by mantasp** [comment]
This improvement shipped in Unity Barracuda `2.2.0-preview` version, which you can grab from Unity Package Manager.
