### ISSUE TITLE
Cannot import LSTM (Tensorflow and Pytorch)

### ISSUE THREAD

**Issue by roger-creus** [Unity-Technologies/barracuda-release#204]
Hello everybody,

I developed a one-layer non-bidirectional LSTM with both Tensorflow and Pytorch and want to export them to ONNX and import them to Unity.

I am using torch.onnx for Pytorch an keras2onnx for the tensorflow model. Pytorch gives me the warning:

`/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:19: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
/opt/conda/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:1805: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  "or define the initial states (h0/c0) as inputs of the model. ")`

and Tensorflow outputs:

`tf executing eager_mode: True
tf.keras model eager_mode: False
The ONNX operator number change on the optimization: 24 -> 17`

The thing is, when I import both in Unity I obtain the same error:

KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key)
Unity.Barracuda.ONNXModelImporter.BuildNodeSkipList (Onnx.GraphProto graph)

Any clue on what is going on?

Thank you very much ;)

**Comment by amirebrahimi** [comment]
Would you be willing to send us a copy of the model to barracuda-support at unity3d dot com?

**Comment by amirebrahimi** [comment]
@yuyecreus - what version of Barracuda are you using?

On my end, when I import lstm-tensorflow.onnx it doesn't import because we don't support the `Loop` operator. However, lstm-pytorch.onnx imports correctly.

**Comment by roger-creus** [comment]
@amirebrahimi I have barracuda installed by installing the ML agents as barracuda alone does not appear in the Package Manager. It uses Barracuda 1.0.4. Still, lstm-pytorch giving me the same import error. Thank you.

**Comment by AlexRibard** [comment]
You need to enable `show preview packages` in order to see the Barracuda package:
https://docs.unity3d.com/Manual/pack-preview.html
Once enabled you can update the package to latest. 
It shouldn't impact ML-Agents. And your model will import

**Comment by roger-creus** [comment]
@AlexRibard I have checked "Enable Preview Packages" in  Edit > Project Settings > Package Manager and Barracuda still does not appear. What version of Barracuda should support the LSTM?

**Comment by amirebrahimi** [comment]
@yuyecreus - is the LSTM model originating from ML-Agents or is it your own? Better LSTM support came for Barracuda in version 1.4.0.

**Comment by roger-creus** [comment]
@amirebrahimi it is my own LSTM, implemented and trained on pytorch and exported to onnx with torch.onnx.

**Comment by amirebrahimi** [comment]
> @AlexRibard I have checked "Enable Preview Packages" in Edit > Project Settings > Package Manager and Barracuda still does not appear. What version of Barracuda should support the LSTM?

What version of Unity are you using? I think possibly from ~2019.4~ 2020.1 and up it requires manually editing your `Packages/manifest.json` file directly. Try adding a line for Barracuda:
```
    "com.unity.barracuda": "1.4.0",
```

**Comment by AlexRibard** [comment]
@yuyecreus I've run your model. Unfortunately it looks like it doesn't run.
I have a fix for it. I'll share it to you once I land it.

**Comment by roger-creus** [comment]
> @yuyecreus I've run your model. Unfortunately it looks like it doesn't run.
> I have a fix for it. I'll share it to you once I land it.

Okay. Thank you all for your time! :)

**Comment by roger-creus** [comment]
> > @AlexRibard I have checked "Enable Preview Packages" in Edit > Project Settings > Package Manager and Barracuda still does not appear. What version of Barracuda should support the LSTM?
> 
> What version of Unity are you using? I think possibly from ~2019.4~ 2020.1 and up it requires manually editing your `Packages/manifest.json` file directly. Try adding a line for Barracuda:
> 
> ```
>     "com.unity.barracuda": "1.4.0",
> ```

By the way, editing manifest.json works for "com.unity.barracuda": "1.0.4", but not for the "com.unity.barracuda": "1.4.0" release.

**Comment by mantasp** [comment]
1.4.0 was a preview version, so you would need to specify full version name `1.4.0-preview`. But if you want to try very latest Barracuda version you should try `2.1.0-preview`

**Comment by AlexRibard** [comment]
closing thread as model imports and runs on latest.
@yuyecreus I have send you the specific fixes via email so you don't need to wait for the upcoming release.
