### ISSUE TITLE
ArgumentException: Kernel TextureToTensor and TextureToTensor_NHWC are both missing

### ISSUE THREAD

**Issue by roger-creus** [Unity-Technologies/barracuda-release#205]
Hello, 

A few months ago I was using an app built with Unity2020 which integrates a CNN (in ONNX and thanks to Barracuda of course). I used it in Android and everything worked fine. Now I want to reproduce the built for that project and obtain the following error:

ArgumentException: Kernel TextureToTensor and TextureToTensor_NHWC are both missing
Unity.Barracuda.ComputeFunc..ctor (UnityEngine.ComputeShader[] cs, System.String kn) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:1783)

I wonder if anything changed...

Thank you!

**Comment by AlexRibard** [comment]
Are you running with a GPU or CPU worker?

**Comment by roger-creus** [comment]
> Are you running with a GPU or CPU worker?

just using default:

model = ModelLoader.Load(modelSource, verbose: false);
worker = WorkerFactory.CreateWorker(model, verbose: false);

**Comment by AlexRibard** [comment]
On which platform are you building on?
Android? WebGL? Are you using OpenGL or Vulkan?

**Comment by roger-creus** [comment]
> On which platform are you building on?
> Android? WebGL? Are you using OpenGL or Vulkan?

I am targeting Android and using Vulkan.

**Comment by AlexRibard** [comment]
Are you seeing the error when running the application on your PC or when the build is running on the phone?
On older unity version, when running the game while in Android mode on the PC, it wouldn't load the shaders. If that is the case and you want to test locally, change the target platform to PC or update unity version

**Comment by amirebrahimi** [comment]
I think I've seen this error before. Try this @yuyecreus: Search for "TextureUtils" with filter "All" or go directly to `Runtime/Core/Resources/Barracuda` and reimport that compute shader there. You must be on the target platform (i.e. Android/Vulkan) that you are building to. My guess is that it says only "Direct3D11" and after reimport will have "Vulkan" added.

**Comment by roger-creus** [comment]
Solved by setting Edit > Project Settings > Player and in the target platform (Android in my case) check the box of "Auto Graphics API". Thank you for your time!
