### ISSUE TITLE
LSTM in Unity Barracuda

### ISSUE THREAD

**Issue by roger-creus** [Unity-Technologies/barracuda-release#206]
Hello everybody :)

I am importing a LSTM (built with Pytorch and exported to ONNX) to Unity with Barracuda 2.1.0-preview and import seems to work correctly. However, when I feed inputs to the model I obtain the following error:

`ArgumentException: Kernel Gather and Gather_NHWC are both missing
Unity.Barracuda.ComputeFunc..ctor (Unity.Barracuda.ComputeShaderContext ctx, System.String kn, Unity.Barracuda.IModelExecutionsReporter reporter) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:2718)`

Thank you very much!

**Comment by AlexRibard** [comment]
Could this issue be similar to https://github.com/Unity-Technologies/barracuda-release/issues/205?

**Comment by roger-creus** [comment]
> Could this issue be similar to https://github.com/Unity-Technologies/barracuda-release/issues/205?

It looks similar but a different feature is missing. At least the solution for #205 does not solve this one

**Comment by AlexRibard** [comment]
Same question then?
Are you trying to run and android project on PC?
Did you try upgrading to Unity 2019.3.0f3?

**Comment by roger-creus** [comment]
> Same question then?
> Are you trying to run and android project on PC?
> Did you try upgrading to Unity 2019.3.0f3?

I tried both targetting android and PC, checking and unchecking Auto Graphics API as in #205. Running everything in Unity 2020 already

**Comment by amirebrahimi** [comment]
@yuyecreus - Can you send us an email with the model to the same support email address you've corresponded with us on before?

**Comment by amirebrahimi** [comment]
@yuyecreus - this happens for you on PC, too?

Also, can you try this tip [here](https://github.com/Unity-Technologies/barracuda-release/issues/205#issuecomment-885100928)?

**Comment by roger-creus** [comment]
@amirebrahimi @AlexRibard All of a sudden, the error I obtain is not the same anymore (KernelGather and so). Now I get: 

```
AssertionException: Assertion failure. Values are not equal.
Expected: 10 == 30
```

See how the inputs should be given to the model: `https://gyazo.com/1048a2a107eb8b61e8df64f5fc2bf328`

and what I'm doing:

```
// TEXT SEQUENCE (just an example)
Tensor input = new Tensor(n: 1, h: 1, w: 1, c: 30);
for (int i = 0; i < 30; i++)
{
    input[0, 0, 0, i] = i;
}

//Only for LSTM -> hidden states
Tensor h = new Tensor(n: 1, h: 1, w: 4, c: 1);
Tensor c = new Tensor(n: 1, h: 1, w: 4, c: 1);

// JUST EXAMPLE VALUES
for (int i = 0; i < 4; i++)
{
    h[0, 0, i, 0] = i;
    c[0, 0, i, 0] = i;
}

var inputs = new Dictionary<string, Tensor>();
inputs["x"] = input;
inputs["1"] = h;
inputs["2"] = c;

worker.Execute(inputs);

Tensor O = worker.PeekOutput();

```

Is the error I now obtain related to this pipeline?

**Comment by AlexRibard** [comment]
Right, if the model is the same you send us, then this error is fixed in master. And your model is passing tests.
We have a bug in how we dealt with `Gather`. Unfortunately the fix is a bit too big to fit in one email.
But we are planning on releasing a new version this week or next week, so lookup for that!

**Comment by AlexRibard** [comment]
I'll close this issue if it's ok, as the original problem seems to be fixed.
Do open another issue for the remaining problem. We can close it when we ship the next version
