### ISSUE TITLE
Transformer in Unity Barracuda

### ISSUE THREAD

**Issue by roger-creus** [Unity-Technologies/barracuda-release#207]
Hello everybody :)

I am importing a transformer model (built with Pytorch and exported to ONNX) to Barracuda 2.1.0-preview and obtain the following error just on import:

```
Unexpected error while evaluating model output 134. System.ArgumentException: Cannot reshape array of size 3000 into shape (n:1, h:60, w:145287, c:1)
  at Unity.Barracuda.TensorExtensions.Reshape (Unity.Barracuda.TensorShape shape, System.Int32[] size4Dor8D) 
```

Looks like an architecture bug, but the same architecture works well in native pytorch.

Thank you very much!

**Comment by AlexRibard** [comment]
I found a fix for your model. It passes the tests against onnxruntime which is good.
I'll see if I can do a patch for you.

**Comment by roger-creus** [comment]
> I found a fix for your model. It passes the tests against onnxruntime which is good.
> I'll see if I can do a patch for you

Nice! Looking forward to your feedback :)
