### ISSUE TITLE
YOLOV5 Support

### ISSUE THREAD

**Issue by joshbigdaddy** [Unity-Technologies/barracuda-release#208]
Hi, I have been reading a lot about Barracuda and I see that there is support for TinyYolov3.
Is it possible to use YoloV5 on Barracuda as well? I am trying to implement full Yolov5s models for unity in oculus VR and I would like to know if there is a possibility or I do need to change to TinyYolov3.

Thanks!

**Comment by amirebrahimi** [comment]
Hi @joshbigdaddy. Generally, the best way to answer that question is just to try importing an .onnx file into Barracuda to see if it imports correctly. That's a good first step before seeing whether it runs as expected. Our team is small and there are new models coming out daily, so we don't have the resources to validate every model that gets released -- we usually look to our community to signal what is important to support.

While I can't speak to whether the model runs as expected, as a courtesy I went ahead and exported YoloV5 following [these instructions](https://github.com/ultralytics/yolov5/issues/251) and I can verify it imports correctly into the latest version of Barracuda. So, I'd say it's probable that it would run. Go ahead and give it a shot if you like.

Thanks for using Barracuda!
