### ISSUE TITLE
ONNX model import failed 

### ISSUE THREAD

**Issue by Vedaant-J** [Unity-Technologies/barracuda-release#212]
I just trained the efficient net lite4 model on my own dataset. I wanted to import the model however I get the error:

`OnnxImportException: Unknown type DequantizeLinear encountered while parsing layer sequential_1/dense_1/BiasAdd/ReadVariableOp/resource_dequant.
`
 ```
Asset import failed, "Assets/Models/model_surgery.onnx" > OnnxImportException: Unknown type DequantizeLinear encountered while parsing layer sequential_1/dense_1/BiasAdd/ReadVariableOp/resource_dequant.
Could someone help me understand or solve the problem?

```
I appreciate your help. Thank you.

**Comment by AlexRibard** [comment]
We don't support `DequantizeLinear` atm. Can you share the onnx file? I can take a look at it, with luck it might be easy enough to support.

**Comment by Vedaant-J** [comment]
Hi,
This is my onnx file. I would appreciate any help.
[onnx_file.zip](https://github.com/Unity-Technologies/barracuda-release/files/6896624/onnx_file.zip)
