### ISSUE TITLE
Question about Tensor Output

### ISSUE THREAD

**Issue by joshbigdaddy** [Unity-Technologies/barracuda-release#214]
Hi I am trying to make YOLOV5 work , but my outputs in ONNX are like this:
![image](https://user-images.githubusercontent.com/17721131/128374130-e903b7ec-473e-4dc4-b102-2d66d7c962ae.png)

I have been checking the documentation but I do not see any example about how to proccess outputs like this (just simple examples). Could you provide further info about how to procces this kind of outputs? I am working with 1.4 Barracuda.

**Comment by AlexRibard** [comment]
Hello! Could you provide said onnx model for reference? Thank you!

Usually yolo output corresponding bounding boxes, probabilities for each classes. Parsing the output really depends on how your model was encoded.
In the meantime, you can checkout these tutorials, they should help you out to decode the output correctly for a few specific models
https://github.com/keijiro/TinyYOLOv2Barracuda
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx

**Comment by joshbigdaddy** [comment]
Hi, my onnx model is this : https://we.tl/t-iw91eGxIyx (uploaded to wetransfer).
I have seen these tutorials, but still i cannot figure how to take that examples into my code (the size and the multiple outputs is what is giving me trouble).

I would like to take just labels from my tensor but i only can get a huge float[] from the tensor that does not give me any hint on how to process it to just take the label and probabily from my model

**Comment by AlexRibard** [comment]
We sadly cannot help you with how to interpret your outputs, as this is model specific.
However, here is the doc on how to handle the output tensor:
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/TensorHandling.md
You can get the output results with `PeekOutput("output_name")`
And then access them with the tensor accessors

**Comment by AlexRibard** [comment]
I'm closing this thread, as it is not linked to any Barracuda issues. But feel free to ask more questions
