### ISSUE TITLE
Unexpected error while evaluating model output 

### ISSUE THREAD

**Issue by carlsc2** [Unity-Technologies/barracuda-release#215]
Hello, I have been trying to get my model to work with barracuda (2.1.0-preview) but I'm having a lot of trouble. I had issues previously that were sort of resolved with #210, but even with that patch applied I'm having this (albeit different) issue. I tried making this version more barracuda-friendly by changing some of my reshape operators and using opset 9 for maximum compatibility, but upon importing the model I get these errors:

```
Unexpected error while evaluating model output y1. System.ArgumentException: Cannot reshape array of size 1806336 into shape (n:196, h:1, w:1024, c:96)
Unexpected error while evaluating model output y2. System.ArgumentException: Cannot reshape array of size 1806336 into shape (n:196, h:1, w:1024, c:96)
```

I see this warning in the inspector, which is not present in my previous versions, not sure if this is related.

![error](https://user-images.githubusercontent.com/8629347/128643788-bffe65e2-a254-4c5e-ad36-8c7b82a7ec25.png)

I tried disabling optimize model / force arbitrary batch size, but the barracuda imported version still comes out wrong. Here are the two for comparison:

![correct](https://user-images.githubusercontent.com/8629347/128644099-907f29d9-97b1-4d8b-86e7-c1e635b57846.png)

![imported](https://user-images.githubusercontent.com/8629347/128644105-055945bc-6665-4f3d-911f-398788432ddb.png)

It's not clear to me what part of the architecture is causing this; the stack trace is not very informative. Any help is appreciated. I've attached the model in question below.

[debug.zip](https://github.com/Unity-Technologies/barracuda-release/files/6951376/debug.zip)

**Comment by AlexRibard** [comment]
Hello! thanks for providing the model. I'll take a look at it

**Comment by AlexRibard** [comment]
The problem was coming from rank2 gather. We had a bug in 2.1.0 and earlier. It got fixed in latest. It will work in the upcoming release.
I've validated your model against onnxruntime, it's good at 1e-5

**Comment by carlsc2** [comment]
@AlexRibard thanks for looking into this; is there anything I can do to get this working in the meantime or do I just need to wait for the next release and if so, when might that be?

**Comment by AlexRibard** [comment]
the fixes are unfortunately spread out over a few PR, so it becomes a bit hard to untangle things.
We are planning to have a release this week or the upcoming one. Is that ok with you?

**Comment by carlsc2** [comment]
Yeah that's fine; this isn't urgent per se, but it does hinder my experiments. I'm trying to use neural networks for PCG in a game I'm working on and was hoping barracuda would be a viable solution.

**Comment by AlexRibard** [comment]
Ok, I understand. Someone was asking for it too. Let me spend some time and make a patch.
Can you send me and email at barracuda barracuda-support@unity3d.com so I can forward you the patch
