### ISSUE TITLE
Support for the GatherND operator

### ISSUE THREAD

**Issue by martoko** [Unity-Technologies/barracuda-release#216]
Support for the GatherND operator would be nice.

Any idea how complicated/likely this would be?

Here is a model using GatherND (the format is tflite but the GatherNDs carry over in conversion, except for older opsets where they are filled in using loops).
[lite-model_movenet_singlepose_lightning_tflite_float16_4.zip](https://github.com/Unity-Technologies/barracuda-release/files/7006203/lite-model_movenet_singlepose_lightning_tflite_float16_4.zip)
Looking at the model it seems to produce 4 outputs, which are then combined using 3 GatherNDs.

My current workaround is likely going to be using an ONNX model with the 4 outputs, and then manually replicating the GatherND part in code. Here is the model without the part using GatherND.
[model_cut_off_before_gathernds.zip](https://github.com/Unity-Technologies/barracuda-release/files/7006216/model_cut_off_before_gathernds.zip)

**Comment by olokobayusuf** [comment]
@martoko I recommend [checking out NatML](https://github.com/natsuite/NatML), which has support for all ONNX ops because it delegates parts of the inference graph to ONNX Runtime's kernels. Also, [MoveNet is already available on NatML](https://hub.natsuite.io/predictor/@natsuite/movenet).

DISCLAIMER: I'm the author of NatML.

**Comment by FlorentGuinier** [comment]
Hey @martoko, 

I have added GatherND to our backlog, could you describe your use case please? Would be good to know target platform / CPU vs GPU inference + your project state / deadlines to prioritize GatherND support.

Another option is definitively to look at NatML as @olokobayusuf pointed if this feed your need :)

**Comment by martoko** [comment]
It is not a high priority as I have some workarounds:
 - I could rewrite the GatherND as other operations (essentially a polyfill)
 - I could replicate the part using GatherNDs outside of barracuda

As for the use case it is used as the "post-process" step of the model, where we extract the actual useful values from the model (17 keypoints) from the large vectors produced by the model.
This means that it is not actually part of the machine learning part, but I imagine that other existing models also end with a step like this.
As such, if the idea is to import models from existing workflows, this would broaden the amount of models that are supported out of the box (including the one I am using).

**Comment by FlorentGuinier** [comment]
Thanks @martoko , we will let you know when GatherND work start. 
Closing the issue as this is now part of the backlog, please reopen if needed.

**Comment by fmannhardt** [comment]
We just came across the same question. Use case is to be able to gather the results from a NonMaxSupression layer. 

@martoko do you have, by chance, a pointer to the polyfill of GatherND. Thanks.

**Comment by NathanielB123** [comment]
I also just ran into this with a PyTorch Geometric model exported to ONNX.
