### ISSUE TITLE
Add Erf Operator

### ISSUE THREAD

**Issue by Peamon** [Unity-Technologies/barracuda-release#217]
I put an issue in ml-agent about barracuda (don't know if i was right)
https://github.com/Unity-Technologies/ml-agents/issues/5503#issue-973670965

**Comment by AlexRibard** [comment]
Hey thanks for raising the issue and for sharing the model.
It shouldn't be too hard to add.

**Comment by AlexRibard** [comment]
ok done, it'll be available in the next release.
I also tested your model, it works and passes validation

**Comment by Peamon** [comment]
Thanks a lot
