### ISSUE TITLE
Barracuda runs very slow on Android devices 

### ISSUE THREAD

**Issue by wojciechp6** [Unity-Technologies/barracuda-release#22]
Hi, I've built recognition app with barracuda and on Editor it works well, but if I build it as Android app it has many problems. I've already submitted another issue also for Android builds https://github.com/Unity-Technologies/barracuda-release/issues/21

But if I run it on CPU or another phone to avoid opengl error it is very slow.
I'm using that network: https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny_yolov2

On Huawei Mate 10 it runs on GPU without errors but it takes about 11 seconds to finish interference. In profiler the most time consuming is Barracuda.DownloadDataFromGPU which takes hundreds up to thousands miliseconds to finish.

But on CPU it takes a few minutes to finish one interference! I thing that it isn't correct behaviour. 
Do you have idea why time of interference on mobiles are so high?

**Comment by mantasp** [comment]
11 seconds on GPU sounds bit extreme, I think it was running faster in my tests. Thanks for reporting, will double check.

**Comment by mantasp** [comment]
@wojciechp6 we have small improvement for Mali-G71 GPUs in 0.6.1-preview release: https://github.com/Unity-Technologies/barracuda-release/releases/tag/0.6.1-preview. Could you please try it on your phone and check if performance improved?
Thanks!

**Comment by wojciechp6** [comment]
Sorry for late response but I had break with the project. I'm sorry but I have no longer that phone. On second one app crashes as I posted on second issue.
