### ISSUE TITLE
Model from customvision not working

### ISSUE THREAD

**Issue by HuygnourT** [Unity-Technologies/barracuda-release#221]
Hi, I need some help
I trained models in customvision.ai and import them into Unity and use an algorithm created by CustomVision.AI to detect objects in Unity but it seems not to work correctly.
Please tell me models from CustomVision.AI can be used in Barracuda, thanks

**Comment by Aurimasp** [comment]
Hi, what do you see when you try to run the model? Could you share the model or the model setup in the Unity project with us?

**Comment by HuygnourT** [comment]
// Camera ProcessImage and Detect 
	private void TFDetect()
    {
        if (this.isWorking)
        {
            return;
        }

        this.isWorking = true;
        StartCoroutine(ProcessImage(Detector_Rework.IMAGE_SIZE, result =>
        {
            StartCoroutine(this.detector.Detect(result, boxes =>
            {
                this.boxOutlines = boxes;
                Resources.UnloadUnusedAssets();
                this.isWorking = false;
            }));
        }));
    }


    private IEnumerator ProcessImage(int inputSize, System.Action<Color32[]> callback)
    {
        yield return StartCoroutine(TextureTools.CropSquare(backCamera,
            TextureTools.RectOptions.Center, snap =>
            {
                var scaled = Scale(snap, inputSize);
                var rotated = Rotate(scaled.GetPixels32(), scaled.width, scaled.height);
                callback(rotated);
            }));
    }

    private Texture2D Scale(Texture2D texture, int imageSize)
    {
        var scaled = TextureTools.scaled(texture, imageSize, imageSize, FilterMode.Bilinear);

        return scaled;
    }


    private Color32[] Rotate(Color32[] pixels, int width, int height)
    {
        return TextureTools.RotateImageMatrix(
                pixels, width, height, -90);
    }
	
	public static IEnumerator CropSquare(
            WebCamTexture texture, RectOptions rectOptions, System.Action<Texture2D> callback)
        {
            var smallest = texture.width < texture.height ? texture.width : texture.height;
            var rect = new Rect(0, 0, smallest, smallest);

            if(rect.height < 0 || rect.width < 0)
            {
                throw new System.ArgumentException("Invalid texture size");
            }

            Texture2D result = new Texture2D((int)rect.width, (int)rect.height,TextureFormat.BGRA32,true);
            
            if(rect.width != 0 && rect.height != 0)
            {
                float xRect = rect.x;
                float yRect = rect.y;
                float widthRect = rect.width;
                float heightRect = rect.height;

                switch(rectOptions)
                {
                    case RectOptions.Center:
                        xRect = (texture.width - rect.width) / 2;
                        yRect = (texture.height - rect.height) / 2;
                        break;

                    case RectOptions.BottomRight:
                        xRect = texture.width - rect.width;
                        break;

                    case RectOptions.BottomLeft:
                        break;

                    case RectOptions.TopLeft:
                        yRect = texture.height - rect.height;
                        break;

                    case RectOptions.TopRight:
                        xRect = texture.width - rect.width;
                        yRect = texture.height - rect.height;
                        break;

                    case RectOptions.Custom:
                        float tempWidth = texture.width - rect.width;
                        float tempHeight = texture.height - rect.height;
                        xRect = tempWidth > texture.width ? 0 : tempWidth;
                        yRect = tempHeight > texture.height ? 0 : tempHeight;
                        break;
                }

                if (texture.width < rect.x + rect.width || texture.height < rect.y + rect.height || 
                    xRect > rect.x + texture.width || yRect > rect.y + texture.height || 
                    xRect < 0 || yRect < 0 || rect.width < 0 || rect.height < 0)
                {
                    throw new System.ArgumentException("Set value crop less than origin texture size");
                }

                result.SetPixels(texture.GetPixels(Mathf.FloorToInt(xRect), Mathf.FloorToInt(yRect),
                                                Mathf.FloorToInt(widthRect), Mathf.FloorToInt(heightRect)));
                yield return null;
                result.Apply();
            }

            yield return null;
            callback(result);
        }
		
		
		public IEnumerator Detect(Color32[] picture, System.Action<IList<BoundingBox>> callback)
    {
        using (var tensor = TransformInput(picture, IMAGE_SIZE, IMAGE_SIZE))
        {
            var inputs = new Dictionary<string, Tensor>();
            inputs.Add(INPUT_NAME, tensor);
            yield return StartCoroutine(worker.ExecuteAsync(inputs));

            var output = worker.PeekOutput(OUTPUT_NAME);
            var results = ParseOutputs(output);
            var boxes = FilterBoundingBoxes(results, 5, MINIMUM_CONFIDENCE);
            callback(boxes);
        }
    }


    public static Tensor TransformInput(Color32[] pic, int width, int height)
    {
        float[] floatValues = new float[width * height * 3];

        for (int i = 0; i < pic.Length; ++i)
        {
            var color = pic[i];

            floatValues[i * 3 + 2] = (color.r - IMAGE_MEAN) / IMAGE_STD;
            floatValues[i * 3 + 1] = (color.g - IMAGE_MEAN) / IMAGE_STD;
            floatValues[i * 3 + 0] = (color.b - IMAGE_MEAN) / IMAGE_STD;
        }

        return new Tensor(1, height, width, 3, floatValues);
    }


    private IList<BoundingBox> ParseOutputs(Tensor output, float threshold = .1F)
    {
        var boxes = new List<BoundingBox>();

        for(int row = 0; row < ROW_COUNT; row++)
        {
            for(int column = 0; column < COL_COUNT; column++)
            {
                for(int box = 0; box < boxAnchors.Length; box++)
                {
                    var channel = box * (labels.Length + featuresPerBox);

                    var boundingBox = ExtractBoundingBoxPrediction(output, row, column, channel);

                    var mappedBoundingBox = MapBoundingBoxToCell(row, column, box, boundingBox);

                    if (boundingBox.Confidence < threshold)
                        continue;

                    float[] classProbabilities = ExtractClassProbabilities(output, row, column, channel, boundingBox.Confidence, labels);

                    var (topProbability, topIndex) = classProbabilities.Select((probability, index) => (Score: probability, Index: index)).Max();

                    if (topProbability < threshold)
                        continue;

                    boxes.Add(new BoundingBox
                    {
                        Dimensions = mappedBoundingBox,
                        Confidence = topProbability,
                        Label = labels[topIndex]
                    });
                }
            }
        }

        return boxes;
    }

    private BoundingBox ExtractBoundingBoxPrediction(Tensor modelOutput,int row,int column, int channel)
    {
        return new BoundingBox
        {
            Dimensions = new BoundingBoxDimensions
            {
                X = modelOutput[GetOffset(row, column, channel++)],
                Y = modelOutput[GetOffset(row, column, channel++)],
                Width = modelOutput[GetOffset(row, column, channel++)],
                Height = modelOutput[GetOffset(row, column, channel++)]
            },
            Confidence = Sigmoid(modelOutput[GetOffset(row, column, channel++)]),
        };
    }
    private BoundingBoxDimensions MapBoundingBoxToCell(int row, int column, int box, BoundingBox boxDimensions)
    {
        float cellWidth = IMAGE_SIZE / COL_COUNT;
        float cellHeight = IMAGE_SIZE / ROW_COUNT;

        var mappedBox = new BoundingBoxDimensions
        {
            X = (row + Sigmoid(boxDimensions.Dimensions.X)) * cellWidth,
            Y = (column + Sigmoid(boxDimensions.Dimensions.Y)) * cellHeight,
            Width = (float)Math.Exp(boxDimensions.Dimensions.Width) * cellWidth * boxAnchors[box].x,
            Height = (float)Math.Exp(boxDimensions.Dimensions.Height) * cellHeight * boxAnchors[box].y,
        };

        // The x,y coordinates from the (mapped) bounding box prediction represent the center
        // of the bounding box. We adjust them here to represent the top left corner.
        mappedBox.X -= mappedBox.Width / 2;
        mappedBox.Y -= mappedBox.Height / 2;

        return mappedBox;
    }

    private float[] ExtractClassProbabilities(Tensor modelOutput, int row, int column, int channel, float confidence, string[] labels)
    {
        var classProbabilitiesOffset = channel + featuresPerBox;
        float[] classProbabilities = new float[labels.Length];
        for (int classProbability = 0; classProbability < labels.Length; classProbability++)
            classProbabilities[classProbability] = modelOutput[GetOffset(row, column, classProbability + classProbabilitiesOffset)];
        return Softmax(classProbabilities).Select(p => p * confidence).ToArray();
    }


    private static int GetOffset(int row, int column, int channel)
    {
        const int channelStride = ROW_COUNT * COL_COUNT;
        return (channel * channelStride) + (column * COL_COUNT) + row;
    }

    private static float Sigmoid(float value)
    {
        var k = (float)Math.Exp(value);
        return k / (1.0f + k);
    }

    private static float[] Softmax(float[] classProbabilities)
    {
        var max = classProbabilities.Max();
        var exp = classProbabilities.Select(v => Math.Exp(v - max));
        var sum = exp.Sum();
        return exp.Select(v => (float)v / (float)sum).ToArray();
    }

    private float IntersectionOverUnion(Rect boundingBoxA, Rect boundingBoxB)
    {
        var areaA = boundingBoxA.width * boundingBoxA.height;

        if (areaA <= 0)
            return 0;

        var areaB = boundingBoxB.width * boundingBoxB.height;

        if (areaB <= 0)
            return 0;

        var minX = Math.Max(boundingBoxA.xMin, boundingBoxB.xMin);
        var minY = Math.Max(boundingBoxA.yMin, boundingBoxB.yMin);
        var maxX = Math.Min(boundingBoxA.xMax, boundingBoxB.xMax);
        var maxY = Math.Min(boundingBoxA.yMax, boundingBoxB.yMax);

        var intersectionArea = Math.Max(maxY - minY, 0) * Math.Max(maxX - minX, 0);

        return intersectionArea / (areaA + areaB - intersectionArea);
    }


    private IList<BoundingBox> FilterBoundingBoxes(IList<BoundingBox> boxes, int limit, float threshold)
    {
        var activeCount = boxes.Count;
        var isActiveBoxes = new bool[boxes.Count];

        for (int i = 0; i < isActiveBoxes.Length; i++)
        {
            isActiveBoxes[i] = true;
        }

        var sortedBoxes = boxes.Select((b, i) => new { Box = b, Index = i })
                .OrderByDescending(b => b.Box.Confidence)
                .ToList();

        var results = new List<BoundingBox>();

        for (int i = 0; i < boxes.Count; i++)
        {
            if (isActiveBoxes[i])
            {
                var boxA = sortedBoxes[i].Box;
                results.Add(boxA);

                if (results.Count >= limit)
                    break;

                for (var j = i + 1; j < boxes.Count; j++)
                {
                    if (isActiveBoxes[j])
                    {
                        var boxB = sortedBoxes[j].Box;

                        if (IntersectionOverUnion(boxA.Rect, boxB.Rect) > threshold)
                        {
                            isActiveBoxes[j] = false;
                            activeCount--;

                            if (activeCount <= 0)
                                break;
                        }
                    }
                }

                if (activeCount <= 0)
                    break;
            }
        }

        return results;
    }
I used Detect Algorithm in ML.NET ( it's working ) but in Barracuda it is not working correctly

**Comment by Aurimasp** [comment]
Could you also send us the '.onnx' model? 

What exactly is not working? Do you see any errors? Are there incorrect output values?

**Comment by HuygnourT** [comment]
You can download the model here: https://drive.google.com/drive/u/0/folders/19NGfyhFyQE4A22KK8WY1fM8ZIptl0_l-
No error but the calculate BoundingBox is not correct, I already try this algorithm on ML.NET and it is still working

**Comment by AlexRibard** [comment]
Hi! Thanks for providing the model, I'll double check that it passes the tests.
I don't think there should be any issues with that as the model looks quite standard.
What could be an issue however:
In `GetOffset` you are accessing the `Tensor` in NCHW format so channel first.
However Barracuda is channel last NHWC so, to match you access patern, you should be accessing it like so
```
n * height * width * channels + h * width * channels + w * channels + c;
```
Note you can also query the tensor with it's 4D accessor so `modelOutput[n,h,w,c]` if that makes things easier

Let me know if that fixed your problem. In the meantime I'll validate the model

**Comment by tichise** [comment]
I'm having the exact same problem. This issue is very helpful.

**Comment by AlexRibard** [comment]
@tichise did my comment help you out or you are still having issues?

**Comment by tichise** [comment]
@AlexRibard  Thanks for the response.

I'm not familiar with Unity or ONNX, so I don't really understand the meaning of the code above, but your explanation of the code above is very helpful.

It would be very helpful if there is an official sample code to run CustomVision's Object Detection model in Barracuda.

**Comment by mantasp** [comment]
Thank you for suggestion, we will add this request to our backlog.
