### ISSUE TITLE
Gym-torch back to Unity ML Agents

### ISSUE THREAD

**Issue by Ademord** [Unity-Technologies/barracuda-release#226]
Hello, I've been in touch with other posters that tried this before and they couldnt go past this point where I am at. 

I exported my unity env to gym, trained, exported back to onnx but i don't know how to name the tensors appropriately / adapt the tensors for this onnx to be compatible and visualized in unity.

Can someone please help me / us ?

**Comment by amirebrahimi** [comment]
Hi @Ademord,

Are you referring to this? https://github.com/Unity-Technologies/ml-agents/tree/main/gym-unity
Is this an error coming from Barracuda or ML Agents?

**Comment by Ademord** [comment]
My question in one sentence is: what is the right way to export from a torch file to an onnx file compatible with barracuda/MLAgents?

For context: 
_What must be taken into acccount when working with the pipeline? Unity ML Agents Agent > Exported to Gym Environment with the MLAgents Gym Wrapper > Trained with SB3 > Exported to ONNX > Imported back to Unity > Current "constant errors"._

The error received is in the photo below (sorry for the bad quality). In other words, my doubts are:

🟥  **Critical**
- How can I adjust the "constants" error shown by Unity? 

🟦 **Important**
- Where can I see the input names and output names of an already onnx model from MLAgents, so that I dont have to reverse engineer? 

🟦 **Additional**
- is the way I am doing it correct? I am using `torch.onnx.export(model)`. (Missing input and output names).


![image](https://user-images.githubusercontent.com/4501464/136157170-9de41e49-a618-4dc5-9f17-47af7a86029e.png)

**Comment by Aurimasp** [comment]
Hi Ademord,

Torch > Onnx conversion usually also requires a dummy input batch.

You can see input and output names in the Unity Editor Inspector by clicking on the Onnx file.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/26163719/136175775-9c001706-f1b8-4bfd-9685-b6a44b89d9a9.png">

**Comment by Ademord** [comment]
Hello, yes I generate a dummy input batch as follows. Please help me with the questions above.

```python
    @measure
    def _export_pipeline(self, model, env):
        print("\n\n===============================================================================")
        print("Exporting model...")
        print("------------------------------------------------------------------------------")

        # temp
        full_model = self._get_full_model_for_export(model, env)
        s = self._get_empty_observations_for_export(env)

        # export to onnx
        export_path = os.path.join(self.config.run_dir, "model.onnx")
        torch.onnx.export(full_model, s, export_path)
        print("Model successfully exported." if os.path.isfile(export_path) else "Error: Could not export to onnx.")
        print("------------------------------------------------------------------------------")

    def _get_full_model_for_export(self, model, custom_env):
        print("LOG: type of model: ", type(model))
        return FullModel(
            model.policy.features_extractor,
            model.policy.mlp_extractor,
            model.policy.action_net,
            model.policy.value_net,
            [custom_env.observation_space[i].shape for i in custom_env.observation_space.sample().keys()]
        )

    def _get_empty_observations_for_export(self, env):
        # adapt environment and observations
        s = env.reset()
        print("state shapes:", s[0].shape)

        x = torch.randn(1, *env.observation_space[0].shape).cuda()
        y = torch.randn(1, *env.observation_space[1].shape).cuda()
        z = torch.randn(1, *env.observation_space[2].shape).cuda()
        s = [x, y, z]

        print("--------------------------")
        print(s[0].shape)
        print(x.shape)
        print(y.shape)
        print(z.shape)
        print("--------------------------")

        return s
```

**Comment by Aurimasp** [comment]
Does the error come from the Onnx model itself or from the agent component? It looks like some data used by ML-Agents is being stripped from the model in the conversion process. Could you share an example model before and after the conversion process?

**Comment by Ademord** [comment]
Sure. These models were trained in the same environment.
**- MLAgents-trained model (Windows, Unity):**  `Drone.onnx`
**- Torch model (Linux, Stable Baselines):**  `model.zip`
**- Previous Torch to ONNX model:**   `model.onnx`

which can be found here: https://www.dropbox.com/sh/paxqzs8ip1x09l6/AAA5c-sYtCAPobpqTkGi90-1a?dl=0

From another perspective, the goal is that `model_linux.onnx` is the same as `drone.onnx` so that the import back to Unity is problem-free.

**Comment by AlexRibard** [comment]
Thanks for providing the models. the linux model did have some import issue which I fixed.
We will be in touch with the ml agent teams to dig more into what could be going on.

**Comment by Ademord** [comment]
@AlexRibard : I think there is a misunderstanding here. I am _training a Unity ML Agents agent with the UnityGymWrapper with Baselines (SB3)_, and then saving this model "manually" through torch as described above. 

==> How did you fix it exactly so I can do the same?  
==> My question is still open: could you (or @Aurimasp) tell me how to properly export the model to a compatible .onnx?

**Comment by mantasp** [comment]
@Ademord ML-Agents runtime is expecting some additional metadata constants being embedded into model. "version_number" is one of them. You can see them being added in their model construction code: https://github.com/Unity-Technologies/ml-agents/blob/97eb505f9a34597563aadcde9f9e10479de3ac2b/ml-agents/mlagents/trainers/torch/networks.py#L585
Also they get exported as part of ONNX file: https://github.com/Unity-Technologies/ml-agents/blob/97eb505f9a34597563aadcde9f9e10479de3ac2b/ml-agents/mlagents/trainers/torch/model_serialization.py#L120.
For more information I would suggest you better ask ML-Agents team directly, either on their forum: https://forum.unity.com/forums/ml-agents.453/ or via GitHub issues https://github.com/Unity-Technologies/ml-agents/issues.

**Comment by Ademord** [comment]
@mantasp : thank you so much, i will try to figure out how to do this on my own in the meantime. 
@AlexRibard : if you can share the way you did it, too, that would be amazing.

**Comment by AlexRibard** [comment]
@Ademord I've sent you an email with the fixes

**Comment by AlexRibard** [comment]
(closing this thread for now as most Barracuda issues have been resolved)
