### ISSUE TITLE
How to install barracuda if my currently using unity platform doesn't have a package manager?

### ISSUE THREAD

**Issue by ArronChan** [Unity-Technologies/barracuda-release#229]
Hi!  Thank for your amazing work!
But currently I using unity 5.4.2 for developing for some reason.
This version doesn't have a package manager.
So how should I do to install  barracuda in it？

**Comment by likemango** [comment]
Barracuda need brust and other indepences , unity 5.4.2 is too old , I guess it can't work on it. Howerer, I use Unity2020.3 and barracuda 2.2.1-preview ,those works great

**Comment by Aurimasp** [comment]
Hello, the oldest currently supported version of Unity is 2019.4, and 2017.4 for very early Barracuda versions.
