### ISSUE TITLE
Android (Samsung) issues: GLSL Link error / Unable to link compute shader

### ISSUE THREAD

**Issue by kdsh7** [Unity-Technologies/barracuda-release#23]
Hi everyone,

I have a yolov2 model that is working in editor with releases 0.40 and 0.60 however when on device it's throwing these linker errors. I've pulled these out of adb logcat:

`02-24 19:43:56.438 21717 21857 E Unity   : -------- GLSL link error:  Max number of total work group invocations exceeded.
02-24 19:43:56.438 21717 21857 E Unity   : 
02-24 19:43:56.438 21717 21857 E Unity   : 
02-24 19:43:56.438 21717 21857 E Unity   :  
02-24 19:43:56.438 21717 21857 E Unity   : (Filename:  Line: 645)
02-24 19:43:56.438 21717 21857 E Unity   : 
02-24 19:43:56.438 21717 21857 E Unity   : ERROR: Unable to link compute shader: Dense.Dense_T16x16_R4x4 
02-24 19:43:56.438 21717 21857 E Unity   : (Filename:  Line: 2596)
02-24 19:43:56.438 21717 21857 E Unity   : 
02-24 19:43:56.694 21717 21857 E Unity   : -------- GLSL link error:  Max number of total work group invocations exceeded.
02-24 19:43:56.694 21717 21857 E Unity   : 
02-24 19:43:56.694 21717 21857 E Unity   : 
02-24 19:43:56.694 21717 21857 E Unity   :  
02-24 19:43:56.694 21717 21857 E Unity   : (Filename:  Line: 645)
02-24 19:43:56.694 21717 21857 E Unity   : 
02-24 19:43:56.694 21717 21857 E Unity   : ERROR: Unable to link compute shader: Conv.Conv2DKernelKxK_T16x16_R4x4 
02-24 19:43:56.694 21717 21857 E Unity   : (Filename:  Line: 2596)
02-24 19:43:56.694 21717 21857 E Unity   : 
02-24 19:43:56.775 21717 21857 E Unity   : -------- GLSL link error:  Max number of total work group invocations exceeded.
02-24 19:43:56.775 21717 21857 E Unity   : 
02-24 19:43:56.775 21717 21857 E Unity   : 
02-24 19:43:56.775 21717 21857 E Unity   :  
02-24 19:43:56.775 21717 21857 E Unity   : (Filename:  Line: 645)
02-24 19:43:56.775 21717 21857 E Unity   : 
02-24 19:43:56.775 21717 21857 E Unity   : ERROR: Unable to link compute shader: Conv.Conv2DKernelKxK_StrictC16K64_T16x16_R4x4 
02-24 19:43:56.775 21717 21857 E Unity   : (Filename:  Line: 2596)
02-24 19:43:56.775 21717 21857 E Unity   : 
02-24 19:43:56.829 21717 21857 E Unity   : -------- GLSL link error:  Max number of total work group invocations exceeded.
02-24 19:43:56.829 21717 21857 E Unity   : 
02-24 19:43:56.829 21717 21857 E Unity   : 
02-24 19:43:56.829 21717 21857 E Unity   :  
02-24 19:43:56.829 21717 21857 E Unity   : (Filename:  Line: 645)
02-24 19:43:56.829 21717 21857 E Unity   : 
02-24 19:43:56.829 21717 21857 E Unity   : ERROR: Unable to link compute shader: Conv.Conv2DKernel1x1_StrictC16K64_T16x16_R4x4 
02-24 19:43:56.829 21717 21857 E Unity   : (Filename:  Line: 2596)
02-24 19:43:56.829 21717 21857 E Unity   : 
02-24 19:43:57.145 21717 21857 E Unity   : -------- GLSL link error:  Max number of total work group invocations exceeded.
02-24 19:43:57.145 21717 21857 E Unity   : 
02-24 19:43:57.145 21717 21857 E Unity   : 
02-24 19:43:57.145 21717 21857 E Unity   :  
02-24 19:43:57.145 21717 21857 E Unity   : (Filename:  Line: 645)
02-24 19:43:57.145 21717 21857 E Unity   : 
02-24 19:43:57.145 21717 21857 E Unity   : ERROR: Unable to link compute shader: Conv.Conv2DTrans_KernelCached_K5x5_T16x16 
02-24 19:43:57.145 21717 21857 E Unity   : (Filename:  Line: 2596)
`

**Comment by mantasp** [comment]
At the moment we dropped GLES support on Android and focusing on Vulkan instead. Please let us know if Vulkan doesn't work for you.

**Comment by kdsh7** [comment]
Thanks for the clarification @mantasp. A lot of our potential uses for barracuda are centred around AR and ARCore which doesn't support Vulkan currently.

**Comment by Blackclaws** [comment]
This is still an issue, using Barracuda together with ARCore is therefore not intended?

**Comment by Aurimasp** [comment]
Hi Blackclaws. We are working on a Pixel Shader worker, which will enable GPU on GLES. If everything goes well, it should be released soon.

**Comment by Berenice2018** [comment]
Hi @Aurimasp , Are there any news concerning the Pixel Shader worker you have mentioned recently? As previous commenters stated, we would like to use Barracuda together with ARFoundation, especially since the Unity Perception package and the DataMaker made good progress. I would look forward to hearing from you.
P. S.: I am using Barracuda  v 2.3.1 preview, Unity 2020.3

**Comment by Blackclaws** [comment]
You can use it on iOS with GPU and on Android with CPU workers. It does kill performance on Android if running large inference regularly though. Make sure you run the neural net one operation per frame and not all at once.

**Comment by Aurimasp** [comment]
Hey, we have added the Pixel Shader backend in the 2.3.0+ version of Barracuda. You can select it like this: "WorkerFactory.Type.PixelShader".
