### ISSUE TITLE
Barracuda ONNX model import fails with assertion failures

### ISSUE THREAD

**Issue by mikhailjacob** [Unity-Technologies/barracuda-release#232]
I am trying to import a ONNX model from PyTorch for a convolutional VAE (operating on 1D data (batch, 4, 32) in channels first form) into Unity (2021.1.22f1) with Barracuda release 2.0.0 (I have also tried 2.3.1 with same results). Import fails with two assertion failures in the debug console.

First: 'AssertionException: Assertion failure. Value was False Expected: True'
Second: 'Asset import failed, "Path/To/Model/model.onnx" > AssertionException: Assertion failure. Value was False Expected: True'.

Looking at the line numbers for the failure, I'm struggling to understand the problem here. It's in Unity.Barracuda.TensorExtensions.AdjustPadToKernel, right? I'm attaching the ONNX models I tried (opset 10 first, then opset 9), the export script I used, and the model definition script.

[onnx_models.zip](https://github.com/Unity-Technologies/barracuda-release/files/7442678/onnx_models.zip)
[model_scripts.zip](https://github.com/Unity-Technologies/barracuda-release/files/7442686/model_scripts.zip)

Minor addition in case it's related: There are also warnings about dilations in my decoder where I use convTranspose operations. However, I'm not actually using dilations (or rather, they're set to the default params)? I might be wrong, but this issue seem orthogonal, so I'm not attaching those warning messages here.

Please let me know if I'm missing any other detail or if any more information would be helpful. 

Thanks a ton in advance!
---------------
Full exception message details:

First assertion failure:

AssertionException: Assertion failure. Value was False
Expected: True
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition, System.String message) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
Unity.Barracuda.TensorExtensions.AdjustPadToKernel (Unity.Barracuda.TensorShape shape, Unity.Barracuda.TensorShape kernel, System.Int32[] stride, System.Int32[] pad) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/TensorExtensions.cs:527)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.ShapeInference.InferOutputShapeNCHW (Unity.Barracuda.Layer layer, System.Int32[] inputRanks, Unity.Barracuda.TensorShape[] inputShapes) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/ShapeInference/IRShapeInferenceHelper.cs:184)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.ShapeInference.UpdateKnownTensorShapesNCHW (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName, System.Collections.Generic.IDictionary`2[System.String,System.Nullable`1[Unity.Barracuda.TensorShape]]& shapesByName) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/ShapeInference/IRShapeInferenceHelper.cs:781)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.FuseShapesIntoConstants (Unity.Barracuda.Model& model, System.Collections.Generic.IDictionary`2[TKey,TValue] shapesByName, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:66)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:23)
Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:12)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:170)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <33fb8f3984d146e083d756d969c06738>:0)

Second assertion failure:

Asset import failed, "Assets/ML/Models/vae_model_99999_opset_9.onnx" > AssertionException: Assertion failure. Value was False
Expected: True
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition, System.String message) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
Unity.Barracuda.TensorExtensions.AdjustPadToKernel (Unity.Barracuda.TensorShape shape, Unity.Barracuda.TensorShape kernel, System.Int32[] stride, System.Int32[] pad) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/TensorExtensions.cs:527)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.ShapeInference.InferOutputShapeNCHW (Unity.Barracuda.Layer layer, System.Int32[] inputRanks, Unity.Barracuda.TensorShape[] inputShapes) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/ShapeInference/IRShapeInferenceHelper.cs:184)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.ShapeInference.UpdateKnownTensorShapesNCHW (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName, System.Collections.Generic.IDictionary`2[System.String,System.Nullable`1[Unity.Barracuda.TensorShape]]& shapesByName) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/ShapeInference/IRShapeInferenceHelper.cs:781)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.FuseShapesIntoConstants (Unity.Barracuda.Model& model, System.Collections.Generic.IDictionary`2[TKey,TValue] shapesByName, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:66)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:23)
Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:12)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:170)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <33fb8f3984d146e083d756d969c06738>:0)

**Comment by FlorentGuinier** [comment]
Hi mikhailjacob,

The problem come from ConvTranspose layers witch are operated on 1D spatial input. This is a bug on our side and happen because so far we assumed ConvTranspose to operate on 2D spatial inputs. I'm opening a bug and we will warn you as soon as it is fixed. Meantime Upsample+Conv could be a workaround, is that something you can try?

Florent

**Comment by FlorentGuinier** [comment]
Hi mikhailjacob,

Fix was actually trivial and is in landing process for next version (2.3.2), if Upsample+ConvTranspose does not fix or you can't wait the version, i can send you a patch, just let us know.

As issue seems to be fixed i'm closing the bug, please feel free to reopen if needed.
Florent

**Comment by mikhailjacob** [comment]
Hi Florent,

Thanks for your help on this and for getting back to me so quickly! I look forward to hearing when the bug is fixed.

I tried your workaround. I am not sure if I've implemented it correctly or missed something in there, but here's my updated decoder (class DecoderUpsampleConv) + the ONNX export script, as well as the exported model.
[export_model_test_upsampleconv.zip](https://github.com/Unity-Technologies/barracuda-release/files/7454668/export_model_test_upsampleconv.zip). The new decoder does not work in Unity when Barracuda imports it. Different output error message (added at the end on here), though it sounds like the same problem with using 1D operations. The alternative decoder (class DecoderLinear) using Linear layers that is in the attached script exports fine as expected.

Thanks so much once again for any help or advice you have on this.

Best,
Mikhail.

First error message in debug console:

AssertionException: InferOutputRank.*Upsample2D inputRanks
Assertion failure. Values are not equal.
Expected: 4 == 3
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Assertions.Assert.AreEqual (System.Int32 expected, System.Int32 actual, System.String message) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.RankInference.InferOutputRank (Unity.Barracuda.Layer layer, System.Int32[] inputRanks) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/ShapeInference/IRRankInferenceHelper.cs:56)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.RankInference.UpdateKnownTensorRanks (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/ShapeInference/IRRankInferenceHelper.cs:256)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.FuseShapesIntoConstants (Unity.Barracuda.Model& model, System.Collections.Generic.IDictionary`2[TKey,TValue] shapesByName, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:65)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:23)
Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:12)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:170)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <33fb8f3984d146e083d756d969c06738>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

Second error message in debug console:

Asset import failed, "Assets/RG/ML/Models/test_model_decoderupsampleconv_opset_9.onnx" > AssertionException: InferOutputRank.*Upsample2D inputRanks
Assertion failure. Values are not equal.
Expected: 4 == 3
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Assertions.Assert.AreEqual (System.Int32 expected, System.Int32 actual, System.String message) (at <41d34619c06946aebeba0ca1ee6d765b>:0)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.RankInference.InferOutputRank (Unity.Barracuda.Layer layer, System.Int32[] inputRanks) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/ShapeInference/IRRankInferenceHelper.cs:56)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.RankInference.UpdateKnownTensorRanks (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/ShapeInference/IRRankInferenceHelper.cs:256)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.FuseShapesIntoConstants (Unity.Barracuda.Model& model, System.Collections.Generic.IDictionary`2[TKey,TValue] shapesByName, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:65)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:23)
Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:12)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:170)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <33fb8f3984d146e083d756d969c06738>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by mikhailjacob** [comment]
Apologies, Florent. It looks like I replied before seeing your latest reply and the issue closure. I would absolutely LOVE a patched version if that's possible. Anything else you could suggest to help would also save my bacon. :) Do let me know if this warrants reopening the issue. Thanks!

**Comment by FlorentGuinier** [comment]
Hi mikhailjacob,

Here is the patch that should apply cleanly on Barracuda 2.3.1
[ConvTranspose1DSupport.zip](https://github.com/Unity-Technologies/barracuda-release/files/7458934/ConvTranspose1DSupport.zip)

To apply it: 
git clone https://github.com/Unity-Technologies/barracuda-release/
cd barracuda-release
git apply -p2 --reject <path to unziped patch file>

You will then need to use Barracuda from source:
https://docs.unity3d.com/Packages/com.unity.barracuda@2.3/manual/Installing.html

Let us know how it goes!
Florent

**Comment by mikhailjacob** [comment]
Excellent! This worked like a charm! Thank you so much, Florent! Woohoo!
