### ISSUE TITLE
wrong results given by Barracuda with ONNX models

### ISSUE THREAD

**Issue by mukae1997** [Unity-Technologies/barracuda-release#233]
Barracuda v 2.3.1

Hello, I use paddle-detection(https://github.com/PaddlePaddle/PaddleDetection)  and try to import an onnx YOLOV3 model to unity.
my original model is here: 
https://drive.google.com/file/d/14NiGD2uoMyx1E78Of9WUooVVZohHtFCk/view?usp=sharing

I modify it by using the code from   https://github.com/Unity-Technologies/barracuda-release/issues/138    
Also, to solve the errors I remove one of the output `save_infer_model/scale_1.tmp_1` which I think representing the number of objects it infers in the original model.(I don't know much about machine-learning so I just delete the things that may cause error)
The modified model is here: https://drive.google.com/file/d/1OswWCaKYQoEgIBpu5ZVuwg8OIhVxjbdJ/view?usp=sharing

It runs well with one target object,  but gives strange output when there are multiple targets in the image.

The paddle-detection infer tool gives correct results. 

> person 0.9897104501724243 185.04901123046875 1.5121612548828125 185.43353271484375 159.27772521972656
> person 0.823543906211853 316.06182861328125 395.7960205078125 141.93524169921875 151.66363525390625

This is the output Tensor by Barracuda:

> (n:4, h:1, w:1, c:6)
>
> 0 0.974982 189.248 449.2132 364.9202 607 0 0 0 0 0 0 309.2759 0 0 0 0 0 334.8578 0 0 0 0 0 

It seems that Barracuda only gives correct prediction of the first object it recognized.

I wonder where the problem comes, should I keep the outputs as they are? Or is there any other problem with the model and Barracuda?

My Unity code:

```c#
 
public RenderTexture OutputBuffer;

...

var inputs = new Dictionary<string, Tensor>();

inputs["im_shape"] = new Tensor(1, 1, 1, 2, new float[] { 608, 608 }); // scale of screen co-ordinates; should be original resolution

inputs["image"] = new Tensor(OutputBuffer, 3); // must match NN input 
inputs["scale_factor"] = new Tensor(1, 1, 1, 2, new float[] { 1, 1 }); // affects coordinate
_worker.Execute(inputs);


inputs["im_shape"].Dispose();
inputs["image"].Dispose();
inputs["scale_factor"].Dispose();


Tensor res = _worker.PeekOutput("save_infer_model/scale_0.tmp_1");
```

**Comment by mukae1997** [comment]
I set to Verbose mode and I think there are sensible results before operator `Squeeze_18`
```
> {3} # (n:1, h:1, w:6, c:4)
```

```
> After Concat 
0 0 0 0 
0.974982 0.7966061 0.02215337 0.01147567 
189.248 319.2078 309.2759 334.8578 
449.2132 64.4518 321.2975 328.4952 
364.9202 456.528 484.7987 455.3504 
607 208.4764 479.2567 422.7904 
```

```
> Layer: Transpose Squeeze_18
```

**Comment by Aurimasp** [comment]
Hi @mukae1997 

Thanks for reporting the issue. It looks like there is a bug in our code. 0 is not inverted with 'Neg' operator (Neg_0 in your model). We registered the issue and you can track the progress here: https://issuetracker.unity3d.com/product/unity/issues/guid/BAR-184

**Comment by Aurimasp** [comment]
Hi again @mukae1997 

So it appears there is a different issue in our code. There is a missing Transpose before the TopK_5 layer and the dimensions are inverted. Here is a workaround to fix the issue. Just add it into your Unity code:

```
        var newLayer = new ModelBuilder(new Model()).Transpose(name:"Reverse", input:"Neg_0", permutations:new int[] {3,2,1,0});
        int negLayer = FindLayerIndexByName(model.layers, "Neg_0");
        model.layers.Insert(negLayer+1,newLayer);
        var nextLayer = model.layers.Find(layer => layer.name == "TopK_5");
        nextLayer.inputs[0] = "Reverse";
```
