### ISSUE TITLE
Incorrect result and assertion failure when running ONNX model with Barracuda

### ISSUE THREAD

**Issue by cwitkowitz** [Unity-Technologies/barracuda-release#238]
Hello Barracuda Team,

I've been troubleshooting an ONNX model exported using PyTorch, and have verified that the model gives the intended result when using `onnxruntime` in Python.

I experienced some difficulties getting Barracuda to even compile the model, but eventually solved these by upgrading to Barracuda 2.3.1 and switching out some operations that were failing with equivalent operations that happened to work, e.g. `tensor.flatten()` to `torch.reshape()`.

After that, my model appeared to run smoothly in Unity, but I noticed that the output did not match what I was seeing in Python, even when I fed in the _exact_ same input. I then saw the note in the [docs](https://docs.unity3d.com/Packages/com.unity.barracuda@2.3/manual/Worker.html) about switching to a different worker. I was originally using `ComputePrecompiled`, and after trying all other workers, I realized the only other one that worked was `Compute`. The rest gave me a similar error during runtime:

```
AssertionException: Assertion failure. Values are not equal.
Expected: 3648 == 14656
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <ca496b8c93454b2f9b9924292c19379f>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <ca496b8c93454b2f9b9924292c19379f>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at <ca496b8c93454b2f9b9924292c19379f>:0)
UnityEngine.Assertions.Assert.AreEqual (System.Int32 expected, System.Int32 actual) (at <ca496b8c93454b2f9b9924292c19379f>:0)
Unity.Barracuda.ReferenceComputeOps.Dense (Unity.Barracuda.Tensor X, Unity.Barracuda.Tensor W, Unity.Barracuda.Tensor B, Unity.Barracuda.Layer+FusedActivation fusedActivation) (at C:/Users/cwitk/Desktop/barracuda-release/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:873)
Unity.Barracuda.ReferenceComputeOps.MatMul (Unity.Barracuda.Tensor X, System.Boolean xTranspose, Unity.Barracuda.Tensor Y, System.Boolean yTranspose) (at C:/Users/cwitk/Desktop/barracuda-release/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:859)
Unity.Barracuda.ReferenceCPUOps.MatMul (Unity.Barracuda.Tensor X, System.Int32 rankX, Unity.Barracuda.Tensor Y, System.Int32 rankY) (at C:/Users/cwitk/Desktop/barracuda-release/Barracuda/Runtime/Core/Backends/BarracudaReferenceCPU.cs:742)
Unity.Barracuda.ReferenceComputeOps.MatMul (Unity.Barracuda.Tensor X, System.Int32 rankX, Unity.Barracuda.Tensor Y, System.Int32 rankY) (at C:/Users/cwitk/Desktop/barracuda-release/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:844)
Unity.Barracuda.StatsOps.Unity.Barracuda.IOps.MatMul (Unity.Barracuda.Tensor X, System.Int32 rankX, Unity.Barracuda.Tensor Y, System.Int32 rankY) (at C:/Users/cwitk/Desktop/barracuda-release/Barracuda/Runtime/Core/Backends/StatsOps.cs:92)
Unity.Barracuda.GenericWorker+<StartManualSchedule>d__35.MoveNext () (at C:/Users/cwitk/Desktop/barracuda-release/Barracuda/Runtime/Core/Backends/GenericWorker.cs:305)
Unity.Barracuda.GenericWorker.Execute () (at C:/Users/cwitk/Desktop/barracuda-release/Barracuda/Runtime/Core/Backends/GenericWorker.cs:182)
Unity.Barracuda.GenericWorker.Execute (System.Collections.Generic.IDictionary`2[TKey,TValue] inputs) (at C:/Users/cwitk/Desktop/barracuda-release/Barracuda/Runtime/Core/Backends/GenericWorker.cs:167)
Transcriber.Update () (at Assets/Scripts/Transcriber.cs:2178)
```

My ONNX model is too large (42.5 MB zipped) to upload here, but I would be happy to send it along. When I feed in [this audio](https://github.com/Unity-Technologies/barracuda-release/files/7700309/input.txt), along with all 0s for each initial hidden/cell state, I expect [this output](https://github.com/Unity-Technologies/barracuda-release/files/7700324/output.txt). Additionally, I expect the following hidden/cell states as output:
- [onset_hidden.txt](https://github.com/Unity-Technologies/barracuda-release/files/7700333/onset_hidden.txt)
- [onset_cell.txt](https://github.com/Unity-Technologies/barracuda-release/files/7700335/onset_cell.txt) 
- [offset_hidden.txt](https://github.com/Unity-Technologies/barracuda-release/files/7700339/offset_hidden.txt)
- [offset_cell.txt](https://github.com/Unity-Technologies/barracuda-release/files/7700349/offset_cell.txt)
- [adjoin_hidden.txt](https://github.com/Unity-Technologies/barracuda-release/files/7700351/adjoin_hidden.txt)
- [adjoin_cell.txt](https://github.com/Unity-Technologies/barracuda-release/files/7700352/adjoin_cell.txt)

Any help would be greatly appreciated. Thanks in advance!

**Comment by cwitkowitz** [comment]
Here is a Google Drive link to the model: https://drive.google.com/file/d/1y8vOxGopphNbfBOEUHbE28YofhsA7yNK/view?usp=sharing

**Comment by AlexRibard** [comment]
Thank you for providing the model!
We'll take a look and get back to you

**Comment by AlexRibard** [comment]
I've taken a look at your model, there is a few issues:
* Split, at the moment we don't support this version of the operator. But it's fixable
* tf2onnx actually returns me an error and is not able to generate `NonMaxSuppression` correctly.
Are you able to generate the onnx file without error? If so can you provide it?
Thanks!

**Comment by AlexRibard** [comment]
@cwitkowitz letting you know that I have fixed the issue.
Look forward to the next version.

If you are interested in getting the workaround earlier, feel free to email us at barracuda-support@unity3d.com and I will provide the PR
