### ISSUE TITLE
the speed of reading onnx file gets slower by updating from 0.4 to 0.6.

### ISSUE THREAD

**Issue by h-nakae** [Unity-Technologies/barracuda-release#24]
Hi,
Firstly,We really appreciate for you've done.
Thanks to your product, we could build our results↓
https://github.com/digital-standard/ThreeDPoseUnityBarracuda

And there is a question this time.
We are using version 0.4 of Barracuda to read onnx file and move 3D avatar in unity and it goes well.
But the speed gets slower by updating the version to 0.6.

Do you know the reason or solution of this?
It is very kind of you, if you could tell me that.

Thank you for your help.
Hiro

**Comment by FlorentGuinier** [comment]
Hi h-nakae, Barracuda 0.6.1 was just published. Along with it a performance regression was fixed. Could you give it a try please?

**Comment by h-nakae** [comment]
Hi FlorentGuinier ,
Thank you for your replying.
I have just tried the new version, but it seems that the speed is still slow unfortunately...

Here, I put the screen shot.
The left one is version0.4, the second is 0.6.
The speed is as follwing.
---------------------
v0.4 ⇒ 29.2 FPS
v0.61 ⇒ 16.2FPS
---------------------
![barracuda_compare](https://user-images.githubusercontent.com/56616438/75836401-1ea1f780-5e05-11ea-9064-da8e13021273.PNG)


Thank you for your helping.

**Comment by h-nakae** [comment]
Hi FlorentGuinier ,
Thank you for your replying.
I have just tried the new version, but it seems that the speed is still slow unfortunately...

Here, I put the screen shot.
The left one is version0.4, the second is 0.6.
The speed is as follwing.

v0.4 ⇒ 29.0 FPS
v0.61 ⇒ 15.7FPS

![barracuda_compare](https://user-images.githubusercontent.com/56616438/75837397-1b5c3b00-5e08-11ea-9ec3-39d4d4fb500a.PNG)


Thank you for your helping.

**Comment by yukihiko** [comment]
Hi,
In the model I am using, the model layer was 145 layers in Ver0.4, 405 layers in Ver0.6.1, and there was a difference after loading the onnx model.
The layer added in Ver0.6.1. was of Type.Load.
This may be one of the reasons.
I do not understand what the data of Type.Load, but I tried put this code at the top of the loop in the ExecuteAsync method in GenericWorker.cs

    if (l.type == Layer.Type.Load) continue;

The processing was improved from 23fps to 43fps.
(It is about 55fps in ver0.4)
At Type.Load, I don't know if PrepareStorage method is not needed.

**Comment by mantasp** [comment]
@yukihiko we managed to reproduce issue, we expect to ship fix in `0.6.2`. 
Thanks for reporting!

**Comment by yukihiko** [comment]
Thank you! I'm hoping for the next release.

**Comment by mantasp** [comment]
@yukihiko we just shipped `0.6.2`, could you please check if your use case performance is back?

**Comment by yukihiko** [comment]
I tried ver.0.6.2.
It's a great job!
It became almost the same speed as ver.0.4.(I think ver.0.4 is about 1fps faster)
Thank you!

**Comment by h-nakae** [comment]
@mantasp  , @FlorentGuinier 

Thank you for the updating.
That is nice of you.

I'm satisfied with that so I will close this issue.
Thanks
