### ISSUE TITLE
Inference time on mobile phones

### ISSUE THREAD

**Issue by giga1992** [Unity-Technologies/barracuda-release#240]
Hello, I've been using Barracuda for a few months now. I'm learning how to use the engine as well as learning about neural networks and machine learning by using some pretrained and some custom models as well as combination of two models, mostly focusing on computer vision model implementations. My main concern is inference time on mobile devices. It is really slow, taking 250-400 ms for basic TinyYolov2 detection. I've tried and tested all execution options Barracuda has to offer and still, inference is unacceptable on mobile devices. Then it came to mind to ask if there is some idea for when will(or will it at all?) Barracuda start using AI chips for model execution. They are pretty much found on every newer device and this would actually render Barracuda dominant in the ML world and would definitely place Unity shoulder to shoulder with native implementations through Android studio and Xcode.

**Comment by FlorentGuinier** [comment]
Hi giga1992,

First thanks for using our product.
Indeed mobile performance can be greatly improved by using dedicated AI chips! It is not unusual that hardware vendor display around 10x performance improvement when comparing GPU and NPU inference! However there are a few quirks:
* A lot of AI chips are only supporting int8/16 while GPU implementation works on fp16/32. Those comparison thus require a quantized model to run on the NPU.
* While on Apple platform coreML (itself using NPU when possible) performance and support are quite uniform across devices, it is not the same for android devices where the fragmentation could make a particular model fallback to a slow implementation on a particular device.

While i definitively share your feeling that NN hardware are the go to solution to get the best performance on mobile, and despite the team have experimented with both CoreML and NNAPI inside Barracuda we don't ship those backend at the moment. The reason being that if one target a subset of hardware there is less value at the moment to be a wrapper around only one of those API. On the contrary we currently focus on generic optimization that apply to all the platform we support:
Some examples:
* Convolution were recently improved by 20% on mobile
* PixelShader worker (first release 2.3.0, more operator support in coming 2.4.0 release) often improve performance on mobile
* fp16 GPU support is in progress.

That being said! It is not the end of the story, in the future we expect NPU to be more flexible, better integrated with the graphic pipeline and globally more present in the device landscape. We will continue to monitor the HW landscape closely and revise our priority accordingly!

I hope it make sense? Please let us know your opinion!

BTW performance is obviously very dependant of the model and input size here are some number from Barracuda 2.3.0
![image](https://user-images.githubusercontent.com/20201082/146207596-0f2274cf-ab1a-42eb-9203-11075f0cbc6d.png)

**Comment by FlorentGuinier** [comment]
That being said there might be a problem on the particular model(s) you are working on, I'm closing the bug for now however:
- Let's continue discution, we love your feedback!
- Feel free to reopen if you think your model should run faster in term of CPU/GPU. Something might not be right! Also feel free to share the model so we can profile it!

Florent
