### ISSUE TITLE
PRoblem using LSTM NN in Barracuda (unity)

### ISSUE THREAD

**Issue by giorgiogamba** [Unity-Technologies/barracuda-release#241]
Hi,
I'm new in Barracuda in Unity and I would like to execute a LSTM Neural Network inside my unity project. The Neural network is well imported inside the project, but inference results are different from the ones I get from the not-converted original neural network, so maybe it could be the onnx conversion causing the damage.
Is there a specific procedure I have to follow for converting this type of NN? I also tried with a simple multilayerperceptron and everything is ol
Thanks

**Comment by AlexRibard** [comment]
Hello @giorgiogamba thank you for point out the issue.
Could you provide the model in question so I can see if everything is alright?
Did you make sure your input tensor matches the input shape the model is expecting?

**Comment by giorgiogamba** [comment]
Hi,
Sorry for the delay in my answer.
It seems I was able to correct the problem, it was about the input data I was using during inference. I was using data at the start of the simulation, but the network was trained using different kind of data, so now it should work. 
Thanks the same for your fast answer and help!! 😊
