### ISSUE TITLE
Unsupported ScatterND operator

### ISSUE THREAD

**Issue by sanarberkebayram01** [Unity-Technologies/barracuda-release#242]
Currently im trying to implement computer vision algorithms to barracuda. However, some of my models include built-in scatternd operation of tensorflow. Can i assume that the operation will be included in further versions of barracuda ?

**Comment by Aurimasp** [comment]
Hey, thanks for reaching out to us. Yes, we are planning to add it in the near future.

**Comment by AlexRibard** [comment]
`ScatterND` is supported in latest barracuda. I suggest you try out version 2.4.0

If it still doesn't import, would you share your model?
Let me know.
