### ISSUE TITLE
Transpose conv operation unsupported output_shape 

### ISSUE THREAD

**Issue by sanarberkebayram01** [Unity-Technologies/barracuda-release#244]
I was trying to implement a model including conv transpose operation which was originally tensorflow model. 
Model graph : [Link](https://i.ibb.co/FxPZbvX/modell.png)

I'm having issue with 640 - 657 and 674th layer which are conv transpose layers.

`Unsupported attribute output_shape, node ConvTranspose__640:0 of type ConvTranspose. Value will be ignored and defaulted to [].
UnityEngine.Debug:LogWarning (object)
Unity.Barracuda.D:LogWarning (object) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/Core/Internals/Debug.cs:72)
Unity.Barracuda.ONNX.ONNXNodeWrapper:Warn (string) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/ONNX/ONNXNodeWrapper.cs:154)
Unity.Barracuda.ONNX.ONNXNodeWrapper:UnsupportedAttribute (string,int[]) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/ONNX/ONNXNodeWrapper.cs:188)
Unity.Barracuda.ONNX.ONNXModelConverter/<>c__DisplayClass27_0:<UseStandardImporter>b__88 (Unity.Barracuda.ModelBuilder,Unity.Barracuda.ONNX.ONNXNodeWrapper) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1004)
Unity.Barracuda.ONNX.ONNXModelConverter:ConvertOnnxModel (Onnx.ModelProto) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2934)
Unity.Barracuda.ONNX.ONNXModelConverter:Convert (Google.Protobuf.CodedInputStream) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:170)
Unity.Barracuda.ONNX.ONNXModelConverter:Convert (string) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:98)
Unity.Barracuda.ONNXModelImporter:OnImportAsset (UnityEditor.AssetImporters.AssetImportContext) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Editor/ONNXModelImporter.cs:65)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
`
------
`InvalidOperationException: Nullable object must have a value.
System.Nullable`1[T].get_Value () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Unity.Barracuda.Compiler.Passes.NCHWToNHWCPass.CorrectConstantsForBroadCast (Unity.Barracuda.Model& nhwc) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/Core/Compiler/Passes/NCHWToNHWC/CorrectForBroadcast.cs:139)
Unity.Barracuda.Compiler.Passes.NCHWToNHWCPass.Rewrite (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/Core/Compiler/Passes/NCHWToNHWCPass.cs:151)
Unity.Barracuda.Compiler.Passes.NCHWToNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/Core/Compiler/Passes/NCHWToNHWCPass.cs:39)
Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:38)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:188)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:98)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@b1eac6c34b/Barracuda/Editor/ONNXModelImporter.cs:65)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at /Users/bokken/buildslave/unity/build/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:22)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
`

**Comment by FlorentGuinier** [comment]
Hi @sanarberkebayram01,

Indeed at the moment we don't have support for the **output_shape** parameters for convtranspose operators. Here is ONNX definition of this parameters: 
```
output_shape : list of ints
The shape of the output can be explicitly set which will cause pads values to be auto generated. If output_shape is specified pads values are ignored. See doc for details for equations to generate pads
```
from https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvTranspose 

A possible workaround would be to set the pad values rather than the output_shape parameter, is that something that could work for you?

Happy new year!
Florent
