### ISSUE TITLE
Barracuda ONNX import assertion error

### ISSUE THREAD

**Issue by Darth-Carrotpie** [Unity-Technologies/barracuda-release#246]
Hello,
I've got an assertion error that I've seen others also got (two errors saying the same thing), but mine cries a little different:
```
AssertionException: InferOutputRank.*Conv2D* inputRanks
```
The model I'm trying to use is an export from pre-trained **wav2vec2-base-960h** from ```transformers``` library. It's a speech to text made by facebook last year.
You can find the export code [in my kaggle notebook](https://www.kaggle.com/danieliusv/transformers-test), but there I simply do torch.onnx.export();

Model is too large to attach here, so I'm attaching at least the properties.
![model properties](https://user-images.githubusercontent.com/9535319/148089789-4baf5348-021c-4179-9616-11fedd104ddf.PNG)

<details>
  <summary>See for full message</summary>

```
Asset import failed, "Assets/Models/wav2vec2-base-960h.onnx" > AssertionException: InferOutputRank.*Conv2D* inputRanks
Assertion failure. Value was False
Expected: True
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <ad50157ee00e45cdb3c8bd67012f8804>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition, System.String message) (at <ad50157ee00e45cdb3c8bd67012f8804>:0)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.RankInference.InferOutputRank (Unity.Barracuda.Layer layer, System.Int32[] inputRanks) (at Library/PackageCache/com.unity.barracuda@2.3.1-preview/Barracuda/Runtime/Core/Compiler/ShapeInference/IRRankInferenceHelper.cs:39)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.RankInference.UpdateKnownTensorRanks (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@2.3.1-preview/Barracuda/Runtime/Core/Compiler/ShapeInference/IRRankInferenceHelper.cs:254)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.FuseShapesIntoConstants (Unity.Barracuda.Model& model, System.Collections.Generic.IDictionary`2[TKey,TValue] shapesByName, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName, System.Collections.Generic.List`1[Unity.Barracuda.Model+ImporterWarning]& warnings) (at Library/PackageCache/com.unity.barracuda@2.3.1-preview/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:72)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.Run (Unity.Barracuda.Model& model, System.Collections.Generic.List`1[T] warnings) (at Library/PackageCache/com.unity.barracuda@2.3.1-preview/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:30)
Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.3.1-preview/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:15)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@2.3.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:188)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@2.3.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:98)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@2.3.1-preview/Barracuda/Editor/ONNXModelImporter.cs:65)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <0cde216a590a4d6fbc3d7db7ac203c5d>:0)

```

</details>
Edit: forgot to mention package version: 2.3.1-preview

**Comment by AlexRibard** [comment]
Thanks, would it be possible for you to link your model via a google drive?
If not I'll try out your notebook

**Comment by Darth-Carrotpie** [comment]
Thanks for quick reply. Here you go, the drive file:
https://drive.google.com/file/d/12ftoOx-0d69sTv7A5FOJ3QaEcKC_ArPj/view?usp=sharing

**Comment by AlexRibard** [comment]
I took a look at it. There was a few issues on our end. I fixed those.
One issue remaining is with `Conv` layer `308`
At the moment we do not support convolution with number of group different from 1 or the number of input channels.
Would you be able to replace layer `308` with something else?

Let me know

**Comment by Darth-Carrotpie** [comment]
Thank you for looking into the problems and fixing some.

It's a pre-trained model made by Facebook with hundreds of hours of heavy lifter GPUs on the job... not really an option to recreate and retrain with the measly resources and understanding of the process that I have :(
Even in the previous version of wav2vec they trained on eight V100 cards, for a 1k epochs. This is huge to say the least.

**Comment by AlexRibard** [comment]
I understand. 
I've added Conv group support to the backlog, I'll let you know as soon as it lands.
(closing thread for now, feel free to comment on the thread if you have additional questions)

**Comment by Darth-Carrotpie** [comment]
Hey,
Something must have been updated: I've tried the same model in 2.4-Preview and the group feature error is gone, but now there's a different error:
<details><summary>Cannot reshape array of size</summary>
Unexpected error while evaluating model output Y. System.ArgumentException: Cannot reshape array of size 4621824 into shape (n:1, h:512, w:45140, c:1)
  at Unity.Barracuda.TensorExtensions.Reshape (Unity.Barracuda.TensorShape shape, System.Int32[] size4Dor8D) [0x0019e] in C:\Users\carro\Documents\Unity Projects\VRoid\Library\PackageCache\com.unity.barracuda@2.4.0-preview\Barracuda\Runtime\Core\TensorExtensions.cs:579 
  at Unity.Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes, System.Collections.Generic.IDictionary`2[System.String,System.Nullable`1[Unity.Barracuda.TensorShape]]& shapesByName) [0x00de8] in C:\Users\carro\Documents\Unity Projects\VRoid\Library\PackageCache\com.unity.barracuda@2.4.0-preview\Barracuda\Runtime\Core\Backends\ModelAnalyzer.cs:432 
  at Unity.Barracuda.ModelAnalyzer.TryGetOutputTensorShape (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes, System.String output, Unity.Barracuda.TensorShape& shape) [0x00007] in C:\Users\carro\Documents\Unity Projects\VRoid\Library\PackageCache\com.unity.barracuda@2.4.0-preview\Barracuda\Runtime\Core\Backends\ModelAnalyzer.cs:630 
  at Unity.Barracuda.Editor.NNModelEditor+<>c__DisplayClass36_0.<OnEnable>b__2 (System.String i) [0x00006] in C:\Users\carro\Documents\Unity Projects\VRoid\Library\PackageCache\com.unity.barracuda@2.4.0-preview\Barracuda\Editor\ONNXModelImporterEditor.cs:233 
UnityEngine.Debug:LogError (object)
Unity.Barracuda.D:LogError (object) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/Core/Internals/Debug.cs:131)
Unity.Barracuda.Editor.NNModelEditor/<>c__DisplayClass36_0:<OnEnable>b__2 (string) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Editor/ONNXModelImporterEditor.cs:238)
System.Linq.Enumerable:ToList<string> (System.Collections.Generic.IEnumerable`1<string>)
Unity.Barracuda.Editor.NNModelEditor:OnEnable () (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Editor/ONNXModelImporterEditor.cs:228)
</details>

The error is again thrown on import.

**Comment by AlexRibard** [comment]
That's indirectly related to the group issue. We warn of unsupported attribute in the importer, but fail when doing shape inference.
Errors will go away when `group` support is added
