### ISSUE TITLE
Onnx to Barracuda Error (YOLO V3 Model)

### ISSUE THREAD

**Issue by Pouyan97** [Unity-Technologies/barracuda-release#25]
I recently trained a yolov3-tiny-1 class model to import on barracuda for detection. I was able to export the model to an ONNX file. I tried two ways to import the model into Unity.

 _1. Changing format to Barracuda with onnx_to_barracuda_
When I run: `python onnx_to_barracuda.py last.onnx last.nn --verbose True`  
I get the following error:
```
     File "barracuda-release\Tools\onnx_to_barracuda.py", line 336, in get_tensor_data
          floats = struct.unpack('<'+str(int(elems))+'f', tensor.raw_data)
struct.error: unpack requires a buffer of 20 bytes
```
The error is happening in Reshape Layer.

_2. Use ONNX import feature of Barracuda_
When I export the file into Unity I get the following error:
```
Unknown type ConstantOfShape encountered while parsing layer 53.
OnnxImportException: Unexpected error while parsing layer 54 of type Reshape.
Only tensors of rank 4 or less are supported, but got rank 5
```

Does barracuda support YOLO V3? Is there something I need to specify during training? 
SSD models are not supported on Barracuda yet so I decided using YOLO which I do not have much experience with so any guidance would be appreciated.  

Now, I can get all the errors to disappear if I check the _**Treat Errors as Warning**_ on the model but I am pretty sure that is the reason my app fails to run.

**Comment by mantasp** [comment]
Hi @Pouyan97, YOLO v3 is not supported at the moment, but YOLO v2 should work.
