### ISSUE TITLE
ONNX Conv2D Layer with Stride different to 1 not supported

### ISSUE THREAD

**Issue by ptrem** [Unity-Technologies/barracuda-release#250]
Hello guys, 
would like to use an ONNX model in Unity. The first layer is a Conv2D with Stride 4. 
I see in the object details that this is also stored in the model. However, when I run the inference, there is an error that the array size is not correct. 
It turns out that the given size is the result of a Conv2D layer with Stride 1. 
Also, there is no problem loading models that only contain Conv2D layers with Stride 1. 
The model was originally created with Tensorflow2.

Has anyone already had experience with this and can provide some help?
Or is there a better way to use TF2 Models directly with Barracuda.

Thanks
<img width="664" alt="Unbenannt" src="https://user-images.githubusercontent.com/58425593/149378586-66482c55-3f11-4b77-9135-51c47f7ff7bc.PNG">

**Comment by AlexRibard** [comment]
@ptrem strides should work! It is probably an import issue with your model.
Would it be ok if you share your models so we can take a look?

**Comment by ptrem** [comment]
@AlexRibard thanks for our fast reply.
Sure, this zip contains the model in different formats.
[small_model.zip](https://github.com/Unity-Technologies/barracuda-release/files/7864761/small_model.zip)

**Comment by Walsamer** [comment]
Hi @AlexRibard ! Is there an update about the issue? I'm facing the same problem!

**Comment by AlexRibard** [comment]
Hello, the problem lies in our importer.
We are working on making the import process less error prone.
It should address issues like this.
Might take some time to land, so I'd advise to change model.
Let us know if that is not an option and this is greatly impacting your project.
If this is the case, you can contact us via email at barracuda-support@unity3d.com

**Comment by FlorentGuinier** [comment]
Closing the issue as the problem as been explained and solution is being worked on in our internal roadmap.
