### ISSUE TITLE
Clean up issue

### ISSUE THREAD

**Issue by loeffel-io** [Unity-Technologies/barracuda-release#252]
Hello,

i am using the `barracuda-2.4` package.

As described here https://docs.unity3d.com/Packages/com.unity.barracuda@2.4/manual/MemoryManagement.html and here https://docs.unity3d.com/Packages/com.unity.barracuda@2.4/manual/TensorHandling.html i am clearing the worker and inputs onDestroy.

```csharp
                var worker = NetworkModelManager.Instance.GetNetworkModel(GroundDetector.Name).GetWorker();
                _groundDetectorDatasetInputs = _groundDetectorDataset.Inputs(_groundDetectorDataset.RawDataset());
                worker.Execute(_groundDetectorDatasetInputs);

                var output = worker.PeekOutput("output_1");
```

```csharp
        public void OnDestroy()
        {
            if (_groundDetectorDatasetInputs != null)
            {
                foreach (var key in _groundDetectorDatasetInputs.Keys)
                {
                    _groundDetectorDatasetInputs[key].Dispose();
                }

                _groundDetectorDatasetInputs.Clear();
            }

            Destroy();
        }
```

```csharp
      private void Dispose()
      {
          foreach (var keyValuePair in _networkModels)
          {
              keyValuePair.Value.GetWorker().Dispose();
          }
      }

      private void OnDestroy()
      {
          Dispose();
      }
```

Everything works as expected as long i am stop the application: 

```bash
GarbageCollector disposing of ComputeBuffer allocated in C:\Users\lucas\Documents\Unity\MTB Dirt\Library\PackageCache\com.unity.barracuda@2.4.0-preview\Barracuda\Runtime\Core\Backends\BarracudaReferenceCompute.cs at line 73. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
UnityEngine.ComputeBuffer:Finalize ()

Found unreferenced, but undisposed Tensor data which might lead to GPU resource leak: (GPU:#2143661056 (n:1, h:1, w:1, c:1) buffer: UnityEngine.ComputeBuffer created at: )
UnityEngine.Debug:LogWarning (object)
Unity.Barracuda.D:LogWarning (object) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/Core/Internals/Debug.cs:72)
Unity.Barracuda.ComputeTensorData:Finalize () (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:121)
```

as there anything i am doing wrong? 

thanks

**Comment by FlorentGuinier** [comment]
Hi Ioeffel, 

Seems to me that you are missing a call to Dispose on the worker itself. Please see:
https://docs.unity3d.com/Packages/com.unity.barracuda@2.4/manual/MemoryManagement.html

Important note: 
When calling worker.Destroy() the tensor retrieved here
`var output = worker.PeekOutput("output_1");`
will also be released/dispose. You might want to use `.CopyOutput() or .TakeOwnerShip()` depending of your use case.

Finally tensor obtained via `.PeekOutput();` are only valid until the next call to `worker.Execute()` call, if you need the data further using `.CopyOutput() or .TakeOwnerShip()` is also the solution.

Hope it helps :)
Florent

**Comment by FlorentGuinier** [comment]
I'm closing the issue as i feel the question was answered. Please reopen if needed!

**Comment by loeffel-io** [comment]
Thanks ❤️ 

The problem were undisposed inputs - made it!
