### ISSUE TITLE
OnnxImportException: Unknown type Scatter 

### ISSUE THREAD

**Issue by Fqlox** [Unity-Technologies/barracuda-release#256]
Hi, I tried to add an onnx export of a pix2pix model from [this project](https://github.com/NVIDIA/pix2pixHD) and when I import it into unity I got `OnnxImportException: Unknown type Scatter encountered while parsing layer 63.` 

How can I prevent that ?

Thanks in advance

**Info**
OS: Windows 10
Barracuda 2.0.0
Unity 2019.4.34

**Edit:**

Thanks for your answer, 
Since the issues is closed I have to say that the linked project is now outdated and no longer maintained, and work only on Unity 2018 and the creator had suggested to use [barracuda instead](https://github.com/keijiro/Pix2Pix/issues/16#issuecomment-899887271) 
Also does Barracuda not support Pix2Pix and Spade Architecture ?

**Comment by FlorentGuinier** [comment]
Hi @Fqlox, 
We do not support Scatter operator from ONNX at the moment, here is the list of our supported operator:
https://docs.unity3d.com/Packages/com.unity.barracuda@2.4/manual/SupportedOperators.html

To avoid the use of this operator you would need to change the model architecture and retrain it. Another option is to use a different pix2pix model for example from this repo: https://github.com/keijiro/Pix2Pix

PS: I'm adding support to Scatter to our backlog, I can't promise any ETA however.

Closing the question as i feel it was answered. Feel free to reopen if needed.

Have a great day!
Florent
