### ISSUE TITLE
wrong results given by Barracuda with ONNX models

### ISSUE THREAD

**Issue by fangxm233** [Unity-Technologies/barracuda-release#259]
Barracuda 2.4.0-preview
Unity 2021.1.1f1c1
Hello, I try to export my model to onnx model and import it to unity.
The model looks exported and imported with params successfully: 
![image](https://user-images.githubusercontent.com/30077393/152736532-42603819-b792-4df0-a5ea-f8c1c61ea69e.png)

And I tried to execute the model as the code below:
```
RenderTexture inputRT = RenderTexture.GetTemporary(256, 256, 0, RenderTextureFormat.ARGB32, RenderTextureReadWrite.sRGB);
Graphics.Blit(OutputTexRGB, inputRT);

Tensor input = new Tensor(inputRT, 4);
Dictionary<string, Tensor> temp = new Dictionary<string, Tensor> {{"RGBD", input}};
Worker.Execute(temp);
Tensor o = Worker.PeekOutput();
RenderTexture outputRT = RenderTexture.GetTemporary(256, 256, 0, RenderTextureFormat.ARGB32, RenderTextureReadWrite.sRGB);
o.ToRenderTexture(outputRT);

RenderTexture scaleUp = RenderTexture.GetTemporary(Width, Height, 0, RenderTextureFormat.ARGB32, RenderTextureReadWrite.sRGB);
Graphics.Blit(outputRT, scaleUp);
```

I expect that the black area of the image should be filled as I got in PyTorch:
![3527](https://user-images.githubusercontent.com/30077393/152738574-2ea50d38-2d5b-4fbc-addf-babab2f57228.png)

But I got in unity:
![111](https://user-images.githubusercontent.com/30077393/152739151-686cbc95-1287-4e18-aa47-683d682c77b9.png)

I wonder where the problem comes from, is there any other problem with the model and Barracuda?

**Comment by Aurimasp** [comment]
Hi @fangxm233 , you should compare both input and output numerical values to see if the issue lies in the data processing or Barracuda.

**Comment by Aurimasp** [comment]
We can take a deeper look at the neural net model if you could share it with us.

**Comment by fangxm233** [comment]
Thanks for the fast reply! I have already solved the problem. Thanks a lot.
