### ISSUE TITLE
OnnxImportException: Unknown type ScatterND encountered while parsing layer 316.

### ISSUE THREAD

**Issue by kirin111697** [Unity-Technologies/barracuda-release#261]
Hi, I am currently using ml-agents 2.0.0.
I encounter this exception when importing my custom trained yolov3 tiny onnx model into Unity.
OnnxImportException: Unknown type ScatterND encountered while parsing layer 316.
I converted the onnx file from a .pth file.
How can I solve this?

**Comment by FlorentGuinier** [comment]
> OnnxImportException: Unknown type ScatterND encountered while parsing layer 316.

Have you tried to update to latest 2.4.0 ?

**Comment by kirin111697** [comment]
No, I haven't. I am using unity 2020.3 and unity said it can't find the package when I add "com.unity.barracuda": "2.4.0" to the manifest.json. I did try to update the ml-agents package to 2.0.1 which supports barracuda 2.3.1 I believe, and it's still not working.

**Comment by kirin111697** [comment]
I clone the 2.4.0 repository and installed that version. Now the error changed to this:

Asset import failed, "Assets/Model/CustomYolov3Tiny.onnx" > AssertionException: Assertion failure. Value was False
Expected: True
<img width="1249" alt="Screenshot 2022-02-21 143247" src="https://user-images.githubusercontent.com/17411461/155016509-f3df27ee-3f9a-405b-9441-73ed095d2173.png">

**Comment by FlorentGuinier** [comment]
Thanks for the test, the new problem is in the internal of Barracuda where we are missing genericity. We are currently focusing deeply in improving Barracuda extendibility however this will take time and we don't have an ETA. For now the workaround would thus be to modify the model architecture. Here you can find an example of yolov3tiny in Barracuda: https://github.com/Unity-Technologies/barracuda-starter-kit.

I'm closing the issue as i feel the problem as been explained and the solution is currently work in progress in our internal roadmap.

**Comment by kirin111697** [comment]
Can you gave me a direction about how should I change the architecture of the model?
I tried the pre-trained yolov3Tiny model from the starter kit and it works, that's why I am using the yolov3Tiny architecture for my own data set training.
I am a bit confused why my model doesn't work but the pre-trained one does.
I attached the .cfg file I used for the training.
Or is it because how I convert it from pth to onnx format?
If you could give my some direction about what to change, that would be great. 
[yolo-obj.zip](https://github.com/Unity-Technologies/barracuda-release/files/8111750/yolo-obj.zip)

**Comment by FlorentGuinier** [comment]
> Can you gave me a direction about how should I change the architecture of the model?

here is the list of supported operator as of Barracuda 2.4.0 
https://docs.unity3d.com/Packages/com.unity.barracuda@2.4/manual/SupportedOperators.html

With our current importing technology it is safer to rely on rank 4 or 2 tensors also static dimensions should be preferred, finally the best is probably to look at the difference in the model and experiment based on that.

**Comment by kirin111697** [comment]
> > Can you gave me a direction about how should I change the architecture of the model?
> 
> here is the list of supported operator as of Barracuda 2.4.0 https://docs.unity3d.com/Packages/com.unity.barracuda@2.4/manual/SupportedOperators.html
> 
> With our current importing technology it is safer to rely on rank 4 or 2 tensors also static dimensions should be preferred, finally the best is probably to look at the difference in the model and experiment based on that.

Thank you for the reply. I will try it out.
