### ISSUE TITLE
Could not read tensor data for constant tensor

### ISSUE THREAD

**Issue by rmib200** [Unity-Technologies/barracuda-release#262]
OnnxLayerImportException: Could not read tensor data for constant tensor.
Unity.Barracuda.ONNXTensor..ctor (Onnx.TensorProto onnxTensor) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Editor/ONNXTensor.cs:163)
Unity.Barracuda.ONNXModelImporter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Editor/ONNXModelImporter.cs:1057)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Editor/ONNXModelImporter.cs:1005)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <af1a2f671a98418f910899d70a717c00>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

I'm using the Barracuda version inside ML-Agents v1.0.8

I've done the model on Scikit-learn and exported with skl2onnx

The model is compressed here: 
[knn_test.zip](https://github.com/Unity-Technologies/barracuda-release/files/8113341/knn_test.zip)

I don't know what else to do. I been with this for a week :(
I would really appreciate any help at this point.

**Comment by FlorentGuinier** [comment]
Hi @rmib200 , 

The model contain onnx nodes of type `ArrayFeatureExtractor `and `ZipMap`, Witch we don't support at the moment. Here is the list of [supported operator for Barracuda 2.4.0](https://docs.unity3d.com/Packages/com.unity.barracuda@2.4/manual/SupportedOperators.html).

Thanks you for the feedback, Scikit-learn + skl2onnx seems to be gaining a lot of interrest and traction lately in the community, we will definitively consider looking into this.

I'm closing the issue as i feel it was answered.
