### ISSUE TITLE
Error when exporting my ONNX model

### ISSUE THREAD

**Issue by karen-velasquez** [Unity-Technologies/barracuda-release#264]
hello, not long ago I've been using Unity, I created an ONNX model to read it with Barracuda but I get the following errors when importing my model:

OnnxImportException: Unknown type Scan encountered while parsing layer UU002UU.
Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@956eb962af/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:3394)
 
and the error:

Asset import failed, "Assets/Karen/Models/knn_test 1.onnx" > OnnxImportException: Unknown type Scan encountered while parsing layer UU002UU.
Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@956eb962af/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:3394)

I think the error is found when I create the model but I'm not sure:
If you could give me any help I would appreciate it.
With this code create my ONNX:

import pandas as pd
path='https://raw.githubusercontent.com/iannjari/datasets/main/diabetes.csv'
df=pd.read_csv(path,engine='python')

target_name = "Outcome"
target = df[target_name]
data = df.drop(columns=[target_name])

# Train a model.
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
X_train, X_test, y_train, y_test = train_test_split(data,target, test_size=0.30, random_state=42)
knn = KNeighborsClassifier(n_neighbors = 1)
# Fit the classifier to the data
knn.fit(X_train,y_train)
print(knn.score(X_test, y_test))

# Convert into ONNX format
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
initial_type = [('float_input', FloatTensorType([None, 8]))]
onx = convert_sklearn(knn, initial_types=initial_type)
with open("/content/drive/MyDrive/Colab Notebooks/model/knn_test.onnx", "wb") as f:
    f.write(onx.SerializeToString())

# Compute the prediction with ONNX Runtime
import onnxruntime as rt
import numpy
sess = rt.InferenceSession("/content/drive/MyDrive/Colab Notebooks/model/knn_test.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
print(type(X_test))
X_test_numpy=X_test.to_numpy()
print(X_test_numpy)
pred_onx = sess.run([label_name], {input_name: X_test_numpy.astype(numpy.float32)})[0]
print(pred_onx)

**Comment by AlexRibard** [comment]
`OnnxImportException: Unknown type Scan encountered while parsing layer UU002UU.`
Layer of name UU002UU is a Scan operator. Which we don't support at the moment unfortunately.

We currently don't have plans of adding support to this operator, unless it becomes something extensively used across the user base.
Closing for now, will comment if we decide to add support to it.
