### ISSUE TITLE
Crepe Pitch Detection Model in Unity

### ISSUE THREAD

**Issue by ptrem** [Unity-Technologies/barracuda-release#265]
Hello guys,
I try to use the [Crepe](https://github.com/marl/crepe) Pitch detection model within a an application coded with unity.
I'm struggeling with some issues explained in this [post](https://github.com/Unity-Technologies/barracuda-release/issues/250). 
Is there any possibility to get this model into a unity compatible format?
Or are there alternative approaches workaround? For example call an external python, java, c++ programm to run the model inference and hand over the result. For example with tflite model etc.

Thanks for in advance

**Comment by Aurimasp** [comment]
Hi, sadly at the moment there is no workaround from the Barracuda side, but we are addressing issues like this issue in our future refactor.
