### ISSUE TITLE
NCHW model usage

### ISSUE THREAD

**Issue by kdziedzic66** [Unity-Technologies/barracuda-release#266]
Hello,

We are trying to use the model exported from pytorch. The format of input (and therefore the way of onnx export) in the framework is Batch x Channels x Hight x Width, while it looks like the importer of the model in Barracuda expects us to have Batch x Height x Width x Channels format (screenshot from the model inspection in Barracuda attached).

Is there a convenient way in which we can import correctly a model in the pytorch's input format ? 

If it would be helpful our model can be downloaded from https://drive.google.com/file/d/1cI1f0F2wiLvvf-l1YlrDIMuqGMUZcmX9/view?usp=sharing
![gaugan_unity](https://user-images.githubusercontent.com/12718383/156177629-7ac29207-d305-490c-8369-6fca6a331d73.PNG)

**Comment by Aurimasp** [comment]
Hey, at the moment we don't have a convenient way to do that, but we are working on a refactor, in which we are addressing this issue.

**Comment by Aurimasp** [comment]
There is also a possible workaround. You can add a Transpose layer at the beginning of the model using the Model Builder.
