### ISSUE TITLE
RobustVideoMatting with Barracuda

### ISSUE THREAD

**Issue by leavittx** [Unity-Technologies/barracuda-release#269]
I've just filled a Unity bug report on that (CASE 1411678).
Just posting that info here, so it's not accidentally missed.
Thank you, hope it's something you can look into!

**Comment by Aurimasp** [comment]
Hey, thanks for the report. Link to track the status of this issue: 
https://issuetracker.unity3d.com/product/unity/issues/guid/BAR-258
