### ISSUE TITLE
Only tensors of rank 4 or less are supported, but got rank 5

### ISSUE THREAD

**Issue by damonbla** [Unity-Technologies/barracuda-release#27]
Hi, I'm fairly new to all of this, so hopefully I can explain this in a way that will make sense.

I'm using PyTorch 1.0.0 and managed to perform transfer learning on a pretrained ResNet18 model. It works great in the Python code I've written, but now I'm trying to bring it into Unity. I used PyTorch's built-in ONNX exporter (https://pytorch.org/docs/stable/onnx.html?highlight=onnx#module-torch.onnx) to create an onnx file of the model. I know this exporter does work, because when I tried it on a very simple model I created from scratch it imported fine.

When I bring the pretrained model into Unity, I get this:
OnnxImportException: Unexpected error while parsing layer 194 of type Unsqueeze.
Only tensors of rank 4 or less are supported, but got rank 5

This must be because the pretrained ResNet18 model uses rank 5 tensors, though I'm not even sure of that. I can't seem to find any information about that in the PyTorch docs. I'm not sure if there's any way to convert them to rank 4 in the python code so they'll work with Barracuda. It's possible I'm asking in the wrong place, and I should be going to PyTorch's Issue queue, but I'm hoping someone here will have more experience with this kind of thing. 

Maybe I should try one of the other pretrained models that comes with PyTorch? Does anyone know if there is a good one out there that already uses rank 4 tensors? Am I even on the right planet?

**Comment by mantasp** [comment]
Any chance you could share your ONNX file?

**Comment by damonbla** [comment]
I just tried uploading it and it did not work - the file was too large (40 MB). I'll put it here temporarily: http://www.damoweb.com/random/bracket_transfer_training.onnx

In the meantime today I've tried the same thing but with an Inception_v3 pretrained model instead of ResNet, and ended up with a different error that is possibly easier to resolve:

OnnxImportException: Unexpected error while parsing layer 587 of type Constant.
Tensor data type Double is not supported.

Maybe that one's easier to work around, but I'm not sure. Thank you for the help!

**Comment by damonbla** [comment]
Working on this during the day today I've found that the same error with rank size occurs with not just the ResNet pretrained model through PyTorch, but also DenseNet and SqueezeNet. For reference, the full list of models is here: https://pytorch.org/docs/stable/torchvision/models.html

FYI I've also updated my PyTorch version to 1.3.1, so I can confirm just updating pytorch doesn't change anything (didn't really think it would, but it's good to know!).

If there's any way around this I'd love to know. Is there a particular reason Barracuda limits the tensor rank to 4? I'm not sure whether to keep trying other models until I find one that imports or do some work on the Barracuda source to try and increase the limit.

**Comment by tim-jagenberg-ws** [comment]
We're seeing the similar problems on a ResNet based model. Is there a work-around or can we help fixing this in Barracuda?
`Unexpected error while parsing layer 1051 of type Unsqueeze.
Only tensors of rank 4 or less are supported, but got rank 5`
`Unexpected error while parsing layer 257 of type Reshape.
Unsupported combination of tensor layout NCHW and tensor rank 6`

**Comment by damonftl** [comment]
If there is a workaround I have not figured it out yet, though I haven't worked too much on this for the last few weeks. Eventually I'll be trying it out with an object detection model like FasterRCNN, and I can post when I give it a try.

**Comment by AlexRibard** [comment]
@damonbla Double type support was added in v0.7
@damonbla  and @tim-jagenberg-ws Barracuda only supports Tensor of rank <= 4 atm. There are plans to support higher ranks, but it will take some time to land.

Looking at Resnet50 example I do not see the reason to use tensors of rank 5. 
For the example @damonbla gave, the problem is here:
![image](https://user-images.githubusercontent.com/12990800/80494435-a6534080-8934-11ea-9297-d478b945da50.png)
What pytroch is being used at the end? Can you replace it with a AveragePool and a different size Gemm?
![image](https://user-images.githubusercontent.com/12990800/80494523-bcf99780-8934-11ea-9b53-0b8c03af85cc.png) like so?

Let me know!

**Comment by tim-jagenberg-ws** [comment]
@mantasp @AlexRibard could we share our model privately with you to get an idea of how far from barracuda-runnable we currently are? We'd also be interested in a better understanding of the current roadmap.

**Comment by mantasp** [comment]
@tim-jagenberg-ws you can send me private link to mantas [x] unity3d. com.

**Comment by bbico** [comment]
Same here

**Comment by yog-strina** [comment]
Hello, I'm having a similar issue with a U-net and transfer learning on a resnet34. The model is exported to ONNX format perfectly but when imported in Unity I have the following error:

```OnnxImportException: Unexpected error while parsing layer 409 of type Reshape.
Only tensors of rank 4 or less are supported, but got rank 6

Json: { "input": [ "407", "408" ], "output": [ "409" ], "opType": "Reshape" }
  at Unity.Barracuda.ONNXLayout.AxisPermutationsForMappingONNXLayoutToBarracuda (System.Int32 onnxRank, System.String onnxLayout) [0x00028] in C:\Users\Quentin\Desktop\Inference Module\Library\PackageCache\com.unity.barracuda@1.0.1\Barracuda\Editor\ONNXLayout.cs:44 
  at Unity.Barracuda.ONNXLayout.PermuteToBarracuda (System.Int64[] shape, System.String onnxLayout) [0x00005] in C:\Users\Quentin\Desktop\Inference Module\Library\PackageCache\com.unity.barracuda@1.0.1\Barracuda\Editor\ONNXLayout.cs:158 
  at Unity.Barracuda.ONNXLayout.ConvertSymbolicShapeToBarracuda (System.Int64[] onnxShape, System.String onnxLayout) [0x00001] in C:\Users\Quentin\Desktop\Inference Module\Library\PackageCache\com.unity.barracuda@1.0.1\Barracuda\Editor\ONNXLayout.cs:223 
  at Unity.Barracuda.ONNXModelImporter.<.ctor>b__14_1 (Unity.Barracuda.ModelBuilder net, Unity.Barracuda.ONNXNodeWrapper node) [0x000dd] in C:\Users\Quentin\Desktop\Inference Module\Library\PackageCache\com.unity.barracuda@1.0.1\Barracuda\Editor\ONNXModelImporter.cs:105 
  at Unity.Barracuda.ONNXModelImporter.ConvertOnnxModel (Onnx.ModelProto onnxModel) [0x00367] in C:\Users\Quentin\Desktop\Inference Module\Library\PackageCache\com.unity.barracuda@1.0.1\Barracuda\Editor\ONNXModelImporter.cs:1088 

Unity.Barracuda.ONNXModelImporter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.0.1/Barracuda/Editor/ONNXModelImporter.cs:1404)
Unity.Barracuda.ONNXModelImporter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.0.1/Barracuda/Editor/ONNXModelImporter.cs:1097)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.0.1/Barracuda/Editor/ONNXModelImporter.cs:1005)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <af78ad00a40d4f61b82afc6cafb0a416>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
``` 

Has anyone solved their issue about this yet ?

**Comment by mantasp** [comment]
Latest Barracuda 1.2.0-preview now has support for more than 4 dimensions, some of the importing problems above should be gone. Please feel free to open new issue if you still run into issues.

**Comment by ihabkh** [comment]
Hello, I'm having a similar problem with ResNet, Could you please advice @mantasp @AlexRibard? I'm using Barracuda 1.2.1

You can find the model here: https://www.dropbox.com/s/amad4ko9opi4kts/hyb_net_weights.model
Reference: https://github.com/karoly-hars/DE_resnet_unet_hyb

```
Asset import failed, "Assets/TrainedModels/resnet_unet_hybrid_specific_input.onnx" > OnnxImportException: Unexpected error while parsing layer 660 of type Unsqueeze.
Unsqueeze leading to tensor of rank >= 4, Not supported

Json: { "input": [ "642" ], "output": [ "660" ], "name": "Unsqueeze_138", "opType": "Unsqueeze", "attribute": [ { "name": "axes", "ints": [ "3" ], "type": "INTS" } ] }
  at Unity.Barracuda.ONNX.ONNXLayout.UnSqueezeAxisPermutationForMappingONNXLayoutToBarracuda (System.Int32 onnxRank, System.Int32 onnxAxis, System.String onnxLayout) [0x00156] in /home/ihab/unity/helloword/Assets/barracuda-release-1.2.1-preview/Barracuda/Runtime/ONNX/ONNXLayout.cs:446 
  at Unity.Barracuda.ONNX.ONNXModelConverter+<>c__DisplayClass17_0.<.ctor>b__5 (Unity.Barracuda.ModelBuilder net, Unity.Barracuda.ONNX.ONNXNodeWrapper node) [0x00090] in /home/ihab/unity/helloword/Assets/barracuda-release-1.2.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:319 
  at Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) [0x00360] in /home/ihab/unity/helloword/Assets/barracuda-release-1.2.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1629 

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Assets/barracuda-release-1.2.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2100)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Assets/barracuda-release-1.2.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1638)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Assets/barracuda-release-1.2.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:89)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Assets/barracuda-release-1.2.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:67)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Assets/barracuda-release-1.2.1-preview/Barracuda/Editor/ONNXModelImporter.cs:59)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at /home/bokken/buildslave/unity/build/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:22)
```

**Comment by AlexRibard** [comment]
@ihabkh can you provide the onnx model?

**Comment by ihabkh** [comment]
Hi,
Here is the onnx model: https://www.dropbox.com/s/jhxx2kn6k9fcmyv/resnet_unet_hybrid_specific_input.zip?dl=0

**Comment by AlexRibard** [comment]
Thanks a lot! I will look at it

**Comment by AlexRibard** [comment]
Ok, I fixed in latest. It'll come out in the upcoming release

**Comment by ihabkh** [comment]
Thanks a lot @AlexRibard 
Could you please share the fix so we don't have to wait long? Thanks for the understanding

**Comment by AlexRibard** [comment]
@ihabkh unfortunately I cannot for this as it involves quite some files...

**Comment by GunLengend** [comment]
I got the same issue, I'm looking for solution

**Comment by AlexRibard** [comment]
@GunLengend can you share your model so I can test on latest?

**Comment by romygt** [comment]
I got the same issue, I'm looking for solution
