### ISSUE TITLE
Problem about the support to torch.nn.GroupNormal

### ISSUE THREAD

**Issue by CLiMalik** [Unity-Technologies/barracuda-release#273]
Hi all,

Recently, I have exported a torch.nn.GroupNormalization layer to a onnx file. As a result, this file includes Aten type. An error occured when I tried to import this onnx file into a Unity project. The error is posted below:

OnnxImportException: Unknown type ATen encountered while parsing layer 27.
Asset import failed, "Assets/NN/example.onnx" > OnnxImportException: Unknown type ATen encountered while parsing layer 27.

Is there any possible method to import a neural network including GroupNormalization layer into unity projects?

Thanks.
Chen

**Comment by CLiMalik** [comment]
The previous problem seems to be fixed. I just updated my PyTorch to 1.11.0 and the torch.nn.GroupNorm was supported by an op in onnx called InstanceNormalization. However, another problem occurs when I imported the new model into Unity. 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/103299050/163115129-a511557f-5c97-4871-8719-bfcdfe592a09.png">
You can find the model here: https://drive.google.com/file/d/10rSZHetlZ6arR2AezX2JVu0bL7Emgn1n/view?usp=sharing

**Comment by Aurimasp** [comment]
Hi CLiMalik, do the outputs differ between PyTorch and Barracuda? Barracuda points out these shapes as unusual, but if it returns expected outputs, then you can ignore these warnings. I will close this issue but feel free to reopen it if model outputs do not match.

**Comment by EmileGr** [comment]
@Aurimasp Those warnings aren't necessarily harmless. In my case I have a model that was converted from Pytorch that also uses torch.nn.GroupNormal and it throws errors when trying to use it during runtime. The runtime error seems to correlate with the warnings.
![image - Copy](https://user-images.githubusercontent.com/49959029/167638664-31578832-4ed6-4d2c-b895-ea324942dff2.png)
![image - Copy (2)](https://user-images.githubusercontent.com/49959029/167639112-695b9fff-99a2-4642-a839-245b4d35837b.png)

**Comment by Aurimasp** [comment]
Hi @EmileGr ,  would it be possible to share this model with us?
