### ISSUE TITLE
[CRASH] Cannot dispose/release ComputeBuffer when move to other scene after using Barracuda

### ISSUE THREAD

**Issue by CanvasVu** [Unity-Technologies/barracuda-release#274]
I'm using a project on Github link: https://github.com/wojciechp6/YOLO-UnityBarracuda,
This project using Barracuda (version 0.7.0) combine with YOLOv2 Tiny to make object detection app,
Everything okay but when I move to other scene, ComputeBuffer cannot disposed (see attached log image).
When on UnityEditor that will be okay (can move to other scene) but in built app, it's will crash. (I tried Barracuda version 0.7.0 to 1.4.0 but same issue)

My dispose code:
![image](https://user-images.githubusercontent.com/87170649/162897646-ab2c4386-4d22-4107-8ae6-51dfb8576612.png)
(see more in attached file)
[YOLOHandler.txt](https://github.com/Unity-Technologies/barracuda-release/files/8470194/YOLOHandler.txt)

※Question:
How can I dispose/release undisposed ComputeBuffer or some another way to make built app not crash when move to other scene after using Barracuda?
Note: In development build mode, built app will not crash when move to another scene.

Thanks for reading.

![image](https://user-images.githubusercontent.com/87170649/162896884-16d4c382-515a-44af-97f7-553b7ab3f829.png)

**Comment by CanvasVu** [comment]
Fixed!
Change to below code:

![image](https://user-images.githubusercontent.com/87170649/162932677-5dbbba33-4470-424f-b574-0ac7fc12b1ec.png)

**Comment by paTRICK-swk** [comment]
My life saver!
