### ISSUE TITLE
 InferOutputRank.*Conv2D* inputRanks Assertion failure. Value was False

### ISSUE THREAD

**Issue by BaMarcy** [Unity-Technologies/barracuda-release#275]
Hi, I am having trouble with using Silero VAD .onnx file in my Unity3D project. Cannot really import the model itself:

**_AssertionException: InferOutputRank.*Conv2D* inputRanks Assertion failure. Value was False_**

Could you help me? Thanks in advance!

**Comment by Arminasss** [comment]
Hello!

Thank you for reaching out! We successfully recreated this issue and filled the bug report. You can check the status using this link: https://issuetracker.unity3d.com/product/unity/issues/guid/1423375 (link will become reachable after an hour)

Thanks for making Unity better!
