### ISSUE TITLE
Support 'dilation' operation?

### ISSUE THREAD

**Issue by DanielDorDev** [Unity-Technologies/barracuda-release#28]
I am getting unsupported attribute dilations of type conv, when importing onnx

*Edit*

I changed the the layer, and the problem is dilation = 2?
what could be the problem? 
if set this value the attribute unsupported and set to default 1

thank you :)

**Comment by abigos** [comment]
I'd also like to request support for dilation (for values of greater than 1).  Our application is for image inpainting (see for example https://arxiv.org/abs/1801.07892).

**Comment by AlexRibard** [comment]
Hi!
Unfortunately, dilatation is not currently supported in 0.7 version.
It is something we could add.
Looking at it (https://arxiv.org/pdf/1603.07285.pdf) it seems that there exists a workaround.
You can dilate the kernel manually and add zeros in the intermediate rows/columns (cf picture and example)
![image](https://user-images.githubusercontent.com/12990800/80492411-f7ae0080-8931-11ea-9c9a-14c08cdfa15d.png)

Let me know if that helps

**Comment by abigos** [comment]
Hi Alex,

Thanks for the update and the link.  Although a workaround is possible I'm concerned that the performance hit will be very large as this is a fundamental operation in the models that use it.  The dilation factor is typically a parameter to conv2d as it's so tightly coupled to the basic convolution operation and would need to be implemented efficiently on the GPU to get good performance.
 
We would certainly appreciate if you could consider supporting dilation for a future update after 0.7.  Thanks again for your consideration.

**Comment by AlexRibard** [comment]
I would tend to agree also. 
We will add it to the roadmap and let you know when it is implemented.

**Comment by abigos** [comment]
Thanks Alex, that's great news.

**Comment by AlexRibard** [comment]
fixed in 0.8.0
