### ISSUE TITLE
Is Barracuda on the HoloLense suppoted?

### ISSUE THREAD

**Issue by KnuniK** [Unity-Technologies/barracuda-release#280]
When I add barracuda and MRTK to a project, switch the platform to UWP and compile I get the error:

`Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'`

I have done nothing else in the project.

Should barracuda work on UWP/hololense ?

**Comment by Arminasss** [comment]
Hi!

Barracuda is supported on UWP, although there are currently some issues with the Burst package (which Barracuda uses as a dependency) and UWP. We are planning to upgrade the Burst version to avoid this error in the future. You can check the status here: https://issuetracker.unity3d.com/issues/barracuda-mono-dot-cecil-dot-assemblyresolution-exception-is-thrown-when-building-the-player-to-uwp-platform-1

For now, you can try to disable the Burst Compiler (Jobs > Burst > Enable Compilation) that should force the Barracuda package to fall back to the regular CPU backend, but it will come at a cost of a big performance drop.

That said if you have any additional questions feel free to reply!
