### ISSUE TITLE
Exception: Must have input rank for onnx::Reshape_162 in order to convert Reshape to NHWC

### ISSUE THREAD

**Issue by eric9687** [Unity-Technologies/barracuda-release#283]
Hi.
Please let me know how to deal with this error below. 
"Exception: Must have input rank for onnx::Reshape_162 in order to convert Reshape to NHWC."

the Input size of my model is (batsch_size, 36, 64), and I read that Barracuda can support 2D.

you can download the onnx file If you need.
Thanks.
[b2h_zpt.zip](https://github.com/Unity-Technologies/barracuda-release/files/8868488/b2h_zpt.zip)

**Comment by Arminasss** [comment]
Hello!

Thank you for reporting this issue, we successfully reproduced it. You can check the status here: https://issuetracker.unity3d.com/product/unity/issues/guid/BAR-293'

Cheers!
Arminas M.
Customer QA Team
