### ISSUE TITLE
Barracuda do not support 'group convolution' operation.

### ISSUE THREAD

**Issue by shyu92** [Unity-Technologies/barracuda-release#284]
I tried to infer RegNet which uses group convolution, but unity raise error that number of group should be same as number of input channels.

so, I found that barracuda supports convolution operation only depthwiseConv2d and Conv2d.

Do you have any plan for support group convolution ?
or
Would you mind implementing group convolution ?

**Comment by Arminasss** [comment]
Hello @shyu92, we will look into it!
I couldn't find a RegNet onnx model for repro purposes, could you attach it here?

**Comment by shyu92** [comment]
[RegNetY-200MF.zip](https://github.com/Unity-Technologies/barracuda-release/files/9044797/RegNetY-200MF.zip)

Hello, thanks for your reply
Here is RegNetY-200MF model onnx file !

**Comment by Arminasss** [comment]
Hello!

Sorry for taking a bit longer to reply. At the moment Barracuda only support groups that are equal to the number of input channels, or equal to 1. We have plans to support non-equal groups in future releases, but for now, it is kept at a lower priority, unfortunately. Hope that answers your question.

Best Regards!
Arminas
