### ISSUE TITLE
About data preprocessing for input tensor

### ISSUE THREAD

**Issue by guoguoguilai** [Unity-Technologies/barracuda-release#29]
I came from opencvforunity.  Is there any way to do data preprocessing in barracuda like this:
dnn.blobFromImage(Mat image, double scalefactor, Size size, Scalar mean, bool swapRB, bool crop)

**Comment by AlexRibard** [comment]
There is unfortunately no single function which would allow you to do all of that in one call.
There is however a few ways to implement it:
* Custom Compute Shader
You pass it your input texture, constants and you do the math in the kernel and save the result to another texture.
* Pixel Shader, same thing but then you blit the output to a texture.
=> for both you then create a Tensor from the resulting texture.
* You can use the ModelBuidler and construct a model which implements it.
(ScaleBias, Resize, Transpose channels)

I would personally recommend doing the data processing with a custom compute shader as this gives you the most flexibility in the processing you wish to do.

**Comment by guoguoguilai** [comment]
> There is unfortunately no single function which would allow you to do all of that in one call.
> There is however a few ways to implement it:
> 
> * Custom Compute Shader
>   You pass it your input texture, constants and you do the math in the kernel and save the result to another texture.
> * Pixel Shader, same thing but then you blit the output to a texture.
>   => for both you then create a Tensor from the resulting texture.
> * You can use the ModelBuidler and construct a model which implements it.
>   (ScaleBias, Resize, Transpose channels)
> 
> I would personally recommend doing the data processing with a custom compute shader as this gives you the most flexibility in the processing you wish to do.

Thank for your answer. For running in Andriod and iOS, which one is the most recommended ?

**Comment by AlexRibard** [comment]
If you are targeting recent mobile versions, I would go for the Compute Shader.
It has slightly less overhead to using the PixelShader and blitting.
Older versions do not support compute shaders however.
But this raises more issue as Barracuda Compute path will not work for them. So in that case a CPU path is mandatory.

**Comment by guoguoguilai** [comment]
> If you are targeting recent mobile versions, I would go for the Compute Shader.
> It has slightly less overhead to using the PixelShader and blitting.
> Older versions do not support compute shaders however.
> But this raises more issue as Barracuda Compute path will not work for them. So in that case a CPU path is mandatory.

Thank you!
