### ISSUE TITLE
Barracuda 4.0+ (Unity Sentis)

### ISSUE THREAD

**Issue by Aurimasp** [Unity-Technologies/barracuda-release#294]
We have stopped working on the Barracuda package but are continuing it’s mission with the Sentis package, which is in a closed beta phase and we plan to release later this year. Refer to the [Sentis documentation](https://docs.unity3d.com/Packages/com.unity.sentis@1.0) for more technical details, and [see our AI announcement](https://blog.unity.com/engine-platform/introducing-unity-muse-and-unity-sentis-ai) for more information. You can [sign up for the closed beta here.](https://create.unity.com/ai-beta)

**Comment by PieceByPieceDevelopment** [comment]
Is there any update to this?

**Comment by srcnalt** [comment]
Hi folks, after about 2 years, how close do you think we are to using Barracuda 4.0? Or is it abandoned? Version 3.0 is missing quite many new features and it makes it hard to convert new models into onnx due to unknown functions.

**Comment by OmarVector** [comment]
it has been one year now, Is there any updates regard that?

**Comment by Aurimasp** [comment]
Hey, it is: https://forum.unity.com/threads/unity-sentis.1454530/
