### ISSUE TITLE
multiple precompiled assemblies with the same name google.protobuf.dll included on the current platform

### ISSUE THREAD

**Issue by KornilovaK** [Unity-Technologies/barracuda-release#295]
Hello. I have unity project which contains custom package. Then I want to include ml agents stuff. So well, when I install it, barracuda automatically do the same (that's what I need). And I receive the error 
```
Multiple precompiled assemblies with the same name Google.Protobuf.dll included on the current platform.
Only one assembly with the same name is allowed per platform.
```
because of conflict of included google.protobuf.dll both in the custom package and barracuda.

How can I resolve it?
I tried deleting dll file from:
- custom package. It resulted the errors related with other dependences
- barracuda package. The dll file was reinstalled by itself.

Thanks in advance!

**Comment by stellacheng21** [comment]
I have the same question, can u please tell me how to solve this problem? Thanks a lot!!
