### ISSUE TITLE
Object detection from ONNX Model Zoo not working

### ISSUE THREAD

**Issue by d-lay** [Unity-Technologies/barracuda-release#30]
Hi, I want to realize an object detection in Unity. For this I tested all object detectors in the ONNX Model Zoo. But only 2 out of 9 could be imported by the ONNXModelImporter without error messages (DUC and Tiny Yolo V2). So what I actually wanted to know is:

1.  Is Barracuda meant to be used for Object Detection?

2. And if so, can it be optimized for mobile, to achieve similar inference times the same model would achieve as an optimized .tflite version?

3. Where can I read up on which restrictions my model would be able to be run in Baracuda? I assume the listed error messages are not just result of additional unsupported operations.

Here are the summarized error messages of the failed imports: 

Asset import failed, "Assets/Model/yolov2_coco.onnx" > OnnxImportException: Unexpected error while parsing layer 204 of type Reshape. Only tensors of rank 4 or less are supported, but got rank 6

Asset import failed, "Assets/Model/yolov2.onnx" > OnnxImportException: Unknown type ImageScaler encountered while parsing layer image2.

Asset import failed, "Assets/Model/yolov3.onnx" > OnnxLayerImportException: Tensor data type Bool is not supported.

Asset import failed, "Assets/Model/mask_rcnn_R_50_FPN_1x.onnx" > OnnxImportException: Unexpected error while parsing layer 400 of type Gather. Index was outside the bounds of the array.

Asset import failed, "Assets/Model/yolov3-tiny.onnx" > OnnxLayerImportException: Tensor data type Bool is not supported.

Asset import failed, "Assets/Model/faster_rcnn_R_50_FPN_1x.onnx" > OnnxImportException: Unexpected error while parsing layer 400 of type Gather. Index was outside the bounds of the array.

Asset import failed, "Assets/Model/ssd.onnx" > OnnxImportException: Unexpected error while parsing layer Unsqueeze_344 of type Unsqueeze. Only tensors of rank 4 or less are supported, but got rank 5

Thank You in advance!

**Comment by AlexRibard** [comment]
Hi @dominiklay !
1* Yes, Barracuda can for sure be used for object detection (c.f. https://classifai.net/blog/tensorflow-onnx-unity/ and https://github.com/Syn-McJ/TFClassify-Unity-Barracuda for example)

2* Mobile optimization is something we are constantly improving and thinking of. Be sure to be on latest release and let us know if things are slower than they should be

3* For restrictions, the best is to check the official docs (https://docs.unity3d.com/Packages/com.unity.barracuda@0.3/manual/index.html)

For your error messages:
- Only Tensor of rank <= 4 are support atm
- Bool tensor type got added in 0.7

For image classification, MobileNet, Resnet and SqueezeNets are quite well supported atm.
But try to have a model with tensors of rank 4 and try to limit yourself to simple nodes or the one we list as having full support.

Hope that helps
