### ISSUE TITLE
Barakuda 4.0

### ISSUE THREAD

**Issue by dragan07-07** [Unity-Technologies/barracuda-release#301]
When will it be released barakuda 4.0?

**Comment by Arminasss** [comment]
Hello! The Barracuda 4.0 is already being tested internally. If everything goes smoothly it should be released sometime next year. It is hard to estimate the correct date of the release.

**Comment by cullenwire1** [comment]
Hi @dragan07-07, if you would like to talk to Unity directly about this please grab a [time w/ me here](https://bit.ly/unitybill). I am seeking feedback about Barracuda to inform our future plans.
