### ISSUE TITLE
Warnings: Number of elements in InstanceNorm must match the previous layer.

### ISSUE THREAD

**Issue by elephantpanda** [Unity-Technologies/barracuda-release#307]
So I tried to run this onnx file [vae_decoder.onnx](https://huggingface.co/bes-dev/stable-diffusion-v1-4-onnx/blob/main/vae_decoder.onnx)

https://huggingface.co/bes-dev/stable-diffusion-v1-4-onnx/tree/main

Just to try and see if it would work but I'm getting lots of warnings such as "Number of elements in InstanceNorm must match the previous layer." and assert fails when I try to run it.

Is there something wrong with the Normalization function? It has a "to do" note in it so perhaps it's not fully implemented?

I am using the Barracuda in the package manager of Unity.

**Comment by Aurimasp** [comment]
https://github.com/Unity-Technologies/barracuda-release/issues/308
