### ISSUE TITLE
Please can you fix the errors for these Stable Diffusion ONNX?

### ISSUE THREAD

**Issue by elephantpanda** [Unity-Technologies/barracuda-release#308]
Here are 4 onnx which don't work:

https://huggingface.co/bes-dev/stable-diffusion-v1-4-onnx/tree/main

I was especially interested in using the vae_decoder.onnx

It may be a simple fix???

But it is getting errors which I can't fix due to incompataible shape sizes. If anyone knows how to get this one working or even a way to edit the onnx file to get it working let me know! Thanks!

**Comment by Aurimasp** [comment]
Hey, we have added support for these models and it should be working in the upcoming new Barracuda version.

**Comment by elephantpanda** [comment]
Nice! You may want to check it on Stable Diffusion 2.1 by converting the it to onnx. Just to make sure! Both float32 and float16 versions. 

Any ideas when the new Baracuda will come out?

**Comment by Aurimasp** [comment]
Sometime in the second or the third quarter of the year.

**Comment by elephantpanda** [comment]
That's a long time in these days. The singularity might have happened by then.

You could try to get it to work with the new Meta LLama language model. But the smallest model is 13GB . 😯
