### ISSUE TITLE
GenericWorker NullReferenceException line 172

### ISSUE THREAD

**Issue by apiotuchAoD** [Unity-Technologies/barracuda-release#31]
NullReferenceException: Object reference not set to an instance of an object
Barracuda.GenericWorker+<ExecuteAsync>d__28.MoveNext () (at Assets/Coach-ML/Barracuda/Core/Backends/GenericWorker.cs:172)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <94c5f4c38cdc42d2b006f8badef04394>:0)

**Comment by apiotuchAoD** [comment]
my guess is m_Vars is null.

**Comment by mantasp** [comment]
@apiotuchAoD could you please post sample code on how you are invoking Barracuda?
