### ISSUE TITLE
Challenge: Make Baracuda work with Lllama

### ISSUE THREAD

**Issue by elephantpanda** [Unity-Technologies/barracuda-release#318]
If you would like to put Baracuda to an ultimate test,

why not try and see if you can [get Llama (Meta's language model) to work with it!](https://github.com/facebookresearch/llama)

The smallest is the 7B model which is about 13GB of weights!

This would be a good test of efficiency, speed, and test of working with large models.

Large language models are all the rage these days, and incorporating them with the 3D abilities of Unity would be amazing to create AI avatars.

**Comment by hayden-donnelly** [comment]
I might take on this challenge, but I'm not sure if running models directly inside of Unity is the best way to go. It seems much easier to build things like knowledge graphs and memory systems for LLMs outside the engine. Then you could have them running on a local port that some code inside the engine queries.

**Comment by AlexRibard** [comment]
I'd recommend trying out [Sentis](https://create.unity.com/ai-beta) (Barracuda refactor update).
Sentis loads and runs all sorts of LLMs no problem (modulo your hardware is good enough)
