### ISSUE TITLE
Tensorflow to Barracuda (.pb to .nn) conversion Error.

### ISSUE THREAD

**Issue by ShayanRiyaz** [Unity-Technologies/barracuda-release#32]
Hi, I am trying to convert my .pb file to a .nn version. I followed the guidelines provided by the documentation. Using the correct layers and the method suggested for loading the model to a .pb file.

However when I try to convert it using 
``` 
python tensorflow_to_barracuda.py train.pb saved_model.nn
```
I get the error:
```
Instructions for updating:
non-resource variables are not supported in the long term
Converting train.pb to saved_model.nn
Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 28, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "D:\OneDrive\Documents\CyberSens\envs\ml-agents\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py", line 1549, in convert
    i_model.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
```

I've attached my notebook below for reference.
[Model.zip](https://github.com/Unity-Technologies/barracuda-release/files/4500179/Model.zip)

**Comment by AlexRibard** [comment]
hey! could you share the .pb?
Thanks!

**Comment by ShayanRiyaz** [comment]
Hi, I was able to created newer and better model.However, I am still getting an error when I convert the tensorFlow file to barracuda but the model easily converts to an ONNX format. I am still confused how this will effect the NNModel I upload on Unity.

 I am also confused on how to provide this model an input in unity. For example a .csv file with the correct input shape. 


[random_files_tensorflow.zip](https://github.com/Unity-Technologies/barracuda-release/files/4506984/random_files_tensorflow.zip)

The documentation has not been of much help for this kind of input.

**Comment by AlexRibard** [comment]
Hi!
Ok that's great! :)
With a valid .onnx model it should be easy to get things working.
To use it in Unity, simply drop it in your Asset folder. It should appear in the viewer as a asset with custom inspector.
You then load it like so (cf example file)
[LoaderExample.txt](https://github.com/Unity-Technologies/barracuda-release/files/4507044/LoaderExample.txt)

Then just plug the .onnx model in the inspector!

Let me know if that helped :)

We will do our best to clarify the documentation!

**Comment by ShayanRiyaz** [comment]
Can you give me a little guidance, or direct me to the valid documentation, on how to make a prediction inside Unity? 

Currently I have an input of a (20,9) float values saved as a .csv file. I'm trying to pass that csv file through my model in order to make a prediction. The csv file would be saved in the assets folder before the model is called.

Any help would be very much appreciated.

**Comment by AlexRibard** [comment]
https://github.com/Syn-McJ/TFClassify-Unity-Barracuda
https://classifai.net/blog/tensorflow-onnx-unity/
Are good tutorials.

I also made you a simple example illustrating your example.
[Inference Example.zip](https://github.com/Unity-Technologies/barracuda-release/files/4507441/Inference.Example.zip)

Good luck!

**Comment by ShayanRiyaz** [comment]
Hi Alex,

I studied the links and example your provided. It did help in how the C# tensor syntax works.

However, I am still having trouble converting a file such as this into a tensor Input and passing it through my model.
(can be csv or txt)
```
28.75, 120.02, 44.02, 102.95, 14.57, 128.26, 21.05, 104.83, 6.01
28.68, 120.01, 44.00, 102.94, 14.48, 128.35, 20.77, 104.62, 5.86
28.61, 120.19, 44.00, 103.27, 14.32, 128.69, 20.35, 104.89, 5.61
8.42, 120.21, 44.08, 103.44, 14.66, 128.94, 20.81, 105.04, 5.91
28.47, 120.29, 44.06, 103.59, 14.43, 128.78, 20.43, 104.62, 5.88
28.46, 120.09, 44.01, 103.57, 14.59, 128.70, 20.68, 104.69, 6.08
28.33, 120.10, 43.95, 103.81, 14.44, 128.94, 20.71, 104.33, 5.91
28.27, 120.03, 43.89, 103.94, 14.44, 128.94, 20.80, 104.79, 5.84
28.24, 119.79, 43.72, 103.67, 14.28, 128.40, 21.03, 105.20, 5.85
28.16, 119.82, 43.71, 103.69, 14.13, 128.58, 20.72, 104.91, 5.94
28.17, 119.88, 43.83, 103.73, 14.36, 128.62, 20.66, 104.88, 5.79
28.06, 119.87, 43.83, 103.69, 14.49, 128.53, 20.69, 104.83, 5.84
28.11, 119.78, 43.82, 103.60, 14.32, 128.41, 20.57, 104.70, 5.72
27.91, 119.71, 43.83, 103.59, 14.41, 128.48, 20.49, 104.57, 5.79
27.81, 119.75, 43.82, 103.63, 14.43, 128.69, 20.64, 104.94, 5.91
27.73, 119.66, 43.67, 103.67, 14.21, 128.50, 20.50, 104.67, 5.79
27.97, 119.65, 43.87, 103.63, 14.70, 128.41, 20.93, 105.15, 5.69
27.78, 119.67, 43.72, 103.78, 14.24, 128.72, 20.61, 104.96, 5.79
27.91, 119.66, 43.91, 103.67, 14.58, 128.46, 20.46, 104.81, 5.77
27.81, 119.58, 43.82, 103.65, 14.56, 128.67, 20.68, 104.82, 5.65
```

If you can guide me to the relevant documentation. That would be great.

Thank you!

**Comment by AlexRibard** [comment]
Hi!
For that you'll need to parse the .csv into a float array. And then use this as input to your Tensor (cf example).
Here is a good explanation on how to do the parsing:
https://stackoverflow.com/questions/5282999/reading-csv-file-and-storing-values-into-an-array
Once you have the float array, you can create the Tensor accordingly
https://docs.unity3d.com/Packages/com.unity.barracuda@0.3/manual/index.html
