### ISSUE TITLE
Does Barracuda support quantization model?

### ISSUE THREAD

**Issue by guoguoguilai** [Unity-Technologies/barracuda-release#33]
When I put my onnx file into project, it occurs:
OnnxLayerImportException: Tensor data type Uint8 is not supported.
Asset import failed, "Assets/Model/quantized_model.onnx" > OnnxLayerImportException: Tensor data type Uint8 is not supported.

**Comment by AlexRibard** [comment]
Hi!
At the moment, inference is done in floating point precision. 
If you import a quanitzed model we will convert it to float.
But you are right, we forgot to handle the UInt8 case. Will be fixed in the upcoming release.

**Comment by xunyiljg** [comment]
I also encountered this problem and hope to update it as soon as possible. After all, it is more important to greatly optimize the existing model than to support more network architectures.

**Comment by mantasp** [comment]
@guoguoguilai Uint8 -> float automatic conversion landed to 0.7.0, please let us know if it helped to load your model.
