### ISSUE TITLE
OnnxImportException: Unknown type LayerNormalization encountered while parsing layer /transformer/layers.0/norm1/LayerNormalization_output_0.

### ISSUE THREAD

**Issue by PascalSpiegler** [Unity-Technologies/barracuda-release#332]
I am attempting to import Meta's Segment Anything Model (SAM) as a .onnx file into Unity using the Barracuda plugin, but I am encountering an asset import failure. Here are the details of the issue:

After exporting the SAM model as a .onnx file from [here ](https://github.com/facebookresearch/segment-anything/blob/main/scripts/export_onnx_model.py) and importing the model to Unity’s Barracuda Plugin, I receive the following error during the import process:

Asset import failed, "Assets/Models/sam_onnx_example.onnx" > OnnxImportException: Unknown type LayerNormalization encountered while parsing layer /transformer/layers.0/norm1/LayerNormalization_output_0.

Environment:
Unity Version: 2022.3.3f1
Barracuda Version: 3.0.1

Is this caused by a lack of support of LayerNormalization? Any guidance on how to resolve this issue and successfully import the SAM model into Unity using Barracuda would be much appreciated. Thank you!

**Comment by WritingTyping** [comment]
Hi,

Thank you for reporting this issue!

Can you see if the issue still reproduces with the Sentis package?

The Sentis package is a new version of Barracuda, and most issues with Barracuda are already fixed for Sentis.

If you still experience the issue after upgrading please post about it in [the Sentis Discussions forum](https://discussions.unity.com/c/ai-beta/sentis/10), and we will investigate it further.

You can refer here for the Sentis package installation guide: https://discussions.unity.com/t/about-sentis-beta/260899/24

**Comment by PascalSpiegler** [comment]
It works with the Sentis package. Thank you!
