### ISSUE TITLE
OnnxImportException: Unknown type Scan encountered while parsing layer UU000UU

### ISSUE THREAD

**Issue by nctrnal** [Unity-Technologies/barracuda-release#333]
Hi I am new to this but please I need help ASAP in which I had encountered this error code when trying to import a ONNX Model file into unity "Assets/Model/KNN_Model.onnx" > OnnxImportException: Unknown type Scan encountered while parsing layer UU000UU.

here is my code : https://colab.research.google.com/drive/17UGm6gOlhdHcFuMA1MnVEUuW3v2bpq7m?usp=sharing

this is my graph
![apakahinibisa3 onnx](https://github.com/Unity-Technologies/barracuda-release/assets/72295906/8f60560a-ff37-4345-9ece-a64e51ae6a19)

**Comment by LiutaurasVysniauskasUnity** [comment]
Hi,
Thank you for reporting this issue!
Can you please check if the same issue still reproduces with the Sentis 1.3.0-pre.2 package?
The Sentis package is the new version of Barracuda, you can learn more about it [here](https://discussions.unity.com/t/about-sentis-beta/260899).
If your problem still exists after upgrading, please report your issue in [the Sentis Discussions forum](https://discussions.unity.com/c/ai-beta/sentis/10).
Thanks!

**Comment by nctrnal** [comment]
Hi,
thank you for reply,
im trying to re-create onnx model using keras, and it's all fine now. i think the problem is Ca_Cast node.
