### ISSUE TITLE
Is cyclegan supported in Barracuda

### ISSUE THREAD

**Issue by pengyumic** [Unity-Technologies/barracuda-release#35]
I have been trying to import cyclegan model inside the Barracuda. I am not familiar with neural network, so I am a little bit struggling now. I try to convert different pretrained cyclgan gan model into nn model, but usullay it comes to errors like missing layers(I am not sure if this will affect the usage of the model, I have one converted successfully to nn with missing layers, but failed when run on Android. At the same time, I am not quite sure if I am correctly writing C# script for executing the model.), -1 not supported by lamda...   
Thus, there are two problems for me now.
1. how to convert cyclegan model to Barracuda or onnx. 
2. how to use the model correctly, I used the solo texture as a solo tensor to put into the worker engine, and then use the output as texture. I am quite familiar with Tensor, so I don't know if this is correct. However, I am getting errors: Error Unity KeyNotFoundException: The given key was not present in the dictionary.

**Comment by AlexRibard** [comment]
Hi @pengyumic!
CycleGan inference part is pix2pix if I am not mistaken?
If so, this is supported!
1* To convert it to Barracuda or onnx, I would refer to our documentation (https://docs.unity3d.com/Packages/com.unity.barracuda@0.3/manual/index.html). There is some resources online to export it to onnx (https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html)
2* on how to use it, refer to the docs or this tutorial
https://github.com/Syn-McJ/TFClassify-Unity-Barracuda

Hope that helps!

**Comment by pengyumic** [comment]
IGNORED: StopGradient unknown layer
IGNORED: Rsqrt unknown layer
IGNORED: StopGradient unknown layer
IGNORED: Rsqrt unknown layer
IGNORED: StopGradient unknown layer
IGNORED: Rsqrt unknown layer
IGNORED: TensorArrayV3 unknown layer
Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 21, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "E:\Documents\study\cs590vr\fianlproject\convert\tensorflow_to_barracuda.py", line 1364, in convert
    process_model(i_model, args)
  File "E:\Documents\study\cs590vr\fianlproject\convert\tensorflow_to_barracuda.py", line 1211, in process_model
    new_layers = transform_patterns[pattern_name](nodes, var_tensors, const_tensors, o_context)
  File "E:\Documents\study\cs590vr\fianlproject\convert\tensorflow_to_barracuda.py", line 451, in <lambda>
    inputs[0], context.layer_ranks[inputs[0]],
IndexError: list index out of range

Hello, this is the error that I got when I tried to convert my tf model. Also, I attached my own model link.

https://drive.google.com/open?id=1OeICwYmw6uQatt8qAniFA4EdCDmTGaYX

**Comment by AlexRibard** [comment]
Hi!
So I tried to convert your model to ONNX using tf2onnx and get a few errors:
![image](https://user-images.githubusercontent.com/12990800/80503373-c2101400-893f-11ea-838b-72dc6fa3333a.png)
This part gets an import error (pads attribute is wrong)
The end part of the model (after G_7/output/Conv2D) fails to export.

I would focus on these two parts and try to get tf2onnx to export without errors.
https://github.com/onnx/tensorflow-onnx

Once you have a .onnx file that got exported correctly,  you can drag and drop it in Unity and use it directly.
