### ISSUE TITLE
Possibility to Add another Operators in ONNX

### ISSUE THREAD

**Issue by alexivaner** [Unity-Technologies/barracuda-release#37]
Hi, I really willing that you could help me by adding new operators from ONNX. I need ReduceLogSumExp  and ReduceSumSquare for my onnx model.

I need to load onnx model in unity, but currently Baraccuda still not supported those operators.
Could we have the possibility to add these operators in Baraccuda?

Here I attached my model maybe it will help to implement these new operators.

[https://drive.google.com/file/d/1utXlhL2W1q62EYI7vOYiYnmrsu1Mncy-/view?usp=sharing
](url)
Thank you

**Comment by alexivaner** [comment]
![image](https://user-images.githubusercontent.com/57290644/80686061-b6b51800-8afa-11ea-9261-f381e549cdff.png)
Here I attached kind of error that I guess because unsupported onnx operator.

**Comment by AlexRibard** [comment]
We do not currently support them, but adding more ONNX coverage is our priority.

In the meantime, I think you could get away by splitting those operators with the following:
x -> y = exp(x) -> z = reduce_sum(y) -> log(z) for ReduceLogSumExp 
and 
x -> y = x^2 -> z = reduce_sum(y) for ReduceSumSquare

Hope that helps

**Comment by alexivaner** [comment]
@AlexRibard I already split my model and It seems to work, but do you have an idea for ArgMax, how we could use Baraccuda ONNX supported operator to getting the same result with ArgMax?

**Comment by AlexRibard** [comment]
Adding that to the TODO as we unfortunately haven't implemented it as a node yet.
We do have a CPU helper function that you can call.
int[] indices = myTensor.ArgMax();
Note that this will copy the buffer to CPU.

**Comment by alexivaner** [comment]
@AlexRibard 
I wonder why the prediction using Barracuda always like this:
![image](https://user-images.githubusercontent.com/57290644/81248767-b2838000-904f-11ea-9def-d88095cfa394.png)

at output[0] the result is correct, but the next output is always the same and not correct. I think it is because when I drag my onnx model to unity, Barracuda will give this:
![image](https://user-images.githubusercontent.com/57290644/81248793-c0390580-904f-11ea-94ac-f80d068b7280.png)

While actually my input_data is 144,40, is it possible to modify the "float_input" shape to 144,1,1,40. 
Because this model could predict well on C# using OnnxRuntime, but unfortunately OnnxRuntime could not run in Magic Leap so I used Barracuda since Barracuda can be used in Magic Leap.
In OnnxRuntime I modify the input shape by using this code:
![image](https://user-images.githubusercontent.com/57290644/81248809-c929d700-904f-11ea-9d70-5c06a1f74048.png)

It is at line 23

I will be very happy if you could help, 
Thank you.

**Comment by AlexRibard** [comment]
Ok, it would seem that it's doing something at least!
* First clarification:
ONNX data format in encoded in NCHW (batch, channels, height, width). So your input of dim (144,40) has a batch size of 144, 40 channels and 1 height and 1 width. => (144,40,1,1)
In Barracuda data is encoded in NHWC (batch, height, width, channels), so when you create an input of dim (144,40), it is thus represented as 144 batch, 1 heigh, 1 width and 40 channels => (144,1,1,40)
So judging from the inspector the dimensions are correct. 

* Secondly, data access:
internally data is laid out sequencially, and being in NHWC format we thus have the following data layout:
<--  n0  --> <--  n1  -->
c0 c1 .... c39  c0 c1 .... c39

So be sure you are correctly accessing data.
=> you have a few accessors available. [index] or [batch, channel], [batch, height, width, channel]

* Thridly output access:
It seems that you have multiple output of your network. By defauly CopyOutput will give you the first output.  If you want a specific output, call it with CopyOutput(string name)

So be sure you are accessing the correct output

**Comment by AlexRibard** [comment]
I was not able to access your shared model, so I cannot veryfy if Barracuda output matches with OnnxRuntime.
If you could share the onnx model, I could validate if output indeed matches. You can give me a model with randomly initialized weights if you wish

**Comment by alexivaner** [comment]
This is my onnx model:
https://drive.google.com/open?id=1RbaovvlORLvHEILfZ3idKHvvgdRDLmMD

and this is my data to predict in csv:
https://drive.google.com/file/d/1i8yPuCijmB1N2XwULvGlJ2iHL9lPI1IJ/view?usp=sharing

this is how I load the csv:
![image](https://user-images.githubusercontent.com/57290644/81252556-ced7ea80-9058-11ea-95f5-7bd5342c0c34.png)

**Comment by alexivaner** [comment]
I am sorry, this is the correct model

https://drive.google.com/file/d/1AThNGikvEJX3yC5m2LAQusAriR6Vpba4/view?usp=drivesdk
@AlexRibard

**Comment by alexivaner** [comment]
Actually I hope some output like this,
this is my output using onnxruntime in C#, maybe I have anything wrong initiate the tensor

![image](https://user-images.githubusercontent.com/57290644/81261880-73fdbd80-906f-11ea-9473-aee556904762.jpeg)

**Comment by AlexRibard** [comment]
Ok, I was able to repro it locally. Thanks for the model. 
Atm, work around seems to use the slow CSharpRef backend (WorkerFactory.TypeCSharpRef).
I'll provide some update when I have more info

**Comment by alexivaner** [comment]
How is it going? Is it because I initiate tensor in wrong way?

**Comment by AlexRibard** [comment]
Hi! Found the issue and a fix for it.
There was an internal bug linked to incorrect batch size handling on our end.
The issue was on the last Sub before the writing to _probabilities_ output with batchsizes > 1.

**Comment by alexivaner** [comment]
I am sorry, is this the internal bug of Barracuda? or internal bug of my model? So the bug is in the last sub before writing to probabilities but why the score also gave incorrect result then. Thank you.

**Comment by AlexRibard** [comment]
Ah sorry if my previous message was not clear.
There was an internal bug with Barraduca for broadcasting ops.
![image](https://user-images.githubusercontent.com/12990800/81587153-9f8cea80-9384-11ea-8980-670f3a75b0ea.png)
This Sub was leading to incorrect values for the _probabilities_ output.
The rest of the outputs were correct.
But I was using random input data. I can try with your .cvs and check if they match with onnx runtime

**Comment by alexivaner** [comment]
but why I just could get the first result from score_samples? because it must be 144 result from score_samples also. But when I used Barracuda, I just can get the first correct result, the rest of it is not correct.

I got result like this:
![image](https://user-images.githubusercontent.com/57290644/81587883-3f309400-93ea-11ea-825c-ad71ad45c0ac.jpeg)
instead of this:
![image](https://user-images.githubusercontent.com/57290644/81587906-48b9fc00-93ea-11ea-800f-01894ae8c76c.jpeg)

Only the first of result produce the correct result,
my vector.csv actually a tensor with shape (144,40)

**Comment by AlexRibard** [comment]
ah, my bad you were right. They are indeed all wrong.
With the fix I get the expected result
![image](https://user-images.githubusercontent.com/12990800/81590390-ba615e00-9388-11ea-823f-966c342e5ba8.png)
While the fix lands in trunk, does the CSharpRef path yields correct result for you? I am getting all correct with your inputs

**Comment by alexivaner** [comment]
Yes that result I wanted. I used onnxruntime in C# it produced the same result as your result. That is the correct result but in barracuda I can just got -17.52674 (The first result only)

**Comment by AlexRibard** [comment]
yeah, without the fix, it only works with batch size of 1 unfortunately...
If the C#Ref path (var worker = BarracudaWorkerFactory.CreateWorker(BarracudaWorkerFactory.Type.CSharpRef, model)) is too slow for you, you can split up your input into 140 1x40 inputs and execute the network 140 times.
I'll land the fix in the next release

**Comment by alexivaner** [comment]
Thank you very much for your help, really appreciate it. When is the next release will released? because I really need this library to implement my model in magic leap.

**Comment by AlexRibard** [comment]
Probably next week.

**Comment by alexivaner** [comment]
@AlexRibard Is this also a bug?
![image](https://user-images.githubusercontent.com/57290644/81891476-191e1600-95db-11ea-8840-7e5d3ed92410.png)

Finally, I found a better solution to produce only one output instead of 144 output, I count the mean of 144 output. But Barracuda now doesn't want to load my model.
Because this model runs normally in OnnxRuntime, and I think ReduceMean already supported by Barracuda.

This is the model:
https://drive.google.com/file/d/1x7VEpqLdOWsmwh8DWIvM1vjOl_q55gtT/view?usp=sharing

**Comment by alexivaner** [comment]
@AlexRibard oh yeah looks like it is only worked for a batch size of 1 currently. I already tried to change my model a little bit but still not work for second batch and so on.  Glad to hear if you could fix this soon. Thank you.

**Comment by alexivaner** [comment]
@AlexRibard I have 14 Models in my project. I must iterate the vector to every model and get the maxed value from 14 models then I could choose this vector belongs to which model after knowing the result of all my model. And in each model, as you suggest to split the vector from 144,1,1,40 to 144x(1,1,1,40) so I iterate 144x for each model.

This is worked in Unity in my PC but after deploy to magic leap, it always blanks or forces close. I guess this is because of memory overloading in magic leap GPU since it doesn't have a memory as big as my pc. What is the best way to do this?

This is so far what I did:
![image](https://user-images.githubusercontent.com/57290644/82071962-68fafb00-9709-11ea-8988-c584f462cf3e.png)

![image](https://user-images.githubusercontent.com/57290644/82071945-626c8380-9709-11ea-9a69-9fd77e206835.png)

![image](https://user-images.githubusercontent.com/57290644/82071999-7617ea00-9709-11ea-96fe-81a861c7dfbb.png)

Should I disposing the worker or something? Or I doing the worker an incorrect way. If the bug already fixed and the model could receive 144 input directly maybe it could be faster.
Thank You.

**Comment by AlexRibard** [comment]
Do you have a log for the reason of the crash?

Yes, you need to Dispose of both allocated Tensors and Worker when you are done with the computation.
GPU should work on MagicLeap. 
Can you try with a less intense workload? So maybe just 1 input and 1 tensor for start.
Be sure to dispose worker and Tensor after you are done.
If that works, you can try to increase workload progressively. So more Executes and then more models.
Also check with both ComputeRef and CSharp code path to see if it crashes.

Let me know how it goes!

**Comment by alexivaner** [comment]
![image](https://user-images.githubusercontent.com/57290644/82073404-c728dd80-970b-11ea-95f9-6f575ee09186.png)
Kind of this in my pc. although it worked, but taking long time. The result appear after around 4 second press the play button.

**Comment by alexivaner** [comment]
in my case, which one is better. worker.PeekOutput or Worker.Fetch?

**Comment by alexivaner** [comment]
![image](https://user-images.githubusercontent.com/57290644/82076629-b9298b80-9710-11ea-848a-9ade9bb3e610.png)
@AlexRibard this is the log of magic leap

**Comment by AlexRibard** [comment]
worker.PeekOutput is good

**Comment by alexivaner** [comment]
@AlexRibard Thank you for your suggestion, finally I use worker.PeekOutput and dispose the tensor and also worker. Now it worked in Magic Leap, but still taking a long time to recognize. Is there any recommendation to do it faster since I have 14 model here to iterate. Thank you for your help.

**Comment by alexivaner** [comment]
@AlexRibard Please tell me if you already fix the bug. Thank you very much for your help.

**Comment by AlexRibard** [comment]
Hi! Fix should be coming by the end of this week in v0.8.
For your performance issue: - assuming they are 14 different models.
Try to only create workers and input once (on Start() for example) and save execution for Update().
You can also try to dispatch your network executions over a few frames to keep interactive framerate.
Either by have 1or 2 networks per frame.
You can also execute models in parts like so:
```Csharp
    private Tensor ExecuteInParts(IWorker worker, Tensor I, int syncEveryNthLayer = 5)
    {
        var executor = worker.ExecuteAsync(I);
        var it = 0;
        bool hasMoreWork;

        do
        {
            hasMoreWork = executor.MoveNext();
            if (++it % syncEveryNthLayer == 0)
                worker.WaitForCompletion();

        } while (hasMoreWork);

        return worker.CopyOutput();
    }
```
It will execute n layers per frame.

**Comment by alexivaner** [comment]
I am sorry, if we initiate the worker only once at the start, can we load the new model or change the worker to load another model without starting the worker again? Could you give me example about update() part. Thank you very much for your help and really appreciate the bug fixes.

**Comment by AlexRibard** [comment]
There might be a few issues at play, so mostly throwing ideas:
* your inference is done on the GPU. Assuming you are retrieving the outputs on the CPU, that will cause a heavy synchronization between GPU and CPU, possibly causing a noticeable hitching.
-> if you do not fetch outputs, do you still see the hitching? What if the worker is set to a CPU backend, do you see the issue?
As a general rule of thumb, try to keep everything on the same pipe.

* if the issue is the inference, I would frame slice the scheduling.
So, try to schedule your networks over a few frames. Maybe executing 2 is ok to maintain correct framerate... In that case you can spread the 14 executions over 7 frames.
-> you do not block your application to run and render, but inputs will take a few frames to arrive so you'll need to figure out how your application will run while waiting for the result.

**Comment by alexivaner** [comment]
> Hi! Fix should be coming by the end of this week in v0.8.
> For your performance issue: - assuming they are 14 different models.
> Try to only create workers and input once (on Start() for example) and save execution for Update().
> You can also try to dispatch your network executions over a few frames to keep interactive framerate.
> Either by have 1or 2 networks per frame.
> You can also execute models in parts like so:
> 
> ```cs
>     private Tensor ExecuteInParts(IWorker worker, Tensor I, int syncEveryNthLayer = 5)
>     {
>         var executor = worker.ExecuteAsync(I);
>         var it = 0;
>         bool hasMoreWork;
> 
>         do
>         {
>             hasMoreWork = executor.MoveNext();
>             if (++it % syncEveryNthLayer == 0)
>                 worker.WaitForCompletion();
> 
>         } while (hasMoreWork);
> 
>         return worker.CopyOutput();
>     }
> ```
> 
> It will execute n layers per frame.

I am sorry to asked a lot of question, I am a beginner in C# also. Now I already initiate the worker at the start(). If I use this async worker, do I still need to split the tensor into 144x of (1,1,1,40)? What is layer here mean? Thank you

**Comment by AlexRibard** [comment]
That code executes the model n-layers at a time before syncing. That way you can spread the execution over a few frames.
By layer it's the _network layers_: so Add and Mul will be executed one frame and the next, MaxPool and Sub will be executed (random example). Your input stays the same.

**Comment by alexivaner** [comment]
Hi thank you for your recommendation to sync the model per layer. Yes, it makes my execution little bit faster,

**Comment by alexivaner** [comment]
May I know when is the bug fixes released? thank you very much for your help @AlexRibard

**Comment by AlexRibard** [comment]
You will be notified as soon as it is released.
We are currently working in releasing 0.8.0 that contains those fixes. Will be coming out shortly

**Comment by alexivaner** [comment]
@AlexRibard Thank you very much for all of Barracuda Developer's help. Really appreciate it.

**Comment by alexivaner** [comment]
@AlexRibard looks like the bugs now already fixed, but How I can get all the tensor output and make average on it? I have O[0] until O[100]

**Comment by AlexRibard** [comment]
Awesome!
For that, I would suggest two ways:
* create a new network with a single node GlobalAveragePool
https://github.com/onnx/onnx/blob/master/docs/Operators.md#GlobalAveragePool
* use the model builder to create the model yourself (without loading a onnx file)
```
            Model model = new Model();
            ModelBuilder builder = new ModelBuilder(model);
            builder.GlobalAvgPool2D("c0", input);
...
            var worker = WorkerFactory.CreateWorker(workerType, builder.model, workerConfiguration);
            worker.Execute(input);
```
Let me know if that helps

**Comment by alexivaner** [comment]
how to wrap O[0] until O[100] to input? because its tensor, I wonder how to convert all of O[0] to O[100] to an array or list. Or I just append to list manually? Or in Barracuda, is there any function to convert the tensor to array directly? thank you @AlexRibard

**Comment by alexivaner** [comment]
@AlexRibard sorry for my silly question, I already got it now, It is a lot faster now, from  10 seconds to only 500 ms. Thank you very much for fixing the bugs.

**Comment by alexivaner** [comment]
Hi, I have different behavior of Barracuda for load some model inside Unity. This is actually related to previous issues when Barracuda can only receive 1 batch of tensor. After the bugs fixed, the model worked really well and can load more than 1 batch of tensor in PC. But when I deploy to magic leap, the behavior quite different and not produce same result. Thank you very much for your help. @AlexRibard

**Comment by AlexRibard** [comment]
Which graphics backend are you using on MagicLeap? OpenGL or Vulkan? OpenGL compiler is usually less maintained than Vulkan. So I would recomend using a Vulkan backend.

**Comment by alexivaner** [comment]
@AlexRibard Hi I am sorry for the question. Last time my Barracuda for magic leap program maybe didn't update properly, I try to delete and reinstall Barracuda, and it worked as usual. Thank you very much for your nice help.

**Comment by AlexRibard** [comment]
Perfect then!
