### ISSUE TITLE
error CS0433: The type 'ValueTuple<T1, T2>' exists in both 'System.ValueTuple' and 'mscorlib'

### ISSUE THREAD

**Issue by AMGMNPLK** [Unity-Technologies/barracuda-release#40]
I'm upgrading a Unity custom project with an ML-Agents 0.4b version to the last 1.0 and I'm getting 12 errors like this:

`Library\PackageCache\com.unity.timeline@1.2.6\Editor\Window\TimelineWindow_Breadcrumbs.cs(91,47): error CS0433: The type 'ValueTuple<T1, T2>' exists in both 'System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
`

`Library\PackageCache\com.unity.barracuda@0.7.0-preview\Barracuda\Runtime\Core\Backends\BarracudaCompute.cs(586,25): error CS0433: The type 'ValueTuple<T1, T2, T3>' exists in both 'System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`

...

I'm a junior self-taught dev and I'm not confident on what I have to do. I found some links about it, but I don't know how to implement it:

https://github.com/dotnet/roslyn/issues/21156

On this link there is a reference to this pull request: https://github.com/dotnet/roslyn/pull/21851/commits/850799c50d4ee810966b10aaa6a63dcebdc05f46

but I have no idea what I should change to fix it.

I would like to know, also, what I should study to be capable to deal with this kind of problems. Any recommendation?

**Comment by mantasp** [comment]
Which Scripting Runtime Version do you have selected in your Player Settings in Unity Editor?

**Comment by AMGMNPLK** [comment]
I´m in the 2019.3.12f1 version:
![image](https://user-images.githubusercontent.com/19272675/81063457-1c791980-8ed8-11ea-8680-e4638c6076b2.png)

**Comment by mantasp** [comment]
Could you please try it with Barracuda 1.2.0-preview and re-open the issue if it's still a problem?

**Comment by lulukdog** [comment]
I meet the same problem.Unity version is 2020.3.14.Platform is iOS.
Problem:Library/PackageCache/com.unity.timeline@1.4.8/Editor/Animation/BindingTreeViewDataSource.cs(195,37): error CS0433: The type '(T1, T2)' exists in both 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

![image](https://user-images.githubusercontent.com/4277659/135072646-32d8e95f-fd5d-4831-854e-820ca4a815d0.png)

**Comment by amirebrahimi** [comment]
@lulukdog - Your error is coming from a different package: `com.unity.timeline`. Try removing that package and see if that fixes your issue. Also, please create a new issue if you are still having a problem.

**Comment by lulukdog** [comment]
> @lulukdog - Your error is coming from a different package: `com.unity.timeline`. Try removing that package and see if that fixes your issue. Also, please create a new issue if you are still having a problem.

ty I resolve it by delete one of System.ValueTuple.dll
