### ISSUE TITLE
Tensorflow model to Barracuda or Onnx

### ISSUE THREAD

**Issue by JonasX99** [Unity-Technologies/barracuda-release#41]
I would like to know if it would be possible to get a [Teachable Machine](https://teachablemachine.withgoogle.com/) model into Unity and use it with Barracuda Currently I have tried to convert a Tensorflow model with tensorflow_to_barracuda.py which I get this error: google.protobuf.message.DecodeError: Error parsing message

I have also tried to convert the model with the [tf2onnxt](https://github.com/onnx/tensorflow-onnx) but when I have successfully convert the model and import it the model has warnings

also when I import any model of my own the camera is responding every second

-Unity version 2020.1
-Barracuda version have tried with 0.4.0 and 0.6.3

Hope Teachable Machine models is possible to use since it's fast and easy for the project i am working on

**Comment by AlexRibard** [comment]
Hi @JonasX99 !
I am assuming that the models are generic image recognition models.
It should be possible to import them into Barracuda, albeit if you can export them to ONNX or TF format.
* for the tensorflow_to_barracuda, I am guessing the tensorflow model is not of the same format. Has it been exported with TF2 of TF? Could you share the .pb model?
* what warning are you getting with the imported ONNX model? Could you share the model?
* I would assume, there is a performance issue, if the response time is slow. Are you using a Compute worker? The CSharp path is generally slow for image recognition models.
If it is not that, could you share more info about the setup and/or share your problematic scene?

Thanks!

**Comment by JonasX99** [comment]
[This is the model](https://drive.google.com/drive/folders/1r9npbC_TtV9W6pfh5xoVNVG27zfHLLaC?usp=sharing)
I fixed the problem with it only responding every second by downgrading to Unity 2019 instead of 2020
