### ISSUE TITLE
Support for LSTM in keras_to_barracuda.py

### ISSUE THREAD

**Issue by Austinmack-dev** [Unity-Technologies/barracuda-release#42]
Hello Barracuda Team,

I am curious if using the keras LSTM layer is supported in the keras_to_barracuda.py script or even the tensorflow_to_barracuda.py script?

I would like to use an LSTM in the Barracuda inference engine and am not sure of the best way to do this.  Is it possible to just convert a keras LSTM model to onnx and use that in barracuda?

Edit:  After converting a simple keras model with only an LSTM and a Dense layer to onnx via keras2onnx, and importing the .onnx file into Unity, I get a 'KeyNotFoundException: the key was not found in the dictionary.'  Is this because the LSTM model is not supported within Unity?
I am on Unity version 2019.3.6f1.  

If I create a simple model without the LSTM layer, and convert it to onnx via keras2onnx, and importing the .onnx file into Unity, I do not get the same error as the model with the LSTM layer.

I really appreciate all of your help on this issue!

Thanks,
Austin

**Comment by AlexRibard** [comment]
Hi @Austinmack-dev !
We recommend a new workflow to import a model in Unity.
Could you try to convert your keras model to a `.onnx` file with `keras2onnx`
https://github.com/onnx/keras-onnx
Once you have the exported `.onnx` file you can drag and drop it in Unity.

Let me know if it works!
If not, please share the generated onnx file and/or your keras model and we will investigate :)

Thanks!
