### ISSUE TITLE
Platform support: UWP / Microsoft Hololens 2

### ISSUE THREAD

**Issue by brookman** [Unity-Technologies/barracuda-release#44]
When I try to compile for Hololens 2 I am getting this error:
`Library\PackageCache\com.unity.barracuda@0.7.1-preview\Barracuda\Runtime\Core\Tensor.cs(858,57): error CS0433: The type 'ICloneable' exists in both 'Microsoft.Windows.MixedReality.DotNetWinRT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`
I assume UWP / HL2 is not supported yet. If that is so, are there any plans for the future?

Edit: I could get it running by removing some third party code and disabling Burst.

**Comment by AlexRibard** [comment]
I have found a similar issue:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7616
It would seem that both dll use the same class name...
https://stackoverflow.com/questions/1057853/the-type-type-exists-in-both-dlls seems to indicate that you can get away with namespace alias:
```
using Vendor1 = Vendor.Namespace;
using Vendor2 = OtherVendor.Namespace;
```

Let me know if that helps!
