### ISSUE TITLE
ArgumentException: Kernel TextureToTensor and TextureToTensor_NHWC are both missing

### ISSUE THREAD

**Issue by guoguoguilai** [Unity-Technologies/barracuda-release#46]
It was good last few days. But today I don't know why it fails in Android(Windows good)
When I trying to excute inferece with yield return _worker.ExecuteAsync(input), it throwed such error. How can I solve this problem?
Barracuda : 0.7 and 0.71
Unity: 2018.3.10f1
OpenGLES3 and 2

**Comment by mantasp** [comment]
GLES 2 doesn't support compute shaders and is not supported by Barracuda. Which platform are you testing on? 
Sometimes people see such error because GLES 3.0 emulation is enabled in the Unity Editor, if you switch to "No Emulation" in "Edit" -> "Graphics Emulation" menu it should work again.
