### ISSUE TITLE
Why Does this Barracuda error suddenly pops and stops training - unity ml agents

### ISSUE THREAD

**Issue by chenh1001** [Unity-Technologies/barracuda-release#47]
I have been working on this project for a long time, I want to train a team of agents to simulate a game of basketball (kinda like the soccer example but more complicated because I have tought the agent to shoot and pass separately with different neural networks). I didnt have any problems training the agent to shoot perffectly and pass aswell but when I changed both of the neural nets to inference mode and act like an action in the bigger neural network things started to fail. Everything works well but after training for like a million steps I suddenly get a NullReferenceException from the Unity.Barracuda and then a lot of IndexOutOfRangeException(20 times each frame +-) (image attached) .Why is this error popping up and stopping my training procces? image of error - https://imgur.com/a/SW2bGp6

**Comment by mantasp** [comment]
@chenh1001 are you using CPU or GPU inference? Does it help if you switch to CPU mode?
