### ISSUE TITLE
Barracuda stops VideoPlayer playing in Android.

### ISSUE THREAD

**Issue by guoguoguilai** [Unity-Technologies/barracuda-release#49]
I am working on an take Barracuda as inference engine in Unity. The input was RenderTexture taken from VideoPlayer. For Windows, all functions work just well. But for Android, I found this issue below in Unity2019.3.1, Unity2019.3.5：
When the VideoPlayer is playing and Barracuda is disabled, The VideoPlayer works well.  While Barracuda is inferencing, the VideoPlayer just stopped. The state of VideoPlayer.isPlaying is True, but the RenderTexture stay the same.
This issue was found only in Android. 
Any help will be appreciated.

**Comment by mantasp** [comment]
Thanks for the report! Any chance you could share simple test project that shows the issue?

**Comment by guoguoguilai** [comment]
> Thanks for the report! Any chance you could share simple test project that shows the issue?

Thanks for your quick response. 
I also found that although the VideoPlayer.isPlaying is true, the VideoPlayer stays in the frame that inference starts in Android(Not sure about iOS). 
I am wondering if I can send my demo via Email. My email address is guoguoguilai@gmail.com. I am about to send my code to you as soon as you send me an email.
Thanks in advance.

**Comment by justinw-fun** [comment]
Unity2019.3.11 failed, too.

**Comment by guoguoguilai** [comment]
Untiy2018.3.10, Unity2019.3.11 failed, too.

**Comment by justinw-fun** [comment]
Any update? I am really looking forward to solving this problem.

**Comment by guoguoguilai** [comment]
Any update? I am really looking forward to solving this problem.

**Comment by Aurimasp** [comment]
Hi guoguoguilai, I contacted you via email.

**Comment by Aurimasp** [comment]
Issue link: https://jira.unity3d.com/browse/BAR-4

**Comment by guoguoguilai** [comment]
Something is wrong with Jira, Jira said my password was wrong, but I couldn't able to recieve any email or SMS code from Jira. Is there any update?

**Comment by Aurimasp** [comment]
I've sent you an updated inference script. It uses manual scheduling and doesn't stop the video, but it still runs slow on mobile devices. We have mobile optimization plans in our roadmap, so it may improve in future versions of Barracuda.

**Comment by guoguoguilai** [comment]
Recieved! Thank you so much!
