### ISSUE TITLE
Trying to debug Tensors

### ISSUE THREAD

**Issue by Adrian-Cook** [Unity-Technologies/barracuda-release#5]
I am attempting to debug some Tensors from a pose model integration following dahburj's repo.

To debug this I decided to try and visualise the tensors using the Barracuda utils.

`

    Tensor heatmap = localWorker.Fetch("heatmap");
        
    Debug.Log("Heatmap: " + heatmap.width + ":" + heatmap.height);

    RenderTexture heatmapTexture = new RenderTexture(heatmap.width, heatmap.height, 32, RenderTextureFormat.ARGB32);

    heatmapTexture.Create();

    BarracudaTextureUtils.TensorToRenderTexture(heatmap, heatmapTexture);
`
When I run this I get the following exceptions:

`
RenderTexture.Create failed: format unsupported for random writes - RGBA8 sRGB (4).
UnityEngine.RenderTexture:Create()
Barracuda.ReferenceComputeOps:TensorToRenderTexture(Tensor, RenderTexture, Int32, Int32, Single, Single)
Barracuda.BarracudaTextureUtils:TensorToRenderTexture(Tensor, RenderTexture, Int32, Int32, Single, Single)
BarracudaPoseEstimation:GeneratePose(Texture2D, Int64, RawImage) (at Assets/Scripts/PoseEstimation/BarracudaPoseEstimation.cs:49)`

The Create that is failing is not the one in my code but the one called by BarracudaTextureUtils

I also get the following exception (I suspect because of the previous exception):
`
ArgumentException: Kernel TensorToTexture is missing
Barracuda.ComputeFunc..ctor (UnityEngine.ComputeShader[] cs, System.String kn) (at <a57b068757aa4cec9131100114e8a39b>:0)
Barracuda.ComputeFunc..ctor (UnityEngine.ComputeShader cs, System.String kn) (at <a57b068757aa4cec9131100114e8a39b>:0)
Barracuda.ReferenceComputeOps.TensorToRenderTexture (Barracuda.Tensor X, UnityEngine.RenderTexture target, System.Int32 batch, System.Int32 fromChannel, System.Single scale, System.Single bias) (at <a57b068757aa4cec9131100114e8a39b>:0)
`

For what it's worth I tried each of the BarracudaTextureUtils calls and both raised the same exceptions.

I am running Unity 2019.2.12f1 on a Macbook Pro 2017. Barracuda v 0.3.2 Build target is set to Android but exceptions raised while running in editor.

Any advice or pointers greatly appreciated. 

Thanks
Adrian

**Comment by mantasp** [comment]
Hi @Adrian-Cook, it might be related to Android target being selected. Which Graphics API is set in player settings? Also could you please try switching to Sandalone/Mac as a build platform and check if problem persists.
Thanks

**Comment by Adrian-Cook** [comment]
Hi Mantas, 
Thank you for the reply.
The Graphics API set in Player Settings for Android is OpenGLES3

I have gone into Build Settings and selected PC, Mac, Linux Standalone and run my project in the editor, it produces exactly the same error exceptions.

(I looked at the Mac Graphics API and they were set to Metal and OpenGL Core, I switched them round and tried again, same error).

**Comment by mantasp** [comment]
Hmm.. Any chance you could share your Editor.log + Neural Net model (random weights are fine)?
