### ISSUE TITLE
Creating a tensor from a texture maps pixel colour values to 0 and 1.

### ISSUE THREAD

**Issue by nicholasmaurer** [Unity-Technologies/barracuda-release#51]
The model I'm using expects pixel values between 0 ad 255. When I use `new Tensor()` to create a tensor from a texture all the values are mapped to 0 and 1.

I think it needs to be sign posted better in the docs that the values inside tensors will be between 0 and 1, or -1 and 1, not sure which it is because I just went back to the docs and couldn't find it.

At the moment I'm creating a tensor from scratch with values between 0 and 255 and this works fine.

The model I'm using for reference:
https://github.com/onnx/models/tree/master/vision/style_transfer/fast_neural_style

**Comment by FlorentGuinier** [comment]
Hi Nicholasmaurer,

Indeed this is a very good point, I'm fixing the doc from Tensor.cs at the moment, thanks for your feedback!
