### ISSUE TITLE
Getting output is 50x slower than running inference

### ISSUE THREAD

**Issue by tomasondrias** [Unity-Technologies/barracuda-release#53]
Calling worker.Execute is very fast (about **0.02 seconds**), but getting the data from the outputs using Tensor.AsFloats(), Tensor.data, Tensor.Download, or anything similar is very slow (more than **1 second**). The number of floats it returns is **2560**.

Platform: Android (with Vulkan)
Model: probably not the cause of the issue, it's an implementation of [AlignedReID](https://arxiv.org/abs/1711.08184), essentially it's just a wrapper for MobileNet. I've uploaded it [here](https://drive.google.com/file/d/1dsqfcPVeLLmFbe-7pfluN1grrFSDh2mX/view?usp=sharing) just in case 

```
void Start()
{
    model = ModelLoader.Load(modelFile);
    worker = WorkerFactory.CreateWorker(model, WorkerFactory.Device.GPU);
}

// Run the model and return the array of floats it outputs.
public float[] GetFeatures(Texture2D img)
{
    float start = Time.realtimeSinceStartup;
    var inputs = new Dictionary<string, Tensor>();
    var inputTensor = new Tensor(img);
    inputs.Add(model.inputs.First().name, inputTensor);

    worker.Execute(inputs);

    output = worker.PeekOutput();
    float[] features = output.AsFloats();
    Debug.Log($"Time taken: {Time.realtimeSinceStartup - start}");
    return features;
}

```
Is there anything that can affect the speed of getting output data? The only time that is runs fast is when I call Tensor.ToRenderTexture so it's probably the transport from GPU to CPU that is causing the problem.

**Comment by mantasp** [comment]
For GPU backends Execute() just schedules work on GPU and synchronisation happens only when you request actual output data, which means that in your case GPU was busy for 1s. This is quite unexpected for MobileNet architecture, but on other hand it depends a lot on how many channels intermediate convolutional layers have. 
Which Android device did you use for testing?

**Comment by tomasondrias** [comment]
I'm using a Huawei P20 Lite.

The model is from PyTorch. Do you have any idea why copying to a render texture is so much faster?

**Comment by AlexRibard** [comment]
When you copy to RenderTexture, you stay on the GPU pipe. So there is no CPU/GPU synchronization.
Hence you have no latency/wait until the GPU has finished rendering the frame.

Are you rendering anything?

**Comment by tomasondrias** [comment]
No, I'm not rendering anything. I just need to get the output as an array of floats to compare with another float array. Is there a way to schedule this on the GPU or should I try optimizing the model?

**Comment by tomasondrias** [comment]
I upgraded to Barracuda 1.0.0 and tried the Burst CSharp worker and got great results on mobile, about 0.2 seconds for inference and getting output. Only issue is that while it works on my device, in the Editor it throws an error. Should I open a separate issue?

UnityException: ScheduleBatchedJobsAndComplete can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
Unity.Jobs.JobHandle.Complete () (at <f38c71c86aa64e299d4cea9fb7c715e1>:0)
Unity.Barracuda.UnsafeArrayCPUOps.Pin (Unity.Barracuda.Tensor X) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Runtime/Core/Backends/BarracudaUnsafeArrayCPU.cs:135)
Unity.Barracuda.UnsafeArrayCPUOps+<>c__DisplayClass64_2.<ApplyPadding>b__0 (System.Int32 y) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Runtime/Core/Backends/BarracudaUnsafeArrayCPU.cs:2010)
System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1[TLocal].<ForWorker>b__1 () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Threading.Tasks.Task.InnerInvoke () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Threading.Tasks.Task.InnerInvokeWithArg (System.Threading.Tasks.Task childTask) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Threading.Tasks.Task+<>c__DisplayClass178_0.<ExecuteSelfReplicating>b__0 (System.Object <p0>) (at <437ba245d8404784b9fbab9b439ac908>:0)
Rethrow as AggregateException: One or more errors occurred.
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Threading.Tasks.Task.Wait () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Threading.Tasks.Parallel.ForWorker[TLocal] (System.Int32 fromInclusive, System.Int32 toExclusive, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action`1[T] body, System.Action`2[T1,T2] bodyWithState, System.Func`4[T1,T2,T3,TResult] bodyWithLocal, System.Func`1[TResult] localInit, System.Action`1[T] localFinally) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Threading.Tasks.Parallel.For (System.Int32 fromInclusive, System.Int32 toExclusive, System.Action`1[T] body) (at <437ba245d8404784b9fbab9b439ac908>:0)
Unity.Barracuda.UnsafeArrayCPUOps.ApplyPadding (Unity.Barracuda.Tensor X, System.Int32[] pad, System.Single constant, System.Action`1[T] paddingOp) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Runtime/Core/Backends/BarracudaUnsafeArrayCPU.cs:2000)
Unity.Barracuda.UnsafeArrayCPUOps.Border2D (Unity.Barracuda.Tensor X, System.Int32[] pad, System.Single constant) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Runtime/Core/Backends/BarracudaUnsafeArrayCPU.cs:2034)
Unity.Barracuda.StatsOps.Unity.Barracuda.IOps.Border2D (Unity.Barracuda.Tensor X, System.Int32[] pad, System.Single value) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Runtime/Core/Backends/StatsOps.cs:157)
Unity.Barracuda.GenericWorker+<StartManualSchedule>d__29.MoveNext () (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Runtime/Core/Backends/GenericWorker.cs:306)
Unity.Barracuda.GenericWorker.Execute () (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Runtime/Core/Backends/GenericWorker.cs:118)
Unity.Barracuda.GenericWorker.Execute (System.Collections.Generic.IDictionary`2[TKey,TValue] inputs) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Runtime/Core/Backends/GenericWorker.cs:106)
CV.AlignedReId.GetFeatures (UnityEngine.Texture2D img, System.Boolean includeLocal) (at Assets/CV/Scripts/AlignedReId.cs:62)
CV.AlignedReId.Update () (at Assets/CV/Scripts/AlignedReId.cs:47)

**Comment by RobinDenaux** [comment]
> 
> 
> For GPU backends Execute() just schedules work on GPU and synchronisation happens only when you request actual output data, which means that in your case GPU was busy for 1s. This is quite unexpected for MobileNet architecture, but on other hand it depends a lot on how many channels intermediate convolutional layers have.

Hi, I'm seeing the same problem with CSharpBurst and tinyYOLOv2 on android (1s download of tensor on a Redmi note 8). Is it a normal inference time? 

I am seeing a big improvement if I put a 2s wait between the worker Execute and the output Peek. Any way to know when it's safe to peek the output without blocking the main thread?

I’ve tried to move the worker to another thread (the thread waits for a texture and return the bounding boxes), but I guess it's not supported as I got an error in the worker.execute, can someone confirm this?

Thank you

**Comment by AlexRibard** [comment]
@tomasondrias open a new issue for Burst. Can you see if taking latest burst package fixes anything.

Looks like your problem seems to be that the execution is taking too long for your frame time.
Did you try to only execute part of the network every frame. So you execute 80% in the first frame. And 20% followed by the read for the result?
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation~/ModelExecution.md

I am bit confused with your last part. Can you detail a bit what you are trying to do?

**Comment by RobinDenaux** [comment]
I'll try again, I might have missed the worker.WaitForCompletion() when I did it this way.

For the last part, I don't need real time, so if the worker could work on another thread it would free my main thread (CSharpBurst is on the CPU so it make sense right?)

**Comment by AlexRibard** [comment]
Yes, CSharpBurst is a asynchronous CPU worker, it would free up main thread.

**Comment by tomasondrias** [comment]
Another issue that it looks like I never noticed is that the inputs in Barracuda are wrong. The inputs should be [1, 3, 256, 128], but Barracuda is showing [1, 256, 128, 3]. My results are very different from running the model in PyTorch and I am wondering if fixing the inputs might solve it. This is with the same model as before, it is a mobilenet_v2-specific problem?

Model was exported with:
```
dummy_input = torch.ones([1, 3, 256, 128])
torch_out = model(dummy_input)
torch.onnx.export(model, dummy_input, args.output_file, export_params=True, input_names=['input'], output_names=['output'], example_outputs=model(dummy_input))
```

But Barracuda shows:
![screenshot](https://user-images.githubusercontent.com/10598541/86737434-9478d280-c034-11ea-9d8e-95e2ca2411ea.png)

**Comment by AlexRibard** [comment]
Hi! @tomasondrias no this is expected.
Pytroch data layout is NCHW so in your case [1,3,256,128]
Barracuda is NHWC so in your case [1,256,128,3]
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/TensorHandling.md

**Comment by tomasondrias** [comment]
@AlexRibard Yeah, thanks I noticed that in the docs. But the question I have is if that could be affecting the model's results?

**Comment by FlorentGuinier** [comment]
It should not affect the result, aka Barracuda tensor should be a transposed version of the pytorch one (given some epsilon in values)

**Comment by AlexRibard** [comment]
closing, @tomasondrias feel free to create a new issue if the results are not as expected
