### ISSUE TITLE
keras_to_barracuda not working

### ISSUE THREAD

**Issue by alvinsat** [Unity-Technologies/barracuda-release#57]
Hello I tried to convert .h5 to .nn 

I saved my model with
model.save("namaSendiri.h5")

then running
keras_to_barracuda.py namaSendiri.h5 namaSendiei.nn

got following error
keras_to_barracuda.py namaA.h5 namaA.nn with a message yield from pattern(x)  invalid syntax

**Comment by AlexRibard** [comment]
Hi!
We are slowly deprecating keras_to_barracuda.py going forward.
Can you try with keras2onnx
(c.fL https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Exporting.md)

Let me know how it goes!

**Comment by alvinsat** [comment]
It is working.. I am using tensorflow 2 with keras2onnx. thanks!

**Comment by alvinsat** [comment]
P.S for anyone using tensorflow 2.x it is best to install keras2onnx from source
