### ISSUE TITLE
Different Behaviour of Barracuda in PC and Magic Leap

### ISSUE THREAD

**Issue by alexivaner** [Unity-Technologies/barracuda-release#60]
Hi, I have different behavior of Barracuda for load some model inside Unity. This is actually related to previous issues when Barracuda can only receive 1 batch of tensor. After the bugs fixed, the model worked really well and can load more than 1 batch of tensor in PC. But when I deploy to magic leap, the behavior quite different and not produce same result. Thank you very much for your help.

**Comment by amirebrahimi** [comment]
I think this was resolved based on your last comment to #37. Is it working now?
