### ISSUE TITLE
Best way to test a network multiple times with different inputs?

### ISSUE THREAD

**Issue by rotolonico** [Unity-Technologies/barracuda-release#61]
For the sake of this example, I have a network that takes two inputs (x and y coordinates) and spits out a pixel (RGB). I trained this network on a 128x128 image and now I want to retrieve that image back. In order to do that, I have to test the network for all of the pixels in the 128x128 image, so 16384 times.

This is the code I am currently using:

``
public float[] TestNetwork(float[] pixelsCoords)
{
    var input = new Tensor(0, 1, 1, 2, pixelsCoords);
    worker.Execute(input);
    var output = worker.PeekOutput("activation_4");
    return (float[]) output.ToReadOnlyArray().Clone();
}``

I am calling this function every iteration but I have noticed it is quite slow. Is there a better way to accomplish this task?

I am using the CSharp WorkerFactor (I have also tried the CSharpBurst with similar results). All of the other factories seemed even slower!

Thanks

**Comment by AlexRibard** [comment]
Your network takes in a 2D input (x,y coordinates) and outputs a 3D output (rgb).
You want to pass in N 2D inputs (N = 128x128) and get N rgb outputs
For that the best is to interpret the 128x128 input as a single 2D tensor of batch size 128x128.
```
        Tensor input= new Tensor(128*128,1,1,2);
         // initialize input
        ...
        Tensor result = worker.ExecuteAndWaitForCompletion(input);
        // result is thus a (128,128,1,3) Tensor
        result = result.Reshape(new TensorShape(1, 128, 128, 3));
```
Let me know if that solves the issue.
Can you also share your network, so I can get a better idea?

Thanks!

**Comment by rotolonico** [comment]
Hey, thanks for the reply! I tried the code but I get the "Values are not equal" error when I execute, because my network is looking for an input Tensor which is (0,1,1,2) while your input Tensor is (128. 128, 1, 2).

[Link to the model.onnx trained on a red checkboard](https://www.mediafire.com/file/0js246m4iqnhgps/model_test.onnx/file)

This is how I implemented your code in the TestNetwork function:

```
      Tensor input = new Tensor(64, 64, 1, 2, pixelsCoords);
       // pixelsCoords is now a 64*64*1*2 array with all the possible coords
      Tensor result = worker.ExecuteAndWaitForCompletion(input);
      result = result.Reshape(new TensorShape(1, 128, 128, 3));
      return result.ToReadOnlyArray();
```

**Comment by AlexRibard** [comment]
Hi! Sorry for the confusion, I had a typo in my answer:
I tried the following code locally:
```
// assuming pixelCoords is layedout in the following pattern:
// [X0,Y0 , X1,Y1 , ... , Xn,Yn] 
Tensor input = new Tensor(256 * 256, 1, 1, 2, pixelCoords);

worker.Execute(input);
Tensor result = m_Worker.PeekOutput();
// result is a [256x256, 1, 1, 3] Tensor
// Reshaping to get back to an image
result = result.Reshape(new TensorShape(1, 256, 256, 3));
```

Since you are dealing with images, the following might be of help if you want to avoid back and forth with the CPU...
You can also pass in your input as a Texture, and then reshape before executing
```
// my input data comes from a RenderTexture (I initialize it in a ComputeShader)
Tensor input = new Tensor(inputRenderTexture, 2);
// input is a Texture, so a [1, 256, 256, 2] Tensor
// we need to reshape accordingly
input = input.Reshape(new TensorShape(256*256,1,1, 2));

worker.Execute(input);
Tensor result = m_Worker.PeekOutput();
// result is a [256x256, 1, 1, 3] Tensor
// Reshaping to get back to an image
result = result.Reshape(new TensorShape(1, 256, 256, 3));
```

If you are using a GPU worker backend, you can save `result` to a RenderTexture directly (and avoid the costly `ToReadOnlyArray`
```
RenderTexture resultTexture = new RenderTexture(256, 256, 0);
resultTexture.enableRandomWrite = true;
resultTexture.Create();
        
result.ToRenderTexture(resultTexture);
```

Let me know!

**Comment by rotolonico** [comment]
That works wonderfully, even with the ToRenderTexture method. Thank you very much!
