### ISSUE TITLE
Upcoming support for WebGL?

### ISSUE THREAD

**Issue by rotolonico** [Unity-Technologies/barracuda-release#63]
Hello,
I have tested my barracuda WorkerFactory.Type.CSharp worker on a WebGL build and it crashes:
```
ArgumentException: Kernel TensorToTextureNoLUT and TensorToTextureNoLUT_NHWC are both
missing
  at Unity.Barracuda.ComputeFunc..ctor (UnityEngine.ComputeShader[] cs, System.String know)
[0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)
```

Is there a way to make barracuda work on WebGL or is this still unsupported?
Thanks!

**Comment by amirebrahimi** [comment]
Currently GPU inference on WebGL is unsupported. It is recommended to use CPU inference for now.
https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/manual/SupportedPlatforms.html

**Comment by AlexRibard** [comment]
On a side note, it would seem that you are trying to convert a Tensor to RenderTexture.
Being on WebGL and as you mentioned your Worker Type is already CSharp. 
The problem is ToRenderTexture actually uses the GPU pipe (RenderTextures being a GPU resource), resulting in your crash.
So unfortunately you'll need some workaround and manually create a Texture2D (CPU resource) from the tensor
```
    private void TensorToTexture(Tensor X, int batch, Texture2D tex)
    {
        var pixels = new Color[X.width * X.height];

        int index = 0;
        for (var y = 0; y <  X.height; y++)
            for (var x = 0; x < X.width; ++x)
            {
                var v0 = X[batch, y, x, 0];
                var v1 = X[batch, y, x, 1];
                var v2 = X[batch, y, x, 2];
                pixels[index++] = new Color(v0, v1, v2, 1);
            }

        tex.SetPixels(pixels);
        tex.Apply();
    }
```
Once you have the Texture2D, you can create a RenderTexture like follows
https://answers.unity.com/questions/1177491/texture2d-to-rendertexture.html

Hope that helps

**Comment by rotolonico** [comment]
Thank you for that. I'll try it out as soon as I can! As an unrelated note, I had someone try the same code on a macOS build and got similar problems. Could it be because they don't have GPU drivers, Nvidia drivers, or is it something else? (pardon my ignorance on the topic).

Would it be wise to make two different versions of the App, one using only CPU and another one for GPU? If so, would I need to change the WorkerFactory type because I have read that the CSharp one is for GPU?

**Comment by AlexRibard** [comment]
You can find all these info here:
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Worker.md

* CPU
        `CSharpBurst`: highly efficient, jobified and parallelized CPU code compiled via Burst.
        `CSharp` : slightly less efficient CPU code.
        `CSharpRef`: a less efficient but more stable reference implementation.
* GPU
        `ComputePrecompiled` : highly efficient GPU code with all overhead code stripped away and precompiled into the worker.
        `Compute` : highly efficient GPU but with some logic overhead.
        `ComputeRef` : a less efficient but more stable reference implementation.

If you are working with a _CPU_ worker, the TensorToRenderTexture will crash.
For it to work, either change the worker to operate on the GPU or use the code I shared previously

**Comment by rotolonico** [comment]
Thanks!

**Comment by rotolonico** [comment]
Lastly, I am wondering, what does the Auto one do? I assume it checks if GPU is available and then fallbacks to CPU if it's not, but which factory does it actually use? I wasn't able to find this in the docs

**Comment by AlexRibard** [comment]
you are correct. If your device has a GPU, it defaults to ComputePrecompiled if not CSharpBurst

**Comment by rotolonico** [comment]
Cool! Would there be a way to know which one of the two was chosen or just a helper function that tells me whether the device I am running the code on has a GPU or not?

**Comment by AlexRibard** [comment]
You can use
`SystemInfo.supportsComputeShaders`
or
`SystemInfo.graphicsDeviceType == GraphicsDeviceType.Null`
