### ISSUE TITLE
Bad result with custom tiny yolo v2

### ISSUE THREAD

**Issue by RobinDenaux** [Unity-Technologies/barracuda-release#64]
Hi, I have a custom tiny yolo v2 model with 2 classes, trained with darknet, converted in a .pb with darkflow. So far all good, I tested both and got the expected boxes.

I tried exporting to onnx with tensorflow_to_barracuda.py but importing the onnx into unity throw this error :
```
InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
Google.Protobuf.CodedInputStream.ReadTag () (at T:/src/github/protobuf/csharp/src/Google.Protobuf/CodedInputStream.cs:389)
Onnx.ModelProto.MergeFrom (Google.Protobuf.CodedInputStream input) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Editor/Generated/Onnx.cs:1642)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Editor/ONNXModelImporter.cs:996)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <b488b1e4b0d9483380363f0744c5b6ab>:0)
```

I used tf2onnx instead and got a valid .onnx file, but the result I get are all wrong (using mostly this code https://github.com/Syn-McJ/TFClassify-Unity-Barracuda, with updated anchors and class count).
`python -m tf2onnx.convert --graphdef .\built_graph\saved_model.pb --output output.onnx --inputs input:0 --outputs output:0`

I'll add a zip with the relevant elements if someone can help me with this.
Thanks

models, test image & script : https://www.dropbox.com/s/wh6ou2ig4qthcj9/Bad_result_with_custom_tiny_yolo_v2_elements.zip?dl=0

**Comment by AlexRibard** [comment]
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Exporting.md

**Comment by AlexRibard** [comment]
You can follow this guide on how to export the model
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Exporting.md
I'll check your model's result

**Comment by RobinDenaux** [comment]
Thank you, I'm using tensorflow 1.15 as required for darkflow, can it be the problem ? 

I'll try the code version suggested in your link

**Comment by AlexRibard** [comment]
After investigation, it seems that there are some issues with tf2onnx.
When using --inputs-as-nchw it fails completely and adds transposes everywhere.
As a result when we go to the first Sub, dimensions matching with the constant fails. (constant is 1,1,1,16 and input at this point is 1,416,16,416), so the Broadcast fails.

If you are ok with it, I can post the issue on tf2onnx github?
In the meantime, try to explicitly write out the constants as being 1,16,1,1 in TF, maybe it would help.

**Comment by RobinDenaux** [comment]
Sure go ahead,
I'm in no hurry, I'll just wait to see if the bug get fixed. Can you put the link to the issue ?

if needed, the model generated from the script with tf_optimize : https://www.dropbox.com/s/d2ll20frszyq7y6/output_from_script_tensorflow.onnx?dl=0

**Comment by AlexRibard** [comment]
And here is the link to the tf2onnx issue
https://github.com/onnx/tensorflow-onnx/issues/977

**Comment by RobinDenaux** [comment]
I tried with the fix, all transpose but one are gone, but I don't get any boxes when running the model. 
The shape of the model and of the input is different between the pb and the onnx, but I can't tell if it's a problem.
https://www.dropbox.com/s/gen5ymzyuavp9lj/output_after_issue_977.onnx?dl=0

**Comment by AlexRibard** [comment]
Tested the new model against ONNXRuntime with random input. Getting correct results :)
Everything looks good!

As an explanation to why the dimensions changes between TF and onnx as well as what the `--inputs-as-nchw` means:
TF internal data layout is `NHWC` (batch x height x width x channels) so channels last
ONNX layout is `NCHW` (batch x channels x height x width) so channels first.
so a [1,416,416,3] input becomes transposed to a [1,3,416,416] in ONNX
By default tf2onnx keeps the same layout as TF, but makes it ONNX runnable. I.e: it adds a bunch of Transposed before problematic layers.
The flag `--inputs-as-nchw` tells the compiler that inputs will be `NCHW` so it can remove the transposes.

Hope that clarifies

**Comment by RobinDenaux** [comment]
Got it to work, thanks for your help!

I just noticed that in unity inspector my model inputs' shape is 0, 416, 3, 416 and output is -1, -1, -1, -1.
