### ISSUE TITLE
Running a model returns the same result every run

### ISSUE THREAD

**Issue by HaMMeRSI** [Unity-Technologies/barracuda-release#66]
Hello,

I have builded a model in pyTorch and exported it to ONNX to try with barracuda.
In pyTorch my model worked as expected in the testing but once I have imported the ONNX to unity and tried to peek an output the same output was returned each time.
I have followed the exact steps as in the tutorial, and using the latest version (1.0.0)

My models input is a 50*50 single chanel (0 / 1 value) jagged float array to represet an image and the output is 9 categories.

``` C#
private Model model;
private IWorker worker;
private void Start()
{
    model = ModelLoader.Load(modelAsset);
    worker = WorkerFactory.CreateWorker(model);
}
```

``` C#
public void Predict(float[][] points)
{
    TensorShape s = new TensorShape(1, 50, 50, 1);
    Tensor input = new Tensor(s, points);
    worker.Execute(input);
    var output = worker.PeekOutput();
    var result = output.data.Download(new TensorShape(1, 1, 1, 9));
    Debug.Log(string.Join(",", result));
    input.Dispose();
}
```

When I Run different tests the result print the same.

![image](https://user-images.githubusercontent.com/18597544/85414398-ba9e6d00-b574-11ea-8031-091ca002348e.png)

ONNX File
[onnx.zip](https://github.com/Unity-Technologies/barracuda-release/files/4820254/onnx.zip)

Please help I have no idea where is my mistake

**Comment by AlexRibard** [comment]
Hey!
Can you try printing accessing the output values as follows:
```
    var result = output.ToReadOnlyArray();
```
Or accessing directly via the Tensor
```
for(int i = 0; i < output.length; i++)
  float x = output[i];
```
Let me know.

**Comment by HaMMeRSI** [comment]
Thanks for the fast response alex,
I have changed it and the results are the same.
I also validated the onnx model with onnxruntime in python and it seemed to work as expected

**Comment by AlexRibard** [comment]
Ok, I don't see problematic issues with your model.
I'll validate it against onnxruntime with a random input to check.

Just to be sure:
* Inputs are changing every frame? 
* I see that you are Joining the results to a string. Are you clearing that string at every dispatch? Or checking the end of the string? If not the console will probably only log a few of the first elements which are the data from the first run.

**Comment by HaMMeRSI** [comment]
> yes

> I join them just to see the results, even if I replay unity the results are the same

**Comment by HaMMeRSI** [comment]
[BarracudaTester.zip](https://github.com/Unity-Technologies/barracuda-release/files/4823909/BarracudaTester.zip)
Here is a small tester with actuall data to demonstrate the issue

**Comment by AlexRibard** [comment]
ok thanks!
Taking a look at it

**Comment by AlexRibard** [comment]
@HuMMeRSI 
The issue is the following:
When creating a Tensor from a `float[][]`. The first dimension is the batch size, the rest should be of dim H*W*C.
So in your project, points is interpreted as a Tensor of 50 batches and rest [W*H*C] = 50.
So the construction is wrong.
```
float[][] points = new float[1][];
points[0] = new float[50 * 50];
// 1 batch and W*H*C = 50*50*1
for (int i = 0; i < 50; i++)
{
     var jarr2 = jarr[i] as JArray;
     for (int j = 0; j < 50; j++)
     {
          points[0][j + 50 * i] = int.Parse(jarr2[j].ToString());
     }
}
Tensor tensor = new Tensor(s, points);
```

or simply with a 1D array
```
float[] points = new float[50 * 50];
// 1 batch and W*H*C = 50*50*1
for (int i = 0; i < 50; i++)
{
     var jarr2 = jarr[i] as JArray;
     for (int j = 0; j < 50; j++)
     {
          points[j + 50 * i] = int.Parse(jarr2[j].ToString());
     }
}
Tensor tensor = new Tensor(s, points);
```

Running this yields different results for the runs.

**Comment by AlexRibard** [comment]
FYI.
* Remember to call `tensor.Dispose()` at the end of the for loop, else you'll leak memory.
* Same with `worker.Dispose()` when all work is done.
* Since your input is a 2D image, I debuged it with copying the tensor to a RenderTexture and displaying the result via:
```
RenderTexture inputRT = new RenderTexture(50, 50, 0);
inputRT.enableRandomWrite = true;
inputRT.Create();
tensor.ToRenderTexture(inputRT); // inputRT represents now the input tensor 
```

**Comment by AlexRibard** [comment]
Let me know

**Comment by HaMMeRSI** [comment]
Thaks alot alex, works like a charm!
Also thanks for the tips I will definitely use them.
