### ISSUE TITLE
Support for tensor data types other than float,int32 and int64?

### ISSUE THREAD

**Issue by AndrewJones-vt** [Unity-Technologies/barracuda-release#7]
Hi there.
We're doing some very interesting work with trained ResNet and MobileNet models which we're successfully running across various deviced in Unity using the Barracuda runtime via the built-in .onnx support. The vast majority of our weights are floats, and we're interested in being able to use small datatypes for (mainly) size reasons. I'm not intimately familiar with how mobile compute shader support might allow or hamper implementation of other datatypes, but we've converted one of our models from float to int8 with promising results outside of Barracuda, which of course won't import the model. Any chance of support for int8 and/or other small datatypes on the horizon?

Andrew

**Comment by mantasp** [comment]
Hi @AndrewJones-vt it's great to read that you find Barracuda useful! :)
At the moment we support only float32, though we have plans for float16 support, not sure about smaller formats. There are some limitations in how Unity supports compute shaders to have full float16 pipeline support, but we are working on improvements.
