### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by JackWei0310** [Unity-Technologies/barracuda-release#72]
Hi, I am a beginner for using unity. I met a problem when I tried to execute inputs.  I searched for reasons but I still had no idea. The problems are shown in the picture.
![image](https://user-images.githubusercontent.com/67232658/87228045-9e813500-c396-11ea-8785-62dbc9ff913b.png)
Here is the part of codes:
![image](https://user-images.githubusercontent.com/67232658/87228069-b3f65f00-c396-11ea-918c-40c3d85a6e8e.png)
And this is my model details:
![image](https://user-images.githubusercontent.com/67232658/87228144-12bbd880-c397-11ea-9fe3-a5ad2948d9f6.png)

**Comment by AlexRibard** [comment]
From what I can see the problem seems to be coming from the `Concat` op.
Would it be possible for you to provide your onnx file?

Thanks!

**Comment by JackWei0310** [comment]
> From what I can see the problem seems to be coming from the `Concat` op.
> Would it be possible for you to provide your onnx file?
> 
> Thanks!

Thanks. This is the link for my .onnx file.
https://drive.google.com/drive/folders/13wHU12FWsZOamS8tr1VswDnuljX24ZaT?usp=sharing

**Comment by JackWei0310** [comment]
> From what I can see the problem seems to be coming from the `Concat` op.
> Would it be possible for you to provide your onnx file?
> 
> Thanks!

Do you find the problem?

**Comment by JackWei0310** [comment]
I found a strange thing. There is a border2D. It should be Pad. And I can not found Border2D in Barracuda onnx operator document. What is it? Is it caused the problem?
![image](https://user-images.githubusercontent.com/67232658/87243476-27977b00-c42e-11ea-8c9b-27bc6a221c98.png)

**Comment by JackWei0310** [comment]
I found something strange which might cause the problem. When I put the model in unity. The input of Relu become the next concat input, so concat input is Relu inputs, it should be the Relu output as concat input, which might be caused the mistake. But I have no idea how to solve it.
![image](https://user-images.githubusercontent.com/67232658/87243843-37fd2500-c431-11ea-8241-4d284d088506.png)

**Comment by AlexRibard** [comment]
Hi @JackWei0310 
I've figured it out. We were missing a null_check in `ComputePrecompiled.Concat` causing the crash.
I've pushed a fix for the next version. I've also validated against ONNX runtime and get correct results.
In the meantime you can change your worker to be of type `Compute` it should work.
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Worker.md

Let me know

**Comment by AlexRibard** [comment]
Regarding your comment,
We do some optimization under the hood, and the Relu gets fused in the Conv node, thus why you don't see the Relu node anymore.
You can toggle compile time optimization ON/OFF in the inspector:
![image](https://user-images.githubusercontent.com/12990800/87253431-27f13f80-c449-11ea-9899-7cc80211c212.png)

**Comment by JackWei0310** [comment]
Yes. It works now. Thanks for helping!
By the way, I have a question about tensors. If  I have 3 textures and I want to combine them. Just like each one is a tensor(225,225,1). I want to combine them together as (225,225,3), which means each texture will be treated as a channel. Can I realize it?

**Comment by AlexRibard** [comment]
You can create it like this:
```
UnityEngine.Texture[] srcTextures = ...;
int channels = 3;
Tensor(srcTextures, channels, "myTensorName))
```

**Comment by JackWei0310** [comment]
> You can create it like this:
> 
> ```
> UnityEngine.Texture[] srcTextures = ...;
> int channels = 3;
> Tensor(srcTextures, channels, "myTensorName))
> ```

I just quickly try it. The tensor will be (3,225,225,3), But actually I want (1,225,225,3). I want 3 textures can be merged as a channel.

**Comment by AlexRibard** [comment]
Ah right, I see. 
In that case, you'll need to create 3 individual tensors from your Textures and `Concat` them.
```
// build a new model that concats 3 inputs
var builder = new ModelBuilder();
builder.Concat("concat", new[] { "tensor0", "tensor1", tensor2" }, 3);
var worker = WorkerFactory.CreateWorker(builder.model, WorkerFactory.Device.GPU);

worker.Execute(new Dictionary<string, Tensor> { { "tensor0", tensor0 }, { "tensor1", tensor1 }, { "tensor2", tensor2 } });
Tensor tensor = worker.PeekOutput();
```

**Comment by JackWei0310** [comment]
> Ah right, I see.
> In that case, you'll need to create 3 individual tensors from your Textures and `Concat` them.
> 
> ```
> // build a new model that concats 3 inputs
> var builder = new ModelBuilder();
> builder.Concat("concat", new[] { "tensor0", "tensor1", tensor2" }, 3);
> var worker = WorkerFactory.CreateWorker(builder.model, WorkerFactory.Device.GPU);
> 
> worker.Execute(new Dictionary<string, Tensor> { { "tensor0", tensor0 }, { "tensor1", tensor1 }, { "tensor2", tensor2 } });
> Tensor tensor = worker.PeekOutput();
> ```
Here is the problem when I copy these codes for testing.
![image](https://user-images.githubusercontent.com/67232658/87321830-a078fe80-c524-11ea-9be0-916aac49ea86.png)

**Comment by AlexRibard** [comment]
I would guess that the 3 input textures don't have the same spatial dimensions.
Be sure to resize them before creating the tensor.
the 3 tensors should have the same #batch #width #height for the Concat to work.

You can either resize by hand or by doing the following:
```
        var targetRT0 = RenderTexture.GetTemporary(225, 225, 0);
        Graphics.Blit(texture0, targetRT0, postprocessMaterial);

        Tensor tensor0 = new Tensor(targetRT0, 1);
```

**Comment by JackWei0310** [comment]
> I would guess that the 3 input textures don't have the same spatial dimensions.
> Be sure to resize them before creating the tensor.
> the 3 tensors should have the same #batch #width #height for the Concat to work.
> 
> You can either resize by hand or by doing the following:
> 
> ```
>         var targetRT0 = RenderTexture.GetTemporary(225, 225, 0);
>         Graphics.Blit(texture0, targetRT0, postprocessMaterial);
> 
>         Tensor tensor0 = new Tensor(targetRT0, 1);
> ```

The problem still exists. Here is my code:
![image](https://user-images.githubusercontent.com/67232658/87325532-7544de00-c529-11ea-8748-95da5a2459b8.png)
Here is 4 tensors shape:
![image](https://user-images.githubusercontent.com/67232658/87325666-a7eed680-c529-11ea-96c2-80dc70ed5c38.png)

**Comment by AlexRibard** [comment]
`Concat` axis should be 3 and not 4.
Dimension axis expects a dimension index and thus starts at 0.
So batch = index 0, height = index 1, width = index 2, channels = index 3
The axis parameter tells us which dimensions to concatenate on. Since you want channel, that is axis = channel dimension index = 3.

**Comment by JackWei0310** [comment]
> `Concat` axis should be 3 and not 4.
> Dimension axis expects a dimension index and thus starts at 0.
> So batch = index 0, height = index 1, width = index 2, channels = index 3
> The axis parameter tells us which dimensions to concatenate on. Since you want channel, that is axis = channel dimension index = 3.

Yes. You are right. Thanks for helping. You solved all my problems!
