### ISSUE TITLE
Unsupported Split operation

### ISSUE THREAD

**Issue by SestoAle** [Unity-Technologies/barracuda-release#74]
Hi,

I imported my ONNX model to Unity but it says 

`OnnxImportException: Unknown type Split encountered while parsing layer`

Is it possible to add Split operation to the supported ones?
I can't change the model cause it's built by a python framework.

Thanks!

**Comment by AlexRibard** [comment]
Should be doable. Adding it to the list

**Comment by MikeJanks** [comment]
I too would really like Split operation added

**Comment by re-cheid** [comment]
+1 I'd also need that Split operation

**Comment by AlexRibard** [comment]
`Split` got implemented and will land in the upcoming release.
I will let you know once that is out

**Comment by mantasp** [comment]
`Split` support was released with Barracuda `1.2.0-preview`
