### ISSUE TITLE
Manual doesn't clarify what is 'Auto' Worker type

### ISSUE THREAD

**Issue by Marcloure** [Unity-Technologies/barracuda-release#75]
https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/manual/Worker.html

The manual lists the different approaches, but it doesn't say anything about the 'Auto' option. Does it automatically pick the best supported option or what?

**Comment by AlexRibard** [comment]
Hi!
Sorry for the confusion.
Atm `Auto` does not do much; it defaults to GPU.

The idea was for it to do a fancier selection, but we haven't gotten to this yet.
I'll update the documentation.
