### ISSUE TITLE
NotSupportedException: Format version not supported: 241

### ISSUE THREAD

**Issue by vra** [Unity-Technologies/barracuda-release#76]
Hi all!
I convert a pytorch model to onnx with pytorch version 1.0,0, when load the onnx file using modelloder, error comes:
```csharp
_model = ModelLoader.Load(myModelPath)
```
error:
```
NotSupportedException: Format version not supported: 241
Unity.Barracuda.ModelLoader.Load (System.IO.BinaryReader fileReader, System.Boolean verbose, System.Boolean applyPatching, System.Boolean skipWeights) (at D:/ThreeDPoseTracke_yunran_taobao_v2/ThreeDPoseTracker_yunran_taobao_v2/Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Runtime/Core/ModelLoader.cs:70)
Unity.Barracuda.ModelLoader.Load (System.String filepath, System.Boolean verbose, System.Boolean skipWeights) (at D:/ThreeDPoseTracke_yunran_taobao_v2/ThreeDPoseTracker_yunran_taobao_v2/Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Runtime/Core/ModelLoader.cs:40)
TmpBarracudaRunner.Start () (at Assets/Scripts/TmpBarracudaRunner.cs:232)
```

Does this mean my pytorch version is too new? But I guess pytorch 1.0.0 is a quite normal version for now. Could you please help me with this? Thanks in advance.

**Comment by mantasp** [comment]
Is your ONNX file part of Assets filesystem in your Unity project?

**Comment by vra** [comment]
> Is your ONNX file part of Assets filesystem in your Unity project?

no, I just added the onnx file to the folder named `Assets/StreamingAssets` by `Ctrl-C` `Ctrl-V`. Maybe I need to add it explicity using menu in Unity project?

**Comment by mantasp** [comment]
Currently ONNX importing is supported only via Unity Editor importing mechanisms, which means model should outside of StreamingAssets folder. You basically have two choices:
1.  place model somewhere under Assets, but outside of StreamingAssets, then add public NNModel field to your Monobehaviour script and just connect it to your ONNX model in the scene. Like with any other asset type. Then you can pass contents of NNModel field to the ModelLoad.Load() method. You could look this example project for the sample setup: https://github.com/mantasp/Barracuda-SqueezeNetTest
2. place model somewhere under Resources folder, then load it at runtime via ModelLoader.Load(Resources.Load<NNModel>("yourmodelfile_without_onnx_extension")).

**Comment by vra** [comment]
Hi @mantasp ,
Thanks for your solutions. I tried the 2nd approach and it works! exactly command that I used is:
```csharp
// My onnx file is located in `Resources` folder with name `sml_model.onnx`
_model = ModelLoader.Load((NNModel)Resources.Load("sml_model"));
```
Thanks again for help
