### ISSUE TITLE
Tensor get output spikes

### ISSUE THREAD

**Issue by DanielDorDev** [Unity-Technologies/barracuda-release#79]
Hello, 
I am having trouble with using the model output

Basic idea , use the result
***
var output = worker.PeekOutput(outputLabel);

doSomething(output)

***

Because the work is done on cpu , i know the device data need to be downloaded
So i add: 
***
output .PrepareCacheForAccess(false);
***

And then wait for some frames, but still i get "wait for" spikes

What is the correct way ? 

Thank you:)

**Comment by mantasp** [comment]
Could you please try code from this example and let us know if you still see the issue?
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.1/Barracuda/Runtime/Core/Barracuda.cs#L85

**Comment by DanielDorDev** [comment]
Using WaitForCompletion worked
(execute() freezes, so i use worker.StartManualSchedule())

Thank you !

**Comment by DanielDorDev** [comment]
I am still having huge spikes 
Is there option to wait for the execution to finish?

![Screenshot (45)](https://user-images.githubusercontent.com/51891040/90274029-8a829480-de68-11ea-91ca-898c5bb60b89.png)

**Comment by amirebrahimi** [comment]
You could try this model, which synchronizes every nth layer:
https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/manual/ModelExecution.html

**Comment by DanielDorDev** [comment]
Thank you, but i got 99 layers (resnet50), some layers i guess freeze  the render thread

**Comment by DanielDorDev** [comment]
@mantasp Okey, i found the what causes the spikes, 
I didn't notice it at first, until i deep profile the gpu, it gives me a new perspective about NN in and StartManualSchedule,
Until now i sync every n layer, it was mistake, not all layers are the same, some conv2 layers took most of the time, 
for now i manually path sync, so the heavy layers sync every frame, and the simple one 10-20 in frame.
It is Intresting subject ,if it is possible to score layers (by size or complex op) , and then create schedule manager, and facade style, ask the manager to schedule by target frame

IEnumerator BarracudaManager.ScheduleBalance(NumberSlicesTarget: int)

**Comment by amirebrahimi** [comment]
Internally, we have something sort of like that called `StatsOps` for resource estimates, but it isn't exposed as a backend.

**Comment by DanielDorDev** [comment]
I think it is a problem with conv2, because only this op gives very high spike (76ms)
