### ISSUE TITLE
tf2.x   module 'tensorflow' has no attribute 'GraphDef'

### ISSUE THREAD

**Issue by xunyiljg** [Unity-Technologies/barracuda-release#8]
This error occurs when .pb is converted to. nn.     maybe in tf2, it is called tf.compat.v1.GraphDef? when i used the new one, the other error occurs:
![image](https://user-images.githubusercontent.com/28186769/71307984-641f6d00-2431-11ea-8d10-cd07b1cf5bba.png)

It's exciting to be able to run the neural network in unity, hoping to fix the bugs in the transformation.  also hope to add conv2d-transpose(deconvolution) and up-sampling layer, which is also common.

**Comment by robinydv** [comment]
Hi @xunyiljg, how did you fix the problem? I have the same issue.

**Comment by mantasp** [comment]
@xunyiljg any chance to look into your .pb file? How did you save it?

**Comment by Cecil16** [comment]
I get the same issue.

**Comment by mantasp** [comment]
@Cecil16 could you please share your network file? Thanks!

**Comment by Cecil16** [comment]
> 
> 
> @Cecil16 could you please share your network file? Thanks!

I try to convert tensorflow pb file to barracuda with the appropriate python script :
`python tensorflow_to_barracuda.py saved_model.pb saved_model.nn`
Unfortunately I get the same error @xunyiljg describes.
Here is the pb file.
[saved_model.zip](https://github.com/Unity-Technologies/barracuda-release/files/4102220/saved_model.zip)

Hope it will help.

**Comment by AlexRibard** [comment]
@Cecil16 are you sure to have exported the model correctly?
Could it be that the model isn't frozen? On my side I get a really big and complicated model...
