### ISSUE TITLE
IOps concat does not work on GPU (NullReferenceException)

### ISSUE THREAD

**Issue by albanmdb3d** [Unity-Technologies/barracuda-release#80]
Hello, 

I believe you are aware of this bug but I'm reporting it because the context is slightly different and it might benefit the community. 
When using: `m_Ops = new PrecompiledComputeOps();`, calling `m_Ops.Concat(new[] {tensor1, tensor2}, 0)` returns NullReferenceException. The work around is to do it on CPU: `IOps m_Ops_cpu = new BurstCPUOps();`
Cheers.

**Comment by mantasp** [comment]
Bit curious why are you calling Ops directly?

**Comment by albanmdb3d** [comment]
I have to do some post-processing after my network inference. Using an ONNX model does not cut it because I use some custom operators that are not implemented in Barracuda.

**Comment by AlexRibard** [comment]
can you post your callstack?
When creating a `PrecompiledComputeOps` you need to give it the kernels else it won't find them. You can create it like so:
```
            return new PrecompiledComputeOps(ComputeShaderSingleton.Instance.kernels,
                                            ComputeShaderSingleton.Instance.referenceKernels);
```
Let me know if it helps

**Comment by albanmdb3d** [comment]
Here is a snippet that yields the same error. I don't have issues with other operators (e.g. StridedSlice, Min, Sub, etc.). Hope that helps to narrow down the issue.

using UnityEngine;
using Unity.Barracuda;
public class ModelInference : MonoBehaviour
{
    private IOps m_Ops;
    private IOps m_Ops_cpu;

    // Start is called before the first frame update
    void Start()
    {
        m_Ops = new PrecompiledComputeOps(ComputeShaderSingleton.Instance.kernels, ComputeShaderSingleton.Instance.referenceKernels);
        // m_Ops_cpu = new BurstCPUOps();  // TEMPORARY: Concat and other operators do not work on GPU yet, using CPU

        Tensor t1 = new Tensor(4, 1, 1, 6);
        Tensor t2 = new Tensor(4, 1, 1, 2);

        Tensor output = m_Ops.Concat(new[] {t1, t2}, 3);

    }

**Comment by AlexRibard** [comment]
Ah sorry, 
`PrecompiledOps` is more complicated that `ComputeOps` as it involves baking out part of the execution.
So for you to use it you need some setup.
```
    private PrecompiledComputeOps m_Ops;
    void Start()
    {
        m_Ops = new PrecompiledComputeOps(ComputeShaderSingleton.Instance.kernels, ComputeShaderSingleton.Instance.referenceKernels);

        Model model = new Model();
        m_Builder = new ModelBuilder(model);
        m_Builder.Concat("concat", new[] { "input0", "input1" }, 3);

        m_Ops.PrepareModel(model, new Dictionary<string, TensorShape>() { ["input0"] = new TensorShape(4, 1, 1, 6), ["input1"] = new TensorShape(4, 1, 1, 2) });
        
        Tensor t1 = new Tensor(4, 1, 1, 6);
        Tensor t2 = new Tensor(4, 1, 1, 2);
       
        m_Worker = WorkerFactory.CreateWorker(WorkerFactory.Type.ComputePrecompiled, model);
        m_Worker.Execute(new Dictionary<string, Tensor>() { ["input0"] = t1, ["input1"] = t2 });
}
```
We need to call `PrepareModel` to pre-compute part of the network ops.

For `ComputeOps` you can use your code that works as there is no precomputation passes
```
   private IOps m_Ops;
    
    void Start()
    {
        m_Ops = new ComputeOps(ComputeShaderSingleton.Instance.kernels, ComputeShaderSingleton.Instance.referenceKernels);

         Tensor t1 = new Tensor(4, 1, 1, 6);
         Tensor t2 = new Tensor(4, 1, 1, 2);
        
         Tensor output = m_Ops.Concat(new[] {t1, t2}, 3);
   }
```

**Comment by mantasp** [comment]
You also could use ModelBuilder to just append Concat operation right to your network.

**Comment by albanmdb3d** [comment]
Hmmmm I see thank you for that. This makes me wonder. I assume PrecompiledComputeOps is faster than using ComputeOps. By how much roughly?

**Comment by AlexRibard** [comment]
It really depends on the operator (some Conv2D and ConvTranspose it is 5% faster I would say). It is mostly much better on the CPU side.

**Comment by albanmdb3d** [comment]
Thank you for the help I'm closing the issue
