### ISSUE TITLE
Train mlagents executable environment by pytorch, converting and inference 

### ISSUE THREAD

**Issue by Maxpridy** [Unity-Technologies/barracuda-release#82]
Hi. I was trying a few things.
Let me tell you what I've been doing.

1. make mlagents executable environment. FoodCollector.
2. Learn from outside with a pytorch.
3. Convert the pytorch model to onnx(using torch.onnx.export, modify some names)
4. Like .nn file, drag and drop .onnx in Unity editor.

I did this for the freedom of learning.

https://github.com/Unity-Technologies/ml-agents/issues/3096
I have referenced this issue. and it was executed successfully. 
It runs inside the Unity editor.

But the agent didn't inference the same. 
In my code, inference of 'executable' tends to turn right.
But in the Unity editor, it looks completely different. It is a different model even with the naked eye.

What am I missing and how can I do the same inference?
I want to know what to pay attention to when doing the conversion.
Thanks for the help.

**Comment by mantasp** [comment]
Hi @Maxpridy, could you please share your ONNX file so we could look into it?
Thanks!

**Comment by Maxpridy** [comment]
https://drive.google.com/file/d/1tqO6yKJELzfur6abGghBscSKvjtd5pKs/view?usp=sharing

- What I did when converting

1. I don't know normal usage, so I forcibly inserted a constant. 
The only example of putting constants in pytorch model was a something strange example.

2. And I used actionflatten. (3, 3, 3, 2) -> (54).
Could this be a problem? I think it will be a problem because the default is MultiDiscrete.

3. Conversion source
`net.load_state_dict(torch.load("save_195.pt"))`
`x = torch.randn(10, 53)`
`torch.onnx.export(net, x, "example.onnx", export_params=True, opset_version=11, input_names = ['vector_observation'], output_names = ['action'], dynamic_axes={'vector_observation' : {0 : 'batch_size'}, 'action' : {0 : 'batch_size'}})`

and added it like this.

`memory_size = np.array([0])`
`add_node_1 = onnx.helper.make_node(
    'Constant',
    inputs=[],
    outputs=['memory_size'],
    value=onnx.helper.make_tensor(
        name='memory_size',
        data_type=onnx.TensorProto.FLOAT,
        dims=memory_size.shape,
        vals=memory_size.flatten().astype(float),
    ),
)`
`onnx_model.graph.node.extend([add_node_1])`

The other three RequiredConstants were also put in this way.

Additionally, actions inside the Unity editor appear in a form that is rarely learned. It is almost random.

I am very sorry for the lack of understanding of the library. Thanks!

**Comment by mantasp** [comment]
@Maxpridy I tested your ONNX model (via onnxruntime) against Barracuda and their outputs are matching closely. So maybe it's an exporting issue. Could you please check on your end if Pytorch output matches onnxruntime output?

**Comment by Maxpridy** [comment]
![pytorch_inference](https://user-images.githubusercontent.com/16449397/92059621-af658a00-edcc-11ea-9d3f-6e1109380d71.JPG)
This is pytorch inference 

![onnx_inference](https://user-images.githubusercontent.com/16449397/92059637-bc827900-edcc-11ea-9c25-17a7484f5e0d.JPG)
and this is onnx inference. 
(input is np.array([1.0]*53))

I think it is due to the difference in output. The output(action size) of my model(ActionFlattener) is 54(3\*3\*3\*2), but the output of FoodCollector(MultiDiscrete or Branched) is 11(3+3+3+2). The two may have the same output, but very different in the model level. But I want to use the former.

I don't know why it doesn't get error in CheckDiscreteActionOutputShape. maybe 4 != 54(branches / actions)
Should I learn with MultiDiscrete? or... Is the problem elsewhere?

I'm also trying to run it with barracuda.

**Comment by Maxpridy** [comment]
Looking at the ml-agents code(C#), I think I know how. 

I think it's too broad a question, so I'll close it.
