### ISSUE TITLE
Importing GPT-2 into barracuda

### ISSUE THREAD

**Issue by eublefar** [Unity-Technologies/barracuda-release#86]
Hi,
 
I have been trying to import ONNX [Huggingface](https://huggingface.co/transformers/) GPT-2 pretrained transformer into barracuda. 
It was failing to import and after applying "Treat Errors as Warnings" I found a lot of issues:
- Unsupported operators: Range, Split and Where.
- Other failures that could be affected by unknown ops since they are replaced by identity layer:
   - Tensors of rank 5 (only rank 4 or less are supported).
   - Constants are not supported for input in nodes Gather, Reshape, MatMul and bunch of others.

Are these features coming any time soon?

I have also tried to implement these operators with CPU reference back-end. I was able to successfully implement Range op (at least the warning during import disappeared, didn't test the back-end impl), but Split operator requires new attribute **split** that is not present in Layer class and I have no idea how to add it. 

If these features are not on the road map could you please help me with implementing support for this model on CPU?

To get the onnx file I am using (you will need linux):
install pytorch
```
pip install transformers
python -m transformers.convert_graph_to_onnx --framework pt --model microsoft/DialoGPT-medium models/gpt2.onnx --opset 11 --check-loading
```

**Comment by AlexRibard** [comment]
Hi @eublefar !
I'm currently working on it. I was going to support the default transformer architecture from Pytorch. But I can check out how well we support GPT-2.
Would it be possible that you share your onnx model via drive or an archive?
Thanks!

**Comment by eublefar** [comment]
Oh, that is great news!
Here is the onnx file (opset 11):
https://drive.google.com/file/d/1FTWP7FI6azKILXyb0X9SXyme_HZo9LpK/view?usp=sharing

**Comment by AlexRibard** [comment]
Thanks!

**Comment by amidos2006** [comment]
Is there a solution to that problem? I have been trying to run GPT2 in Unity. My first intuition was to use the c++ binding of pytorch and use Torchscript to save my models but when I was googling I found this. I was wondering if you manage to make it work.

Also, an unrelated question: is there a good implementation of tokenizer for Unity or should I reimplement that?

Sorry for disturbance

**Comment by eublefar** [comment]
Hi, @amidos2006 

I think you can directly build and add C# [ONNX runtime](https://github.com/microsoft/onnxruntime) API to Unity (did not test execution but compilation worked on Unity 2019.3.13f1, requires manually downloading and importing all missing NuGet packages that it will throw errors about). You'll just need to pick correct provider during onnx runtime build depending on your target platform.

I did not find C# implementation of byte-level BPE tokenizer so, since I am lazy, I am just using python sidecar onnx runtime with Huggingface tokenizers. I pack it with pyinstaller for distribution.
There is C# tokenizer lib https://github.com/microsoft/BlingFire, but it does not have byte-level BPE AFAIK.

P.S. LMK if you figure out tokenization in C#.

**Comment by amidos2006** [comment]
That is nice to know that I do not need to use barracuda and can use ONNX runtime directly in Unity. 

About the tokenizer, I need to read more about GPT2 tokenizer to see what exactly it is using because I am still new using GPT2 but from what I understood is that GPT2 is using byte-level BPE tokenizer. I was wondering when you said python sidecar onnx runtime, does this mean it is like a server for Unity or Unity is not part of the equation anymore?

Sorry for lots of questions

**Comment by AlexRibard** [comment]
Side note on this:
GPT2 and transformers in general are actively being worked on.
We have a few issues to iron out on our end (mostly related to shape logic).
If you are building your own Transformer we recommend you hard code shape related manipulations in the meantime.
We'll let you know when everything is up and running.
Sorry for the delay.

**Comment by amidos2006** [comment]
Thanks @AlexRibard :) looking forward to the update.

**Comment by eublefar** [comment]
> I was wondering when you said python sidecar onnx runtime, does this mean it is like a server for Unity or Unity is not part of the equation anymore?

Like a local server for Unity. Unity starts child process and communicates with it over ZMQ.

**Comment by FlorentGuinier** [comment]
Added to backlog :) (however no ETA for now). Closing the issue then.
