### ISSUE TITLE
difference in inputs (cv2.imread in python and texture2d in unity)

### ISSUE THREAD

**Issue by mohsen0311** [Unity-Technologies/barracuda-release#87]
I trained my model with pytorch and load my images that used for training with cv2 but in unity I use texture2d that obtained from a camera (target texture) but the result are have a little bit difference that in my case is not acceptable . is there any chance to fix this differences?

**Comment by AlexRibard** [comment]
Could you clarify what you mean by `result are have a little bit difference`?
Have you tried running your model with a training example in Unity to validate?
If you save the camera texture to disk and plug that into pytorch, do you get the result you are looking for?

**Comment by FlorentGuinier** [comment]
@mohsen0311 Closing as issue did not get an update, please reopen if needed.
