### ISSUE TITLE
Neural Net running on development build but app crashes on the normal/release build

### ISSUE THREAD

**Issue by sid0913** [Unity-Technologies/barracuda-release#90]
I'm trying to run an android game that uses barracuda and a neural net of mine. The app works on my android device only when I tick the development build box. What is the fundamental difference in these two builds that may be causing this issue?

**Comment by mantasp** [comment]
Hi @sid0913,
in general there should be no difference. Which GFX API are you using on device? Vulkan or Open GLES?

**Comment by sid0913** [comment]
It's open GLES

**Comment by sid0913** [comment]
I've also tried Vulkan

**Comment by mantasp** [comment]
@sid0913 do you see the same issue with Vulkan? (we don't support OpenGLES for running Barracuda on GPU)

**Comment by AlexRibard** [comment]
Could you also provide us the model in question? That way we could validate the issue easily?

**Comment by sid0913** [comment]
Thanks for your response. Yes I see the same issue with Vulkan. I'm trying to use the onnx mobilenet model from onnx's github page

**Comment by AlexRibard** [comment]
sorry for the late reply.
Does the model runs now?
We do have all of the onnx github models working and in our CI atm. So could you provide more details on how the specific hardware you are running with?

**Comment by FlorentGuinier** [comment]
@sid0913 closing the issue as there were no update on it. Please reopen if you are still experiencing the problem.
