### ISSUE TITLE
Kernel TextureToTensor and TextureToTensor_NHWC are both missing with CPU worker

### ISSUE THREAD

**Issue by castanor** [Unity-Technologies/barracuda-release#93]
Hi everybody,

I had to switch to GLES 2.0 on android and the detection stopped working with the error: 
Kernel TextureToTensor and TextureToTensor_NHWC are both missing. 

I tried with Barracuda 1.0.0 (also Barracuda 1.0.3), worker of type CSharpBurst and Unity 2019.3.3.

Is there any way to make the detection work with GLES?

Thanks

**Comment by mantasp** [comment]
@castanor at the moment to convert Texture to Tensor you have to run on graphics API that supports compute shaders, which means GLES 3.1, Vulkan, Metal or DX11.
What kind of texture are your trying to convert to Tensor? Is it RenderTexture, regular Texture2D or maybe WebCamTexture?

**Comment by castanor** [comment]
@mantasp thanks, I tried with both RenderTexture and Texture2D but it's not working with gles2. There is any other way to create a tensor?

Thanks

**Comment by mantasp** [comment]
There is a number of overloads for Tensor creation: https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/api/Unity.Barracuda.Tensor.html
You could use `public Tensor(int n, int h, int w, int c, float[] srcData, string name = "")`, assuming you get pixel data into float[] array before that.

**Comment by castanor** [comment]
Thank you for the info, I was able to solve my problem.
