### ISSUE TITLE
Custom onnx model doesn't works

### ISSUE THREAD

**Issue by mosca-ops** [Unity-Technologies/barracuda-release#94]
I created a custom dataset from Yolov2 and i converted it in onnx model. The onnx model I think is ok but in runtime there are two errors: 

> KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <fb001e01371b4adca20013e0ac763896>:0)
Unity.Barracuda.PrecompiledComputeOps.PrepareModel (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at Library/PackageCache/com.unity.barracuda@1.1.1-preview/Barracuda/Runtime/Core/Backends/BarracudaPrecompiledCompute.cs:241)
Unity.Barracuda.StatsOps.PrepareModel (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at Library/PackageCache/com.unity.barracuda@1.1.1-preview/Barracuda/Runtime/Core/Backends/StatsOps.cs:44)
Unity.Barracuda.GenericWorker+<StartManualSchedule>d__29.MoveNext () (at Library/PackageCache/com.unity.barracuda@1.1.1-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:166)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <d1422b3fc93746018c92eda852993b93>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<Detect>d__19:MoveNext() (at Assets/Scripts/Detector.cs:68)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
PhoneCamera:<TFDetect>b__22_0(Color32[]) (at Assets/Scripts/PhoneCamera.cs:167)
<>c__DisplayClass23_0:<ProcessImage>b__0(Texture2D) (at Assets/Scripts/PhoneCamera.cs:184)
TFClassify.<CropSquare>d__2:MoveNext() (at Assets/Scripts/TextureTools.cs:97)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

and 

> KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <fb001e01371b4adca20013e0ac763896>:0)
Unity.Barracuda.GenericVars.PeekOutput (System.String name) (at Library/PackageCache/com.unity.barracuda@1.1.1-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:1071)
Unity.Barracuda.GenericVarsWithReuse.PeekOutput (System.String name) (at Library/PackageCache/com.unity.barracuda@1.1.1-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:1173)
Unity.Barracuda.GenericWorker.PeekOutput (System.String name) (at Library/PackageCache/com.unity.barracuda@1.1.1-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:857)
Detector+<Detect>d__19.MoveNext () (at Assets/Scripts/Detector.cs:70)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <d1422b3fc93746018c92eda852993b93>:0)

I ran it in this project: https://github.com/Syn-McJ/TFClassify-Unity-Barracuda with:
-unity 2019.4
-barracuda 1.1.1
and I built the custom model (yolov2) with darkflow

**Comment by mantasp** [comment]
Hi, most likely you are omitting some of the required network inputs.

**Comment by mosca-ops** [comment]
which required network inputs?

**Comment by AlexRibard** [comment]
you can inspect the model inputs in the UI Inspector.
Be sure to name your inputs as expected as have the same shape as shown in the UI.
Let me know

**Comment by FlorentGuinier** [comment]
@mosca-ops closing the issue as there were no update on it. Please reopen if you are still experiencing the problem.
