### ISSUE TITLE
Concatenate/Stack output of one model and feed it as input to another 

### ISSUE THREAD

**Issue by chinmaychinara91** [Unity-Technologies/barracuda-release#97]
barracuda version: 1.1.2 (preview)
pytorch: 1.3

**If I got this right on exporting an onnx from PyTorch it gets input in the format [BCHW] but on porting into Unity it follows [BHWC].**

Now I have two models:

Model1: 
Resnet with input [B=1, C=3, H=224, W=224] exported from PyTorch to onnx which shows in Unity as:
![in1](https://user-images.githubusercontent.com/21283733/96693828-8d07db80-133c-11eb-9163-b73749860c06.PNG)
Output as a 1D-512 channel feature vector which on Unity shows as:
![o1](https://user-images.githubusercontent.com/21283733/96694013-c2142e00-133c-11eb-8644-780a95e2c757.PNG)

Model2:
Conv1d classifier with input as [B=1, C=60, H=1, W=512] exported from PyTorch to onnx which shows in Unity as:
![in2](https://user-images.githubusercontent.com/21283733/96694154-f0920900-133c-11eb-90b4-b11261da34e6.PNG)
Ouput as 6 classes which on Unity shows as:
![o2](https://user-images.githubusercontent.com/21283733/96694255-14554f00-133d-11eb-84bb-98f1482da73e.PNG)

Questions:
1. Is the conversions from onnx to Unity correct in the above images of shapes?
2. If yes then, how can I stack/concatenate inference from Model-1 to get 60 feature vectors of dim. 512 **inside Unity** so that I can pass it into Model-2 for inference ? 
As per my current definition, Model-2 expects 1 batch of 60 channel 1D-512 feature vectors. 
Is it better if I can change my Model-2 input to be 60 batches of 1D-512 channel feature vectors i.e. [B=60, H=1, W=1, C=512] ? Either way how can I do the stacking ?

Really appreciate the help.

**Comment by AlexRibard** [comment]
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/TensorHandling.md
Yes you are correct, Barracuda is NHWC layout. Let me add that our shapes are padded no matter what so a 2D NC tensor in Barracuda will be layout as N,1,1,C.
Question1:
Let's analyze the input outputs
* input: N=1,C=3,H=224,W=224 onnx gets transposed to N=1,H=224, W=224, C=3 barracuda
* resnet output is actually 1x512 in onnx so N=1, C=512 onnx gets transposed to N=1, C=512 (H=1,W=1)
* input: N=1,C=3,H=1,W=224 onnx gets transposed to N=1,H=1, W=224, C=3 barracuda
* resnet output is actually 1x6 in onnx so N=1, C=6 onnx gets transposed to N=1, C=6 (H=1,W=1)
So conversion looks correct to me.
Question 2:
A few ways: 
* either you build the tensor by hand. By accessing how you see fit. (this has the draw back from copying the tensors from CPU to GPU)
```
for (k = 0; k<512 k++)
      for (i = 0; i<60 i++)
       concatenatedTensor[1,1,k,i] = outputTensor[k]
```
* or via a few ops
```
private ComputeOps m_Ops;
...
outputTensor = m_Ops.Reshape(outputTensor, new []{1,1,512,1}) // reshape tensor to be N=1,H=1,W=512,C=1
for (i = 0; i<60 i++)
    concatenatedTensor = m_Ops.Concat(new [] {concatenatedTensor, outputTensor}, 3); // concat both tensor on axis 3 = C
```
To do this, you can either use the `ModelBuilder` to add nodes to your network. Declare a ComputeOps and call said opperators
c.f. https://github.com/Unity-Technologies/barracuda-release/issues/80 for more details.

* last method: build a pytroch/onnx model that concats everything the way you want it and use this

But I wouldn't change your model input/outputs.

Let me know if it works

**Comment by chinmaychinara91** [comment]
@AlexRibard Thanks a lot for the input let me try these will keep you posted.

**Comment by chinmaychinara91** [comment]
I tried the following as per method of ops rather than copying from cpu to gpu which I feel will make things less realtime and memory inefficient:

```
private ComputeOps m_Ops;
Tensor concatenatedTensor;
int count = 0; //count no of tensors

void Start()
{
   concatenatedTensor = new Tensor();
}

void Classify()
{
   // till 60 tensors are received from Model-1 inference
   outputTensor = m_Ops.Reshape(outputTensor, new TensorShape(1,1,512,1)); // reshape tensor to be N=1,H=1,W=512,C=1
   concatenatedTensor = m_Ops.Concat(new [] {concatenatedTensor, outputTensor}, 3); // concat both tensor on axis 3 = C
      
   if(count==60)
   {
       //call Model-2 operation passing concatenatedTensor of dim N=1,H=1, W=512, C=60
   }
   count++;
}
```

It gave me the following error:
"NullReferenceException: Object reference not set to an instance of an object" pointing to the line:
`outputTensor = m_Ops.Reshape(outputTensor, new TensorShape(1,1,512,1)); // reshape tensor to be N=1,H=1,W=512,C=1`

Just if you noticed I used `new TensorShape(1,1,512,1)` as compared to `new []{1,1,512,1}` what you recommended above as it was giving "Cannot convert int[] to UnityEngine.Barrcuda.TensorShape" error.

Do I need to create an instance of m_Ops in the Start() function? If yes what kind of instance. I followed #80 but was not very clear with it. Is there some other blunder I might be commiting ?

**Comment by AlexRibard** [comment]
Ah my bad for the Reshape, you are correct.
Yes you need to create the ComputeOps in the start function. Or when you declare it.
You do it like so
`m_Ops = new ComputeOps(ComputeShaderSingleton.Instance.kernels, ComputeShaderSingleton.Instance.referenceKernels);`
or 
`m_Ops = = new ReferenceComputeOps(ComputeShaderSingleton.Instance.referenceKernels);`
If that doesn't work let me know.
You could also use the model builder to build a new model
```
ModelBuilder builder;
Model model = new Model();
builder = new ModelBuilder(model);
var input0 = new Model.Input(); input0.name = "input0"; input0.shape = ...
var input1 = new Model.Input(); input1.name = "input1"; input1.shape = ...
builder.model.inputs.Add(input0); builder.model.inputs.Add(input1);
builder.model.outputs = new [] {"concat0"};
builder.Reshape("reshape0","input0", new []{1,1,512,1});
builder.Concat("concat0", new [] {"reshape0", "input1"}, 3);
```
now `model` is build and you can run it like any model.

**Comment by chinmaychinara91** [comment]
Awesome so now I did that and I am able to concatenate the tensors as [B=1, H=1, W=512, C=60] i.e. I get a tensor of dimension [1,1,1,1,1,1,512,60] when passed to the Model-2 which expects the same input dimension as has the same dimension i.e.
![image](https://user-images.githubusercontent.com/21283733/96801415-6ab5a280-13bc-11eb-869a-59a439eba741.png)

I get this error:

AssertionException: Assertion failure. Values are not equal.
Expected: 1 == 512
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <480508088aee40cab70818ff164a29d5>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <480508088aee40cab70818ff164a29d5>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at <480508088aee40cab70818ff164a29d5>:0)
UnityEngine.Assertions.Assert.AreEqual (System.Int32 expected, System.Int32 actual) (at <480508088aee40cab70818ff164a29d5>:0)
Unity.Barracuda.PrecompiledComputeOps.Conv2D (Unity.Barracuda.Tensor X, Unity.Barracuda.Tensor K, Unity.Barracuda.Tensor B, System.Int32[] stride, System.Int32[] pad, Unity.Barracuda.Layer+FusedActivation fusedActivation) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/Core/Backends/BarracudaPrecompiledCompute.cs:630)
Unity.Barracuda.StatsOps.Unity.Barracuda.IOps.Conv2D (Unity.Barracuda.Tensor X, Unity.Barracuda.Tensor K, Unity.Barracuda.Tensor B, System.Int32[] stride, System.Int32[] pad, Unity.Barracuda.Layer+FusedActivation fusedActivation) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/Core/Backends/StatsOps.cs:69)
Unity.Barracuda.GenericWorker+<StartManualSchedule>d__29.MoveNext () (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:218)
Unity.Barracuda.GenericWorker.Execute () (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:118)
Unity.Barracuda.GenericWorker.Execute (System.Collections.Generic.IDictionary`2[TKey,TValue] inputs) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:106)
ResnetLstmClassifier+<Classify>d__15.MoveNext () (at Assets/MSELI/Examples/BehaviorGenerator/ClassificationDetection/Scripts/ResnetLstmClassifier.cs:84)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <480508088aee40cab70818ff164a29d5>:0)

So I closely checked this some shape issue it is having wrt the Conv2D layer in BarracudaPrecompiledCompute.cs line 630 which says `Assert.AreEqual(X.channels, K.kernelDepth);`. Somewhere there is being a shape issue somewhere.

Also to add `builder.Concat("concat0", new [] {"reshape0", "input1"}, 3);` or any Concat, the last concatenation dimension in this case would be 7 not 3 thats how it worked for me as it is expecting an 8D tensor.
 
Sharing you Model-2 onnx here:
[crnn_conv1d_decoder.zip](https://github.com/Unity-Technologies/barracuda-release/files/5419231/crnn_conv1d_decoder.zip)

**Comment by AlexRibard** [comment]
ok let me check the model

**Comment by AlexRibard** [comment]
ok found out the issue. It will be fixed in the upcoming release.
I also validated your model against onnx runtime, things are good.
In the meantime, let me send you the fix via email

**Comment by chinmaychinara91** [comment]
> Awesome so now I did that and I am able to concatenate the tensors as [B=1, H=1, W=512, C=60] i.e. I get a tensor of dimension [1,1,1,1,1,1,512,60] when passed to the Model-2 which expects the same input dimension as has the same dimension i.e. ![image](https://user-images.githubusercontent.com/21283733/96801415-6ab5a280-13bc-11eb-869a-59a439eba741.png)
> 
> I get this error:
> 
> AssertionException: Assertion failure. Values are not equal. Expected: 1 == 512 UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <480508088aee40cab70818ff164a29d5>:0) UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <480508088aee40cab70818ff164a29d5>:0) UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at <480508088aee40cab70818ff164a29d5>:0) UnityEngine.Assertions.Assert.AreEqual (System.Int32 expected, System.Int32 actual) (at <480508088aee40cab70818ff164a29d5>:0) Unity.Barracuda.PrecompiledComputeOps.Conv2D (Unity.Barracuda.Tensor X, Unity.Barracuda.Tensor K, Unity.Barracuda.Tensor B, System.Int32[] stride, System.Int32[] pad, Unity.Barracuda.Layer+FusedActivation fusedActivation) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/Core/Backends/BarracudaPrecompiledCompute.cs:630) Unity.Barracuda.StatsOps.Unity.Barracuda.IOps.Conv2D (Unity.Barracuda.Tensor X, Unity.Barracuda.Tensor K, Unity.Barracuda.Tensor B, System.Int32[] stride, System.Int32[] pad, Unity.Barracuda.Layer+FusedActivation fusedActivation) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/Core/Backends/StatsOps.cs:69) Unity.Barracuda.GenericWorker+<StartManualSchedule>d__29.MoveNext () (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:218) Unity.Barracuda.GenericWorker.Execute () (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:118) Unity.Barracuda.GenericWorker.Execute (System.Collections.Generic.IDictionary`2[TKey,TValue] inputs) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:106) ResnetLstmClassifier+d__15.MoveNext () (at Assets/MSELI/Examples/BehaviorGenerator/ClassificationDetection/Scripts/ResnetLstmClassifier.cs:84) UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <480508088aee40cab70818ff164a29d5>:0)
> 
> So I closely checked this some shape issue it is having wrt the Conv2D layer in BarracudaPrecompiledCompute.cs line 630 which says `Assert.AreEqual(X.channels, K.kernelDepth);`. Somewhere there is being a shape issue somewhere.
> 
> Also to add `builder.Concat("concat0", new [] {"reshape0", "input1"}, 3);` or any Concat, the last concatenation dimension in this case would be 7 not 3 thats how it worked for me as it is expecting an 8D tensor.
> 
> Sharing you Model-2 onnx here: [crnn_conv1d_decoder.zip](https://github.com/Unity-Technologies/barracuda-release/files/5419231/crnn_conv1d_decoder.zip)

@AlexRibard I am using barracuda 2.0 and still have this issue of concat exapecting the axis parameter as 7 and not 3. Can you look at it.
