### ISSUE TITLE
Unable to use ONNX models with Barracuda

### ISSUE THREAD

**Issue by raphipaffi** [Unity-Technologies/barracuda-release#99]
Hi, my ONNX models fail to run with Barracuda. So far, all ONNX models that I generate show a warning about an unsupported attribute when imported into Unity and throw an error when executed (Tensor index out of bounds).

Steps to reproduce:

1. load **MobileNetV2**, `model = tf.keras.applications.MobileNetV2(...)`
2. save model to pb file, `model.save(output_path)`
3. convert saved_model.pb to ONNX using **tf2onnx**.

For steps 2+3 I also tested **keras2onnx**. Both options seem to work fine. I attached the Jupiter Notebook and the resulting ONNX files below.

4. import ONNX file into Unity project. The following warning is shown:
4a. if the model was generated with **tf2onnx**
`StatefulPartitionedCall/mobilenetv2_1.00_224/global_average_pooling2d_15/Mean:0 Unsupported attribute keepdims, node StatefulPartitionedCall/mobilenetv2_1.00_224/global_average_pooling2d_15/Mean:0 of type ReduceMean. Value will be ignored and defaulted to 1.`
4b. if the model was generated with **keras2onnx**
`predictions Unsupported attribute axis, node predictions of type Softmax. Value will be ignored and defaulted to 1.`

5. run the Unity scene to do image classification with my webcam. The model input expects tensors of shape [N, 224, 224, 3] so in my code I generate tensors of shape [1, 224, 224, 3]. However, the following **error is thrown**:
```
IndexOutOfRangeException: Index was outside the bounds of the array.
Unity.Barracuda.Tensor.get_Item (System.Int32 index) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Tensor.cs:985)
Classifier+<Classify>d__10.MoveNext () (at Assets/Scripts/Classifier.cs:69)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
```

The code to execute the model is based on https://github.com/Syn-McJ/TFClassify-Unity-Barracuda. I only made some minor changes to replace deprecated Barracuda functions. The code runs without warnings or errors when I use  mobilenet_v2.nn that comes with TFClassify-Unity-Barracuda. My Unity project uses
* Unity 2020.1.10f1
* Barracuda 1.0.4

My environment to generate the model:
* py 3.6.11
* tf 2.2.0
* onnx 1.7.0
* tf2onnx 1.7.1
* keras2onnx 1.7.0

I have been struggling with this issue for days now and tried lots of variations to solve it. Also tried to convert the .pb files to barracuda format using the scripts in the tools folder. But they also throw an error (they seem to require TF-1, not sure). Any help on this is highly appreciated!

[onnx_models.zip](https://github.com/Unity-Technologies/barracuda-release/files/5446424/onnx_models.zip)

[GenerateONNXModels.zip](https://github.com/Unity-Technologies/barracuda-release/files/5446635/GenerateONNXModels.zip)

**Comment by raphipaffi** [comment]
I just saw that both models show batch size of 0 in Unity:
![Screenshot from 2020-10-27 17-44-25](https://user-images.githubusercontent.com/25623165/97333772-33436c00-187c-11eb-816f-a43c8744c328.png)

Is it possible that Barracuda cannot handle models with undefined batch sizes N? This could explain the error that is thrown during execution (not the warning during import).

**Comment by AlexRibard** [comment]
Hi @raphipaffi I will check your model!
The 0 batch is bad UI on our end. It means * ie unspecified batch number. But Barracuda does support unspecified batch number

**Comment by raphipaffi** [comment]
Thanks for the quick feedback Alex! Looking forward to hearing back from you.

**Comment by AlexRibard** [comment]
Ok figured out the problems.
First off, `Softmax` on axis 1 warning is gone in the upcoming 1.2.0 version which is good, but it shouldn't impact the execution.
Secondly I managed to get your model working and validating with onnx_runtime :)

* Let's try something before diving in:
TF2Onnx/Keras2Onnx doesn't transpose input dimension by default, but inserts transposes instead. Can you try using the `channel_first_inputs/inputs_as_nchw` flags to get the correct onnx layout.
You can find more info here:
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Exporting.md
I think this should do the trick

* If that doesn't work I'll send you the fixes

**Comment by raphipaffi** [comment]
Hey @AlexRibard, thanks for your analysis. I ran the following test:

I converted to ONNX using the additional parameter you suggested:
```
onnx_model = keras2onnx.convert_keras(model, model.name, channel_first_inputs=model.input.name, target_opset=opset)
keras2onnx.save_model(onnx_model, output_path + "/model_" + converter + ".onnx")
```
Here is the new model (exported with keras2onnx): [model_keras2onnx.zip](https://github.com/Unity-Technologies/barracuda-release/files/5455251/model_keras2onnx.zip)

A quick side by side analysis of yesterday's model (left) and today's model (right) in Netron looks good. No transpose at the input and expected tensor shape is now [N, 3, 224, 224]:
![Screenshot from 2020-10-28 23-57-08](https://user-images.githubusercontent.com/25623165/97505558-5d2e8880-1979-11eb-98e4-cb1a9900a155.png)

However, when I run the model in Unity I still get the same error (index out of bounds). In a second try I also changed the input tensor that I construct in Unity to [1, 3, 224, 224] (last line of code):
```
public static Tensor TransformInput(Color32[] pic, int width, int height)
    {
        float[] floatValues = new float[width * height * 3];

        for (int i = 0; i < pic.Length; ++i)
        {
            var color = pic[i];

            floatValues[i * 3 + 0] = (color.r - IMAGE_MEAN) / IMAGE_STD;
            floatValues[i * 3 + 1] = (color.g - IMAGE_MEAN) / IMAGE_STD;
            floatValues[i * 3 + 2] = (color.b - IMAGE_MEAN) / IMAGE_STD;
        }

        //return new Tensor(1, height, width, 3, floatValues);
        return new Tensor(1, 3, height, width, floatValues);
    }
```
In that case an assertion in Barracuda code fails:
```
AssertionException: Assertion failure. Values are not equal.
Expected: 3 == 224
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at /home/bokken/buildslave/unity/build/Runtime/Export/Assertions/Assert/AssertBase.cs:29)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at /home/bokken/buildslave/unity/build/Runtime/Export/Assertions/Assert/AssertGeneric.cs:31)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at /home/bokken/buildslave/unity/build/Runtime/Export/Assertions/Assert/AssertGeneric.cs:19)
UnityEngine.Assertions.Assert.AreEqual (System.Int32 expected, System.Int32 actual) (at /home/bokken/buildslave/unity/build/Runtime/Export/Assertions/Assert/AssertPrimitiveTypes.cs:176)
Unity.Barracuda.PrecompiledComputeOps.Conv2D (Unity.Barracuda.Tensor X, Unity.Barracuda.Tensor K, Unity.Barracuda.Tensor B, System.Int32[] stride, System.Int32[] pad, Unity.Barracuda.Layer+FusedActivation fusedActivation) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/BarracudaPrecompiledCompute.cs:625)
Unity.Barracuda.StatsOps.Unity.Barracuda.IOps.Conv2D (Unity.Barracuda.Tensor X, Unity.Barracuda.Tensor K, Unity.Barracuda.Tensor B, System.Int32[] stride, System.Int32[] pad, Unity.Barracuda.Layer+FusedActivation fusedActivation) (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/StatsOps.cs:69)
Unity.Barracuda.GenericWorker+<StartManualSchedule>d__30.MoveNext () (at Library/PackageCache/com.unity.barracuda@1.0.4/Barracuda/Runtime/Core/Backends/GenericWorker.cs:214)
Classifier+<Classify>d__10.MoveNext () (at Assets/Scripts/Classifier.cs:55)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<>c__DisplayClass9_0:<TFClassify>b__0(Color32[]) (at Assets/Scripts/PhoneCamera.cs:102)
<>c__DisplayClass10_0:<ProcessImage>b__0(Texture2D) (at Assets/Scripts/PhoneCamera.cs:135)
TFClassify.<CropSquare>d__2:MoveNext() (at Assets/Scripts/TextureTools.cs:96)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
```

Let me know if there is anything else I should try.

**Comment by AlexRibard** [comment]
ok that's perfect. I've tested it in 1.2.0 model imports correctly.
The version should be coming out tomorrow. Let me know if it works then!

**Comment by raphipaffi** [comment]
Great, thanks for the heads up!

**Comment by raphipaffi** [comment]
Hey @AlexRibard , I tested my model with Barracuda 1.2 now. The good news: The model imports without warnings and doesn't throw any errors. However, the model outputs completely wrong values, Almost all outputs are 1 for any input image. When I run the same onnx model in my Jupyter Notebook I get correct results. So the model description in the onnx file seems ok.

Also, I checked my image preprocessing in C# code and compared the resulting input image to what I get with my Jupyter Notebook. Pixel values are exactly the same. So the data fed to the model is also identical.

Then I tried out different WorkerFactory types used in Barracuda. **CSharpBurst** and **CSharp** give the same (wrong) results, **CSharpRef** still throws the "tensor index out of bound" error.

Then I ran my debugger (using CSharp worker). Here is what the debugger shows for m_Model in GenericWorker class:
![Screenshot from 2020-11-01 17-48-20](https://user-images.githubusercontent.com/25623165/97809006-86e1fb00-1c6a-11eb-9c03-6ddbc217c004.png)
...
![Screenshot from 2020-11-01 17-49-18](https://user-images.githubusercontent.com/25623165/97809012-9bbe8e80-1c6a-11eb-9ba8-f0f5a3c33a72.png)
...
![Screenshot from 2020-11-01 20-18-07](https://user-images.githubusercontent.com/25623165/97812120-76884b00-1c7f-11eb-9b30-af666a37dcb8.png)

What's weird:
1) Layer 0 in m_Model (biased_tensor_name with shape 1x1000) should actually be the last layer doing the final classification.
2) Not sure about the warning for layer 49 (invalid attribute). For different executions the layer number with this warning keeps changing and there is no meaurable issue with this layer. Might be a debugger issue.

Any idea what's going on here? Here is the model I was using for these tests:
[model_keras2onnx.zip](https://github.com/Unity-Technologies/barracuda-release/files/5471578/model_keras2onnx.zip)
I was playing around with different opset values so it's probably not identical to the first version I posted above.

**Comment by AlexRibard** [comment]
I've checked your model, yeah you are correct the output values are wrong compared to onnxruntime. Checking why.
As for the shape in the UI, it's on us. We added support for 8D tensors, but as a result the UI is quite unreadable. It will be addressed in the next release.
But I checked, the shape do match

**Comment by AlexRibard** [comment]
@raphipaffi ok figured it out. Issue is two fold.
One keras2onnx messes up with the `inputs_as_nchw` as there is still a Transpose at the end of the model.
Can you share me the model without this `flag`? We have our own sanity check for this case exactly, so it might work out.
We also have a bug in our softmax axis handling. I have a fix for that. In the meantime, can you try by setting the `axis = 1` in `softmax` (compared to the -1 you have atm)?
If those do not work, shoot us an email at barracuda-support@unity3d.com I'll send you the fixes I have to make your model work.

Let me know

**Comment by raphipaffi** [comment]
Ok, I generated two new versions of the model using this code:
```
def SetSoftmaxAxisTo1(model):
    numOfNodes = len(model.graph.node)
    print("Number of nodes in ONNX graph: " + str(numOfNodes))

    print("\nConfiguration of last node:")
    print(model.graph.node[numOfNodes-1])

    # set attribbute "axis" from -1 to 1
    model.graph.node[numOfNodes-1].attribute[0].i = 1

    print("\nConfiguration of last node:")
    print(model.graph.node[numOfNodes-1])
    
    return model

onnx_model = keras2onnx.convert_keras(model, model.name, target_opset=opset)
# set attribbute "axis" in Softmax layer from -1 to 1
onnx_model = SetSoftmaxAxisTo1(onnx_model)
# check modified model
onnx.checker.check_model(onnx_model)
# export model to file
keras2onnx.save_model(onnx_model, output_filename)
```
In one case I used the code as shown and exported the model to **model_keras2onnxSMaxis1.onnx**.
In the other case I **commented out the call to SetSoftmaxAxisTo1** and exported to **model_keras2onnx.onnx**.
Here are the resulting files: [model_keras2onnx.zip](https://github.com/Unity-Technologies/barracuda-release/files/5482628/model_keras2onnx.zip)

The model with axis=1 produces different but still wrong results.

Also, m_Model still has this weird first layer (index 0) that looks like it should come at the very end of the model:
![Screenshot from 2020-11-03 17-32-03](https://user-images.githubusercontent.com/25623165/98013733-06063900-1dfb-11eb-838b-65c03afeed5c.png)

And the final Softmax layer shows axis=5 instead of axis=1:
![Screenshot from 2020-11-03 17-36-23](https://user-images.githubusercontent.com/25623165/98013908-436ac680-1dfb-11eb-9226-d52dd3fe3ee0.png)

In Netron, the same layer looks fine:
![Screenshot from 2020-11-03 17-43-59](https://user-images.githubusercontent.com/25623165/98014682-3e5a4700-1dfc-11eb-9e88-162f3b79234f.png)

**Comment by AlexRibard** [comment]
ok thanks for providing me the networks. I'll take a look at it

**Comment by raphipaffi** [comment]
Hi @AlexRibard, any new insights? Here is also the Jupyter Notebook I use to generate these models:
[GenerateONNXModels.zip](https://github.com/Unity-Technologies/barracuda-release/files/5524431/GenerateONNXModels.zip)
There is nothing special in there. I just take the precomputed MobileNetV2 from Keras and convert and export it to ONNX.

**Comment by AlexRibard** [comment]
@raphipaffi very sorry about the delay.
I checked your model on 1.2.0.
You just need to export it without any changed to the model (no `SetSoftmaxAxisTo1`, just `keras2onnx.convert_keras(model, model.name, target_opset=opset)` (keras2onnx actually overwrites the `SetSoftmaxAxisTo1`...)
On 1.2.0 you need to add
```
ONNXModelConverter.cs l656
if (axis < 0)
    axis = axis + node.Input0Rank;
```
I've pushed the fix on main it will land on the next version.
With that fix, your model imports and validates with `onnx-runtime`.
Let me know

**Comment by raphipaffi** [comment]
Thanks for the quick update @AlexRibard. If I get you right, I'll export my model without any modifications and wait for the next Barracuda update before testing again.

**Comment by AlexRibard** [comment]
Sorry for that, some critical info got hidden away in the code snippet...
* Yes, option 1 is for you to wait for the next release.
* Option 2 is to modify locally ONNXModelConverter.cs on l656 and add the code snippet and export without modifications

**Comment by hajiarab1988** [comment]
> Sorry for that, some critical info got hidden away in the code snippet...
> 
> * Yes, option 1 is for you to wait for the next release.
> * Option 2 is to modify locally ONNXModelConverter.cs on l656 and add the code snippet and export without modifications

Thank you a lot
The second option totally solved the problem
I just added this: if (axis < 0)
    axis = axis + node.Input0Rank;
to ONNXModelConverter.cs on the line 656 and every thing works perfect!

Edit : And also I unchecked 'Optimize Model' in Inspector then 'Apply' and checked it again and 'Apply' again.

**Comment by raphipaffi** [comment]
Hey @AlexRibard, while trying your suggestion I noticed an issue with my labels file that I copied from https://github.com/Syn-McJ/TFClassify-Unity-Barracuda. The file has an additional label at the top (called "background") so combined with the 1000 labels from ImageNet it contains 1001 labels.
The model I generate with TF and Keras expects 1000 labels, corresponding to the 1x1000 Softmax output layer. I removed this extra label from the file and (coincidentally) **switched back to Barracuda 1.0.4 and now the model generates correct results!** Finally :)

Once I realized that I was on 1.0.4 again I moved back to 1.2. However, **with 1.2 my model still generates 1's for all outputs** (as before). Adding the "axis code" to ONNXModelConverter doesn't make a difference. And given that I get correct results with 1.0.4 despite the warning about the axis attribute in the Softmax layer, the issue in 1.2 seems to be something else.

So for now I will stick to 1.0.4 and live with the axis warning about my model.

**Comment by AlexRibard** [comment]
oh... ok strange. 
Sorry about that.
I've added the model in the test suite so it should be fixed in the next version.
But yeah, stick to 1.0.4 then since it is easier.

**Comment by raphipaffi** [comment]
No worries, I am happy that it works now :)

So given my experiments, Barracuda 1.2 should return 1 for every element in the output tensor of my model in your test case at the moment. Using Barracuda 1.0.4 the output values correctly sum up to 1 (and maximum value corresponds to the correct class).

**Comment by sharpgraf** [comment]
> Hey @AlexRibard, while trying your suggestion I noticed an issue with my labels file that I copied from https://github.com/Syn-McJ/TFClassify-Unity-Barracuda. The file has an additional label at the top (called "background") so combined with the 1000 labels from ImageNet it contains 1001 labels.
> The model I generate with TF and Keras expects 1000 labels, corresponding to the 1x1000 Softmax output layer. I removed this extra label from the file and (coincidentally) **switched back to Barracuda 1.0.4 and now the model generates correct results!** Finally :)
> 
> Once I realized that I was on 1.0.4 again I moved back to 1.2. However, **with 1.2 my model still generates 1's for all outputs** (as before). Adding the "axis code" to ONNXModelConverter doesn't make a difference. And given that I get correct results with 1.0.4 despite the warning about the axis attribute in the Softmax layer, the issue in 1.2 seems to be something else.
> 
> So for now I will stick to 1.0.4 and live with the axis warning about my model.

Thank you very much  !!! Works for me !
But I had the correct number of labels :)

**Comment by AlexRibard** [comment]
@sharpgraf are you using the same model?
If not, would you mind sharing it? I would be curious to add it to the test suite for 1.3

**Comment by sharpgraf** [comment]
> @sharpgraf are you using the same model?
> If not, would you mind sharing it? I would be curious to add it to the test suite for 1.3

sure !
notebook:
https://colab.research.google.com/github/zaidalyafeai/zaidalyafeai.github.io/blob/master/sketcher/Sketcher.ipynb#scrollTo=NoFI1msFYpCN
my converted to onnx version:
[sketcher.zip](https://github.com/Unity-Technologies/barracuda-release/files/5579163/sketcher.zip)
